-- ============================================================
-- SESSION LIBRARY — Expansion v1
-- Trail (28 nouvelles), Natation (28+), Vélo (28+), Brique (30+)
-- ============================================================

-- ============================================================
-- TRAIL — 28 nouvelles séances (total ~40)
-- Catégories : technique, montagne, ville/route, fractionné, ultra
-- ============================================================
INSERT INTO public.session_library (code, type, category, name, duration_min, intensity_rpe, warmup, main_set, recovery, cooldown, coach_notes, compatible_goals, sport, montagne_only, sort_order) VALUES

-- ── Trail ville / asphalte ───────────────────────────────────
('TRAIL-13', 'trail', 'trail', 'Trail urbain — 45min allure endurance', 45, 5,
 NULL,
 '45 min en milieu urbain à 65-72% VMA — escaliers, trottoirs, changements de direction : profite du relief naturel de la ville',
 NULL, NULL,
 'Le trail ne se limite pas à la montagne. La ville est un terrain d''entraînement excellent : escaliers, côtes de rue, changements de surface. Adapte-toi à l''environnement.',
 ARRAY['trail_court', 'trail_long'], 'trail', false, 15),

('TRAIL-14', 'trail', 'trail', 'Trail urbain — Escaliers 8x3min', 60, 8,
 '15 min footing lent en ville',
 '8x3min de montée d''escaliers à RPE 8 — montée rapide, descente lente et contrôlée',
 'Descente lente entre chaque montée',
 '10 min footing lent',
 'Les escaliers urbains sont l''équivalent parfait des côtes de montagne. Genoux hauts, appui actif, bras qui aident. La descente est technique — utilise la rampe si besoin au début.',
 ARRAY['trail_court', 'trail_long', 'ultra'], 'trail', false, 16),

('TRAIL-15', 'trail', 'trail', 'Trail urbain — 6x5min montée de rue', 65, 8,
 '15 min footing lent',
 '6x5min sur côte de rue à RPE 7-8 — effort soutenu, course ou marche rapide selon la pente',
 'Descente trot lent entre chaque montée',
 '10 min footing lent',
 'La rue remplace la montagne. Cherche les côtes les plus raides de ta ville et enchaîne les montées. L''intensité est identique à la montagne — le terrain est juste différent.',
 ARRAY['trail_court', 'trail_long'], 'trail', false, 17),

('TRAIL-16', 'trail', 'trail', 'Trail urbain progressif — 60min', 60, 6,
 NULL,
 '20 min à 65-68% VMA → 20 min à 70-75% VMA avec recherche de dénivelé → 20 min à 75-80% VMA sur les montées, récup en descente',
 NULL, NULL,
 'Progressif en milieu urbain. Tu montes en régime en cherchant de plus en plus les côtes et les escaliers. Parfait quand tu n''as pas accès à la nature.',
 ARRAY['trail_court', 'trail_long'], 'trail', false, 18),

-- ── Trail technique spécifique ────────────────────────────────
('TRAIL-17', 'trail', 'trail', 'Technique de passage — Pierriers et sentiers', 50, 6,
 '15 min footing lent sur sentier',
 '35 min sur sentier technique (pierriers, racines, passages délicats) à RPE 6 — allure réduite, focus total sur le placement des pieds',
 NULL,
 '10 min footing lent',
 'Séance de technique pure sur terrain difficile. Ralentis autant que nécessaire pour placer chaque pied correctement. La vitesse vient avec la répétition. Regarde 2-3m devant, pas à tes pieds.',
 ARRAY['trail_court', 'trail_long', 'ultra'], 'trail', true, 22),

('TRAIL-18', 'trail', 'trail', 'Technique descente rapide — 6x descentes 3min', 65, 7,
 '20 min footing progressif avec montée initiale',
 '6 répétitions de descente rapide 3min — cherche la fluidité, les lignes de fuite, le relâchement total',
 'Remontée lente entre chaque descente',
 '5 min footing lent',
 'Descendre vite en trail, ça s''apprend. Session focus descente : varie les trajectoires, cherche les lignes naturelles, laisse la gravité travailler. Tes quadriceps vont chauffer — c''est normal.',
 ARRAY['trail_court', 'trail_long', 'ultra'], 'trail', true, 23),

('TRAIL-19', 'trail', 'trail', 'Marche nordique technique — 1h30 bâtons', 90, 5,
 NULL,
 '1h30 marche rapide avec bâtons sur terrain montagneux — technique de poussée bâton, fréquence élevée, dénivelé maximal',
 NULL, NULL,
 'Les bâtons changent tout en montagne. Pousse fort derrière, synchronise avec le pas opposé. Séance basse intensité mais volume de D+ élevé — parfait pour les ultra-traileurs.',
 ARRAY['ultra'], 'trail', true, 24),

('TRAIL-20', 'trail', 'trail', 'Simulation ravitaillement — 2h avec arrêts', 120, 6,
 NULL,
 '2h trail avec 3 arrêts ravitaillement simulés (à 40min, 80min, 100min) — mange, bois, repars rapidement comme en course',
 NULL, NULL,
 'Entraîne-toi à manger et boire en mouvement et à gérer tes arrêts ravitaillement. En ultra, perdre 2 minutes par ravito sur 10 ravitos = 20 minutes perdues. Teste tes gels, tes barres, tes boissons.',
 ARRAY['ultra'], 'trail', true, 25),

-- ── Trail fractionné montagne ─────────────────────────────────
('TRAIL-21', 'trail', 'trail', 'Fractionné montagne — 5x8min montée', 80, 8,
 '20 min footing progressif',
 '5x8min de montée à RPE 7-8 — effort aérobie soutenu, technique de montée optimale',
 'Descente lente 4min entre chaque montée',
 '10 min footing lent',
 'Huit minutes en montée c''est une vraie épreuve. L''effort doit être régulier du bas au sommet. Si tu exploses sur les 2 dernières minutes, tu pars trop vite au départ.',
 ARRAY['trail_court', 'trail_long', 'ultra'], 'trail', true, 26),

('TRAIL-22', 'trail', 'trail', 'Fractionné montagne — 3x15min montée longue', 90, 8,
 '20 min footing progressif',
 '3x15min de montée continue à RPE 7 — effort long et régulier, cherche ton rythme de croisière en montée',
 'Descente lente 5min entre chaque montée',
 '10 min footing lent',
 'Quinze minutes de montée continue — c''est la distance qui te prépare aux longues ascensions de trail. Gère ton effort dès le départ. La marche rapide est autorisée si la pente est raide.',
 ARRAY['trail_long', 'ultra'], 'trail', true, 27),

('TRAIL-23', 'trail', 'trail', 'Fractionné montagne — 2x25min montée très longue', 100, 8,
 '20 min footing progressif',
 '2x25min de montée continue à RPE 6-7 — effort long, marche active acceptée dans les passages très raides',
 'Descente lente 8min entre les 2 montées',
 '10 min footing lent',
 'Vingt-cinq minutes de montée, c''est une ascension de vrai trail. L''objectif est de maintenir un effort aérobie constant du début à la fin, que tu coures ou marches vite.',
 ARRAY['trail_long', 'ultra'], 'trail', true, 28),

('TRAIL-24', 'trail', 'trail', 'Fractionné vertical — 10x2min côtes très raides', 70, 9,
 '15 min footing lent',
 '10x2min de montée très raide (>20% de pente) à RPE 8-9 — course ou marche rapide selon la pente, effort maximal',
 'Descente lente 2min entre chaque',
 '10 min footing lent',
 'La pente raide développe la force spécifique trail comme rien d''autre. Monte de la façon la plus efficace possible — courir ou marcher vite, peu importe. C''est l''effort qui compte.',
 ARRAY['trail_court', 'trail_long', 'ultra'], 'trail', true, 29),

-- ── Trail endurance montagne ──────────────────────────────────
('TRAIL-25', 'trail', 'trail', 'Sortie montagne 2h30 — D+ 800-1000m', 150, 6,
 NULL,
 '2h30 en montagne avec 800-1000m de D+ — alternance course/marche selon la pente, descentes techniques',
 NULL, NULL,
 'Grosse sortie montagne. Le D+ est le vrai volume de travail ici, pas la durée. Hydrate-toi toutes les 20min, mange toutes les 45min. Gère les descentes — tes quadriceps en auront besoin.',
 ARRAY['trail_long', 'ultra'], 'trail', true, 105),

('TRAIL-26', 'trail', 'trail', 'Sortie montagne 3h — D+ 1000-1500m', 180, 6,
 NULL,
 '3h en montagne avec 1000-1500m de D+ — effort ultra, allure très conservatrice, marche systématique en montée raide',
 NULL, NULL,
 'Trois heures et 1000m de D+ — une vraie sortie montagne. Pars plus lentement que tu ne le penses. L''erreur classique est de vouloir aller vite dès le début. Tu le paieras en fin de sortie.',
 ARRAY['ultra'], 'trail', true, 110),

('TRAIL-27', 'trail', 'trail', 'Back-to-back trail — J1 2h / J2 1h30 jambes chargées', 210, 7,
 NULL,
 'Jour 1 : 2h trail à 65-70% VMA. Jour 2 (lendemain) : 1h30 trail à 65% VMA sur jambes fatiguées — simule les 2ème et 3ème jours d''un ultra',
 NULL, NULL,
 'L''entraînement back-to-back est essentiel pour l''ultra. Le 2ème jour sur jambes fatiguées t''apprend à courir économiquement quand ton corps est déjà entamé. C''est exactement ce qui se passe après 30-40km d''ultra.',
 ARRAY['ultra'], 'trail', true, 115),

-- ── Trail spécifique montagne ─────────────────────────────────
('TRAIL-28', 'trail', 'trail', 'Reconnaissage de course — Simulation terrain', 180, 6,
 NULL,
 'Reproduis exactement le profil de ta course objectif sur le terrain réel ou similaire — même D+, mêmes surfaces, même équipement, même alimentation qu''en compétition',
 NULL, NULL,
 'Si tu peux reconnaître ta course, fais-le. Sinon, trouve un terrain similaire. Teste absolument tout ce que tu utiliseras en compétition. Rien ne doit être découvert le jour J.',
 ARRAY['trail_court', 'trail_long', 'ultra'], 'trail', true, 120),

('TRAIL-29', 'trail', 'trail', 'Sortie crête — Terrain exposé et vent', 120, 6,
 NULL,
 '2h sur crête ou terrain exposé au vent — gestion de l''équilibre sur terrain irrégulier, adaptation aux conditions météo',
 NULL, NULL,
 'Les crêtes sont un environnement à part : vent, terrain instable, passages exposés. Adapte ton allure, reste concentré sur le placement de tes pieds. L''exposition mentale fait partie de l''entraînement.',
 ARRAY['trail_long', 'ultra'], 'trail', true, 125),

('TRAIL-30', 'trail', 'trail', 'Trail froid — Adaptation conditions hivernales', 75, 6,
 NULL,
 '75 min trail en conditions froides (< 5°C) — gestion de la thermorégulation, adaptation de la foulée sur terrain gelé ou enneigé',
 NULL, NULL,
 'Courir dans le froid s''apprend. Couvre-toi plus que tu ne le penses au départ — tu te réchaufferas. Sur terrain gelé, raccourcis la foulée et reste sur l''avant-pied. La prudence avant la performance.',
 ARRAY['trail_court', 'trail_long', 'ultra'], 'trail', false, 130),

-- ── Trail mental / spécifique compétition ────────────────────
('TRAIL-31', 'trail', 'trail', 'Séance mentale — 4h jeûne partiel', 240, 5,
 NULL,
 '4h trail à allure ultra très conservative (60-65% VMA ressenti) avec ravitaillement réduit intentionnellement — apprend à gérer le manque',
 NULL, NULL,
 'Séance mentale et métabolique. Tu t''habitues à courir avec des réserves basses — comme tu le vivras en fin d''ultra. Ne pousse pas l''intensité. L''objectif est l''adaptation, pas la performance.',
 ARRAY['ultra'], 'trail', true, 135),

('TRAIL-32', 'trail', 'trail', 'Sortie nocturne longue — 2h lampe frontale montagne', 120, 6,
 NULL,
 '2h trail de nuit avec lampe frontale en terrain montagneux — allure conservative, terrain connu, technique nocturne',
 NULL, NULL,
 'La nuit en montagne change tout. Porte une lampe frontale puissante et une lampe de secours. Réduis ton allure de 15-20%. Reste sur des sentiers que tu connais. L''expérience nocturne est obligatoire avant tout ultra avec partie de nuit.',
 ARRAY['trail_long', 'ultra'], 'trail', true, 140),

('TRAIL-33', 'trail', 'trail', 'Simulation passage de cols — 3 cols enchaînés', 210, 7,
 NULL,
 'Enchaîner 3 montées/descentes de 400-600m de D+ chacune — simulation d''étapes à cols multiples comme dans les grands ultras',
 NULL, NULL,
 'Trois cols enchaînés — mentalement et physiquement, c''est différent d''une seule longue montée. Après le 2ème col, le 3ème arrive sur des jambes qui commencent à lâcher. C''est exactement pour ça qu''il faut s''y entraîner.',
 ARRAY['ultra'], 'trail', true, 145),

('TRAIL-34', 'trail', 'trail', 'VMA trail — 6x400m en côte à 100%', 60, 9,
 '20 min footing progressif',
 '6x400m en côte à 100-107% VMA — sprint de côte court et explosif, récupération complète',
 'Descente trot lent + 2min repos entre chaque',
 '10 min footing lent',
 'Même en trail, le travail de VMA est essentiel. Ces 400m en côte développent ta puissance maximale aérobie et ta force spécifique en même temps. Reste explosif sur chaque répétition.',
 ARRAY['trail_court', 'trail_long'], 'trail', true, 30),

('TRAIL-35', 'trail', 'trail', 'Tempo trail — 3x20min sur sentier plat', 90, 7,
 '20 min footing lent',
 '3x20min sur sentier plat ou légèrement vallonné à 83-88% VMA — allure seuil adaptée au trail',
 '5min footing lent entre chaque bloc',
 '10 min footing lent',
 'Le tempo trail se fait sur terrain roulant. L''allure est identique au tempo route mais les appuis sont moins réguliers — ce qui renforce aussi la proprioception. Cherche les sentiers forestiers.',
 ARRAY['trail_court', 'trail_long'], 'trail', false, 31),

('TRAIL-36', 'trail', 'trail', 'Fractionné trail court — 12x2min côtes', 65, 8,
 '15 min footing lent',
 '12x2min de montée à RPE 8 — effort court et répété, récupération active en descente',
 'Descente trot lent 1min30 entre chaque',
 '10 min footing lent',
 'Volume élevé sur effort court. Douze montées de 2min, ça représente 24min de travail intensif. Les 4 dernières arrivent sur des jambes bien chargées — c''est là que la séance se gagne.',
 ARRAY['trail_court', 'trail_long', 'ultra'], 'trail', true, 32),

('TRAIL-37', 'trail', 'trail', 'Endurance trail — 45min terrain varié', 45, 5,
 NULL,
 '45 min trail sur terrain varié (forêt, chemins, un peu de route) à 65-72% VMA — allure endurance fondamentale',
 NULL, NULL,
 'Sortie trail courte idéale pour les débutants ou les semaines de récupération. L''important c''est de sentir le terrain sous tes pieds et d''apprendre à t''adapter naturellement.',
 ARRAY['trail_court'], 'trail', false, 65),

('TRAIL-38', 'trail', 'trail', 'Endurance trail — 55min chemins forestiers', 55, 5,
 NULL,
 '55 min trail forêt à 65-72% VMA — chemins naturels, focus relâchement et adaptation au terrain',
 NULL, NULL,
 'Le trail en forêt est le meilleur terrain de progression. Les racines et les irrégularités renforcent ta proprioception sans que tu t''en rendes compte. Va à l''aise.',
 ARRAY['trail_court', 'trail_long'], 'trail', false, 67),

('TRAIL-39', 'trail', 'trail', 'Endurance trail — 2h15 terrain mixte', 135, 6,
 NULL,
 '2h15 trail sur terrain mixte (route + sentier + côtes) à 65-72% VMA — volume endurance long',
 NULL, NULL,
 'Deux heures et quart de trail mixte. La variété du terrain évite la monotonie et sollicite différents groupes musculaires. Ravitaillement à 60min et 90min.',
 ARRAY['trail_long', 'ultra'], 'trail', false, 92),

('TRAIL-40', 'trail', 'trail', 'Récupération trail — 35min très lent', 35, 3,
 NULL,
 '35 min trail très lent à 57-63% VMA — allure récupération, terrain plat de préférence',
 NULL, NULL,
 'Récupération en trail. Va sur un sentier plat ou en forêt douce. L''idée est de bouger sans se fatiguer. Si quelque chose fait mal, marche — tu es en récupération, pas en entraînement.',
 ARRAY['trail_court', 'trail_long', 'ultra'], 'trail', false, 5);


-- ============================================================
-- NATATION — 28 nouvelles séances (total ~40)
-- ============================================================
INSERT INTO public.session_library (code, type, category, name, duration_min, intensity_rpe, warmup, main_set, recovery, cooldown, coach_notes, compatible_goals, sport, triathlon_disciplines, sort_order) VALUES

-- ── Technique ─────────────────────────────────────────────────
('NAT-13', 'natation', 'natation', 'Technique crawl — Focus appui et traction', 40, 4,
 '200m nage libre lente',
 '8x50m technique : 2 longueurs catch unilatéral → 2 longueurs drill doigt dans l''eau → 4 longueurs nage complète focus traction — récup 20'' entre chaque',
 '20'' entre chaque longueur',
 '100m retour au calme',
 'Le catch (saisie de l''eau) est le geste technique le plus rentable en natation. Coude haut, avant-bras perpendiculaire à l''eau, tire vers ta hanche. Un bon catch fait plus que 10km de natation approximative.',
 ARRAY['sprint', 'olympique', '70.3', 'ironman'], 'triathlon', ARRAY['natation'], 5),

('NAT-14', 'natation', 'natation', 'Technique crawl — Focus rotation et gainage', 40, 4,
 '200m nage libre lente',
 '10x50m technique : 2 longueurs nage latérale → 2 longueurs 6-3-6 (6 battements, 3 coups, 6 battements) → 6 longueurs nage complète focus rotation de hanche — récup 15'' entre chaque',
 '15'' entre chaque longueur',
 '100m retour au calme',
 'La rotation des hanches génère de la puissance et réduit la résistance. Si tu nages "à plat", tu nages contre l''eau. Travaille la rotation jusqu''à ce qu''elle soit naturelle.',
 ARRAY['sprint', 'olympique', '70.3', 'ironman'], 'triathlon', ARRAY['natation'], 6),

('NAT-15', 'natation', 'natation', 'Technique respiration — Bilatérale et rythme', 35, 4,
 '200m nage libre lente',
 '8x75m : 25m respiration tous les 2 → 25m respiration tous les 3 → 25m respiration tous les 5 — focus sur l''expiration complète sous l''eau — récup 20''',
 '20'' entre chaque',
 '100m retour au calme',
 'Apprendre à respirer tous les 3 (bilatéral) est la meilleure chose que tu puisses faire en natation. En eau vive, les vagues viendront souvent d''un côté — respirer des 2 côtés te rend adaptable.',
 ARRAY['sprint', 'olympique', '70.3', 'ironman'], 'triathlon', ARRAY['natation'], 7),

('NAT-16', 'natation', 'natation', 'Technique — Départ plongeon et virage culbute', 45, 5,
 '300m nage libre lente',
 '10 départs plongeon + 20 virages culbute sur 25m — focus sur l''impulsion et la glisse sous-marine',
 'Récup complète entre chaque départ',
 '100m nage lente',
 'Le plongeon et la culbute font gagner plusieurs secondes par course. En triathlon c''est moins critique mais la culbute te rend plus fluide aux murs. Travaille-les séparément.',
 ARRAY['sprint', 'olympique'], 'triathlon', ARRAY['natation'], 8),

-- ── Fractionné court nat ──────────────────────────────────────
('NAT-17', 'natation', 'natation', 'Sprint natation — 12x50m vitesse maximale', 40, 9,
 '400m échauffement varié',
 '12x50m à 95-100% effort — récup 40'' entre chaque (récup complète pour maintenir la qualité)',
 '40'' bord entre chaque',
 '200m retour au calme',
 'Séance de vitesse pure. Chaque 50m doit être couru à ton maximum. Si tu ralentis significativement sur les derniers, réduis à 10x. La qualité prime sur la quantité.',
 ARRAY['sprint', 'olympique'], 'triathlon', ARRAY['natation'], 15),

('NAT-18', 'natation', 'natation', 'Sprint natation — 8x50m + 4x25m finish', 40, 9,
 '400m échauffement varié',
 '8x50m à 90-95% CSS → récup 30'' → 4x25m sprint maximal → récup 45''',
 '30'' bord sur les 50m / 45'' sur les 25m',
 '200m retour au calme',
 'Les 25m finaux arrivent sur des bras déjà fatigués. Tu apprends à trouver de la vitesse dans l''état de fatigue — exactement comme sur la fin d''une épreuve.',
 ARRAY['sprint', 'olympique'], 'triathlon', ARRAY['natation'], 16),

('NAT-19', 'natation', 'natation', 'Endurance vitesse — 16x100m CSS', 55, 7,
 '400m échauffement varié',
 '16x100m à 83-88% CSS — récup 20'' entre chaque',
 '20'' bord entre chaque',
 '200m retour au calme',
 'Seize fois 100m avec peu de récup — le volume de qualité. La régularité entre le 1er et le 16ème 100m est l''objectif. Si tu chutes de plus de 5 secondes, tu es parti trop fort.',
 ARRAY['olympique', '70.3', 'ironman'], 'triathlon', ARRAY['natation'], 17),

('NAT-20', 'natation', 'natation', 'Séries courtes — 20x50m progressif', 50, 7,
 '400m échauffement varié',
 '20x50m : 5x50m à 75% CSS → 5x50m à 80% CSS → 5x50m à 87% CSS → 5x50m à 93% CSS — récup 15'' entre chaque',
 '15'' entre chaque',
 '200m retour au calme',
 'Séance en 4 blocs progressifs. Tu montes en régime sur 1000m. La dernière série de 5x50m arrive quand tu es déjà bien chargé — c''est là que tu testes ta vraie condition.',
 ARRAY['sprint', 'olympique', '70.3'], 'triathlon', ARRAY['natation'], 18),

-- ── Fractionné moyen nat ──────────────────────────────────────
('NAT-21', 'natation', 'natation', 'Intervalles natation — 6x200m CSS', 50, 7,
 '400m échauffement varié',
 '6x200m à 85-90% CSS — récup 30'' entre chaque',
 '30'' bord entre chaque',
 '200m retour au calme',
 'Six fois 200m — 1200m de travail de qualité. La gestion de l''allure sur 200m est la compétence clé. Pars régulier et maintiens jusqu''à la touche.',
 ARRAY['olympique', '70.3', 'ironman'], 'triathlon', ARRAY['natation'], 25),

('NAT-22', 'natation', 'natation', 'Intervalles natation — 8x200m endurance', 60, 7,
 '400m échauffement varié',
 '8x200m à 82-87% CSS — récup 25'' entre chaque',
 '25'' bord entre chaque',
 '200m retour au calme',
 'Huit fois 200m — 1600m de qualité avec peu de récup. L''économie de nage devient cruciale à partir du 5ème. Reste technique même quand tu es fatigué.',
 ARRAY['70.3', 'ironman'], 'triathlon', ARRAY['natation'], 26),

('NAT-23', 'natation', 'natation', 'Intervalles natation — 5x300m seuil', 55, 8,
 '400m échauffement varié',
 '5x300m à 83-88% CSS — récup 40'' entre chaque',
 '40'' bord entre chaque',
 '200m retour au calme',
 'Cinq fois 300m au seuil — 1500m de travail intensif. La gestion de l''effort sur 300m est délicate : trop vite au départ et tu coules sur les 100 derniers mètres.',
 ARRAY['olympique', '70.3', 'ironman'], 'triathlon', ARRAY['natation'], 35),

('NAT-24', 'natation', 'natation', 'Intervalles natation — 3x500m tempo', 55, 7,
 '400m échauffement varié',
 '3x500m à 80-85% CSS — récup 1min entre chaque',
 '1min bord entre chaque',
 '200m retour au calme',
 'Le 500m en natation demande une vraie gestion de l''effort sur la durée. Pars conservateur — les 100 derniers mètres de chaque bloc doivent rester à allure.',
 ARRAY['70.3', 'ironman'], 'triathlon', ARRAY['natation'], 45),

('NAT-25', 'natation', 'natation', 'Intervalles natation — 4x500m volume seuil', 65, 7,
 '400m échauffement varié',
 '4x500m à 80-85% CSS — récup 1min entre chaque',
 '1min bord entre chaque',
 '200m retour au calme',
 'Deux kilomètres de travail de qualité au seuil. Séance de référence pour Ironman. La régularité entre les 4 blocs est l''objectif principal.',
 ARRAY['ironman'], 'triathlon', ARRAY['natation'], 46),

-- ── Fractionné long nat ───────────────────────────────────────
('NAT-26', 'natation', 'natation', 'Endurance longue — 2x800m', 55, 7,
 '400m échauffement varié',
 '2x800m à 78-83% CSS — récup 1min30 entre les 2 blocs',
 '1min30 bord entre les 2 blocs',
 '200m retour au calme',
 'Le 800m en natation, c''est presque un kilomètre non-stop. La gestion mentale est importante. Fractionne en 4x200m dans ta tête — ça aide à tenir l''allure.',
 ARRAY['70.3', 'ironman'], 'triathlon', ARRAY['natation'], 55),

('NAT-27', 'natation', 'natation', 'Endurance longue — 1000m + 800m + 400m dégressif', 60, 7,
 '400m échauffement varié',
 '1000m à 78-82% CSS → récup 1min30 → 800m à 82-85% CSS → récup 1min → 400m à 87-90% CSS',
 'Récup variable selon la distance (1min30 / 1min)',
 '200m retour au calme',
 'La distance diminue, la vitesse augmente. Tu finis en sprint relatif après 1800m de travail. Séance complète qui développe l''endurance et la vitesse en une seule session.',
 ARRAY['70.3', 'ironman'], 'triathlon', ARRAY['natation'], 58),

('NAT-28', 'natation', 'natation', 'Volume endurance — 2500m avec blocs', 70, 6,
 '300m nage libre lente',
 '500m EF → 8x100m à 85% CSS (récup 20'') → 500m EF → 4x200m à 82% CSS (récup 30'') → 400m EF',
 'Variable selon les blocs',
 '200m retour au calme',
 'Grosse séance d''endurance 2500m avec des blocs de qualité intercalés. Pour Ironman avancé. Hydrate-toi bien avant et prévois de la nourriture si tu nages plus de 60min.',
 ARRAY['ironman'], 'triathlon', ARRAY['natation'], 68),

('NAT-29', 'natation', 'natation', 'Volume endurance — 3500m continu et blocs', 85, 6,
 '300m nage libre lente',
 '1000m EF → 5x200m à 83% CSS (récup 25'') → 1000m EF → 3x300m à 80% CSS (récup 40'') → 500m EF',
 'Variable selon les blocs',
 '200m retour au calme',
 'Séance phare Ironman. Trois mille cinq cents mètres — très proche de la distance réelle (3,8km). L''objectif est de maintenir une technique correcte malgré la fatigue progressive.',
 ARRAY['ironman'], 'triathlon', ARRAY['natation'], 72),

-- ── Natation spécifique triathlon ────────────────────────────
('NAT-30', 'natation', 'natation', 'Open water simulation — Nage sans lignes', 45, 6,
 '300m nage libre lente piscine',
 '40min nage en eau libre ou piscine sans regarder le fond — pratique de la navigation à vue (sighting toutes les 8-10 brasses)',
 NULL,
 '100m retour au calme',
 'Le sighting (lever la tête pour se repérer) est la compétence n°1 en eau libre. Lève les yeux toutes les 8-10 brasses. Trop souvent = fatigue du cou + mauvaise nage. Pas assez = tu zigzagues et perds 100m.',
 ARRAY['sprint', 'olympique', '70.3', 'ironman'], 'triathlon', ARRAY['natation'], 75),

('NAT-31', 'natation', 'natation', 'Simulation remontée de groupe — Nage contact', 45, 7,
 '400m échauffement varié',
 '5x200m en groupe serré (si possible) ou avec obstacles simulés — habitue-toi au contact physique et à maintenir ton allure malgré les perturbations',
 '30'' entre chaque',
 '200m retour au calme',
 'En triathlon, la nage se fait en groupe. Les premiers 200m sont chaotiques : coups, poussées, changements de direction. Entraîne-toi au contact. L''objectif : ne pas paniquer et maintenir ton allure.',
 ARRAY['sprint', 'olympique', '70.3', 'ironman'], 'triathlon', ARRAY['natation'], 76),

('NAT-32', 'natation', 'natation', 'Test CSS — Détermination allure de référence', 50, 8,
 '400m échauffement progressif',
 '400m time trial à fond → récup 5min → 200m time trial à fond — calcul CSS : (400m - 200m) / 200m en secondes par 100m',
 '5min récup complète entre les 2 time trials',
 '200m retour au calme',
 'Le test CSS (Critical Swim Speed) est ton équivalent VMA en natation. Il te donne ton allure de référence pour calibrer toutes tes séances. Donne tout sur les 2 time trials — c''est un test, pas un entraînement.',
 ARRAY['sprint', 'olympique', '70.3', 'ironman'], 'triathlon', ARRAY['natation'], 77),

('NAT-33', 'natation', 'natation', 'Pyramide longue — 200-400-600-400-200m', 60, 7,
 '400m échauffement varié',
 '200m à 90% CSS → récup 30'' → 400m à 85% CSS → récup 45'' → 600m à 80% CSS → récup 45'' → 400m à 85% CSS → récup 30'' → 200m à 90% CSS',
 'Variable : 30'' sur les 200m, 45'' sur les 400/600m',
 '200m retour au calme',
 'La grande pyramide natation — 1800m de travail. Tu montes puis tu redescends en distance. La 2ème partie (après le 600m) arrive sur des bras fatigués — l''allure doit quand même tenir.',
 ARRAY['olympique', '70.3', 'ironman'], 'triathlon', ARRAY['natation'], 52),

-- ── Récupération natation ─────────────────────────────────────
('NAT-34', 'natation', 'natation', 'Récupération active — 800m très lent', 25, 3,
 NULL,
 '800m nage libre très lente à RPE 3 — focus relâchement, pas de chrono, pas de performance',
 NULL, NULL,
 'Séance de récupération pure. La natation est excellente pour récupérer après une séance de course à pied ou de vélo. L''eau soulage les articulations et active la circulation.',
 ARRAY['sprint', 'olympique', '70.3', 'ironman'], 'triathlon', ARRAY['natation'], 3),

('NAT-35', 'natation', 'natation', 'Récupération active — 1200m varié', 35, 3,
 NULL,
 '400m crawl lent → 200m dos → 200m brasse lente → 200m crawl lent → 200m nage libre au choix — tout à RPE 3',
 NULL, NULL,
 'Récupération en variant les nages. Le dos et la brasse mobilisent différents muscles et permettent un vrai relâchement. Séance idéale le lendemain d''un effort intense.',
 ARRAY['sprint', 'olympique', '70.3', 'ironman'], 'triathlon', ARRAY['natation'], 4),

('NAT-36', 'natation', 'natation', 'Endurance fondamentale — 1800m continu', 50, 6,
 '200m nage libre lente',
 '1800m nage libre à 67-72% CSS — effort régulier et contrôlé, technique maintenue sur toute la distance',
 NULL,
 '100m retour au calme',
 'Dix-huit cents mètres non-stop — belle séance d''endurance. L''objectif est la régularité d''allure sur toute la distance. Pas de sprint, pas de relâchement.',
 ARRAY['olympique', '70.3', 'ironman'], 'triathlon', ARRAY['natation'], 84),

('NAT-37', 'natation', 'natation', 'Endurance fondamentale — 2500m continu', 65, 6,
 '200m nage libre lente',
 '2500m nage libre à 65-70% CSS — effort endurance long, reste économique',
 NULL,
 '200m retour au calme',
 'Deux mille cinq cents mètres non-stop. Pour Ironman 70.3 notamment (1900m en course). Si tu tiens 2500m à l''entraînement, la distance de course est dans tes cordes.',
 ARRAY['70.3', 'ironman'], 'triathlon', ARRAY['natation'], 88),

('NAT-38', 'natation', 'natation', 'Blocs mixtes — Vitesse + Endurance', 55, 8,
 '400m échauffement varié',
 '4x50m sprint (95% CSS) récup 30'' → 400m EF → 4x100m fort (88% CSS) récup 25'' → 400m EF → 4x50m sprint (95% CSS) récup 30''',
 'Variable selon les blocs',
 '200m retour au calme',
 'Alternance vitesse et endurance dans la même séance. Ton système aérobie et anaérobie travaillent ensemble. Les blocs vitesse en fin de séance arrivent sur des bras fatigués — excellent pour développer la résistance à la vitesse.',
 ARRAY['sprint', 'olympique', '70.3'], 'triathlon', ARRAY['natation'], 62),

('NAT-39', 'natation', 'natation', 'Tempo natation — 2x800m seuil', 55, 8,
 '400m échauffement varié',
 '2x800m à 83-87% CSS — récup 1min30 entre les 2 blocs',
 '1min30 bord entre les 2 blocs',
 '200m retour au calme',
 'Deux blocs de 800m au seuil — 1600m de travail intensif. Le 2ème bloc arrive sur des épaules chargées. S''il tient l''allure du 1er, tu es en très bonne forme.',
 ARRAY['70.3', 'ironman'], 'triathlon', ARRAY['natation'], 57),

('NAT-40', 'natation', 'natation', 'Simulation départ course — 3x400m relance', 50, 9,
 '400m échauffement varié',
 '3 départs toutes les 8min : 400m à fond dès le premier mètre → récup passive jusqu''au prochain départ',
 'Récup passive jusqu''au top départ suivant',
 '200m retour au calme',
 'Trois fois un départ de course. En triathlon, les premières centaines de mètres sont à fond — les meilleurs positions se prennent dès le départ. Entraîne-toi à partir vite ET à tenir ensuite.',
 ARRAY['sprint', 'olympique', '70.3'], 'triathlon', ARRAY['natation'], 78);


-- ============================================================
-- VÉLO — 28 nouvelles séances (total ~40)
-- ============================================================
INSERT INTO public.session_library (code, type, category, name, duration_min, intensity_rpe, warmup, main_set, recovery, cooldown, coach_notes, compatible_goals, sport, triathlon_disciplines, sort_order) VALUES

-- ── Récupération vélo ─────────────────────────────────────────
('VEL-13', 'velo', 'velo', 'Récupération vélo — 45min très lent', 45, 2,
 NULL,
 '45 min pédalage à 55-65% FTP (zone 1) — jambes qui tournent, aucune intensité',
 NULL, NULL,
 'Récupération pure sur le vélo. La cadence doit être confortable (80-90 rpm) avec très peu de résistance. L''objectif est d''activer la circulation et d''accélérer la récupération musculaire.',
 ARRAY['sprint', 'olympique', '70.3', 'ironman'], 'triathlon', ARRAY['velo'], 3),

('VEL-14', 'velo', 'velo', 'Récupération vélo — 60min actif doux', 60, 3,
 NULL,
 '60 min à 58-65% FTP — pédalage fluide, pas d''effort, haute cadence légère (90-100 rpm)',
 NULL, NULL,
 'Soixante minutes de récupération active. La haute cadence sur braquet léger est idéale pour récupérer sans se fatiguer. Ne sois pas tenté d''augmenter l''intensité.',
 ARRAY['70.3', 'ironman'], 'triathlon', ARRAY['velo'], 4),

-- ── Endurance vélo ────────────────────────────────────────────
('VEL-15', 'velo', 'velo', 'Endurance vélo — 45min fondamental', 45, 5,
 '5 min pédalage lent zone 1',
 '40 min à 65-72% FTP (zone 2) — cadence 85-90 rpm, allure stable',
 NULL,
 '5 min pédalage très lent',
 'Séance courte mais ciblée. Quarante minutes à zone 2 — c''est la base de tout. La zone 2 est souvent sous-estimée mais c''est là que se construit l''endurance fondamentale.',
 ARRAY['sprint', 'olympique'], 'triathlon', ARRAY['velo'], 88),

('VEL-16', 'velo', 'velo', 'Endurance vélo — 2h15 fondamental', 135, 6,
 '10 min pédalage lent zone 1',
 '2h à 65-75% FTP — effort stable et régulier, terrain varié',
 NULL,
 '5 min pédalage très lent',
 'Deux heures et quart de vélo. La durée est le principal stimulus. Mange toutes les 45min. Reste dans ta zone 2-3 et ne te laisse pas emporter par les descentes.',
 ARRAY['70.3', 'ironman'], 'triathlon', ARRAY['velo'], 102),

('VEL-17', 'velo', 'velo', 'Endurance vélo — 3h fondamental long', 180, 6,
 '10 min pédalage lent zone 1',
 '2h45 à 65-72% FTP — volume endurance marathon, ravitaillement régulier',
 NULL,
 '10 min pédalage très lent',
 'Trois heures de vélo — tu entres dans la préparation Ironman sérieuse. Ravitaillement : 60-80g de glucides/heure, eau régulière. Ne pars pas trop fort les 30 premières minutes.',
 ARRAY['ironman'], 'triathlon', ARRAY['velo'], 108),

('VEL-18', 'velo', 'velo', 'Endurance vélo — 3h30 ultra longue', 210, 6,
 '10 min pédalage lent zone 1',
 '3h10 à 63-70% FTP — endurance ultra, allure très conservative, ravitaillement planifié',
 NULL,
 '10 min pédalage très lent',
 'Trois heures trente — la grande sortie vélo Ironman. Plan nutrition obligatoire avant de partir : gel toutes les 30-40min, eau toutes les 15-20min. Pars TROP lentement — tu ne regretteras pas.',
 ARRAY['ironman'], 'triathlon', ARRAY['velo'], 115),

-- ── Intervalles courts vélo ───────────────────────────────────
('VEL-19', 'velo', 'velo', 'Intervalles courts — 10x1min VO2max', 55, 9,
 '15 min progressif zone 1-2',
 '10x1min à 115-125% FTP (zone 5) — effort maximal, récup 1min zone 1 entre chaque',
 '1min zone 1 entre chaque intervalle',
 '10 min pédalage très lent',
 'Une minute à 120% FTP, c''est très intense. L''objectif est de déclencher une adaptation VO2max. Chaque intervalle doit être aussi dur que le premier — si tu chutes, augmente la récup.',
 ARRAY['sprint', 'olympique'], 'triathlon', ARRAY['velo'], 18),

('VEL-20', 'velo', 'velo', 'Intervalles courts — 12x2min zone 4-5', 60, 9,
 '15 min progressif zone 1-2',
 '12x2min à 105-115% FTP — effort fort et régulier, récup 1min entre chaque',
 '1min zone 1 entre chaque',
 '10 min pédalage très lent',
 'Douze fois 2 minutes à intensité élevée — 24 minutes de travail intense. La régularité sur les 12 intervalles est l''objectif. Si les 3 derniers s''effondrent, passe à 10x.',
 ARRAY['sprint', 'olympique', '70.3'], 'triathlon', ARRAY['velo'], 19),

('VEL-21', 'velo', 'velo', 'Sprints sur résistance — 6x10sec maximaux', 50, 9,
 '20 min progressif avec accélérations',
 '6x10sec sprint maximal en danseuse (grand braquet) — récup 5min complète entre chaque sprint',
 '5min récup complète zone 1 entre chaque sprint',
 '10 min pédalage très lent',
 'Dix secondes à fond sur grand braquet — travail neuromusculaire pur. La puissance développée dépasse 200% du FTP. La récup de 5min est obligatoire pour maintenir la qualité.',
 ARRAY['sprint', 'olympique'], 'triathlon', ARRAY['velo'], 17),

-- ── Intervalles moyens vélo ───────────────────────────────────
('VEL-22', 'velo', 'velo', 'Sweetspot — 3x15min zone 3-4', 75, 7,
 '15 min progressif zone 1-2',
 '3x15min à 88-93% FTP (sweetspot) — effort soutenu mais gérable, cadence 88-92 rpm',
 '5min zone 1-2 entre chaque',
 '10 min pédalage très lent',
 'Le sweetspot (88-93% FTP) est la zone la plus rentable en cyclisme : assez intense pour provoquer des adaptations, assez gérable pour récupérer rapidement. Séance à faire 1-2x par semaine.',
 ARRAY['olympique', '70.3', 'ironman'], 'triathlon', ARRAY['velo'], 37),

('VEL-23', 'velo', 'velo', 'Sweetspot — 2x25min zone 3-4', 80, 7,
 '15 min progressif zone 1-2',
 '2x25min à 88-93% FTP — effort constant, cadence régulière 88-92 rpm',
 '7min zone 1-2 entre les 2 blocs',
 '10 min pédalage très lent',
 'Deux longs blocs au sweetspot — 50 minutes de qualité au total. La récup de 7 minutes est suffisante pour tenir le 2ème bloc. Si le 2ème est nettement moins bon, c''est une info sur ta forme.',
 ARRAY['70.3', 'ironman'], 'triathlon', ARRAY['velo'], 42),

('VEL-24', 'velo', 'velo', 'Sweetspot — 3x20min zone 3-4', 85, 7,
 '15 min progressif zone 1-2',
 '3x20min à 88-93% FTP — effort régulier sur les 3 blocs',
 '5min zone 1-2 entre chaque',
 '10 min pédalage très lent',
 'Soixante minutes de sweetspot au total — séance de référence pour Ironman. Si tu tiens les 3 blocs à la même puissance, tu es dans une excellente forme.',
 ARRAY['70.3', 'ironman'], 'triathlon', ARRAY['velo'], 43),

('VEL-25', 'velo', 'velo', 'Intervalles 4min — 6x4min zone 4-5', 65, 9,
 '15 min progressif zone 1-2',
 '6x4min à 100-110% FTP — effort maximal soutenu, cadence 85-90 rpm',
 '4min zone 1-2 entre chaque',
 '10 min pédalage très lent',
 'La séance classique de développement FTP. Six fois 4 minutes à intensité élevée. Si tu dois choisir une seule séance vélo pour progresser, c''est probablement celle-là.',
 ARRAY['sprint', 'olympique', '70.3'], 'triathlon', ARRAY['velo'], 32),

-- ── Tempo et FTP vélo ─────────────────────────────────────────
('VEL-26', 'velo', 'velo', 'FTP Test — 20min effort maximal', 60, 10,
 '20 min progressif avec 2x1min à 110% FTP, récup 5min',
 '20min effort maximal constant (ton FTP = 95% de la puissance moyenne sur 20min)',
 NULL,
 '15 min pédalage très lent',
 'Test FTP obligatoire tous les 6-8 semaines. Donne TOUT sur 20 minutes — vitesse régulière, pas de sprint final gardé en réserve. La puissance moyenne x 0,95 = ton FTP. Note-le et recalibre toutes tes zones.',
 ARRAY['sprint', 'olympique', '70.3', 'ironman'], 'triathlon', ARRAY['velo'], 78),

('VEL-27', 'velo', 'velo', 'Tempo long — 60min continu zone 3', 85, 7,
 '15 min progressif zone 1-2',
 '60min continu à 76-83% FTP (zone 3) — effort aérobie soutenu, régulier',
 NULL,
 '10 min pédalage très lent',
 'Soixante minutes au tempo — très spécifique Ironman. L''allure est gérable mais demande de la concentration pour rester dans la zone. Ne monte pas en zone 4 même si tu te sens bien.',
 ARRAY['ironman'], 'triathlon', ARRAY['velo'], 80),

('VEL-28', 'velo', 'velo', 'Blocs pyramide — 5-10-15-10-5min FTP', 80, 8,
 '15 min progressif zone 1-2',
 '5min à 100% FTP → récup 3min → 10min à 95% FTP → récup 4min → 15min à 90% FTP → récup 4min → 10min à 95% FTP → récup 3min → 5min à 100% FTP',
 'Récup variable : 3-4min zone 1-2 entre chaque bloc',
 '10 min pédalage très lent',
 'Pyramide de puissance : tu montes en durée en descendant l''intensité, puis tu inverses. Quarante-cinq minutes de travail au total. La dernière montée en puissance à 100% FTP sur jambes chargées est le vrai test.',
 ARRAY['olympique', '70.3'], 'triathlon', ARRAY['velo'], 62),

-- ── Spécifique triathlon vélo ─────────────────────────────────
('VEL-29', 'velo', 'velo', 'Position aéro — 4x20min en position TT', 110, 7,
 '15 min pédalage lent zone 1',
 '4x20min à 78-83% FTP en position aéro (guidon bas, coudes sur les extensions) — 5min position normale entre chaque',
 '5min position normale zone 2 entre chaque',
 '10 min pédalage lent',
 'S''habituer à la position aéro est obligatoire en triathlon. Tu vas plus vite mais tu es moins à l''aise. L''entraînement dans cette position améliore le confort et prépare tes muscles à produire de la puissance en position basse.',
 ARRAY['olympique', '70.3', 'ironman'], 'triathlon', ARRAY['velo'], 65),

('VEL-30', 'velo', 'velo', 'Simulation T2 — Vélo 1h + transition + course 20min', 90, 7,
 '10 min pédalage lent zone 1',
 'Vélo : 50min à 78-83% FTP → descente de vélo → chaussures de course → Course : 20min à 72-78% VMA',
 NULL, NULL,
 'Focus sur la transition T2 : descendre du vélo, chausser les baskets, repartir en course. Tes jambes vont sembler lourdes — normal. Cette séance t''apprend à gérer cette sensation. Pas d''arrêt entre le vélo et la course.',
 ARRAY['olympique', '70.3', 'ironman'], 'triathlon', ARRAY['velo', 'course'], 69),

('VEL-31', 'velo', 'velo', 'Vélo côtes longues — 4x8min montée soutenue', 80, 8,
 '15 min progressif zone 1-2',
 '4x8min de montée en côte à 95-105% FTP — position assise, appui régulier',
 'Descente lente zone 1-2 entre chaque montée',
 '10 min pédalage très lent',
 'Les côtes longues en vélo développent la force et le FTP en même temps. Reste assis le plus possible — la force vient des cuisses, pas du dos. La descente est ta récupération.',
 ARRAY['olympique', '70.3', 'ironman'], 'triathlon', ARRAY['velo'], 52),

('VEL-32', 'velo', 'velo', 'Vélo côtes — 8x3min relances fortes', 65, 9,
 '15 min progressif zone 1-2',
 '8x3min en côte à 105-118% FTP — relance explosive, effort maximal sur chaque montée',
 'Descente lente récup complète entre chaque',
 '10 min pédalage très lent',
 'Relances explosives en côte — tu dépasses ton FTP sur chaque effort. Développe la puissance de pointe et la capacité à suivre un groupe ou à attaquer. Les 3 dernières arriveront sur des jambes chargées.',
 ARRAY['sprint', 'olympique'], 'triathlon', ARRAY['velo'], 26),

('VEL-33', 'velo', 'velo', 'Vélo vent de face — 3x15min résistance', 75, 8,
 '15 min progressif zone 1-2',
 '3x15min contre le vent ou sur braquet élevé à 95-103% FTP — simule la résistance aérodynamique',
 '5min zone 1-2 entre chaque',
 '10 min pédalage très lent',
 'Rouler contre le vent développe la force et la résistance mentale. Si tu n''as pas de vent, augmente le braquet pour simuler. La puissance maintenue contre une résistance élevée = adaptation FTP.',
 ARRAY['olympique', '70.3', 'ironman'], 'triathlon', ARRAY['velo'], 48),

('VEL-34', 'velo', 'velo', 'Sur home-trainer — Séance structurée 5x6min', 70, 8,
 '15 min progressif',
 '5x6min à 95-105% FTP — effort soutenu sur home-trainer, cadence 85-90 rpm',
 '4min zone 1 entre chaque',
 '10 min pédalage très lent',
 'Le home-trainer est parfait pour les séances structurées : pas de feux, pas de descentes, puissance constante. Trente minutes de travail de qualité au total. L''environnement contrôlé te permet de vraiment cibler ta zone.',
 ARRAY['olympique', '70.3', 'ironman'], 'triathlon', ARRAY['velo'], 36),

('VEL-35', 'velo', 'velo', 'Endurance avec accélérations — 2h + 4x3min fort', 130, 7,
 '10 min pédalage lent zone 1',
 '90min à 68-75% FTP → 4x3min à 105-112% FTP (récup 5min entre chaque) → 15min à 68-72% FTP',
 '5min zone 1-2 entre les 4 accélérations',
 '5 min pédalage très lent',
 'Sortie longue avec des pics d''intensité intercalés. Les accélérations arrivent sur des jambes déjà chargées — c''est exactement ce qui se passe en course quand tu dois répondre à une attaque ou accélérer dans une montée.',
 ARRAY['70.3', 'ironman'], 'triathlon', ARRAY['velo'], 106),

('VEL-36', 'velo', 'velo', 'Vélo montagne — 3h avec 1500m D+', 180, 7,
 '10 min pédalage lent',
 '3h sur route ou chemin montagneux avec 1200-1500m de D+ — gestion de l''effort sur les montées et les descentes',
 NULL,
 '10 min pédalage lent',
 'La montagne en vélo — ça change tout. La gestion de l''effort est différente : économise-toi sur les montées, récupère en descente. Ravitaillement solide obligatoire. C''est la meilleure préparation pour les Ironman vallonnés.',
 ARRAY['70.3', 'ironman'], 'triathlon', ARRAY['velo'], 112),

('VEL-37', 'velo', 'velo', 'Cadence basse — Force musculaire 6x5min', 65, 7,
 '15 min progressif zone 1-2',
 '6x5min à 65-70 rpm en zone 3 (braquet lourd) — développe la force musculaire spécifique vélo',
 '3min zone 1 cadence normale entre chaque',
 '10 min pédalage très lent',
 'La cadence basse avec braquet lourd = musculation sur le vélo. Tes quadriceps vont travailler comme jamais. Séance complémentaire parfaite avec les séances de force en salle.',
 ARRAY['olympique', '70.3', 'ironman'], 'triathlon', ARRAY['velo'], 22),

('VEL-38', 'velo', 'velo', 'Intervalles décroissants — 8-6-4-2min FTP+', 70, 9,
 '15 min progressif zone 1-2',
 '8min à 95% FTP → récup 4min → 6min à 100% FTP → récup 3min → 4min à 108% FTP → récup 2min → 2min à 115% FTP',
 'Récup décroissante entre chaque bloc (4/3/2min)',
 '10 min pédalage très lent',
 'La durée diminue, l''intensité augmente, la récup aussi se réduit. Tu finis en effort quasi-maximal sur 2 minutes après 18 minutes de travail. La séance qui révèle ton niveau réel. Ne triche pas sur les allures.',
 ARRAY['sprint', 'olympique', '70.3'], 'triathlon', ARRAY['velo'], 58),

('VEL-39', 'velo', 'velo', 'Endurance active — 1h45 avec 2x10min seuil', 105, 7,
 '10 min pédalage lent zone 1',
 '40min à 68-75% FTP → 10min à 88-93% FTP → 20min à 68-72% FTP → 10min à 88-93% FTP → 15min à 68-72% FTP',
 NULL,
 '10 min pédalage très lent',
 'Sortie endurance avec 2 blocs de qualité intercalés. Les blocs à 88-93% FTP arrivent sur des jambes déjà sollicitées. Belle séance de transition entre endurance pure et intensité.',
 ARRAY['70.3', 'ironman'], 'triathlon', ARRAY['velo'], 104),

('VEL-40', 'velo', 'velo', 'Vélo VO2max — 5x3min à 115% FTP', 60, 9,
 '20 min progressif avec accélérations',
 '5x3min à 112-120% FTP — effort VO2max, récup 3min entre chaque',
 '3min zone 1 entre chaque',
 '10 min pédalage très lent',
 'Séance VO2max vélo. Trois minutes à 115% FTP, c''est extrêmement dur. Chaque intervalle doit être donné à fond. La récup de 3min est juste suffisante. Si tu ne peux pas tenir l''allure, réduis à 110%.',
 ARRAY['sprint', 'olympique'], 'triathlon', ARRAY['velo'], 20);


-- ============================================================
-- BRIQUE — 30 nouvelles séances (total ~40)
-- ============================================================
INSERT INTO public.session_library (code, type, category, name, duration_min, intensity_rpe, warmup, main_set, recovery, cooldown, coach_notes, compatible_goals, sport, triathlon_disciplines, sort_order) VALUES

-- ── Briques courtes / introduction ───────────────────────────
('BRI-11', 'brique', 'brique', 'Micro-brique — Vélo 15min + Course 10min', 35, 6,
 '5 min pédalage lent',
 'Vélo : 15min à 72-78% FTP → transition T2 → Course : 10min à 68-75% VMA',
 NULL, NULL,
 'La plus courte des briques — parfaite pour débuter. Dix minutes de course après 15min de vélo te donnent la première sensation de jambes en béton. Accueille cette sensation : elle disparaît à mesure que tu multiplies les briques.',
 ARRAY['sprint'], 'triathlon', ARRAY['velo', 'course'], 5),

('BRI-12', 'brique', 'brique', 'Brique transition — Vélo 25min + Course 12min', 45, 6,
 '5 min pédalage lent',
 'Vélo : 25min à 73-80% FTP → transition T2 chronométrée → Course : 12min à 68-75% VMA',
 NULL, NULL,
 'Chronomètre ta transition T2. L''objectif est de la réduire chaque semaine. Entraîne-toi à : descendre du vélo, enlever le casque, chausser les baskets. Chaque geste doit être automatique.',
 ARRAY['sprint'], 'triathlon', ARRAY['velo', 'course'], 6),

-- ── Briques natation + vélo ───────────────────────────────────
('BRI-13', 'brique', 'brique', 'Brique T1 — Nage 750m + Vélo 20min', 50, 7,
 NULL,
 'Nage : 750m à allure course → T1 rapide (sortie eau, vélo) → Vélo : 20min à 75-82% FTP',
 NULL, NULL,
 'Simulation de T1. En sortant de l''eau, ton rythme cardiaque est élevé et tes bras sont fatigués. Gère tes premières minutes de vélo avec sagesse — ne pars pas à fond immédiatement.',
 ARRAY['sprint', 'olympique'], 'triathlon', ARRAY['natation', 'velo'], 15),

('BRI-14', 'brique', 'brique', 'Brique T1 — Nage 1000m + Vélo 30min', 65, 7,
 NULL,
 'Nage : 1000m à allure course → T1 rapide → Vélo : 30min à 75-82% FTP',
 NULL, NULL,
 'Mille mètres de nage puis 30min de vélo. Les jambes sont fraîches pour le vélo mais les bras et le souffle sont travaillés. Trouve ton rythme de pédalage dans les 5 premières minutes.',
 ARRAY['olympique', '70.3'], 'triathlon', ARRAY['natation', 'velo'], 16),

('BRI-15', 'brique', 'brique', 'Brique T1 complète — Nage 1500m + Vélo 45min', 85, 7,
 NULL,
 'Nage : 1500m à allure olympique → T1 rapide → Vélo : 45min à 75-82% FTP',
 NULL, NULL,
 'Simulation distance olympique T1 complète. La vraie course démarre sur le vélo après 1500m de nage. Tes premières minutes de vélo te diront beaucoup sur ta gestion de l''énergie en nage.',
 ARRAY['olympique'], 'triathlon', ARRAY['natation', 'velo'], 17),

-- ── Briques fractionnées ──────────────────────────────────────
('BRI-16', 'brique', 'brique', 'Brique fractionnée — 5x(10min vélo + 3min course)', 80, 8,
 '10 min vélo lent zone 1',
 '5 séries de : 10min vélo à 82-90% FTP → transition → 3min course à 78-83% VMA — récup 2min vélo lent entre séries',
 '2min vélo lent zone 1 entre chaque série',
 '5 min vélo lent',
 'Cinq transitions dans la même séance — tu t''habitues à la sensation répétée. Chaque transition doit être aussi propre que la première. Les 3min de course arrivent plus vite qu''on ne le pense.',
 ARRAY['sprint', 'olympique'], 'triathlon', ARRAY['velo', 'course'], 12),

('BRI-17', 'brique', 'brique', 'Brique fractionnée — 4x(20min vélo + 5min course)', 110, 8,
 '10 min vélo lent zone 1',
 '4 séries de : 20min vélo à 80-87% FTP → transition → 5min course à 75-80% VMA — récup 3min vélo lent entre séries',
 '3min vélo lent zone 1 entre chaque série',
 '5 min vélo lent',
 'Version longue de la brique fractionnée. Quatre transitions — la dernière arrive sur des jambes vraiment fatiguées. C''est cette fatigue accumulée qui fait l''entraînement. Gère bien les 20 premières minutes de vélo.',
 ARRAY['olympique', '70.3'], 'triathlon', ARRAY['velo', 'course'], 13),

-- ── Briques simulation distance ───────────────────────────────
('BRI-18', 'brique', 'brique', 'Brique simulation olympique — Vélo 25km + Course 5km', 100, 8,
 '10 min vélo progressif zone 1-2',
 'Vélo : 25km à 80-87% FTP → transition T2 → Course : 5km à 85-90% VMA',
 NULL, NULL,
 'Simulation partielle distance olympique (moitié du vélo, tout le 5km). La course à 85-90% VMA après 25km de vélo — c''est la vraie simulation. Pas de ménagement sur la course.',
 ARRAY['olympique'], 'triathlon', ARRAY['velo', 'course'], 22),

('BRI-19', 'brique', 'brique', 'Brique simulation 70.3 — Vélo 45km + Course 10km', 155, 7,
 '10 min vélo progressif zone 1-2',
 'Vélo : 45km à 76-83% FTP → transition T2 → Course : 10km à 78-83% VMA',
 NULL, NULL,
 'Simulation partielle 70.3 (la moitié du vélo + tout le run). Gérer un 10km après 45km de vélo — c''est là que se gagne ou se perd un 70.3. Pars conservateur sur la course et monte en régime.',
 ARRAY['70.3'], 'triathlon', ARRAY['velo', 'course'], 45),

('BRI-20', 'brique', 'brique', 'Brique simulation 70.3 complète — Vélo 90km + Course 21km', 280, 7,
 '10 min vélo progressif zone 1-2',
 'Vélo : 90km à 73-78% FTP → transition T2 → Course : 21km à 73-78% VMA (demi-marathon sur jambes vélo)',
 NULL, NULL,
 'La grande brique 70.3. Quatre heures d''effort total — cette séance transforme. L''allure course doit être très gérée : un 70.3 se gagne sur le run, pas sur le vélo. Ne part pas trop fort sur le vélo.',
 ARRAY['70.3'], 'triathlon', ARRAY['velo', 'course'], 88),

('BRI-21', 'brique', 'brique', 'Brique simulation Ironman — Vélo 4h + Course 1h', 300, 6,
 '10 min vélo lent zone 1',
 'Vélo : 4h à 63-70% FTP → transition T2 → Course : 1h à 65-70% VMA (très conservateur)',
 NULL, NULL,
 'La brique Ironman ultime. Cinq heures d''effort. La course d''une heure doit être très conservative — l''objectif n''est pas la performance, c''est l''adaptation à l''enchaînement. Ravitaillement planifié toutes les 30-40min sur le vélo.',
 ARRAY['ironman'], 'triathlon', ARRAY['velo', 'course'], 98),

-- ── Briques avec intervalles ──────────────────────────────────
('BRI-22', 'brique', 'brique', 'Brique intensive — Vélo fort + Course seuil', 75, 9,
 '10 min vélo progressif zone 1-2',
 'Vélo : 30min à 90-97% FTP → transition T2 → Course : 25min à 85-90% VMA (allure seuil)',
 NULL, NULL,
 'Brique haute intensité — les deux disciplines sont courrues fort. La course à allure seuil après 30min de vélo intense teste ta vraie endurance spécifique. Réserve cette séance pour les phases de construction avancées.',
 ARRAY['sprint', 'olympique'], 'triathlon', ARRAY['velo', 'course'], 25),

('BRI-23', 'brique', 'brique', 'Brique avec accélérations — Vélo 1h + Course progressive', 85, 8,
 '10 min vélo progressif zone 1-2',
 'Vélo : 50min à 72-80% FTP → transition T2 → Course : 10min à 70-75% VMA + 10min à 80-85% VMA + 5min à 87-92% VMA',
 NULL, NULL,
 'La course en brique doit être progressive — tu ne peux pas partir vite d''emblée. Cette séance t''apprend à monter en régime après le vélo. Les 5 dernières minutes à allure 10km sur jambes chargées sont très formatives.',
 ARRAY['olympique', '70.3'], 'triathlon', ARRAY['velo', 'course'], 35),

('BRI-24', 'brique', 'brique', 'Brique seuil — 3x(15min vélo seuil + 8min course seuil)', 90, 9,
 '10 min vélo lent zone 1',
 '3 blocs : 15min vélo à 90-98% FTP → transition → 8min course à 85-90% VMA — récup 4min vélo lent entre blocs',
 '4min vélo lent zone 1 entre chaque bloc',
 '5 min vélo lent',
 'Trois blocs au seuil dans les deux disciplines. Soixante-neuf minutes de travail intense. La fatigue s''accumule sur les 3 blocs — le dernier bloc de course à 85-90% VMA arrive sur des jambes vraiment chargées.',
 ARRAY['olympique', '70.3'], 'triathlon', ARRAY['velo', 'course'], 28),

-- ── Briques spécifiques ───────────────────────────────────────
('BRI-25', 'brique', 'brique', 'Brique transition T1 rapide — Entraînement transitions', 60, 6,
 NULL,
 'Piscine : 10x100m à 85% CSS → T1 chronométré 5 fois → Vélo : 4x10min zone 3 avec transitions répétées entre les blocs',
 NULL, NULL,
 'Séance dédiée aux transitions. Objectif : T1 < 2min pour sprint, < 3min pour olympique. Travaille la séquence : sortie eau, casque, lunettes, chaussures vélo. Répète jusqu''à ce que ce soit automatique.',
 ARRAY['sprint', 'olympique'], 'triathlon', ARRAY['natation', 'velo'], 8),

('BRI-26', 'brique', 'brique', 'Brique mentale — Vélo 2h30 + Course 1h sur jambes fatiguées', 210, 6,
 '10 min vélo lent zone 1',
 'Vélo : 2h20 à 65-72% FTP → transition T2 → Course : 60min à 63-68% VMA (récupération active sur jambes chargées)',
 NULL, NULL,
 'Séance mentale et physique. Trois heures trente d''effort — la course d''une heure sur jambes chargées de vélo est un apprentissage inestimable. Va plus lentement que tu ne le penses. Le cerveau dit "arrête", le corps peut continuer.',
 ARRAY['70.3', 'ironman'], 'triathlon', ARRAY['velo', 'course'], 82),

('BRI-27', 'brique', 'brique', 'Brique vélo montagne + course — 2h + 30min', 150, 7,
 '10 min vélo lent',
 'Vélo : 1h50 en terrain vallonné/montagneux à 70-78% FTP → transition T2 → Course : 30min à 68-75% VMA',
 NULL, NULL,
 'Combinaison vélo montagneux + course — prépare les triathlons sur parcours vallonnés. La course après un vélo montagneux est plus difficile qu''après un vélo plat. Tes quadriceps sont plus chargés.',
 ARRAY['70.3', 'ironman'], 'triathlon', ARRAY['velo', 'course'], 75),

('BRI-28', 'brique', 'brique', 'Brique matinale — 3x(10min vélo + 5min course)', 60, 7,
 '5 min vélo lent',
 '3 séries de : 10min vélo à 78-83% FTP → transition → 5min course à 73-78% VMA — récup 2min vélo lent entre séries',
 '2min vélo lent entre chaque série',
 '5 min vélo lent',
 'Brique courte et efficace — parfaite pour les matins chargés. Quarante-cinq minutes d''effort total. Trois transitions dans la matinée. Idéale en période de compétition rapprochée.',
 ARRAY['sprint', 'olympique'], 'triathlon', ARRAY['velo', 'course'], 11),

('BRI-29', 'brique', 'brique', 'Brique nage + vélo + course — Triathlon format S', 75, 8,
 NULL,
 'Nage : 400m à allure course → T1 → Vélo : 15km à 82-88% FTP → T2 → Course : 2.5km à allure 5km',
 NULL, NULL,
 'Format S (super sprint) : 400m nage + 15km vélo + 2.5km course. Plus court qu''un sprint officiel mais parfait pour travailler les 2 transitions en situation de course. Idéal en début de saison.',
 ARRAY['sprint'], 'triathlon', ARRAY['natation', 'velo', 'course'], 20),

('BRI-30', 'brique', 'brique', 'Brique récupération — Vélo 40min + Course 20min lents', 65, 4,
 '5 min vélo lent',
 'Vélo : 40min à 60-65% FTP → transition → Course : 20min à 60-65% VMA — allure récupération',
 NULL, NULL,
 'Brique de récupération. Les deux disciplines sont courrues très lentement. L''objectif est juste de pratiquer la transition et de maintenir l''activation musculaire sans se fatiguer.',
 ARRAY['sprint', 'olympique', '70.3', 'ironman'], 'triathlon', ARRAY['velo', 'course'], 4),

('BRI-31', 'brique', 'brique', 'Brique spécifique course — Vélo 1h court + 10km allure', 90, 8,
 '10 min vélo progressif zone 1-2',
 'Vélo : 50min à 76-82% FTP → transition T2 → Course : 10km à allure objectif (90-95% VMA)',
 NULL, NULL,
 'La brique la plus spécifique pour le 10km du triathlon. Le vélo te fatigue, puis tu dois tenir ton allure 10km. Si tu tiens ton allure cible sur le 10km, tu es prêt pour la compétition.',
 ARRAY['olympique'], 'triathlon', ARRAY['velo', 'course'], 30),

('BRI-32', 'brique', 'brique', 'Brique 70.3 partielle — Nage 1900m + Vélo 45km', 130, 7,
 NULL,
 'Nage : 1900m à allure 70.3 → T1 → Vélo : 45km à 75-80% FTP',
 NULL, NULL,
 'Simulation des 2 premières disciplines du 70.3. Travailler la nage + vélo sans la course te permet de te concentrer sur T1 et sur les premières minutes de vélo en sortie d''eau. Économise-toi sur les 10 premiers km de vélo.',
 ARRAY['70.3'], 'triathlon', ARRAY['natation', 'velo'], 55),

('BRI-33', 'brique', 'brique', 'Brique Ironman partielle — Nage 3.8km + Vélo 60km', 225, 6,
 NULL,
 'Nage : 3800m à allure Ironman (très conservateur) → T1 → Vélo : 60km à 65-72% FTP',
 NULL, NULL,
 'Simulation des 2 premières disciplines Ironman. Trois kilomètres huit de nage puis 60km de vélo — tu vas comprendre l''importance de l''économie en nage. Aucune énergie dépensée inutilement en eau.',
 ARRAY['ironman'], 'triathlon', ARRAY['natation', 'velo'], 90),

('BRI-34', 'brique', 'brique', 'Brique dégressive — Vélo fort + Course longue douce', 120, 7,
 '10 min vélo progressif zone 1-2',
 'Vélo : 45min à 85-92% FTP → transition T2 → Course : 50min à 65-70% VMA (endurance douce)',
 NULL, NULL,
 'L''inverse de la brique habituelle : le vélo est intense, la course est douce. Tu apprends à "sauver" tes jambes après un effort vélo élevé pour tenir une course longue. Très spécifique 70.3 et Ironman.',
 ARRAY['70.3', 'ironman'], 'triathlon', ARRAY['velo', 'course'], 70),

('BRI-35', 'brique', 'brique', 'Brique test — Vélo 30min allure course + Course 3km allure course', 65, 9,
 '10 min vélo progressif zone 1-2',
 'Vélo : 30min à 85-92% FTP (allure course sprint/olympique) → transition T2 → Course : 3km à allure objectif 5km (93-100% VMA)',
 NULL, NULL,
 'Brique test — reproduit exactement l''intensité de course. Le vélo est couru à l''allure de course, la course aussi. Séance à faire 2-3 semaines avant la compétition pour valider la forme.',
 ARRAY['sprint', 'olympique'], 'triathlon', ARRAY['velo', 'course'], 32),

('BRI-36', 'brique', 'brique', 'Brique nuit — Vélo 1h + Course 20min en conditions nocturnes', 90, 6,
 '5 min vélo lent',
 'Vélo : 55min à 70-75% FTP (avec éclairage) → transition → Course : 20min à 68-72% VMA (avec lampe frontale)',
 NULL, NULL,
 'Si ton triathlon a une partie nocturne (Ironman parfois), entraîne-toi la nuit. La perception de la vitesse change, la prudence augmente, la gestion thermique est différente. Prévois des éclairages solides.',
 ARRAY['ironman'], 'triathlon', ARRAY['velo', 'course'], 95),

('BRI-37', 'brique', 'brique', 'Brique chaleur — Adaptation conditions chaudes', 80, 7,
 '10 min vélo lent',
 'Vélo : 45min à 68-75% FTP par temps chaud (>25°C) → transition → Course : 25min à 65-70% VMA — hydratation maximale',
 NULL, NULL,
 'S''entraîner par temps chaud provoque des adaptations importantes : augmentation du volume sanguin, meilleure thermorégulation. Réduis ton allure de 5-10% par rapport aux conditions normales. Bois avant d''avoir soif.',
 ARRAY['sprint', 'olympique', '70.3', 'ironman'], 'triathlon', ARRAY['velo', 'course'], 40),

('BRI-38', 'brique', 'brique', 'Brique 2x(Vélo 30min + Course 15min) — Double transition', 105, 8,
 '10 min vélo lent zone 1',
 '30min vélo à 80-85% FTP → T2 → 15min course à 75-80% VMA → T2 inverse → 30min vélo à 80-85% FTP → T2 → 15min course à 75-80% VMA',
 '3min de transition entre chaque discipline',
 '5 min vélo lent',
 'Double brique — tu enchaînes 2 cycles vélo+course. La 2ème course arrive sur des jambes vraiment épuisées. Séance avancée pour triathlètes expérimentés. La gestion mentale est aussi importante que la physique.',
 ARRAY['olympique', '70.3'], 'triathlon', ARRAY['velo', 'course'], 29),

('BRI-39', 'brique', 'brique', 'Brique 3 disciplines légère — Nage 500m + Vélo 25min + Course 10min', 60, 7,
 NULL,
 'Nage : 500m à 80-85% CSS → T1 rapide → Vélo : 25min à 72-78% FTP → T2 rapide → Course : 10min à 70-75% VMA',
 NULL, NULL,
 'Triathlon complet en format réduit. Les 3 disciplines + les 2 transitions — tu répètes le déroulement complet d''une course. Idéal en début de préparation ou pour les débutants en triathlon.',
 ARRAY['sprint'], 'triathlon', ARRAY['natation', 'velo', 'course'], 18),

('BRI-40', 'brique', 'brique', 'Brique Ironman — Vélo 5h + Course 1h30', 390, 6,
 '10 min vélo lent zone 1',
 'Vélo : 4h50 à 63-68% FTP → transition T2 → Course : 1h30 à 62-67% VMA — allure très conservative',
 NULL, NULL,
 'La grande brique Ironman. Six heures et demie d''effort. Cette séance te dit si tu es prêt pour un Ironman. L''allure course doit être très conservatrice — le but est de finir, pas de performer. Nutrition obligatoire et planifiée.',
 ARRAY['ironman'], 'triathlon', ARRAY['velo', 'course'], 100);
