// Trame 3 séances/semaine — Ebook 10km, 8 semaines.
// Structure allégée : 1 EF, 1 séance qualité (alterne selon la semaine), 1 sortie longue.
// Mêmes règles de placeholders que semaines-4.js ({{P}} séquentiel sur `pcts`, {{OBJ}} libre).
module.exports = [
  { num:1, phase:'Adaptation', charge:'Modérée',
    objectif:'Installer les habitudes d\'entraînement et prendre ses marques sur les allures, avec un volume resserré sur 3 séances. Finir chaque séance en se sentant bien.',
    conseil:'Avec seulement 3 séances, chacune compte double. Ne saute pas la sortie longue, c\'est elle qui construit ta capacité à tenir 10km.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Endurance Fondamentale', duree:'40 min', pcts:[[65,70]],
        echauff:'', corps:'Course continue à {{P}}. Allure conversation, tu dois pouvoir parler en phrases complètes. Régulier et relâché.', retour:'',
        note:'RPE 4-5/10 · Finis en te sentant bien.' },
      { jour:'Jeudi', type:'Fractionné', titre:'8 × 400 mètres', duree:'55 min', pcts:[[65,65],[95,100]],
        echauff:'25 min de footing EF à {{P}}.', corps:'8 × 400m à {{P}}. Effort presque maximal. Récupération 90 sec au trot entre chaque. Maintiens la même allure du premier au dernier.', retour:'10 min de jogging léger.',
        note:'RPE 8-9/10 · Avec 3 séances/semaine, cette séance est ta seule dose d\'intensité, donne-toi pleinement.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue', duree:'65 min', pcts:[[70,75]],
        echauff:'', corps:'Course continue à {{P}} pendant 60 minutes, puis les 5 dernières minutes à ton allure objectif 10km ({{OBJ}}). Hydrate-toi, concentre-toi sur ta foulée.', retour:'',
        note:'RPE 5-6/10 · Mémorise la sensation de ces 5 dernières minutes.' },
    ]},
  { num:2, phase:'Adaptation', charge:'Modérée, légère progression',
    objectif:'Confirmer les bases sur ce rythme de 3 séances. Le plan doit commencer à sembler naturel.',
    conseil:'Sur les 10 × 400m, vise la régularité plutôt que la vitesse pure. Si les dernières sont nettement plus lentes, tu es parti trop vite.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Endurance Fondamentale', duree:'40 min', pcts:[[65,70]],
        echauff:'', corps:'40 min à {{P}}. Même principe que la semaine passée. Allure conversation, régulière du début à la fin.', retour:'',
        note:'RPE 4-5/10 · Léger et régulier.' },
      { jour:'Jeudi', type:'Fractionné', titre:'10 × 400 mètres', duree:'60 min', pcts:[[65,65],[95,100]],
        echauff:'25 min de footing EF à {{P}}.', corps:'10 × 400m à {{P}}. Deux répétitions de plus. Récupération 90 sec au trot. Maintiens la même allure sur les 10.', retour:'10 min de footing léger.',
        note:'RPE 8-9/10 · La récupération courte développe ta résistance à l\'effort.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue', duree:'70 min', pcts:[[70,75]],
        echauff:'', corps:'62 min à {{P}}, puis termine par 8 minutes à ton allure objectif 10km ({{OBJ}}). 5 minutes de plus que la semaine dernière.', retour:'',
        note:'RPE 5-6/10 puis 7/10 sur la fin · La sortie longue construit ta base.' },
    ]},
  { num:3, phase:'Développement', charge:'Élevée, première séance tempo',
    objectif:'L\'inconfort arrive, c\'est le signe que tu travailles dans la bonne zone. Introduction du travail au seuil anaérobie.',
    conseil:'Sur le tempo, l\'allure doit être inconfortable mais tenable. Tu peux prononcer des mots isolés mais pas des phrases complètes.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Footing EF', duree:'45 min', pcts:[[70,70],[65,65]],
        echauff:'', corps:'45 min à {{P}}. Long et facile avant la séance de qualité. Travaille ta technique : légère bascule vers l\'avant, attaque milieu du pied.', retour:'',
        note:'RPE 5/10 · Si tu te sens fatigué, passe à {{P}}.' },
      { jour:'Jeudi', type:'Tempo', titre:'Tempo continu, 15 minutes', duree:'55 min', pcts:[[65,70],[85,85]],
        echauff:'25 min de footing progressif à {{P}}.', corps:'15 minutes continues à {{P}}. Première séance au seuil. Difficile mais tenable. Tu peux prononcer des mots mais pas tenir une conversation.', retour:'15 min de jogging très lent.',
        note:'RPE 7-8/10 · C\'est normal si tu souffres sur les dernières minutes, cette zone te fait progresser.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue + accélération', duree:'80 min', pcts:[[70,75],[80,82]],
        echauff:'', corps:'68 min à {{P}}, puis accélération progressive sur les 12 dernières minutes à {{P}}. Tu apprends à finir fort, compétence clé sur les 2 derniers km.', retour:'',
        note:'RPE 6/10 puis 7-8/10 · Mémorise cette sensation, tu la réutiliseras en course.' },
    ]},
  { num:4, phase:'Développement', charge:'Élevée, consolidation du seuil',
    objectif:'Consolider le travail de seuil et le travail à l\'allure objectif. La fatigue s\'installe, mange correctement et dors 8 heures par nuit.',
    conseil:'Si tu ressens une fatigue importante, raccourcis la séance de qualité plutôt que de la sauter. Un athlète reposé progresse davantage.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Footing EF', duree:'45 min', pcts:[[70,70]],
        echauff:'', corps:'45 min à {{P}}. Régulier et facile, volume avant la séance de qualité.', retour:'',
        note:'RPE 5/10 · Cours détendu.' },
      { jour:'Jeudi', type:'Fractionné', titre:'5 × 1000 mètres', duree:'65 min', pcts:[[65,65],[85,88]],
        echauff:'25 min de footing EF à {{P}}.', corps:'5 × 1000m à {{P}}. Intervalles longs, développent ta résistance à l\'allure seuil. Récupération 2 min au trot. Termine par 1 km à ton allure objectif 10km ({{OBJ}}), pour comparer les sensations.', retour:'10 min de footing léger.',
        note:'RPE 7-8/10 · Ton corps est prêt pour cette charge.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue', duree:'85 min', pcts:[[72,75]],
        echauff:'', corps:'85 min à {{P}}. Ta sortie longue la plus importante jusqu\'ici. Régularité et respiration. Hydrate-toi toutes les 20-25 min.', retour:'',
        note:'RPE 6/10 · Tu dois finir fatigué mais pas à plat.' },
    ]},
  { num:5, phase:'Intensification', charge:'Élevée, bloc côtes',
    objectif:'La séance la plus intense du plan. Elle fait progresser le plus sur 10km à volume égal. Donne tout sur les montées.',
    conseil:'Les côtes sont la séance la plus efficace à faible volume. Concentre-toi sur l\'impulsion au sol et la montée des genoux. La descente au trot est ta récupération active.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Footing de récupération', duree:'40 min', pcts:[[60,60]],
        echauff:'', corps:'40 min à {{P}}. Fondamentale avant la séance de côtes, active la circulation sans fatiguer les jambes.', retour:'',
        note:'RPE 3/10 · Vraiment facile.' },
      { jour:'Jeudi', type:'Côtes', titre:'8 × côtes, 150 mètres', duree:'55 min', pcts:[[65,70]],
        echauff:'25 min de footing progressif à {{P}}.', corps:'8 montées de 150m à effort maximal. Genoux hauts, bras actifs, pousse à fond jusqu\'en haut. Descente au trot complète entre chaque montée.', retour:'15 min de footing très léger.',
        note:'RPE 9/10 sur les montées · Les côtes renforcent tes muscles propulseurs.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue avec encart allure', duree:'85 min', pcts:[[70,75]],
        echauff:'', corps:'70 min à {{P}}, puis 3 km à ton allure objectif 10km ({{OBJ}}), puis retour à l\'allure EF. Cet encart t\'apprend à tenir l\'allure quand les jambes sont déjà sollicitées.', retour:'',
        note:'RPE 6/10 en EF · 7-8/10 sur les 3 km · Note ton allure, indicateur fiable de ta forme.' },
    ]},
  { num:6, phase:'Intensification', charge:'Maximale, dernier bloc chargé',
    objectif:'Dernière semaine de charge maximale avant l\'affûtage. Le travail à l\'allure objectif atteint son pic.',
    conseil:'C\'est ta semaine de charge maximale. N\'ajoute rien. Mange des glucides les soirs avant la séance de qualité. Dors 8 heures.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Footing EF', duree:'45 min', pcts:[[70,70]],
        echauff:'', corps:'45 min à {{P}}. Régulier et facile, garde les jambes prêtes pour la séance spécifique.', retour:'',
        note:'RPE 5/10 · Cours détendu.' },
      { jour:'Jeudi', type:'Spécifique', titre:'3 × 2 km à allure objectif', duree:'60 min',
        echauff:'25 min de footing EF.', corps:'3 × 2 km exactement à ton allure objectif 10km ({{OBJ}}). Récupération 90 sec au trot. La séance la plus course-spécifique du plan : c\'est littéralement ton allure de course que tu répètes.', retour:'10 min de footing léger.',
        note:'RPE 8/10 · Si {{OBJ}} est trop facile, ton objectif est peut-être trop prudent.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Dernière sortie longue', duree:'80 min', pcts:[[70,75]],
        echauff:'', corps:'80 min à {{P}}. Ta dernière vraie sortie longue avant la course. Mémorise cette sensation, l\'affûtage va encore l\'améliorer.', retour:'',
        note:'RPE 6/10 · Après cette séance, l\'entraînement dur est terminé.' },
    ]},
  { num:7, phase:'Affûtage', charge:'Volume réduit, intensité maintenue',
    objectif:'L\'affûtage ne fait pas perdre de forme, il la concentre. Tu gardes une séance d\'intensité pour maintenir les sensations.',
    conseil:'Des études montrent qu\'un athlète est au maximum de ses capacités 8 à 14 jours après la dernière grosse charge. Fais confiance au processus.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Footing léger', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min très faciles à {{P}}. Garder les jambes en mouvement sans les fatiguer. Cours au ressenti, sans montre.', retour:'',
        note:'RPE 3/10 · Tu dois finir comme si tu venais de te promener.' },
      { jour:'Jeudi', type:'Fractionné', titre:'4 × 400 mètres, volume réduit', duree:'45 min', pcts:[[95,100]],
        echauff:'25 min de footing progressif EF.', corps:'4 × 400m à {{P}}. Volume très réduit mais intensité maintenue. Récupération 2 min entre chaque. Termine par 1 km à ton allure objectif 10km ({{OBJ}}), pour garder la sensation fraîche en tête.', retour:'10 min de footing léger.',
        note:'RPE 8/10 · Ces répétitions maintiennent tes sensations sans te fatiguer.' },
      { jour:'Samedi', type:'EF', titre:'Footing de 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}. Garde les jambes en mouvement sans les fatiguer. Profite de l\'affûtage, ton corps se recharge pour le jour J.', retour:'',
        note:'RPE 3/10 · Tu dois finir frais, jamais fatigué.' },
    ]},
  { num:8, phase:'Semaine de course', charge:'Conserve, tu es prêt',
    objectif:'Rien ne se gagne à l\'entraînement cette semaine. L\'objectif unique : arriver au départ reposé, confiant, les jambes fraîches.',
    conseil:'Fais confiance à tes 7 semaines de travail. Pars à ton allure objectif {{OBJ}} dès le départ, ne te laisse pas griser par l\'adrénaline.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Footing très léger', duree:'30 min', pcts:[[60,65]],
        echauff:'', corps:'30 min à {{P}}. Maintenir la circulation sanguine. Vraiment facile. Profite pour visualiser ta course à ton allure objectif {{OBJ}}.', retour:'',
        note:'RPE 3/10 · Aucun effort. Juste des jambes qui bougent.' },
      { jour:'Samedi', type:'Activation', titre:'Activation J-1 + accélérations', duree:'30 min', pcts:[[60,65]],
        echauff:'', corps:'20 min de trot à {{P}}. Puis 6 accélérations progressives de 80m, démarre doucement et accélère jusqu\'à passer sous ton allure objectif {{OBJ}} sur les 20 derniers mètres. Récupère 60 sec en marchant entre chaque.', retour:'',
        note:'Ces accélérations réveillent tes fibres rapides. Efficace la veille d\'une course.' },
      { jour:'Dimanche', type:'Course', titre:'COURSE 10 KILOMÈTRES', duree:'Jour J',
        echauff:'10 min de jogging léger avant le départ.', corps:'KM 1-2 : pars à ton allure objectif {{OBJ}}, ne pars surtout pas plus vite. KM 3-8 : maintiens {{OBJ}} exactement, régularité absolue. KM 9 : accélère si tu as des réserves. KM 10 : donne absolument tout.', retour:'10-15 min de marche. Banane et eau dans les 30 min.',
        note:'Les sensations difficiles aux km 6-7 sont normales. C\'est là que se gagne un 10km.' },
    ]},
]
