// Trame 4 séances/semaine — Ebook 10km, 8 semaines.
// {{P}} est remplacé en lecture (échauffement → corps → retour → note) par l'allure
// correspondant à chaque entrée de `pcts`, dans l'ordre. {{OBJ}} est remplacé par
// l'allure objectif course (90% VMA), indépendamment de `pcts`.
module.exports = [
  { num:1, phase:'Adaptation', charge:'Modérée',
    objectif:'Installer les habitudes d\'entraînement et prendre ses marques sur les allures. Finir chaque séance en se sentant bien.',
    conseil:'Sur les 10 × 400m, l\'objectif n\'est pas d\'aller le plus vite, mais de tenir la même allure sur les 10. Garde tes 90 secondes de récupération complètes.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Endurance Fondamentale', duree:'45 min', pcts:[[65,70]],
        echauff:'', corps:'Course continue à {{P}}. Allure conversation, tu dois pouvoir parler en phrases complètes. Si tu as du mal à parler, tu vas trop vite. Régulier et relâché.', retour:'',
        note:'RPE 4-5/10 · Finis en te sentant bien, comme si tu pouvais encore courir.' },
      { jour:'Jeudi', type:'Fractionné', titre:'10 × 400 mètres', duree:'65 min', pcts:[[65,65],[95,100]],
        echauff:'25 min de footing EF à {{P}}.', corps:'10 × 400m à {{P}}. Effort presque maximal. Récupération 90 sec au trot entre chaque. Maintiens la même allure du premier au dernier.', retour:'10 min de jogging léger.',
        note:'RPE 8-9/10 · Si les dernières sont plus lentes, récupère un peu plus la prochaine fois.' },
      { jour:'Samedi', type:'EF', titre:'Footing de récupération', duree:'45 min', pcts:[[60,60]],
        echauff:'', corps:'45 min à {{P}}. Active la circulation et prépare la sortie longue du lendemain. Si tu as des courbatures, ce footing les élimine progressivement.', retour:'',
        note:'RPE 3/10 · Vraiment facile, aucun effort.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue', duree:'75 min', pcts:[[70,75]],
        echauff:'', corps:'Course continue à {{P}} pendant 70 minutes, puis les 5 dernières minutes à ton allure objectif 10km ({{OBJ}}). Hydrate-toi. Concentre-toi sur ta respiration et ta foulée.', retour:'',
        note:'RPE 5-6/10 · Mémorise la sensation de ces 5 dernières minutes, c\'est ton allure du jour J.' },
    ]},
  { num:2, phase:'Adaptation', charge:'Modérée, légère progression',
    objectif:'Confirmer les bases. Le plan doit commencer à sembler naturel. Le corps assimile les nouvelles charges d\'entraînement.',
    conseil:'Sur les 12 × 400m, l\'objectif c\'est de tenir la même allure sur les 12. Si les dernières sont nettement plus lentes, tu es parti trop vite.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Endurance Fondamentale', duree:'45 min', pcts:[[65,70]],
        echauff:'', corps:'45 min à {{P}}. Même principe que la semaine passée. Allure conversation, régulière du début à la fin.', retour:'',
        note:'RPE 4-5/10 · Léger et régulier.' },
      { jour:'Jeudi', type:'Fractionné', titre:'12 × 400 mètres', duree:'70 min', pcts:[[65,65],[95,100]],
        echauff:'25 min de footing EF à {{P}}.', corps:'12 × 400m à {{P}}. Deux répétitions de plus. Récupération 90 sec au trot. Maintiens la même allure sur les 12.', retour:'10 min de footing léger.',
        note:'RPE 8-9/10 · La récupération courte est volontaire pour développer ta résistance.' },
      { jour:'Samedi', type:'EF', titre:'Footing de récupération', duree:'45 min', pcts:[[60,60]],
        echauff:'', corps:'45 min à {{P}}. Active la circulation et prépare la sortie longue du lendemain. Cours très détendu.', retour:'',
        note:'RPE 3/10 · Vraiment facile.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue', duree:'80 min', pcts:[[70,75]],
        echauff:'', corps:'72 min à {{P}}, puis termine par 8 minutes à ton allure objectif 10km ({{OBJ}}). 5 minutes de plus que la semaine dernière sur le volume total.', retour:'',
        note:'RPE 5-6/10 puis 7/10 sur la fin · La sortie longue est la pierre angulaire de ta préparation.' },
    ]},
  { num:3, phase:'Développement', charge:'Élevée, première séance tempo',
    objectif:'L\'inconfort arrive, c\'est le signe que tu travailles dans la bonne zone. Montée en intensité avec la première séance au seuil anaérobie.',
    conseil:'Sur le tempo, l\'allure doit être inconfortable mais tenable. Tu peux prononcer des mots isolés mais pas des phrases complètes.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Footing long EF', duree:'50 min', pcts:[[70,70],[65,65]],
        echauff:'', corps:'50 min à {{P}}. Long et facile avant la semaine chargée. Travaille ta technique : légère bascule vers l\'avant, attaque milieu du pied.', retour:'',
        note:'RPE 5/10 · Si tu te sens fatigué, passe à {{P}}.' },
      { jour:'Mercredi', type:'Tempo', titre:'Tempo continu, 20 minutes', duree:'60 min', pcts:[[65,70],[85,85]],
        echauff:'25 min de footing progressif à {{P}}.', corps:'20 minutes continues à {{P}}. Première séance au seuil. Difficile mais tenable. Tu peux prononcer des mots mais pas tenir une conversation.', retour:'15 min de jogging très lent.',
        note:'RPE 7-8/10 · C\'est normal si tu souffres sur les dernières minutes, cette zone te fait progresser.' },
      { jour:'Vendredi', type:'Fractionné', titre:'5 × 1000 mètres', duree:'70 min', pcts:[[65,65],[85,88]],
        echauff:'25 min de footing EF à {{P}}.', corps:'5 × 1000m à {{P}}. Intervalles plus longs, développent ta résistance à l\'allure seuil. Récupération 2 min au trot. Termine par 1 km à ton allure objectif 10km ({{OBJ}}), pour comparer les sensations.', retour:'10 min de footing léger.',
        note:'RPE 7-8/10 · La progression 400m → 1000m est intentionnelle. Ton corps est prêt.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue + accélération', duree:'85 min', pcts:[[70,75],[80,82]],
        echauff:'', corps:'70 min à {{P}}, puis accélération progressive sur les 15 dernières minutes à {{P}}. Tu apprends à finir fort, compétence clé sur les 2 derniers km.', retour:'',
        note:'RPE 6/10 puis 7-8/10 · Mémorise cette sensation, tu la réutiliseras en course.' },
    ]},
  { num:4, phase:'Développement', charge:'Élevée, consolidation du seuil',
    objectif:'Consolider le travail de seuil et augmenter le volume. La fatigue s\'installe, mange correctement et dors 8 heures par nuit.',
    conseil:'Si tu ressens une fatigue importante, remplace la séance du vendredi par un footing EF de 45 min. Un athlète reposé progresse davantage.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Footing long EF', duree:'55 min', pcts:[[70,70],[65,65]],
        echauff:'', corps:'55 min à {{P}}. Long, régulier, facile. Volume avant la semaine la plus chargée jusqu\'ici.', retour:'',
        note:'RPE 5/10 · Si tu te sens fatigué, passe à {{P}}.' },
      { jour:'Mercredi', type:'Tempo', titre:'2 × 15 minutes au seuil', duree:'65 min', pcts:[[85,85]],
        echauff:'25 min de footing progressif EF.', corps:'2 × 15 min à {{P}} avec 3 min de récupération. La deuxième répétition se termine par 2 minutes à ton allure objectif 10km ({{OBJ}}), plus difficile car les jambes sont déjà fatiguées.', retour:'10 min de footing léger.',
        note:'RPE 7-8/10 · Si la deuxième est plus difficile que la première, c\'est qu\'elle est supposée l\'être.' },
      { jour:'Vendredi', type:'Fractionné', titre:'6 × 1000 mètres', duree:'75 min', pcts:[[87,90]],
        echauff:'25 min de footing EF.', corps:'6 × 1000m à {{P}}. Une répétition de plus, allure légèrement plus haute. Récupération 2 min au trot.', retour:'10 min de footing léger.',
        note:'RPE 8/10 · C\'est normal si les dernières sont dures, tu construis ta résistance aérobie.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue', duree:'90 min', pcts:[[72,75]],
        echauff:'', corps:'90 min à {{P}}. Ta sortie longue la plus importante jusqu\'ici. Régularité et respiration. Hydrate-toi toutes les 20-25 min.', retour:'',
        note:'RPE 6/10 · Tu dois finir fatigué mais pas à plat.' },
    ]},
  { num:5, phase:'Intensification', charge:'Élevée, bloc VMA',
    objectif:'Les séances les plus intenses du plan. Ce sont elles qui font progresser le plus sur 10km. Donne tout sur les répétitions.',
    conseil:'Les côtes sont la séance la plus efficace du plan. Concentre-toi sur l\'impulsion au sol et la montée des genoux. La descente au trot est ta récupération active.',
    seances:[
      { jour:'Mardi', type:'Côtes', titre:'10 × côtes, 150 mètres', duree:'60 min', pcts:[[65,70]],
        echauff:'25 min de footing progressif à {{P}}.', corps:'10 montées de 150m à effort maximal. Genoux hauts, bras actifs, pousse à fond jusqu\'en haut. Descente au trot complète entre chaque montée.', retour:'15 min de footing très léger.',
        note:'RPE 9/10 sur les montées · Les côtes renforcent tes muscles propulseurs.' },
      { jour:'Vendredi', type:'Fractionné', titre:'16 × 300 mètres', duree:'70 min', pcts:[[65,65],[100,105]],
        echauff:'25 min de footing EF à {{P}}.', corps:'16 × 300m à {{P}}. Intensité très élevée. Récupération 60 sec entre chaque. Maintiens la même vitesse sur les 16. Termine par 3 × 1 km à ton allure objectif 10km ({{OBJ}}), récupération 60 sec.', retour:'10 min de footing léger.',
        note:'RPE 9/10 · 60 sec de récupération, calculé pour forcer l\'adaptation aux efforts répétés.' },
      { jour:'Samedi', type:'EF', titre:'Footing de récupération', duree:'45 min', pcts:[[60,60]],
        echauff:'', corps:'45 min à {{P}}. Fondamentale après une grosse semaine, active la circulation pour accélérer la récupération musculaire avant la sortie longue du lendemain.', retour:'',
        note:'RPE 3/10 · Cette séance te fait récupérer plus vite.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue avec encart allure', duree:'90 min', pcts:[[70,75]],
        echauff:'', corps:'60 min à {{P}}, puis 5 km à ton allure objectif 10km ({{OBJ}}), puis retour à l\'allure EF. Cet encart t\'apprend à tenir l\'allure quand les jambes sont déjà sollicitées.', retour:'',
        note:'RPE 6/10 en EF · 7-8/10 sur les 5 km · Note ton allure, indicateur fiable de ta forme.' },
    ]},
  { num:6, phase:'Intensification', charge:'Maximale, dernier bloc chargé',
    objectif:'Dernière semaine de charge maximale avant la consolidation. Tu atteins le pic de ta préparation. Ce que tu construis ici sera transformé en performance lors de la semaine de course.',
    conseil:'C\'est ta semaine de charge maximale. N\'ajoute rien. Mange des glucides les soirs avant les séances clés. Dors 8 heures. Hydrate-toi toute la journée.',
    seances:[
      { jour:'Mardi', type:'Tempo', titre:'3 × 10 minutes au seuil', duree:'70 min', pcts:[[87,90]],
        echauff:'25 min de footing progressif EF.', corps:'3 × 10 min à {{P}} avec 3 min de récupération entre chaque. La troisième répétition est la plus difficile. Maintiens l\'allure.', retour:'10 min de footing léger.',
        note:'RPE 8-9/10 · 30 min totales au seuil, ton record sur ce plan.' },
      { jour:'Jeudi', type:'Spécifique', titre:'4 × 2 km à allure objectif', duree:'70 min',
        echauff:'25 min de footing EF.', corps:'4 × 2 km exactement à ton allure objectif 10km ({{OBJ}}). Récupération 90 sec au trot. La séance la plus course-spécifique du plan : c\'est littéralement ton allure de course que tu répètes.', retour:'10 min de footing léger.',
        note:'RPE 8/10 · Si {{OBJ}} est trop facile, ton objectif est peut-être trop prudent.' },
      { jour:'Samedi', type:'EF', titre:'Footing de récupération', duree:'45 min', pcts:[[60,60]],
        echauff:'', corps:'45 min à {{P}}. Indispensable pour absorber la charge des deux séances clés. Ton corps s\'adapte à un niveau supérieur.', retour:'',
        note:'RPE 3/10 · Le footing de récupération est aussi important que les séances intenses.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Dernière sortie longue', duree:'85 min', pcts:[[70,75]],
        echauff:'', corps:'85 min à {{P}}. Ta dernière vraie sortie longue avant la course. Mémorise cette sensation, la semaine de course va encore l\'améliorer.', retour:'',
        note:'RPE 6/10 · Après cette séance, l\'entraînement dur est terminé.' },
    ]},
  { num:7, phase:'Consolidation', charge:'Volume réduit, intensité maintenue',
    objectif:'La consolidation préserve ta forme sans t\'épuiser. Tu gardes une séance d\'intensité pour maintenir les sensations. L\'objectif : aborder la semaine de course avec les jambes fraîches.',
    conseil:'Cette semaine allégée laisse les adaptations physiologiques de la préparation s\'installer pleinement. Dors 8 heures, mange bien, évite le stress inutile. La semaine de course sera encore plus légère.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Footing léger', duree:'45 min', pcts:[[65,65]],
        echauff:'', corps:'45 min très faciles à {{P}}. Garder les jambes en mouvement sans les fatiguer. Cours au ressenti, sans montre. Profite de cette semaine allégée.', retour:'',
        note:'RPE 3/10 · Tu dois finir comme si tu venais de te promener.' },
      { jour:'Jeudi', type:'Fractionné', titre:'6 × 400 mètres, volume réduit', duree:'55 min', pcts:[[95,100]],
        echauff:'25 min de footing progressif EF.', corps:'6 × 400m à {{P}}. Volume réduit de 40% mais intensité maintenue. Récupération 2 min entre chaque. Termine par 2 × 1 km à ton allure objectif 10km ({{OBJ}}), pour garder la sensation fraîche en tête.', retour:'10 min de footing léger.',
        note:'RPE 8/10 · Ces répétitions maintiennent tes sensations sans te fatiguer.' },
      { jour:'Samedi', type:'EF', titre:'Footing de 45 minutes', duree:'45 min', pcts:[[65,65]],
        echauff:'', corps:'45 min à {{P}}. Garde les jambes en mouvement sans les fatiguer. Cours au ressenti, détendu et régulier. Ton corps se recharge pour le jour J.', retour:'',
        note:'RPE 3/10 · Tu dois finir frais et légèrement dynamisé, jamais fatigué.' },
    ]},
  { num:8, phase:'Semaine de course', charge:'Conserve, tu es prêt',
    objectif:'Rien ne se gagne à l\'entraînement cette semaine. L\'objectif unique : arriver au départ reposé, confiant, les jambes fraîches.',
    conseil:'Fais confiance à tes 7 semaines de travail. Pars à ton allure objectif {{OBJ}} dès le départ, ne te laisse pas griser par l\'adrénaline.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing très léger', duree:'40 min', pcts:[[60,65]],
        echauff:'', corps:'40 min à {{P}}. Maintenir la circulation sanguine. Vraiment facile, si tu te sens fatigué, réduis à 30 minutes.', retour:'',
        note:'RPE 3/10 · Aucun effort. Juste des jambes qui bougent.' },
      { jour:'Mercredi', type:'Fractionné', titre:'8 × 30/30 à allure objectif', duree:'35 min',
        echauff:'15 min de footing EF très léger.',
        corps:'8 × 30 secondes à ton allure objectif 10km ({{OBJ}}) / 30 secondes au trot. Effort court et ciblé, les jambes retrouvent la sensation de vitesse avant la course.',
        retour:'10 min de jogging léger.',
        note:'RPE 6-7/10 · Ces courtes relances maintiennent les sensations sans t\'épuiser avant le jour J.' },
      { jour:'Samedi', type:'Activation', titre:'Activation J-1 + accélérations', duree:'30 min', pcts:[[60,65]],
        echauff:'', corps:'20 min de trot à {{P}}. Puis 6 à 8 accélérations progressives de 80m, démarre doucement et accélère jusqu\'à passer sous ton allure objectif {{OBJ}} sur les 20 derniers mètres. Récupère 60 sec en marchant entre chaque.', retour:'',
        note:'Ces accélérations réveillent tes fibres rapides. Efficace la veille d\'une course.' },
      { jour:'Dimanche', type:'Course', titre:'COURSE 10 KILOMÈTRES', duree:'Jour J',
        echauff:'10 min de jogging léger avant le départ.', corps:'KM 1-2 : pars à ton allure objectif {{OBJ}}, ne pars surtout pas plus vite. KM 3-8 : maintiens {{OBJ}} exactement, régularité absolue. KM 9 : accélère si tu as des réserves. KM 10 : donne absolument tout.', retour:'10-15 min de marche. Banane et eau dans les 30 min.',
        note:'Les sensations difficiles aux km 6-7 sont normales. C\'est là que se gagne un 10km.' },
    ]},
]
