// Trame 4 séances/semaine — Ebook 10km, 12 semaines · Palier Intermédiaire.
// {{P}} remplacé séquentiellement sur la queue de pcts, {{OBJ}} = allure objectif (90% VMA).
module.exports = [
  { num:1, phase:'Adaptation', charge:'Légère',
    objectif:'Prendre ses repères sur les allures et installer le rythme sur 4 séances. Aucune pression de performance, juste finir chaque séance en se sentant bien.',
    conseil:'Sur les 8 × 400m, l\'objectif n\'est pas d\'aller le plus vite, mais de tenir la même allure du premier au dernier. Garde tes 90 secondes de récupération complètes.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Endurance Fondamentale', duree:'45 min', pcts:[[65,70]],
        echauff:'', corps:'Course continue à {{P}}. Allure conversation, tu dois pouvoir parler en phrases complètes. Si tu as du mal à parler, tu vas trop vite. Régulier et relâché.', retour:'',
        note:'RPE 4-5/10 · Finis en te sentant bien, comme si tu pouvais encore courir.' },
      { jour:'Jeudi', type:'Fractionné', titre:'8 × 400 mètres', duree:'60 min', pcts:[[65,65],[92,97]],
        echauff:'20 min de footing EF à {{P}}.', corps:'8 × 400m à {{P}}. Effort soutenu mais maîtrisé. Récupération 90 sec au trot entre chaque. Maintiens la même allure du premier au dernier.', retour:'10 min de jogging léger.',
        note:'RPE 8/10 · Si les dernières sont plus lentes, récupère un peu plus la prochaine fois.' },
      { jour:'Samedi', type:'EF', titre:'Footing de récupération', duree:'40 min', pcts:[[60,60]],
        echauff:'', corps:'40 min à {{P}}. Active la circulation et prépare la sortie longue du lendemain. Cours vraiment détendu, aucun effort.', retour:'',
        note:'RPE 3/10 · Vraiment facile, aucun effort.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue', duree:'60 min', pcts:[[65,70]],
        echauff:'', corps:'Course continue à {{P}} pendant 55 minutes, puis les 5 dernières minutes à ton allure objectif 10km ({{OBJ}}). Hydrate-toi. Concentre-toi sur ta respiration et ta foulée.', retour:'',
        note:'RPE 5/10 · Mémorise la sensation de ces 5 dernières minutes, c\'est ton allure du jour J.' },
    ]},
  { num:2, phase:'Adaptation', charge:'Légère à modérée',
    objectif:'Confirmer les bases. Deux répétitions de plus, volume légèrement augmenté sur la sortie longue. Le plan doit commencer à sembler naturel.',
    conseil:'Sur les 10 × 400m, l\'allure doit être identique sur les 10. Si les dernières sont nettement plus lentes, tu es parti trop vite.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Endurance Fondamentale', duree:'45 min', pcts:[[65,70]],
        echauff:'', corps:'45 min à {{P}}. Même principe que la semaine passée. Allure conversation, régulière du début à la fin.', retour:'',
        note:'RPE 4-5/10 · Léger et régulier.' },
      { jour:'Jeudi', type:'Fractionné', titre:'10 × 400 mètres', duree:'65 min', pcts:[[65,65],[92,97]],
        echauff:'25 min de footing EF à {{P}}.', corps:'10 × 400m à {{P}}. Deux répétitions de plus. Récupération 90 sec au trot. Maintiens la même allure sur les 10.', retour:'10 min de footing léger.',
        note:'RPE 8/10 · La récupération courte est volontaire pour développer ta résistance.' },
      { jour:'Samedi', type:'EF', titre:'Footing de récupération', duree:'40 min', pcts:[[60,60]],
        echauff:'', corps:'40 min à {{P}}. Active la circulation et prépare la sortie longue du lendemain. Cours très détendu.', retour:'',
        note:'RPE 3/10 · Vraiment facile.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue', duree:'65 min', pcts:[[70,75]],
        echauff:'', corps:'60 min à {{P}}, puis termine par 5 minutes à ton allure objectif 10km ({{OBJ}}). La sortie longue construit ta résistance sur la durée.', retour:'',
        note:'RPE 5-6/10 · La sortie longue est la pierre angulaire de ta préparation.' },
    ]},
  { num:3, phase:'Développement aérobie', charge:'Modérée, première séance tempo',
    objectif:'Introduire le travail au seuil anaérobie. Le tempo repousse ta limite lactique, directement responsable de ton allure sur 10km. L\'inconfort arrive, c\'est bon signe.',
    conseil:'Sur le tempo, tu dois pouvoir prononcer des mots isolés mais pas tenir une conversation. C\'est la zone parfaite : difficile mais contrôlée.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Footing long EF', duree:'50 min', pcts:[[70,70],[65,65]],
        echauff:'', corps:'50 min à {{P}}. Long et facile avant la semaine à deux séances de qualité. Travaille ta technique : légère bascule vers l\'avant, attaque milieu du pied. Si tu te sens fatigué, passe à {{P}}.', retour:'',
        note:'RPE 5/10 · Ce footing long est la base de tout.' },
      { jour:'Mercredi', type:'Tempo', titre:'Tempo continu, 15 minutes', duree:'55 min', pcts:[[65,70],[82,82]],
        echauff:'25 min de footing progressif à {{P}}.', corps:'15 minutes continues à {{P}}. Première séance au seuil anaérobie. Difficile mais tenable. Tu peux prononcer des mots mais pas tenir une conversation.', retour:'15 min de jogging très lent.',
        note:'RPE 7-8/10 · C\'est normal si tu souffres sur les dernières minutes, cette zone te fait progresser.' },
      { jour:'Vendredi', type:'Fractionné', titre:'4 × 1000 mètres', duree:'65 min', pcts:[[65,65],[83,86]],
        echauff:'25 min de footing EF à {{P}}.', corps:'4 × 1000m à {{P}}. Intervalles longs pour développer ta résistance à l\'allure seuil. Récupération 2 min au trot. Termine par 1 km à ton allure objectif 10km ({{OBJ}}), pour comparer les sensations.', retour:'10 min de footing léger.',
        note:'RPE 7-8/10 · La progression 400m → 1000m est intentionnelle. Ton corps est prêt.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue', duree:'75 min', pcts:[[70,75]],
        echauff:'', corps:'75 min à {{P}}. Régulier, hydraté, concentré sur ta foulée. Cette semaine est chargée — la sortie longue reste volontairement facile en allure.', retour:'',
        note:'RPE 5-6/10 · La fatigue de fin de semaine est normale. Récupère bien.' },
    ]},
  { num:4, phase:'Développement aérobie', charge:'Élevée, consolidation du travail aérobie',
    objectif:'Consolider le travail de seuil et augmenter le volume. La deuxième semaine avec deux séances de qualité — le corps s\'adapte et les allures commencent à se naturaliser.',
    conseil:'Sur les 2 × 12 min, la deuxième répétition est intentionnellement plus difficile car les jambes sont déjà chargées. Ne ralentis pas, c\'est ce qui fait progresser.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Footing long EF', duree:'55 min', pcts:[[70,70],[65,65]],
        echauff:'', corps:'55 min à {{P}}. Long, régulier, facile. Volume avant la semaine la plus chargée jusqu\'ici. Si tu te sens fatigué, passe à {{P}}.', retour:'',
        note:'RPE 5/10 · Si tu te sens fatigué, passe à la version lente.' },
      { jour:'Mercredi', type:'Tempo', titre:'2 × 12 minutes au seuil', duree:'60 min', pcts:[[84,84]],
        echauff:'25 min de footing progressif EF.', corps:'2 × 12 min à {{P}} avec 3 min de récupération entre chaque. La deuxième répétition se termine fatigué — c\'est voulu, ne ralentis pas.', retour:'10 min de footing léger.',
        note:'RPE 7-8/10 · Si la deuxième est plus difficile que la première, c\'est qu\'elle est supposée l\'être.' },
      { jour:'Vendredi', type:'Fractionné', titre:'5 × 1000 mètres', duree:'70 min', pcts:[[65,65],[85,88]],
        echauff:'25 min de footing EF.', corps:'5 × 1000m à {{P}}. Une répétition de plus que la semaine dernière, allure légèrement plus haute. Récupération 2 min au trot. Termine par 1 km à ton allure objectif 10km ({{OBJ}}).', retour:'10 min de footing léger.',
        note:'RPE 8/10 · C\'est normal si les dernières sont dures, tu construis ta résistance.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue + accélération finale', duree:'80 min', pcts:[[70,75],[80,82]],
        echauff:'', corps:'70 min à {{P}}, puis accélération progressive sur les 10 dernières minutes à {{P}}. Tu apprends à finir fort — compétence clé sur les 2 derniers km d\'un 10km.', retour:'',
        note:'RPE 6/10 puis 7-8/10 · Mémorise cette sensation, tu la réutiliseras en course.' },
    ]},
  { num:5, phase:'Développement VMA', charge:'Élevée, premier bloc VMA',
    objectif:'Commencer à travailler ta vitesse maximale aérobie. Les 400m à 95-100% VMA élèvent ton plafond de vitesse — c\'est ce qui te permet de tenir une allure plus rapide sur les 10km.',
    conseil:'Sur les 12 × 400m, 90 secondes de récupération complètes entre chaque répétition. Pas 70, pas 80 : 90. C\'est la durée calculée pour que l\'effort suivant soit aussi bon que le premier.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Endurance Fondamentale', duree:'45 min', pcts:[[65,70]],
        echauff:'', corps:'45 min à {{P}}. Volume de base avant la séance VMA du jeudi. Très facile, jamais fatigant.', retour:'',
        note:'RPE 4/10 · Garde les jambes fraîches pour le jeudi.' },
      { jour:'Jeudi', type:'Fractionné', titre:'12 × 400 mètres', duree:'70 min', pcts:[[65,65],[95,100]],
        echauff:'25 min de footing EF à {{P}}.', corps:'12 × 400m à {{P}}. Intensité élevée. Récupération 90 sec au trot entre chaque. Maintiens la même allure du premier au dernier.', retour:'10 min de jogging léger.',
        note:'RPE 8-9/10 · La récupération courte est le vrai stimulus de cette séance.' },
      { jour:'Samedi', type:'EF', titre:'Footing de récupération', duree:'40 min', pcts:[[60,60]],
        echauff:'', corps:'40 min à {{P}}. Fondamentale après la séance VMA du jeudi. Active la circulation pour accélérer la récupération musculaire avant la sortie longue du lendemain.', retour:'',
        note:'RPE 3/10 · Cette séance te fait récupérer plus vite.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue avec encart allure', duree:'80 min', pcts:[[70,75]],
        echauff:'', corps:'65 min à {{P}}, puis 4 km à ton allure objectif 10km ({{OBJ}}), puis retour à l\'allure EF. Cet encart t\'apprend à tenir l\'allure quand les jambes sont déjà sollicitées.', retour:'',
        note:'RPE 6/10 en EF · 7-8/10 sur les 4 km · Note ton allure, indicateur fiable de ta forme.' },
    ]},
  { num:6, phase:'Développement VMA', charge:'Très élevée, bloc côtes et fractionnés courts',
    objectif:'Les côtes développent la force propulsive, les 300m la résistance à la vitesse. Ces deux séances ensemble constituent le bloc VMA le plus complet de ces 12 semaines.',
    conseil:'Sur les côtes, chaque montée est un sprint. Genoux hauts, bras actifs, impulsion maximale au sol. La descente au trot est ta récupération active — ne la raccourcis pas.',
    seances:[
      { jour:'Mardi', type:'Côtes', titre:'8 × côtes, 150 mètres', duree:'60 min', pcts:[[65,70]],
        echauff:'25 min de footing progressif à {{P}}.', corps:'8 montées de 150m à effort maximal. Genoux hauts, bras actifs, pousse à fond jusqu\'en haut. Descente au trot complète entre chaque montée.', retour:'15 min de footing très léger.',
        note:'RPE 9/10 sur les montées · Les côtes renforcent tes muscles propulseurs.' },
      { jour:'Vendredi', type:'Fractionné', titre:'12 × 300 mètres', duree:'65 min', pcts:[[65,65],[97,102]],
        echauff:'25 min de footing EF à {{P}}.', corps:'12 × 300m à {{P}}. Intensité très élevée. Récupération 60 sec entre chaque. Maintiens la même vitesse sur les 12. Termine par 2 × 1 km à ton allure objectif 10km ({{OBJ}}), récupération 60 sec.', retour:'10 min de footing léger.',
        note:'RPE 9/10 · 60 sec de récupération, calculé pour forcer l\'adaptation aux efforts répétés.' },
      { jour:'Samedi', type:'EF', titre:'Footing de récupération', duree:'40 min', pcts:[[60,60]],
        echauff:'', corps:'40 min à {{P}}. Deux séances intenses cette semaine — ce footing est fondamental pour absorber la charge et récupérer avant la sortie longue du lendemain.', retour:'',
        note:'RPE 3/10 · Le footing de récupération est aussi important que les séances intenses.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue', duree:'85 min', pcts:[[70,75]],
        echauff:'', corps:'85 min à {{P}}. Ta sortie longue la plus longue jusqu\'ici. Régularité et respiration. Hydrate-toi toutes les 20-25 min.', retour:'',
        note:'RPE 6/10 · Tu dois finir fatigué mais pas à plat.' },
    ]},
  { num:7, phase:'Intensification', charge:'Très élevée, tempo et longs intervalles',
    objectif:'Les séances montent à leur niveau le plus difficile. Tempo et 1000m en même semaine : la combinaison seuil + endurance VMA est la plus efficace pour progresser sur 10km.',
    conseil:'Sur les 2 × 15 min, l\'allure doit être tenue du début à la fin des deux répétitions. Si tu dois lever le pied en fin de deuxième répétition, recalibre l\'allure pour la prochaine fois.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Footing long EF', duree:'55 min', pcts:[[70,70],[65,65]],
        echauff:'', corps:'55 min à {{P}}. Long et facile avant la semaine chargée. Si tu te sens fatigué, passe à {{P}}.', retour:'',
        note:'RPE 5/10 · Ce footing prépare les séances du mercredi et vendredi.' },
      { jour:'Mercredi', type:'Tempo', titre:'2 × 15 minutes au seuil', duree:'65 min', pcts:[[85,85]],
        echauff:'25 min de footing progressif EF.', corps:'2 × 15 min à {{P}} avec 3 min de récupération entre chaque. Difficile mais tenable. La troisième répétition arrive fatiguée, maintiens l\'allure.', retour:'10 min de footing léger.',
        note:'RPE 8/10 · 30 min totales au seuil, ton record sur ce plan.' },
      { jour:'Vendredi', type:'Fractionné', titre:'5 × 1000 mètres', duree:'70 min', pcts:[[65,65],[86,90]],
        echauff:'25 min de footing EF à {{P}}.', corps:'5 × 1000m à {{P}}. Allure légèrement plus haute que les semaines précédentes. Récupération 2 min au trot.', retour:'10 min de footing léger.',
        note:'RPE 8/10 · C\'est normal si les dernières sont dures, tu es en semaine de charge maximale.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue', duree:'90 min', pcts:[[72,75]],
        echauff:'', corps:'90 min à {{P}}. Ta sortie longue la plus longue du plan. Régularité, respiration, hydratation toutes les 20 min.', retour:'',
        note:'RPE 6/10 · Après cette semaine, la forme monte d\'un cran.' },
    ]},
  { num:8, phase:'Intensification', charge:'Maximale, pic de charge du plan',
    objectif:'Le pic de ta préparation. Ce que tu construis ici sera transformé en performance lors des semaines de spécificité. Donne tout sur les séances, récupère complètement entre elles.',
    conseil:'C\'est ta semaine de charge maximale. N\'ajoute rien. Mange des glucides les soirs avant les séances clés. Dors 8 heures. Hydrate-toi toute la journée.',
    seances:[
      { jour:'Mardi', type:'Côtes', titre:'10 × côtes, 150 mètres', duree:'65 min', pcts:[[65,70]],
        echauff:'25 min de footing progressif à {{P}}.', corps:'10 montées de 150m à effort maximal. Genoux hauts, bras actifs, pousse à fond jusqu\'en haut. Descente au trot complète entre chaque montée.', retour:'15 min de footing très léger.',
        note:'RPE 9/10 sur les montées · Plus de répétitions qu\'en semaine 6, ton corps est prêt.' },
      { jour:'Vendredi', type:'Fractionné', titre:'16 × 300 mètres', duree:'70 min', pcts:[[65,65],[100,105]],
        echauff:'25 min de footing EF à {{P}}.', corps:'16 × 300m à {{P}}. Intensité très élevée. Récupération 60 sec entre chaque. Maintiens la même vitesse sur les 16. Termine par 3 × 1 km à ton allure objectif 10km ({{OBJ}}), récupération 60 sec.', retour:'10 min de footing léger.',
        note:'RPE 9/10 · 60 sec de récupération calculées pour forcer l\'adaptation.' },
      { jour:'Samedi', type:'EF', titre:'Footing de récupération', duree:'45 min', pcts:[[60,60]],
        echauff:'', corps:'45 min à {{P}}. Fondamentale après deux séances très dures. Active la circulation, prépare ton corps pour la sortie longue du dimanche.', retour:'',
        note:'RPE 3/10 · Le footing de récupération est aussi important que les séances intenses.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue avec encart allure', duree:'90 min', pcts:[[70,75]],
        echauff:'', corps:'65 min à {{P}}, puis 5 km à ton allure objectif 10km ({{OBJ}}), puis retour à l\'allure EF. Les 5 km à allure objectif quand tu es fatigué te préparent directement à la fin de course.', retour:'',
        note:'RPE 6/10 en EF · 8/10 sur les 5 km · Après cette semaine, l\'entraînement dur est terminé.' },
    ]},
  { num:9, phase:'Spécificité', charge:'Élevée, travail à l\'allure objectif',
    objectif:'Les séances s\'alignent sur ton allure de course. Tempo + spécifique t\'apprennent à tenir {{OBJ}} sous la fatigue — exactement ce qui fait la différence entre le km 6 et le km 9.',
    conseil:'Sur les 3 × 2 km à allure objectif, chaque répétition doit être exactement à {{OBJ}}. Ni plus vite, ni plus lentement. L\'objectif est la répétabilité de cette allure.',
    seances:[
      { jour:'Mardi', type:'Tempo', titre:'3 × 10 minutes au seuil', duree:'70 min', pcts:[[65,70],[87,87]],
        echauff:'25 min de footing progressif à {{P}}.', corps:'3 × 10 min à {{P}} avec 3 min de récupération entre chaque. La troisième répétition est la plus difficile, maintiens l\'allure.', retour:'10 min de footing léger.',
        note:'RPE 8-9/10 · 30 min totales au seuil, une charge sérieuse.' },
      { jour:'Jeudi', type:'Spécifique', titre:'3 × 2 km à allure objectif', duree:'65 min',
        echauff:'25 min de footing EF.', corps:'3 × 2 km exactement à ton allure objectif 10km ({{OBJ}}). Récupération 90 sec au trot. La séance la plus course-spécifique du plan : c\'est littéralement ton allure de course que tu répètes, sous la fatigue.', retour:'10 min de footing léger.',
        note:'RPE 8/10 · Si {{OBJ}} est trop facile, ton objectif est peut-être trop prudent.' },
      { jour:'Samedi', type:'EF', titre:'Footing de récupération', duree:'45 min', pcts:[[60,60]],
        echauff:'', corps:'45 min à {{P}}. Semaine chargée — ce footing absorbe la charge des deux séances de qualité et prépare la sortie longue du lendemain.', retour:'',
        note:'RPE 3/10 · Facile, sans exception.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue', duree:'85 min', pcts:[[70,75]],
        echauff:'', corps:'85 min à {{P}}. Régulier, hydraté, concentré. Cette sortie longue construit la résistance qui te servira aux km 7-10 le jour J.', retour:'',
        note:'RPE 6/10 · Mémorise la sensation, tu la retrouveras en course.' },
    ]},
  { num:10, phase:'Spécificité', charge:'Très élevée, pic de spécificité',
    objectif:'Ta dernière vraie semaine de charge à l\'allure course. Les 4 × 2 km sont ta répétition générale. Après cette semaine, la consolidation commence.',
    conseil:'Sur les 4 × 2 km, la quatrième est la plus précieuse : elle simule la fin de course avec des jambes chargées. Maintiens {{OBJ}} coûte que coûte sur les 2 derniers kilomètres.',
    seances:[
      { jour:'Mardi', type:'Tempo', titre:'3 × 12 minutes au seuil', duree:'75 min', pcts:[[65,70],[87,90]],
        echauff:'25 min de footing progressif à {{P}}.', corps:'3 × 12 min à {{P}} avec 3 min de récupération entre chaque. Légèrement plus long et plus intense qu\'en semaine 9.', retour:'10 min de footing léger.',
        note:'RPE 8-9/10 · 36 min totales au seuil, ton record sur ce plan.' },
      { jour:'Jeudi', type:'Spécifique', titre:'4 × 2 km à allure objectif', duree:'70 min',
        echauff:'25 min de footing EF.', corps:'4 × 2 km exactement à ton allure objectif 10km ({{OBJ}}). Récupération 90 sec au trot. Une répétition de plus qu\'en semaine 9 — la quatrième répétition est ta répétition générale.', retour:'10 min de footing léger.',
        note:'RPE 8-9/10 · Si {{OBJ}} est trop facile sur les 4, ton objectif est probablement trop prudent.' },
      { jour:'Samedi', type:'EF', titre:'Footing de récupération', duree:'45 min', pcts:[[60,60]],
        echauff:'', corps:'45 min à {{P}}. Indispensable pour absorber la charge des deux séances de qualité. Ton corps s\'adapte à un niveau supérieur.', retour:'',
        note:'RPE 3/10 · Le footing de récupération est aussi important que les séances intenses.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue', duree:'85 min', pcts:[[70,75]],
        echauff:'', corps:'85 min à {{P}}. Ta dernière vraie sortie longue avant la course. Mémorise cette sensation, la semaine de consolidation et la semaine de course vont encore l\'affiner.', retour:'',
        note:'RPE 6/10 · Après cette séance, les séances dures sont terminées.' },
    ]},
  { num:11, phase:'Consolidation', charge:'Réduite, affûtage',
    objectif:'La consolidation préserve ta forme sans t\'épuiser. Volume réduit de 40%, intensité maintenue sur une séance clé. L\'objectif : aborder la semaine de course avec les jambes fraîches.',
    conseil:'Cette semaine allégée laisse les adaptations des 10 semaines de travail s\'installer pleinement. Dors 8 heures, mange bien, évite le stress inutile. La semaine de course sera encore plus légère.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Footing léger', duree:'45 min', pcts:[[65,65]],
        echauff:'', corps:'45 min très faciles à {{P}}. Garder les jambes en mouvement sans les fatiguer. Cours au ressenti, sans montre. Profite de cette semaine allégée.', retour:'',
        note:'RPE 3/10 · Tu dois finir comme si tu venais de te promener.' },
      { jour:'Jeudi', type:'Fractionné', titre:'6 × 400 mètres, volume réduit', duree:'55 min', pcts:[[65,65],[95,100]],
        echauff:'25 min de footing progressif EF.', corps:'6 × 400m à {{P}}. Volume réduit de 50% mais intensité maintenue. Récupération 2 min entre chaque. Termine par 2 × 1 km à ton allure objectif 10km ({{OBJ}}), pour garder la sensation fraîche en tête.', retour:'10 min de footing léger.',
        note:'RPE 8/10 · Ces répétitions maintiennent tes sensations sans te fatiguer.' },
      { jour:'Samedi', type:'EF', titre:'Footing de 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}. Garde les jambes en mouvement sans les fatiguer. Cours au ressenti, détendu et régulier. Ton corps se recharge pour le jour J.', retour:'',
        note:'RPE 3/10 · Tu dois finir frais et légèrement dynamisé, jamais fatigué.' },
    ]},
  { num:12, phase:'Semaine de course', charge:'Conserve, tu es prêt',
    objectif:'Rien ne se gagne à l\'entraînement cette semaine. L\'objectif unique : arriver au départ reposé, confiant, les jambes fraîches.',
    conseil:'Fais confiance à tes 11 semaines de travail. Pars à ton allure objectif {{OBJ}} dès le départ, ne te laisse pas griser par l\'adrénaline.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing très léger', duree:'40 min', pcts:[[60,65]],
        echauff:'', corps:'40 min à {{P}}. Maintenir la circulation sanguine. Vraiment facile, si tu te sens fatigué, réduis à 30 minutes.', retour:'',
        note:'RPE 3/10 · Aucun effort. Juste des jambes qui bougent.' },
      { jour:'Mercredi', type:'Fractionné', titre:'8 × 30/30 à allure objectif', duree:'35 min',
        echauff:'15 min de footing EF très léger.',
        corps:'8 × 30 secondes à ton allure objectif 10km ({{OBJ}}) / 30 secondes au trot. Effort court et ciblé, les jambes retrouvent la sensation de vitesse avant la course.',
        retour:'10 min de jogging léger.',
        note:'RPE 6-7/10 · Ces courtes relances maintiennent les sensations sans t\'épuiser avant le jour J.' },
      { jour:'Samedi', type:'Activation', titre:'Activation J-1 + accélérations', duree:'30 min', pcts:[[60,65]],
        echauff:'', corps:'20 min de trot à {{P}}. Puis 6 à 8 accélérations progressives de 80m, démarre doucement et accélère jusqu\'à passer sous ton allure objectif {{OBJ}} sur les 20 derniers mètres. Récupère 60 sec en marchant entre chaque.', retour:'',
        note:'Ces accélérations réveillent tes fibres rapides. Efficace la veille d\'une course.' },
      { jour:'Dimanche', type:'Course', titre:'COURSE 10 KILOMÈTRES', duree:'Jour J',
        echauff:'10 min de jogging léger avant le départ.', corps:'KM 1-2 : pars à ton allure objectif {{OBJ}}, ne pars surtout pas plus vite. KM 3-8 : maintiens {{OBJ}} exactement, régularité absolue. KM 9 : accélère si tu as des réserves. KM 10 : donne absolument tout.', retour:'10-15 min de marche. Banane et eau dans les 30 min.',
        note:'Les sensations difficiles aux km 6-7 sont normales. C\'est là que se gagne un 10km.' },
    ]},
]
