// Trame 3 séances/semaine — Ebook 10km, 12 semaines · Palier Intermédiaire.
// Structure allégée : 1 EF, 1 séance qualité (Jeudi), 1 sortie longue.
// Semaine 12 = 4 séances (semaine de course).
module.exports = [
  { num:1, phase:'Adaptation', charge:'Légère',
    objectif:'Installer les habitudes d\'entraînement avec 3 séances. Prendre ses repères sur les allures sans pression de performance.',
    conseil:'Avec 3 séances, chacune compte. Ne saute pas la sortie longue, c\'est elle qui construit ta capacité à tenir 10km.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Endurance Fondamentale', duree:'40 min', pcts:[[65,70]],
        echauff:'', corps:'Course continue à {{P}}. Allure conversation, tu dois pouvoir parler en phrases complètes. Régulier et relâché.', retour:'',
        note:'RPE 4-5/10 · Finis en te sentant bien.' },
      { jour:'Jeudi', type:'Fractionné', titre:'8 × 400 mètres', duree:'60 min', pcts:[[65,65],[92,97]],
        echauff:'20 min de footing EF à {{P}}.', corps:'8 × 400m à {{P}}. Effort soutenu mais maîtrisé. Récupération 90 sec au trot entre chaque. Maintiens la même allure du premier au dernier.', retour:'10 min de jogging léger.',
        note:'RPE 8/10 · Avec 3 séances/semaine, cette séance est ta principale dose d\'intensité.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue', duree:'55 min', pcts:[[65,70]],
        echauff:'', corps:'Course continue à {{P}} pendant 50 minutes, puis les 5 dernières minutes à ton allure objectif 10km ({{OBJ}}). Hydrate-toi, concentre-toi sur ta foulée.', retour:'',
        note:'RPE 5/10 · Mémorise la sensation de ces 5 dernières minutes.' },
    ]},
  { num:2, phase:'Adaptation', charge:'Légère à modérée',
    objectif:'Confirmer les bases. Deux répétitions de plus, volume légèrement augmenté. Le plan doit commencer à sembler naturel.',
    conseil:'Sur les 10 × 400m, vise la régularité. Si les dernières sont nettement plus lentes, tu es parti trop vite.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Endurance Fondamentale', duree:'40 min', pcts:[[65,70]],
        echauff:'', corps:'40 min à {{P}}. Même principe que la semaine passée. Allure conversation, régulière du début à la fin.', retour:'',
        note:'RPE 4-5/10 · Léger et régulier.' },
      { jour:'Jeudi', type:'Fractionné', titre:'10 × 400 mètres', duree:'65 min', pcts:[[65,65],[92,97]],
        echauff:'25 min de footing EF à {{P}}.', corps:'10 × 400m à {{P}}. Deux répétitions de plus. Récupération 90 sec au trot. Maintiens la même allure sur les 10.', retour:'10 min de footing léger.',
        note:'RPE 8/10 · La récupération courte développe ta résistance à l\'effort.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue', duree:'60 min', pcts:[[70,75]],
        echauff:'', corps:'55 min à {{P}}, puis termine par 5 minutes à ton allure objectif 10km ({{OBJ}}). 5 minutes de plus que la semaine dernière sur le volume total.', retour:'',
        note:'RPE 5-6/10 · La sortie longue construit ta base aérobie.' },
    ]},
  { num:3, phase:'Développement aérobie', charge:'Modérée, première séance tempo',
    objectif:'Introduction du travail au seuil. Le tempo repousse ta limite lactique, le facteur clé de progression sur 10km.',
    conseil:'Sur le tempo, tu dois pouvoir prononcer des mots isolés mais pas tenir une conversation. Zone parfaite : difficile mais contrôlée.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Footing EF', duree:'45 min', pcts:[[65,70]],
        echauff:'', corps:'45 min à {{P}}. Long et facile avant la séance de qualité du jeudi.', retour:'',
        note:'RPE 5/10 · Garde les jambes fraîches pour le jeudi.' },
      { jour:'Jeudi', type:'Tempo', titre:'Tempo continu, 15 minutes', duree:'55 min', pcts:[[65,70],[82,82]],
        echauff:'25 min de footing progressif à {{P}}.', corps:'15 minutes continues à {{P}}. Première séance au seuil anaérobie. Difficile mais tenable. Tu peux prononcer des mots mais pas tenir une conversation.', retour:'15 min de jogging très lent.',
        note:'RPE 7-8/10 · C\'est normal si tu souffres sur les dernières minutes.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue + accélération', duree:'70 min', pcts:[[70,75],[80,82]],
        echauff:'', corps:'60 min à {{P}}, puis accélération progressive sur les 10 dernières minutes à {{P}}. Tu apprends à finir fort — compétence clé sur les 2 derniers km.', retour:'',
        note:'RPE 6/10 puis 7-8/10 · Mémorise cette sensation, tu la réutiliseras en course.' },
    ]},
  { num:4, phase:'Développement aérobie', charge:'Élevée, intervalles et sortie longue',
    objectif:'Consolider le travail aérobie avec des intervalles longs et une sortie longue plus importante. La fatigue s\'installe, dors bien.',
    conseil:'Sur les 4 × 1000m, reste maîtrisé. L\'objectif est de tenir la même allure sur les 4, pas d\'aller le plus vite sur le premier.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Footing EF', duree:'45 min', pcts:[[70,70]],
        echauff:'', corps:'45 min à {{P}}. Régulier et facile, volume avant la séance de qualité.', retour:'',
        note:'RPE 5/10 · Cours détendu.' },
      { jour:'Jeudi', type:'Fractionné', titre:'4 × 1000 mètres', duree:'65 min', pcts:[[65,65],[83,86]],
        echauff:'25 min de footing EF à {{P}}.', corps:'4 × 1000m à {{P}}. Intervalles longs, développent ta résistance à l\'allure seuil. Récupération 2 min au trot. Termine par 1 km à ton allure objectif 10km ({{OBJ}}), pour comparer les sensations.', retour:'10 min de footing léger.',
        note:'RPE 7-8/10 · Ton corps est prêt pour cette charge.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue', duree:'80 min', pcts:[[70,75]],
        echauff:'', corps:'80 min à {{P}}. Ta sortie longue la plus importante jusqu\'ici. Régularité et respiration. Hydrate-toi toutes les 20-25 min.', retour:'',
        note:'RPE 6/10 · Tu dois finir fatigué mais pas à plat.' },
    ]},
  { num:5, phase:'Développement VMA', charge:'Élevée, premier bloc VMA',
    objectif:'Introduire les intervalles à haute intensité. Les 400m à 95-100% VMA élèvent ton plafond de vitesse, ce qui te permettra de tenir une allure plus rapide sur 10km.',
    conseil:'Sur les 12 × 400m, 90 secondes de récupération complètes entre chaque. C\'est la durée calculée pour que l\'effort suivant soit aussi bon que le premier.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Footing de récupération', duree:'40 min', pcts:[[60,60]],
        echauff:'', corps:'40 min à {{P}}. Fondamentale avant la séance VMA du jeudi. Garde les jambes fraîches.', retour:'',
        note:'RPE 3/10 · Vraiment facile.' },
      { jour:'Jeudi', type:'Fractionné', titre:'12 × 400 mètres', duree:'70 min', pcts:[[65,65],[95,100]],
        echauff:'25 min de footing EF à {{P}}.', corps:'12 × 400m à {{P}}. Intensité élevée. Récupération 90 sec au trot entre chaque. Maintiens la même allure du premier au dernier.', retour:'10 min de jogging léger.',
        note:'RPE 8-9/10 · La récupération courte est le vrai stimulus de cette séance.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue avec encart allure', duree:'80 min', pcts:[[70,75]],
        echauff:'', corps:'65 min à {{P}}, puis 4 km à ton allure objectif 10km ({{OBJ}}), puis retour à l\'allure EF. Cet encart t\'apprend à tenir l\'allure quand les jambes sont sollicitées.', retour:'',
        note:'RPE 6/10 en EF · 7-8/10 sur les 4 km · Note ton allure, indicateur de ta forme.' },
    ]},
  { num:6, phase:'Développement VMA', charge:'Très élevée, côtes',
    objectif:'Les côtes développent la force propulsive et le système neuromusculaire. Une seule séance de qualité, mais la plus exigeante du plan jusqu\'ici.',
    conseil:'Chaque montée est un sprint. Genoux hauts, bras actifs, impulsion maximale au sol. La descente au trot est ta récupération — ne la raccourcis pas.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Footing léger', duree:'40 min', pcts:[[60,60]],
        echauff:'', corps:'40 min à {{P}}. Prépare les jambes pour la séance de côtes du jeudi sans les fatiguer.', retour:'',
        note:'RPE 3/10 · Vraiment facile.' },
      { jour:'Jeudi', type:'Côtes', titre:'8 × côtes, 150 mètres', duree:'60 min', pcts:[[65,70]],
        echauff:'25 min de footing progressif à {{P}}.', corps:'8 montées de 150m à effort maximal. Genoux hauts, bras actifs, pousse à fond jusqu\'en haut. Descente au trot complète entre chaque montée.', retour:'15 min de footing très léger.',
        note:'RPE 9/10 sur les montées · Les côtes renforcent tes muscles propulseurs.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue', duree:'85 min', pcts:[[70,75]],
        echauff:'', corps:'85 min à {{P}}. Ta sortie longue la plus longue jusqu\'ici. Régularité et respiration. Hydrate-toi toutes les 20-25 min.', retour:'',
        note:'RPE 6/10 · Tu dois finir fatigué mais pas à plat.' },
    ]},
  { num:7, phase:'Intensification', charge:'Très élevée, tempo long',
    objectif:'Séance tempo plus longue et plus dure que jamais. Avec seulement 3 séances/semaine, cette séance porte toute la charge de qualité — donne-toi pleinement.',
    conseil:'Sur les 2 × 15 min, l\'allure doit être tenue du début à la fin des deux répétitions. Ne lève pas le pied sur la deuxième.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Footing long EF', duree:'50 min', pcts:[[70,70],[65,65]],
        echauff:'', corps:'50 min à {{P}}. Long et facile avant la séance de qualité du jeudi. Si tu te sens fatigué, passe à {{P}}.', retour:'',
        note:'RPE 5/10 · Ce footing prépare la séance du jeudi.' },
      { jour:'Jeudi', type:'Tempo', titre:'2 × 15 minutes au seuil', duree:'65 min', pcts:[[85,85]],
        echauff:'25 min de footing progressif EF.', corps:'2 × 15 min à {{P}} avec 3 min de récupération entre chaque. La deuxième répétition arrive fatiguée, maintiens l\'allure.', retour:'10 min de footing léger.',
        note:'RPE 8/10 · 30 min totales au seuil, ton record sur ce plan.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue', duree:'90 min', pcts:[[72,75]],
        echauff:'', corps:'90 min à {{P}}. Ta sortie longue la plus longue du plan. Régularité, respiration, hydratation toutes les 20 min.', retour:'',
        note:'RPE 6/10 · Après cette semaine, la forme monte d\'un cran.' },
    ]},
  { num:8, phase:'Intensification', charge:'Maximale, pic de charge',
    objectif:'Le pic de ta préparation. Fractionnés courts à très haute intensité. Ce que tu construis ici sera transformé en performance sur les semaines de spécificité.',
    conseil:'C\'est ta semaine de charge maximale. N\'ajoute rien. Mange des glucides les soirs avant la séance de qualité. Dors 8 heures.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Endurance Fondamentale', duree:'45 min', pcts:[[65,70]],
        echauff:'', corps:'45 min à {{P}}. Régulier et facile, garde les jambes prêtes pour la séance du jeudi.', retour:'',
        note:'RPE 4/10 · Cours détendu.' },
      { jour:'Jeudi', type:'Fractionné', titre:'14 × 300 mètres', duree:'70 min', pcts:[[65,65],[100,105]],
        echauff:'25 min de footing EF à {{P}}.', corps:'14 × 300m à {{P}}. Intensité très élevée. Récupération 60 sec entre chaque. Maintiens la même vitesse sur les 14. Termine par 2 × 1 km à ton allure objectif 10km ({{OBJ}}), récupération 60 sec.', retour:'10 min de footing léger.',
        note:'RPE 9/10 · 60 sec de récupération calculées pour forcer l\'adaptation.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue avec encart allure', duree:'85 min', pcts:[[70,75]],
        echauff:'', corps:'65 min à {{P}}, puis 4 km à ton allure objectif 10km ({{OBJ}}), puis retour à l\'allure EF. Les 4 km à allure objectif quand tu es fatigué te préparent directement à la fin de course.', retour:'',
        note:'RPE 6/10 en EF · 8/10 sur les 4 km · Après cette semaine, l\'entraînement dur est terminé.' },
    ]},
  { num:9, phase:'Spécificité', charge:'Élevée, travail à l\'allure objectif',
    objectif:'Toutes les séances s\'alignent sur ton allure de course. Le travail spécifique t\'apprend à tenir {{OBJ}} quand les jambes sont chargées.',
    conseil:'Sur les 3 × 2 km, chaque répétition doit être exactement à {{OBJ}}. L\'objectif est la répétabilité, pas la vitesse maximale.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Footing EF', duree:'45 min', pcts:[[65,70]],
        echauff:'', corps:'45 min à {{P}}. Régulier et facile, prépare les jambes pour la séance spécifique du jeudi.', retour:'',
        note:'RPE 4/10 · Garde les jambes fraîches pour le jeudi.' },
      { jour:'Jeudi', type:'Spécifique', titre:'3 × 2 km à allure objectif', duree:'65 min',
        echauff:'25 min de footing EF.', corps:'3 × 2 km exactement à ton allure objectif 10km ({{OBJ}}). Récupération 90 sec au trot. C\'est littéralement ton allure de course que tu répètes, sous la fatigue.', retour:'10 min de footing léger.',
        note:'RPE 8/10 · Si {{OBJ}} est trop facile, ton objectif est peut-être trop prudent.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue', duree:'80 min', pcts:[[70,75]],
        echauff:'', corps:'80 min à {{P}}. Régulier, hydraté, concentré. Cette sortie construit la résistance qui te servira aux km 7-10 le jour J.', retour:'',
        note:'RPE 6/10 · Mémorise la sensation de fin de sortie.' },
    ]},
  { num:10, phase:'Spécificité', charge:'Très élevée, pic de spécificité',
    objectif:'Ta dernière vraie semaine de charge à l\'allure course. Les 4 × 2 km sont ta répétition générale.',
    conseil:'Sur les 4 × 2 km, la quatrième est la plus précieuse : elle simule la fin de course avec des jambes chargées. Maintiens {{OBJ}} coûte que coûte.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Footing EF', duree:'45 min', pcts:[[65,70]],
        echauff:'', corps:'45 min à {{P}}. Régulier et facile avant la séance spécifique du jeudi.', retour:'',
        note:'RPE 4/10 · Cours détendu.' },
      { jour:'Jeudi', type:'Spécifique', titre:'4 × 2 km à allure objectif', duree:'70 min',
        echauff:'25 min de footing EF.', corps:'4 × 2 km exactement à ton allure objectif 10km ({{OBJ}}). Récupération 90 sec au trot. Une répétition de plus qu\'en semaine 9 — la quatrième est ta répétition générale.', retour:'10 min de footing léger.',
        note:'RPE 8-9/10 · Si {{OBJ}} est trop facile sur les 4, ton objectif est probablement trop prudent.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue', duree:'80 min', pcts:[[70,75]],
        echauff:'', corps:'80 min à {{P}}. Ta dernière vraie sortie longue avant la course. Mémorise cette sensation, la semaine de consolidation va encore l\'affiner.', retour:'',
        note:'RPE 6/10 · Après cette séance, les séances dures sont terminées.' },
    ]},
  { num:11, phase:'Consolidation', charge:'Réduite, affûtage',
    objectif:'La consolidation préserve ta forme sans t\'épuiser. Volume réduit, intensité maintenue sur une courte séance clé. L\'objectif : aborder la semaine de course avec les jambes fraîches.',
    conseil:'Cette semaine allégée laisse les adaptations de la préparation s\'installer pleinement. Dors 8 heures, mange bien, évite le stress inutile.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Footing léger', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min très faciles à {{P}}. Garder les jambes en mouvement sans les fatiguer. Cours au ressenti, sans montre.', retour:'',
        note:'RPE 3/10 · Tu dois finir comme si tu venais de te promener.' },
      { jour:'Jeudi', type:'Fractionné', titre:'4 × 400 mètres, volume réduit', duree:'45 min', pcts:[[65,65],[95,100]],
        echauff:'25 min de footing progressif EF.', corps:'4 × 400m à {{P}}. Volume réduit mais intensité maintenue. Récupération 2 min entre chaque. Termine par 1 km à ton allure objectif 10km ({{OBJ}}), pour garder la sensation fraîche en tête.', retour:'10 min de footing léger.',
        note:'RPE 8/10 · Ces répétitions maintiennent tes sensations sans te fatiguer.' },
      { jour:'Samedi', type:'EF', titre:'Footing de 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}. Garde les jambes en mouvement sans les fatiguer. Ton corps se recharge pour le jour J.', retour:'',
        note:'RPE 3/10 · Tu dois finir frais, jamais fatigué.' },
    ]},
  { num:12, phase:'Semaine de course', charge:'Conserve, tu es prêt',
    objectif:'Rien ne se gagne à l\'entraînement cette semaine. L\'objectif unique : arriver au départ reposé, confiant, les jambes fraîches.',
    conseil:'Fais confiance à tes 11 semaines de travail. Pars à ton allure objectif {{OBJ}} dès le départ, ne te laisse pas griser par l\'adrénaline.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Footing très léger', duree:'40 min', pcts:[[60,65]],
        echauff:'', corps:'40 min à {{P}}. Maintenir la circulation sanguine. Vraiment facile. Profite pour visualiser ta course à ton allure objectif {{OBJ}}.', retour:'',
        note:'RPE 3/10 · Aucun effort. Juste des jambes qui bougent.' },
      { jour:'Mercredi', type:'Fractionné', titre:'8 × 30/30 à allure objectif', duree:'35 min',
        echauff:'15 min de footing EF très léger.',
        corps:'8 × 30 secondes à ton allure objectif 10km ({{OBJ}}) / 30 secondes au trot. Effort court et ciblé, les jambes retrouvent la sensation de vitesse avant la course.',
        retour:'10 min de jogging léger.',
        note:'RPE 6-7/10 · Ces courtes relances maintiennent les sensations sans t\'épuiser avant le jour J.' },
      { jour:'Samedi', type:'Activation', titre:'Activation J-1 + accélérations', duree:'30 min', pcts:[[60,65]],
        echauff:'', corps:'20 min de trot à {{P}}. Puis 6 accélérations progressives de 80m, démarre doucement et accélère jusqu\'à passer sous ton allure objectif {{OBJ}} sur les 20 derniers mètres. Récupère 60 sec en marchant entre chaque.', retour:'',
        note:'Ces accélérations réveillent tes fibres rapides. Efficace la veille d\'une course.' },
      { jour:'Dimanche', type:'Course', titre:'COURSE 10 KILOMÈTRES', duree:'Jour J',
        echauff:'10 min de jogging léger avant le départ.', corps:'KM 1-2 : pars à ton allure objectif {{OBJ}}, ne pars surtout pas plus vite. KM 3-8 : maintiens {{OBJ}} exactement, régularité absolue. KM 9 : accélère si tu as des réserves. KM 10 : donne absolument tout.', retour:'10-15 min de marche. Banane et eau dans les 30 min.',
        note:'Les sensations difficiles aux km 6-7 sont normales. C\'est là que se gagne un 10km.' },
    ]},
]
