// Marathon 12 semaines · 5 séances/semaine · Palier Intermédiaire (VMA 13.5 à 18.5)
// 5 séances : 2 qualités séparées par RA, EF long, SL spécifique marathon. Volume jusqu'à 2h30.
// Palette : EF 60min, FP, RA, CO, FL-07/12/13/14, T-03/04/05, SP-05, SL jusqu'à 2h30
// {{P}} remplacé séquentiellement · {{OBJ}} = allure objectif marathon (80% VMA)
module.exports = [
  { num:1, phase:'Adaptation', charge:'Légère',
    objectif:'Installer le rythme sur 5 séances. Le footing d\'ouverture est long (60 min), la séance de récupération active du jeudi est une spécificité marathon : avec 5 sessions, la récupération entre les sessions est aussi importante que les sessions elles-mêmes.',
    conseil:'Sur les 5×1000m du mercredi, sens la régularité plutôt que la vitesse. Si le dernier est plus lent de plus de 10 secondes, tu es parti trop vite.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Endurance fondamentale 60 minutes', duree:'60 min', pcts:[[65,72]],
        echauff:'', corps:'60 min à {{P}}. Allure conversation. Plus long qu\'un plan semi : le marathon se bâtit sur des volumes plus importants dès les premières séances.', retour:'',
        note:'RPE 5/10 · 60 min de base dès la semaine 1 — marqueur d\'un plan marathon.' },
      { jour:'Mercredi', type:'Fractionné', titre:'5 × 1000 mètres', duree:'65 min', pcts:[[65,65],[85,90]],
        echauff:'25 min progressif à {{P}}, terminer par 4 accélérations de 80m.', corps:'5 × 1000m à {{P}}. Récupération 2 min au trot entre chaque. Maintiens la même allure sur les 5. Termine par 1 km à allure objectif marathon ({{OBJ}}) pour graver la sensation.', retour:'10 min footing très lent.',
        note:'RPE 7-8/10 · La régularité prime sur la vitesse.' },
      { jour:'Jeudi', type:'EF', titre:'Récupération active 35 minutes', duree:'35 min', pcts:[[60,65]],
        echauff:'', corps:'35 min à {{P}}. Très lent, jambes légères, allure de promenade. Relance la circulation après les 1000m de mercredi.', retour:'',
        note:'RPE 3/10 · La récupération active accélère la récupération musculaire. Vraiment lent.' },
      { jour:'Samedi', type:'EF', titre:'Footing de récupération 40 minutes', duree:'40 min', pcts:[[60,65]],
        echauff:'', corps:'40 min à {{P}}. Active la circulation avant la sortie longue de dimanche. Vraiment détendu, sans effort.', retour:'',
        note:'RPE 3/10 · Prépare les jambes pour la sortie longue.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 80 minutes', duree:'80 min', pcts:[[65,72]],
        echauff:'', corps:'80 min à {{P}}. La sortie longue est la séance pilier du marathon. Hydrate-toi toutes les 20-25 min. Régulier et contrôlé.', retour:'',
        note:'RPE 5/10 · La durée prime sur l\'allure.' },
    ]},
  { num:2, phase:'Adaptation', charge:'Légère à modérée',
    objectif:'Introduire le footing progressif et les côtes. Avec 5 séances, les côtes en mardi et les 4×2000m en vendredi ne se marchent pas sur les pieds grâce à la RA du jeudi.',
    conseil:'Sur le footing progressif, la transition entre les zones doit être douce et naturelle. La dernière phase à 80-85% VMA doit être maîtrisée, pas subie.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing progressif 3 phases', duree:'60 min', pcts:[[65,68],[72,75],[80,85]],
        echauff:'10 min trot très lent à {{P}}.', corps:'20 min à {{P}} (aisé) → 20 min à {{P}} (modéré) → 20 min à {{P}} (soutenu). La progression se fait naturellement. Le dernier bloc à allure seuil bas développe ton sens de l\'allure marathon.', retour:'10 min trot très lent.',
        note:'RPE 5-7/10 progressif · Cette séance développe ton sens de l\'allure, clé du marathon.' },
      { jour:'Mercredi', type:'Côtes', titre:'8 côtes de 80 mètres — puissance neuromusculaire', duree:'55 min', pcts:[[65,70]],
        echauff:'25 min progressif à {{P}}, finir par 4 lignes droites.', corps:'8 montées de 80m à RPE 8-9/10 — genoux hauts, bras actifs, appuis dynamiques. Descente en marchant pour récupération complète entre chaque montée.', retour:'10 min footing léger.',
        note:'RPE 8-9/10 sur les montées · Les côtes renforcent les appuis et l\'économie de course sans charge cardio excessive.' },
      { jour:'Jeudi', type:'EF', titre:'Récupération active 35 minutes', duree:'35 min', pcts:[[60,65]],
        echauff:'', corps:'35 min à {{P}}. Récupération active après les côtes de mercredi. Vraiment lent, sans effort. Indispensable avant les 2000m de vendredi.', retour:'',
        note:'RPE 3/10 · Récupération active — ne saute pas cette séance.' },
      { jour:'Vendredi', type:'Fractionné', titre:'4 × 2000 mètres — seuil aérobie long', duree:'70 min', pcts:[[65,65],[80,87]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations 80m.', corps:'4 × 2000m à {{P}}. Récupération 3 min au trot entre chaque. Les 2000m sont la distance marathonienne par excellence. Régularité sur les 4 blocs.', retour:'10 min footing très lent.',
        note:'RPE 7-8/10 · Le dernier doit être aussi rapide que le premier.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 90 minutes', duree:'90 min', pcts:[[65,72]],
        echauff:'', corps:'90 min à {{P}}. 10 min de plus que la semaine 1. Gère ton allure sur les 30 premières minutes. Hydrate-toi toutes les 20-25 min.', retour:'',
        note:'RPE 5-6/10 · La sortie longue est la séance la plus importante du plan marathon.' },
    ]},
  { num:3, phase:'Développement aérobie', charge:'Modérée, deux séances de qualité distinctes',
    objectif:'Avec 5 séances, on peut se permettre deux séances de qualité séparées par une RA le jeudi. Le tempo de 20 min en continu + les 3×3000m constituent la semaine de développement type du marathonien.',
    conseil:'Sur le 20 min continu, pars légèrement en dessous de ta zone cible les 5 premières minutes. 20 min en continu au seuil est plus exigeant mentalement que des blocs.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Endurance fondamentale 60 minutes', duree:'60 min', pcts:[[65,72]],
        echauff:'', corps:'60 min à {{P}}. Long et facile avant la semaine à deux séances de qualité. Travaille ta technique : légère bascule vers l\'avant, attaque milieu du pied.', retour:'',
        note:'RPE 5/10 · Volume de base. Ne rogne pas sur cette séance.' },
      { jour:'Mercredi', type:'Tempo', titre:'Tempo 20 minutes en continu', duree:'65 min', pcts:[[65,72],[82,88]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations 80m.', corps:'20 min continus à {{P}}. Effort soutenu et régulier sans rupture. Tu dois pouvoir prononcer des mots isolés.', retour:'10 min footing très lent.',
        note:'RPE 7-8/10 · 20 min en continu au seuil est le palier clé pour le marathon.' },
      { jour:'Jeudi', type:'EF', titre:'Récupération active 35 minutes', duree:'35 min', pcts:[[60,65]],
        echauff:'', corps:'35 min à {{P}}. Récupération active après le tempo de mercredi. Vraiment détendu. Indispensable avant les 3×3000m de vendredi.', retour:'',
        note:'RPE 3/10 · Cette RA te permet de courir les 3×3000m dans de bonnes conditions.' },
      { jour:'Vendredi', type:'Fractionné', titre:'3 × 3000 mètres — endurance spécifique marathon', duree:'80 min', pcts:[[65,65],[80,85]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations 80m.', corps:'3 × 3000m à {{P}}. Récupération 4 min au trot entre chaque. 9 km à intensité — séance exclusivement marathon. Pars conservateur sur le premier.', retour:'10 min footing très lent.',
        note:'RPE 8/10 · Les 3×3000m sont la séance marathon clé. Si le 3ème s\'effondre, tu es parti trop vite.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 95 minutes + fin allure marathon', duree:'95 min', pcts:[[65,72]],
        echauff:'', corps:'80 min à {{P}}, puis 15 min à ton allure objectif marathon ({{OBJ}}). Premier contact avec l\'allure cible sur jambes fatiguées — mémorise cette sensation.', retour:'',
        note:'RPE 5-6/10 puis 6-7/10 · La fin à {{OBJ}} est un repère précieux sur ta forme actuelle.' },
    ]},
  { num:4, phase:'Développement aérobie', charge:'Élevée, consolidation seuil',
    objectif:'2×20 min au seuil + 3×3000m avec bloc marathon en fin : deux séances de qualité différentes dans la même semaine. Avec 5 séances, la RA du jeudi permet cette progression sans surcharger.',
    conseil:'Sur les 2×20 min, le deuxième bloc est intentionnellement plus difficile. Maintiens l\'allure sans ralentir — c\'est l\'inconfort du deuxième bloc qui produit le progrès.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing progressif 3 phases', duree:'60 min', pcts:[[65,68],[72,75],[80,85]],
        echauff:'10 min trot très lent à {{P}}.', corps:'20 min à {{P}} (aisé) → 20 min à {{P}} (modéré) → 20 min à {{P}} (soutenu). La dernière phase à allure seuil bas est la plus utile pour le marathon.', retour:'10 min trot très lent.',
        note:'RPE 5-7/10 progressif · Développe la capacité à changer de zone en course.' },
      { jour:'Mercredi', type:'Tempo', titre:'2 × 20 minutes au seuil', duree:'80 min', pcts:[[65,72],[82,88]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations 80m.', corps:'2 × 20 min à {{P}} avec 5 min de récupération entre les 2 blocs. 40 min totales au seuil. Si le deuxième bloc est nettement plus lent, note-le.', retour:'10 min footing très lent.',
        note:'RPE 8/10 · 40 min au seuil. Ta séance tempo la plus exigeante jusqu\'ici.' },
      { jour:'Jeudi', type:'EF', titre:'Récupération active 35 minutes', duree:'35 min', pcts:[[60,65]],
        echauff:'', corps:'35 min à {{P}}. Récupération active après le tempo de mercredi. Vraiment détendu. Indispensable avant les 3×3000m de vendredi.', retour:'',
        note:'RPE 3/10 · La RA du jeudi est ce qui rend possible les 3×3000m le lendemain.' },
      { jour:'Vendredi', type:'Fractionné', titre:'3 × 3000 mètres + bloc allure marathon', duree:'85 min', pcts:[[65,65],[80,85]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations 80m.', corps:'3 × 3000m à {{P}}. Récupération 4 min au trot. Après le dernier 3000m et 2 min de récup, termine par 2 km à ton allure objectif marathon ({{OBJ}}).', retour:'10 min footing très lent.',
        note:'RPE 8/10 · Le bloc final à {{OBJ}} grave l\'allure cible dans ta mémoire musculaire.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 100 minutes + 20 min allure marathon', duree:'100 min', pcts:[[65,72]],
        echauff:'', corps:'80 min à {{P}}, puis 20 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h de course. Les 20 dernières minutes à allure cible sont le vrai test de la semaine.', retour:'',
        note:'RPE 6/10 puis 7/10 · Si {{OBJ}} semble gérable sur les 20 dernières minutes, c\'est bon signe.' },
    ]},
  { num:5, phase:'Volume marathon', charge:'Élevée, cap des 2 heures',
    objectif:'30 min de tempo en continu — séance tempo de référence marathon. La sortie longue de 2h avec 30 min à allure marathon constitue la plus grande charge de volume jusqu\'ici.',
    conseil:'Sur le 30 min continu, gère le départ : pars à la limite basse de la zone (82% VMA). À la 20ème minute tu te sens limité — c\'est normal, c\'est là que l\'adaptation se produit.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Endurance fondamentale 60 minutes', duree:'60 min', pcts:[[65,72]],
        echauff:'', corps:'60 min à {{P}}. Volume de base avant la semaine chargée. Très facile, jamais fatigant.', retour:'',
        note:'RPE 5/10 · Lance la semaine en douceur.' },
      { jour:'Mercredi', type:'Tempo', titre:'Tempo 30 minutes en continu', duree:'75 min', pcts:[[65,72],[82,88]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations 80m.', corps:'30 min continus à {{P}}. Ta séance tempo de référence marathon. Pars à la limite basse de la zone, tiens les 30 min complets sans réduire l\'allure.', retour:'10 min footing très lent.',
        note:'RPE 8/10 · 30 min en continu est significativement plus dur que 2×15 min.' },
      { jour:'Jeudi', type:'EF', titre:'Récupération active 35 minutes', duree:'35 min', pcts:[[60,65]],
        echauff:'', corps:'35 min à {{P}}. Récupération active après le tempo de mercredi. Vraiment détendu. Cette séance accélère ta récupération.', retour:'',
        note:'RPE 3/10 · Ce footing te fait récupérer plus vite.' },
      { jour:'Samedi', type:'EF', titre:'Footing de récupération 40 minutes', duree:'40 min', pcts:[[60,65]],
        echauff:'', corps:'40 min à {{P}}. Récupération active avant la grande sortie longue de demain. Vraiment détendu. Les jambes doivent être fraîches pour la SL.', retour:'',
        note:'RPE 3/10 · Jambes fraîches pour la sortie longue de demain.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 2 heures avec 30 min allure marathon', duree:'2h', pcts:[[65,72]],
        echauff:'', corps:'90 min à {{P}}, puis 30 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h et à 1h20. Les 30 dernières minutes à {{OBJ}} simulent le dernier tiers du marathon.', retour:'',
        note:'RPE 6/10 puis 7-8/10 · Après cette séance, tu as une référence directe sur ta capacité à tenir {{OBJ}}.' },
    ]},
  { num:6, phase:'Volume marathon', charge:'Très élevée, séance 2×5000m',
    objectif:'La séance 2×5000m est la plus marathon-spécifique du plan : 10 km à intensité modérée-haute. La sortie longue de 2h15 consolide le volume.',
    conseil:'Sur les 2×5000m, les 3 premières minutes du premier bloc doivent sembler trop faciles. Le 5000m est long — ceux qui partent bien finissent fort. Ceux qui partent trop vite craquent à 3500m.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing progressif 3 phases', duree:'60 min', pcts:[[65,68],[72,75],[80,85]],
        echauff:'10 min trot très lent à {{P}}.', corps:'20 min à {{P}} (aisé) → 20 min à {{P}} (modéré) → 20 min à {{P}} (soutenu). Long et progressif avant la semaine très chargée.', retour:'10 min trot très lent.',
        note:'RPE 5-7/10 progressif · Le footing progressif prépare le corps aux changements de rythme en course.' },
      { jour:'Mercredi', type:'Fractionné', titre:'2 × 5000 mètres — long spécifique marathon', duree:'90 min', pcts:[[65,65],[78,83]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations 80m.', corps:'2 × 5000m à {{P}}. Récupération 5 min au trot entre les 2 blocs. 10 km à intensité — séance exclusivement marathon. Pars conservateur sur le premier.', retour:'10 min footing très lent.',
        note:'RPE 8/10 · Les 2×5000m sont une séance exclusivement marathon. Réserve-toi pour le deuxième bloc.' },
      { jour:'Jeudi', type:'EF', titre:'Récupération active 35 minutes', duree:'35 min', pcts:[[60,65]],
        echauff:'', corps:'35 min à {{P}}. Récupération active indispensable après les 5000m de mercredi. Vraiment très lent, sans chrono.', retour:'',
        note:'RPE 3/10 · Indispensable.' },
      { jour:'Samedi', type:'EF', titre:'Footing de récupération 40 minutes', duree:'40 min', pcts:[[60,65]],
        echauff:'', corps:'40 min à {{P}}. Récupération active avant la sortie longue avec encart marathon. Vraiment détendu.', retour:'',
        note:'RPE 3/10 · Jambes fraîches pour la sortie longue spécifique.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 2h15 avec 10 km allure marathon', duree:'2h15', pcts:[[65,72]],
        echauff:'', corps:'105 min à {{P}}, puis 10 km à ton allure objectif marathon ({{OBJ}}). Gel à 1h et à 1h30. Les 10 km à {{OBJ}} après 1h45 de course testent ta capacité à tenir l\'allure en état de fatigue.', retour:'',
        note:'RPE 6/10 en EF · 7-8/10 sur les 10 km · Note ton ressenti km par km sur le bloc marathon.' },
    ]},
  { num:7, phase:'Intensification', charge:'Très élevée, séance progressive complexe',
    objectif:'La séance 3000/5000/3000 à intensité croissante est la grande séance marathon du plan. Associée à un 2×20 min en vendredi et à la sortie longue de 2h20, c\'est la semaine la plus exigeante jusqu\'ici.',
    conseil:'Sur la séance 3000/5000/3000, le 5000m central doit être tenu régulièrement. La régularité sur le bloc du milieu est la clé. Le dernier 3000m doit être le plus fort des 3.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Endurance fondamentale 60 minutes', duree:'60 min', pcts:[[65,72]],
        echauff:'', corps:'60 min à {{P}}. Long et facile avant la semaine très chargée. Régulier, hydraté, sans effort excessif.', retour:'',
        note:'RPE 5/10 · Prépare les jambes aux séances de qualité de la semaine.' },
      { jour:'Mercredi', type:'Fractionné', titre:'3000m / 5000m / 3000m progressif — séance marathon clé', duree:'90 min', pcts:[[65,65],[80,82],[82,85],[85,88]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations 80m.', corps:'3000m à {{P}} → récup 4 min trot → 5000m à {{P}} → récup 5 min trot → 3000m à {{P}}. Progression sur les 3 blocs : tu dois finir le dernier 3000m plus fort que le premier.', retour:'10 min footing très lent.',
        note:'RPE 8-9/10 sur le dernier bloc · La progression sur les 3 blocs est le vrai test de ta condition marathon.' },
      { jour:'Jeudi', type:'EF', titre:'Récupération active 35 minutes', duree:'35 min', pcts:[[60,65]],
        echauff:'', corps:'35 min à {{P}}. Récupération active après la grande séance de mercredi. Vraiment détendu. Indispensable avant le tempo de vendredi.', retour:'',
        note:'RPE 3/10 · La RA du jeudi est ce qui rend possible le tempo le lendemain.' },
      { jour:'Vendredi', type:'Tempo', titre:'2 × 20 minutes au seuil', duree:'80 min', pcts:[[65,72],[82,88]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations 80m.', corps:'2 × 20 min à {{P}} avec 5 min de récupération entre les 2 blocs. Même séance qu\'en semaine 4 — mais avec la fatigue de mercredi dans les jambes. Tiens les 20 min sur chaque bloc.', retour:'10 min footing très lent.',
        note:'RPE 8/10 · Deux séances de qualité en 3 jours — c\'est ce qui produit l\'adaptation marathon.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 2h20 avec 15 km allure marathon', duree:'2h20', pcts:[[65,72]],
        echauff:'', corps:'90 min à {{P}}, puis 15 km à ton allure objectif marathon ({{OBJ}}). Gel à 1h, à 1h20, à 1h50. Ces 15 km après 90 min simulent exactement la deuxième moitié d\'un marathon réel.', retour:'',
        note:'RPE 6/10 en EF · 7-8/10 sur les 15 km · Ta répétition la plus fidèle du marathon jusqu\'ici.' },
    ]},
  { num:8, phase:'Intensification', charge:'Maximale, pic de charge du plan',
    objectif:'La semaine la plus chargée. La séance mixte (3×2000m seuil + 2×2000m allure marathon) + 8×1000m en vendredi + sortie longue de 2h30 : le pic de préparation.',
    conseil:'Sur la séance 5×2000m mixte, les 3 premiers blocs au seuil te fatiguent pour que les 2 derniers à allure marathon soient courus sur jambes chargées. C\'est exactement ce que tu vivras aux km 30-42.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing progressif 3 phases', duree:'60 min', pcts:[[65,68],[72,75],[80,85]],
        echauff:'10 min trot très lent à {{P}}.', corps:'20 min à {{P}} (aisé) → 20 min à {{P}} (modéré) → 20 min à {{P}} (soutenu). Long et progressif avant la semaine de charge maximale.', retour:'10 min trot très lent.',
        note:'RPE 5-7/10 progressif · Prépare les jambes aux deux séances dures de la semaine.' },
      { jour:'Mercredi', type:'Fractionné', titre:'3×2000m seuil + 2×2000m allure marathon — séance de transition', duree:'85 min', pcts:[[65,65],[82,87],[80,80]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations 80m.', corps:'3 × 2000m à {{P}} (seuil) → récup 3 min trot → 2 × 2000m à ton allure objectif marathon ({{OBJ}}). La transition vers l\'allure marathon sur les 2 derniers blocs — après 6 km de seuil — est l\'élément clé.', retour:'10 min footing très lent.',
        note:'RPE 8-9/10 · Cette séance simule le passage entre effort soutenu et gestion du marathon.' },
      { jour:'Jeudi', type:'EF', titre:'Récupération active 35 minutes', duree:'35 min', pcts:[[60,65]],
        echauff:'', corps:'35 min à {{P}}. Récupération active après la séance de transition. Indispensable avant les 8×1000m de vendredi.', retour:'',
        note:'RPE 3/10 · Indispensable.' },
      { jour:'Vendredi', type:'Fractionné', titre:'8 × 1000 mètres — volume VMA', duree:'75 min', pcts:[[65,65],[83,88]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations 80m.', corps:'8 × 1000m à {{P}}. Récupération 90 sec au trot — plus courte que d\'habitude, ce qui exige une gestion d\'allure intelligente. Pars conservateur, maintiens la régularité sur les 8.', retour:'10 min footing très lent.',
        note:'RPE 8/10 · Semaine de charge maximale. La fatigue en fin de séance est normale.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 2h30 avec 15 km allure marathon', duree:'2h30', pcts:[[65,72]],
        echauff:'', corps:'100 min à {{P}}, puis 15 km à ton allure objectif marathon ({{OBJ}}). Gel à 1h, à 1h30, à 1h55. Ces 15 km après 1h40 sont ta répétition générale.', retour:'',
        note:'RPE 6/10 en EF · 8/10 sur les 15 km · Après cette semaine, l\'entraînement dur est terminé. Récupère sérieusement.' },
    ]},
  { num:9, phase:'Spécificité marathon', charge:'Élevée, travail à l\'allure objectif',
    objectif:'Les séances s\'alignent sur l\'allure de course. Avec 5 séances, deux sessions spécifiques marathon dans la semaine : les 3×5km le mercredi et la sortie longue spécifique le dimanche.',
    conseil:'Sur les 3×5km, chaque bloc doit être exactement à {{OBJ}} — ni plus vite, ni plus lentement. La régularité parfaite des 3 blocs prouve que tu maîtrises l\'allure marathon.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Endurance fondamentale 50 minutes', duree:'50 min', pcts:[[65,72]],
        echauff:'', corps:'50 min à {{P}}. Volume légèrement réduit — le corps entre dans la phase de spécificité. Facile et régulier.', retour:'',
        note:'RPE 5/10 · Volume réduit pour préserver les jambes.' },
      { jour:'Mercredi', type:'Spécifique', titre:'3 × 5 km à allure marathon', duree:'90 min', pcts:[[65,65]],
        echauff:'25 min footing EF à {{P}}, finir par 4 accélérations 80m.', corps:'3 × 5 km exactement à ton allure objectif marathon ({{OBJ}}). Récupération 4 min au trot entre chaque. 15 km à l\'allure de ta course.', retour:'10 min footing léger.',
        note:'RPE 7-8/10 · Si les 3 blocs sont réguliers et {{OBJ}} semble gérable, ton objectif est validé.' },
      { jour:'Jeudi', type:'EF', titre:'Récupération active 35 minutes', duree:'35 min', pcts:[[60,65]],
        echauff:'', corps:'35 min à {{P}}. Récupération après la séance spécifique. Vraiment lent, sans effort.', retour:'',
        note:'RPE 3/10 · Vraiment facile, sans exception.' },
      { jour:'Samedi', type:'EF', titre:'Footing de récupération 40 minutes', duree:'40 min', pcts:[[60,65]],
        echauff:'', corps:'40 min à {{P}}. Active la circulation avant la sortie longue spécifique de demain. Vraiment détendu.', retour:'',
        note:'RPE 3/10 · Jambes fraîches pour demain.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 2h10 avec 12 km allure marathon', duree:'2h10', pcts:[[65,72]],
        echauff:'', corps:'80 min à {{P}}, puis 12 km à ton allure objectif marathon ({{OBJ}}). Gel à 1h et à 1h20. Ces 12 km après 80 min de course consolident la mémoire de l\'allure cible.', retour:'',
        note:'RPE 6/10 en EF · 7-8/10 sur les 12 km · Note ton ressenti sur chaque km du bloc marathon.' },
    ]},
  { num:10, phase:'Spécificité marathon', charge:'Très élevée, pic de spécificité',
    objectif:'Ta dernière vraie semaine de charge. Les 2×5000m en mercredi + les 3×5km en vendredi constituent le pic de spécificité.',
    conseil:'Sur les 2×5000m, le deuxième bloc est le plus précieux : tu es fatigué et tu dois tenir la même allure. C\'est exactement ce que tu feras aux km 25-35 du marathon.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing progressif 3 phases', duree:'50 min', pcts:[[65,68],[72,75],[80,85]],
        echauff:'10 min trot très lent à {{P}}.', corps:'15 min à {{P}} (aisé) → 15 min à {{P}} (modéré) → 20 min à {{P}} (soutenu). Version légèrement réduite avant la semaine de charge spécifique.', retour:'10 min trot très lent.',
        note:'RPE 5-7/10 progressif · Activation avant les séances de référence de la semaine.' },
      { jour:'Mercredi', type:'Fractionné', titre:'2 × 5000 mètres — répétition générale', duree:'90 min', pcts:[[65,65],[78,83]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations 80m.', corps:'2 × 5000m à {{P}}. Récupération 5 min au trot entre les 2 blocs. Le deuxième 5000m est ta répétition générale avant le marathon : jambes chargées, tu dois tenir.', retour:'10 min footing très lent.',
        note:'RPE 8/10 · Le deuxième 5000m aussi régulier que le premier = signe de préparation solide.' },
      { jour:'Jeudi', type:'EF', titre:'Récupération active 35 minutes', duree:'35 min', pcts:[[60,65]],
        echauff:'', corps:'35 min à {{P}}. Récupération active après les 5000m. Indispensable avant les 3×5km de vendredi.', retour:'',
        note:'RPE 3/10 · Indispensable.' },
      { jour:'Vendredi', type:'Spécifique', titre:'3 × 5 km à allure marathon — version finale', duree:'90 min', pcts:[[65,65]],
        echauff:'20 min footing EF à {{P}}.', corps:'3 × 5 km exactement à ton allure objectif marathon ({{OBJ}}). Récupération 4 min au trot. La même séance qu\'en semaine 9 — mais avec la fatigue de mercredi. Si tu tiens les 3 blocs, ta préparation est terminée.', retour:'10 min footing léger.',
        note:'RPE 7-8/10 · Après cette séance, les séances dures sont terminées.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 2h avec 10 km allure marathon', duree:'2h', pcts:[[65,72]],
        echauff:'', corps:'70 min à {{P}}, puis 10 km à ton allure objectif marathon ({{OBJ}}). Gel à 1h et à 1h10. Dernière sortie longue chargée.', retour:'',
        note:'RPE 6/10 en EF · 7-8/10 sur les 10 km · Après cette sortie, les séances dures sont terminées.' },
    ]},
  { num:11, phase:'Consolidation', charge:'Réduite, affûtage',
    objectif:'La consolidation préserve ta forme sans t\'épuiser. Volume réduit de 45%, intensité maintenue sur une séance clé. Arrive à la semaine de course avec les jambes fraîches.',
    conseil:'Cette semaine allégée laisse les adaptations s\'installer. Dors 8h, mange bien. Ne rajoute pas de séances.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Footing léger 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min très faciles à {{P}}. Garder les jambes en mouvement sans les fatiguer. Cours au ressenti, sans montre.', retour:'',
        note:'RPE 3/10 · Tu dois finir comme si tu venais de te promener.' },
      { jour:'Jeudi', type:'Tempo', titre:'2 × 15 minutes au seuil — volume réduit', duree:'55 min', pcts:[[65,72],[82,88]],
        echauff:'25 min progressif à {{P}}.', corps:'2 × 15 min à {{P}}. Volume réduit de 50% mais intensité maintenue. Récupération 4 min. Termine par 1 km à ton allure marathon ({{OBJ}}).', retour:'10 min footing très lent.',
        note:'RPE 7/10 · Ces répétitions maintiennent tes sensations sans te fatiguer.' },
      { jour:'Samedi', type:'EF', titre:'Footing de 35 minutes', duree:'35 min', pcts:[[65,65]],
        echauff:'', corps:'35 min à {{P}}. Garde les jambes en mouvement. Cours au ressenti, détendu. Inclus 4 à 6 accélérations de 60m à allure marathon pour réveiller les sensations.', retour:'',
        note:'RPE 3/10 · Tu dois finir frais et légèrement dynamisé, jamais fatigué.' },
    ]},
  { num:12, phase:'Semaine de course', charge:'Conserve, tu es prêt',
    objectif:'Arriver au départ reposé, confiant, les jambes fraîches. 11 semaines de travail ont été faites. Il ne reste qu\'à exécuter.',
    conseil:'Pars à {{OBJ}}/km dès le départ. L\'adrénaline va te pousser à aller plus vite — résiste. Chaque seconde gagnée trop tôt peut coûter une minute à la fin.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing très léger 30 minutes', duree:'30 min', pcts:[[60,65]],
        echauff:'', corps:'30 min à {{P}}. Maintenir la circulation sanguine. Vraiment facile. Si tu te sens fatigué, réduis à 20 minutes.', retour:'',
        note:'RPE 3/10 · Aucun effort. Juste des jambes qui bougent.' },
      { jour:'Mercredi', type:'Fractionné', titre:'6 × 30/30 à allure marathon', duree:'30 min',
        echauff:'15 min de footing très léger.',
        corps:'6 × 30 secondes à ton allure objectif marathon ({{OBJ}}) / 30 secondes au trot. Les jambes retrouvent la sensation d\'allure avant le grand jour.',
        retour:'10 min de jogging léger.',
        note:'RPE 6/10 · Ces relances maintiennent les sensations sans t\'épuiser.' },
      { jour:'Samedi', type:'Activation', titre:'Activation J-1 + accélérations', duree:'30 min', pcts:[[60,65]],
        echauff:'', corps:'20 min de trot à {{P}}. Puis 6 à 8 accélérations progressives de 80m jusqu\'à ton allure objectif ({{OBJ}}) sur les 20 derniers mètres. Récupère 60 sec en marchant entre chaque.', retour:'',
        note:'Prépare tes affaires ce soir. Visualise les premiers kilomètres à {{OBJ}}/km.' },
      { jour:'Dimanche', type:'Course', titre:'MARATHON', duree:'Jour J',
        echauff:'10-15 min de jogging très léger avant le départ.',
        corps:'KM 1-8 : pars à {{OBJ}}/km exactement. KM 9-21 : régularité absolue, gel à chaque ravitaillement. KM 22-30 : maintiens {{OBJ}}, écoute ton corps. KM 31-35 : raccourcis la foulée, garde les bras actifs. KM 36-42 : donne absolument tout.',
        retour:'20-30 min de marche. Ravitaillement dans les 30 min.',
        note:'La douleur aux km 30-35 est normale. C\'est là que se gagne un marathon. Tiens bon.' },
    ]},
]
