// Marathon 12 semaines · 6 séances/semaine · Palier Intermédiaire (VMA 13.5 à 18.5)
// {{P}} remplacé séquentiellement · {{OBJ}} = allure objectif marathon (80% VMA)
module.exports = [
  { num:1, phase:'Adaptation', charge:'Légère',
    objectif:'Installer le rythme sur 6 séances. Les deux EF supplémentaires par rapport au plan 4 séances sont intentionnellement légers : la priorité est d\'habituer le corps à la fréquence, pas au volume.',
    conseil:'Sur les 6 × 800m, la régularité sur les 6 répétitions est plus importante que la vitesse. Un écart de plus de 10 secondes entre le premier et le dernier indique un départ trop rapide.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Endurance Fondamentale', duree:'40 min', pcts:[[65,70]],
        echauff:'', corps:'Course continue à {{P}}. Allure conversation, tu dois pouvoir parler en phrases complètes. Relâché du début à la fin.', retour:'',
        note:'RPE 4/10 · Lance la semaine en douceur. La fréquence s\'installe progressivement.' },
      { jour:'Mardi', type:'Côtes', titre:'6 côtes de 100 mètres', duree:'45 min', pcts:[[65,70]],
        echauff:'20 min de footing EF à {{P}}.', corps:'6 montées de 100m à effort soutenu mais pas maximal. Genoux hauts, bras actifs, appuis dynamiques. Descente au trot complète entre chaque montée.', retour:'10 min de footing léger.',
        note:'RPE 7/10 sur les montées · Les côtes développent la force spécifique et la foulée sans impact cardio élevé.' },
      { jour:'Jeudi', type:'Fractionné', titre:'6 × 800 mètres', duree:'60 min', pcts:[[65,65],[88,92]],
        echauff:'20 min de footing EF à {{P}}.', corps:'6 × 800m à {{P}}. Effort soutenu mais maîtrisé. Récupération 90 sec au trot entre chaque. Même allure sur les 6.', retour:'10 min de jogging léger.',
        note:'RPE 7-8/10 · Ces 800m posent les fondations de ta résistance à l\'effort.' },
      { jour:'Vendredi', type:'EF', titre:'Footing de récupération', duree:'35 min', pcts:[[60,65]],
        echauff:'', corps:'35 min à {{P}}. Récupération active après les 800m d\'hier. Cours vraiment détendu.', retour:'',
        note:'RPE 3/10 · Ce footing accélère la récupération musculaire.' },
      { jour:'Samedi', type:'EF', titre:'Footing de récupération', duree:'35 min', pcts:[[60,65]],
        echauff:'', corps:'35 min à {{P}}. Active la circulation et prépare la sortie longue du dimanche. Cours vraiment détendu.', retour:'',
        note:'RPE 3/10 · Vraiment facile. Jambes fraîches pour demain.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue', duree:'75 min', pcts:[[65,70]],
        echauff:'', corps:'75 min à {{P}}. La sortie longue est la séance pilier du marathon. Hydrate-toi toutes les 20-25 min. Régulier et contrôlé.', retour:'',
        note:'RPE 5/10 · La durée prime sur l\'allure. Ne t\'emballe pas.' },
    ]},
  { num:2, phase:'Adaptation', charge:'Légère à modérée',
    objectif:'Confirmer les bases à 6 séances. Deux répétitions de plus sur le fractionné, la sortie longue progresse de 10 minutes. Les côtes montées en volume.',
    conseil:'Sur les 8 × 800m, maintiens la même allure sur les 8. Si les deux dernières sont nettement plus lentes, tu es parti trop vite.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Endurance Fondamentale', duree:'40 min', pcts:[[65,70]],
        echauff:'', corps:'40 min à {{P}}. Allure conversation, régulière du début à la fin.', retour:'',
        note:'RPE 4/10 · Léger et régulier. Ces séances construisent ton moteur aérobie.' },
      { jour:'Mardi', type:'Côtes', titre:'8 côtes de 100 mètres', duree:'50 min', pcts:[[65,70]],
        echauff:'20 min de footing EF à {{P}}.', corps:'8 montées de 100m à effort soutenu. Genoux hauts, bras actifs. Deux montées de plus que la semaine 1. Récupération complète entre chaque montée.', retour:'10 min de footing léger.',
        note:'RPE 7/10 sur les montées · La régularité technique est plus importante que la vitesse.' },
      { jour:'Jeudi', type:'Fractionné', titre:'8 × 800 mètres', duree:'65 min', pcts:[[65,65],[88,92]],
        echauff:'25 min de footing EF à {{P}}.', corps:'8 × 800m à {{P}}. Deux répétitions de plus. Récupération 90 sec au trot. Maintiens la même allure sur les 8.', retour:'10 min de footing léger.',
        note:'RPE 7-8/10 · La régularité est plus importante que la vitesse maximale.' },
      { jour:'Vendredi', type:'EF', titre:'Footing de récupération', duree:'35 min', pcts:[[60,65]],
        echauff:'', corps:'35 min à {{P}}. Récupération active après les 800m d\'hier. Vraiment détendu.', retour:'',
        note:'RPE 3/10 · Vraiment facile.' },
      { jour:'Samedi', type:'EF', titre:'Footing de récupération', duree:'35 min', pcts:[[60,65]],
        echauff:'', corps:'35 min à {{P}}. Active la circulation avant la sortie longue. Vraiment détendu.', retour:'',
        note:'RPE 3/10 · Vraiment facile.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue', duree:'85 min', pcts:[[65,70]],
        echauff:'', corps:'85 min à {{P}}. La sortie longue augmente de 10 minutes. Hydrate-toi toutes les 20-25 min.', retour:'',
        note:'RPE 5/10 · La sortie longue est la séance la plus importante du plan marathon.' },
    ]},
  { num:3, phase:'Développement aérobie', charge:'Modérée, deux séances de qualité',
    objectif:'Introduire tempo et longs intervalles dans la même semaine. Avec 6 séances, on peut se permettre deux sessions de qualité séparées par un footing de récupération.',
    conseil:'Sur le tempo de 20 min, tu dois pouvoir prononcer des mots isolés mais pas tenir une conversation. C\'est exactement la bonne intensité seuil.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing long EF', duree:'50 min', pcts:[[65,70]],
        echauff:'', corps:'50 min à {{P}}. Long et facile avant la semaine à deux séances de qualité. Travaille ta technique : légère bascule vers l\'avant, attaque milieu du pied.', retour:'',
        note:'RPE 5/10 · Ce footing long développe ton économie de course.' },
      { jour:'Mardi', type:'Côtes', titre:'8 côtes de 120 mètres', duree:'50 min', pcts:[[65,70]],
        echauff:'20 min de footing EF à {{P}}.', corps:'8 montées de 120m à effort soutenu. Genoux hauts, bras actifs. Distance légèrement allongée. Récupération complète entre chaque montée.', retour:'10 min de footing léger.',
        note:'RPE 7-8/10 sur les montées · Les côtes plus longues développent ta résistance en montée.' },
      { jour:'Mercredi', type:'Tempo', titre:'Tempo continu, 20 minutes', duree:'55 min', pcts:[[65,70],[84,84]],
        echauff:'20 min de footing progressif à {{P}}.', corps:'20 minutes continues à {{P}}. Première séance au seuil anaérobie. Difficile mais tenable sur toute la durée.', retour:'12 min de jogging très lent.',
        note:'RPE 7-8/10 · Cette zone développe directement ta capacité à tenir l\'allure marathon.' },
      { jour:'Jeudi', type:'EF', titre:'Footing de récupération', duree:'35 min', pcts:[[60,65]],
        echauff:'', corps:'35 min à {{P}}. Récupération active après le tempo d\'hier. Vraiment détendu.', retour:'',
        note:'RPE 3/10 · Indispensable avant les 1000m de vendredi.' },
      { jour:'Vendredi', type:'Fractionné', titre:'4 × 1000 mètres', duree:'65 min', pcts:[[65,65],[88,92]],
        echauff:'25 min de footing EF à {{P}}.', corps:'4 × 1000m à {{P}}. Intervalles longs. Récupération 2 min au trot. Termine par 800m à ton allure objectif marathon ({{OBJ}}).', retour:'10 min de footing léger.',
        note:'RPE 7-8/10 · Deux séances de qualité cette semaine plus les côtes. La fatigue est normale.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue', duree:'95 min', pcts:[[65,70]],
        echauff:'', corps:'95 min à {{P}}. Régulier, hydraté, concentré sur ta foulée. La sortie longue reste facile en allure.', retour:'',
        note:'RPE 5-6/10 · La fatigue en fin de semaine est normale. Récupère bien.' },
    ]},
  { num:4, phase:'Développement aérobie', charge:'Élevée, consolidation seuil',
    objectif:'Consolider le seuil et franchir le cap des 100 minutes en sortie longue. Les 6 séances permettent une progression plus rapide mais nécessitent une récupération soigneuse.',
    conseil:'Sur les 2 × 15 min au seuil, la deuxième répétition est intentionnellement plus difficile. Maintiens l\'allure sur les deux blocs. Ne ralentis pas : c\'est l\'inconfort qui produit le progrès.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing long EF', duree:'55 min', pcts:[[70,70],[65,65]],
        echauff:'', corps:'55 min à {{P}}. Long, régulier, facile. Si tu te sens fatigué, passe à {{P}}.', retour:'',
        note:'RPE 5/10 · Récupération active et volume de base.' },
      { jour:'Mardi', type:'Côtes', titre:'10 côtes de 120 mètres', duree:'55 min', pcts:[[65,70]],
        echauff:'20 min de footing EF à {{P}}.', corps:'10 montées de 120m à effort soutenu. Genoux hauts, bras actifs. Deux montées de plus qu\'en semaine 3. Récupération complète.', retour:'10 min de footing léger.',
        note:'RPE 7-8/10 sur les montées · Ces côtes développent la force spécifique course à pied.' },
      { jour:'Mercredi', type:'Tempo', titre:'2 × 15 minutes au seuil', duree:'60 min', pcts:[[65,70],[85,85]],
        echauff:'25 min de footing progressif à {{P}}.', corps:'2 × 15 min à {{P}} avec 3 min de récupération entre chaque. La deuxième répétition se termine fatigué, c\'est voulu.', retour:'10 min de footing léger.',
        note:'RPE 7-8/10 · 30 min totales au seuil, ton record depuis le début du plan.' },
      { jour:'Jeudi', type:'EF', titre:'Footing de récupération', duree:'35 min', pcts:[[60,65]],
        echauff:'', corps:'35 min à {{P}}. Récupération active après le tempo d\'hier. Indispensable avant les 1000m de vendredi.', retour:'',
        note:'RPE 3/10 · Ce footing accélère la récupération musculaire.' },
      { jour:'Vendredi', type:'Fractionné', titre:'5 × 1000 mètres', duree:'70 min', pcts:[[65,65],[88,92]],
        echauff:'25 min de footing EF à {{P}}.', corps:'5 × 1000m à {{P}}. Une répétition de plus. Récupération 2 min au trot. Termine par 1 km à {{OBJ}}.', retour:'10 min de footing léger.',
        note:'RPE 8/10 · Deux séances de qualité plus les côtes cette semaine. Volume élevé.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue avec fin allure marathon', duree:'105 min', pcts:[[65,70]],
        echauff:'', corps:'95 min à {{P}}, puis les 10 dernières minutes à ton allure objectif marathon ({{OBJ}}). Tu apprends à finir sur la bonne allure quand les jambes sont déjà sollicitées.', retour:'',
        note:'RPE 6/10 puis 7/10 · Mémorise la sensation de l\'allure marathon sur jambes fatiguées.' },
    ]},
  { num:5, phase:'Volume', charge:'Élevée, cap des 2 heures',
    objectif:'La sortie longue de 2 heures est un cap important. À 6 séances par semaine, le volume total atteint son niveau de croisière. La récupération entre les sessions est impérative.',
    conseil:'Sur les 3 × 12 min au seuil, chaque répétition doit finir à la même allure. La régularité est le signe d\'une bonne maîtrise de zone.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Endurance Fondamentale', duree:'45 min', pcts:[[65,70]],
        echauff:'', corps:'45 min à {{P}}. Volume de base avant la semaine chargée. Très facile, jamais fatigant.', retour:'',
        note:'RPE 4/10 · Lance la semaine en douceur.' },
      { jour:'Mardi', type:'Côtes', titre:'8 côtes de 150 mètres', duree:'55 min', pcts:[[65,70]],
        echauff:'20 min de footing EF à {{P}}.', corps:'8 montées de 150m à effort soutenu. Distance allongée, plus exigeant. Genoux hauts, bras actifs. Récupération complète entre chaque montée.', retour:'10 min de footing léger.',
        note:'RPE 7-8/10 sur les montées · À 150m, les côtes simulent mieux l\'effort de course prolongé.' },
      { jour:'Mercredi', type:'Tempo', titre:'3 × 12 minutes au seuil', duree:'65 min', pcts:[[65,70],[85,85]],
        echauff:'25 min de footing progressif à {{P}}.', corps:'3 × 12 min à {{P}} avec 3 min de récupération entre chaque. La troisième répétition est la plus difficile.', retour:'10 min de footing léger.',
        note:'RPE 8/10 · 36 min totales au seuil, ton record depuis le début du plan.' },
      { jour:'Jeudi', type:'EF', titre:'Footing de récupération', duree:'35 min', pcts:[[60,65]],
        echauff:'', corps:'35 min à {{P}}. Récupération active après le tempo d\'hier. Vraiment détendu.', retour:'',
        note:'RPE 3/10 · Ce footing te fait récupérer plus vite.' },
      { jour:'Samedi', type:'EF', titre:'Footing de récupération', duree:'40 min', pcts:[[60,65]],
        echauff:'', corps:'40 min à {{P}}. Récupération active indispensable avant la grande sortie longue. Cours vraiment détendu.', retour:'',
        note:'RPE 3/10 · Jambes fraîches pour demain.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 2 heures', duree:'2h', pcts:[[65,70]],
        echauff:'', corps:'2 heures à {{P}}. Ton premier cap à 2 heures. Hydratation toutes les 20 min. Gel à 1h de course.', retour:'',
        note:'RPE 5-6/10 · À 2h, tu touches aux exigences physiques du marathon.' },
    ]},
  { num:6, phase:'Volume', charge:'Très élevée, allure marathon en sortie longue',
    objectif:'La sortie longue avec un bloc à allure marathon est la répétition la plus précieuse. Elle te donne une référence directe sur ta capacité à tenir {{OBJ}}/km en conditions réelles.',
    conseil:'Sur les 8 km à allure marathon dans la sortie longue, si {{OBJ}} te semble trop facile, ton objectif est peut-être trop prudent. Note ton ressenti km par km.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing long EF', duree:'50 min', pcts:[[65,70]],
        echauff:'', corps:'50 min à {{P}}. Long et facile avant la semaine très chargée.', retour:'',
        note:'RPE 5/10 · Récupération active avant les deux séances de qualité.' },
      { jour:'Mardi', type:'Côtes', titre:'10 côtes de 150 mètres', duree:'60 min', pcts:[[65,70]],
        echauff:'20 min de footing EF à {{P}}.', corps:'10 montées de 150m à effort soutenu. Genoux hauts, bras actifs. Deux montées de plus qu\'en semaine 5. Récupération complète.', retour:'10 min de footing léger.',
        note:'RPE 7-8/10 sur les montées · Volume de côtes maximal pour ce plan.' },
      { jour:'Mercredi', type:'Tempo', titre:'2 × 20 minutes au seuil', duree:'70 min', pcts:[[65,70],[86,86]],
        echauff:'25 min de footing progressif à {{P}}.', corps:'2 × 20 min à {{P}} avec 3 min de récupération entre chaque. 40 min totales au seuil. Ta séance tempo la plus longue à ce stade.', retour:'10 min de footing léger.',
        note:'RPE 8/10 · 40 min au seuil, charge sérieuse. Récupère bien le jeudi.' },
      { jour:'Jeudi', type:'EF', titre:'Footing de récupération', duree:'35 min', pcts:[[60,65]],
        echauff:'', corps:'35 min à {{P}}. Récupération active après le tempo d\'hier. Vraiment détendu.', retour:'',
        note:'RPE 3/10 · Vraiment facile, aucun effort.' },
      { jour:'Samedi', type:'EF', titre:'Footing de récupération', duree:'40 min', pcts:[[60,65]],
        echauff:'', corps:'40 min à {{P}}. Récupération active avant la sortie longue avec allure marathon. Vraiment détendu.', retour:'',
        note:'RPE 3/10 · Jambes fraîches pour la sortie longue spécifique.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue avec encart allure marathon', duree:'2h20', pcts:[[65,70]],
        echauff:'', corps:'90 min à {{P}}, puis 8 km à ton allure objectif marathon ({{OBJ}}), puis retour à l\'allure EF. Gel à 1h et à 1h30.', retour:'',
        note:'RPE 6/10 en EF · 7-8/10 sur les 8 km · Note ton ressenti, c\'est un indicateur fiable.' },
    ]},
  { num:7, phase:'Intensification', charge:'Très élevée, pic de charge approche',
    objectif:'Tempo, fractionnés, côtes et sortie longue maximale. Avec 6 séances, la charge atteint son niveau le plus exigeant. Les footings de récupération entre les sessions sont essentiels.',
    conseil:'Sur les 3 × 15 min au seuil, l\'allure doit être tenue sur les trois répétitions. Si tu dois ralentir sur la troisième, recalibre et maintiens la régularité.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing long EF', duree:'55 min', pcts:[[70,70],[65,65]],
        echauff:'', corps:'55 min à {{P}}. Long et facile avant la semaine la plus chargée. Si tu te sens fatigué, passe à {{P}}.', retour:'',
        note:'RPE 5/10 · Ce footing prépare les séances de qualité de la semaine.' },
      { jour:'Mardi', type:'Côtes', titre:'8 côtes de 200 mètres', duree:'60 min', pcts:[[65,70]],
        echauff:'20 min de footing EF à {{P}}.', corps:'8 montées de 200m à effort soutenu. Distance maximale pour ce plan. Genoux hauts, bras actifs, appuis dynamiques. Récupération complète entre chaque.', retour:'10 min de footing léger.',
        note:'RPE 8/10 sur les montées · À 200m, les côtes développent la résistance spécifique à l\'effort.' },
      { jour:'Mercredi', type:'Tempo', titre:'3 × 15 minutes au seuil', duree:'70 min', pcts:[[65,70],[86,86]],
        echauff:'25 min de footing progressif à {{P}}.', corps:'3 × 15 min à {{P}} avec 3 min de récupération entre chaque. La troisième répétition est la plus difficile. Maintiens l\'allure.', retour:'10 min de footing léger.',
        note:'RPE 8-9/10 · 45 min totales au seuil, ton record absolu. Récupère bien le jeudi.' },
      { jour:'Jeudi', type:'EF', titre:'Footing de récupération', duree:'35 min', pcts:[[60,65]],
        echauff:'', corps:'35 min à {{P}}. Récupération active après le tempo d\'hier. Vraiment détendu.', retour:'',
        note:'RPE 3/10 · Indispensable avant les 1000m de vendredi.' },
      { jour:'Vendredi', type:'Fractionné', titre:'6 × 1000 mètres', duree:'70 min', pcts:[[65,65],[88,92]],
        echauff:'25 min de footing EF à {{P}}.', corps:'6 × 1000m à {{P}}. Récupération 2 min au trot. Régulier sur les 6 répétitions.', retour:'10 min de footing léger.',
        note:'RPE 8/10 · Ces 1000m développent ta VMA tout en préservant ton endurance.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 2h35', duree:'2h35', pcts:[[65,70]],
        echauff:'', corps:'2h35 à {{P}}. Ta sortie longue la plus longue jusqu\'ici. Gel à 1h, à 1h30 et à 2h. Régularité, respiration, hydratation toutes les 20 min.', retour:'',
        note:'RPE 6/10 · Après cette semaine, la forme monte d\'un cran. Récupère sérieusement.' },
    ]},
  { num:8, phase:'Intensification', charge:'Maximale, pic de charge du plan',
    objectif:'Le pic absolu de ta préparation. La sortie longue la plus longue du plan avec un bloc à allure marathon. C\'est la semaine qui construit les fondations de ta confiance.',
    conseil:'Semaine de charge maximale. Mange des glucides complexes les soirs avant les séances clés. Dors 8 heures. Après cette semaine, l\'intensité diminue progressivement.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing long EF', duree:'55 min', pcts:[[70,70],[65,65]],
        echauff:'', corps:'55 min à {{P}}. Long et facile avant la semaine la plus chargée. Si tu te sens fatigué, passe à {{P}}.', retour:'',
        note:'RPE 5/10 · Ce footing prépare les deux séances dures de la semaine.' },
      { jour:'Mardi', type:'EF', titre:'Footing léger', duree:'35 min', pcts:[[60,65]],
        echauff:'', corps:'35 min à {{P}}. Récupération active avant les séances de qualité. Semaine maximale, chaque récupération compte.', retour:'',
        note:'RPE 3/10 · Récupération indispensable. Pas de côtes cette semaine.' },
      { jour:'Mercredi', type:'Tempo', titre:'4 × 12 minutes au seuil', duree:'75 min', pcts:[[65,70],[87,87]],
        echauff:'25 min de footing progressif à {{P}}.', corps:'4 × 12 min à {{P}} avec 3 min de récupération entre chaque. La quatrième répétition est la plus difficile. Maintiens l\'allure.', retour:'10 min de footing léger.',
        note:'RPE 8-9/10 · 48 min au seuil. Ton pic de charge sur cette séance.' },
      { jour:'Jeudi', type:'EF', titre:'Footing de récupération', duree:'35 min', pcts:[[60,65]],
        echauff:'', corps:'35 min à {{P}}. Récupération active après le tempo d\'hier. Vraiment détendu.', retour:'',
        note:'RPE 3/10 · Indispensable avant les 1000m de vendredi.' },
      { jour:'Vendredi', type:'Fractionné', titre:'8 × 1000 mètres', duree:'80 min', pcts:[[65,65],[88,92]],
        echauff:'25 min de footing EF à {{P}}.', corps:'8 × 1000m à {{P}}. Deux répétitions de plus que la semaine dernière. Récupération 2 min au trot. Maintiens la même allure sur les 8.', retour:'10 min de footing léger.',
        note:'RPE 8-9/10 · Semaine de charge maximale. La fatigue en fin de séance est normale.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue avec encart allure marathon', duree:'2h50', pcts:[[65,70]],
        echauff:'', corps:'2h à {{P}}, puis 12 km à ton allure objectif marathon ({{OBJ}}), puis retour à l\'allure EF. Gel à 1h, à 1h30, à 2h.', retour:'',
        note:'RPE 6/10 en EF · 8/10 sur les 12 km · Après cette semaine, l\'entraînement dur est terminé.' },
    ]},
  { num:9, phase:'Spécificité marathon', charge:'Élevée, travail à l\'allure objectif',
    objectif:'Les séances s\'alignent sur ton allure de course. Avec 6 séances, la semaine inclut deux sessions spécifiques marathon : l\'une courte et intense, l\'autre longue et spécifique.',
    conseil:'Sur les 3 × 6 km à allure marathon, chaque bloc doit être exactement à {{OBJ}}. L\'objectif est la répétabilité parfaite de cette allure sur des jambes fraîches.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Endurance Fondamentale', duree:'45 min', pcts:[[65,70]],
        echauff:'', corps:'45 min à {{P}}. Volume de base avant la semaine spécifique. Très facile.', retour:'',
        note:'RPE 4/10 · Lance la semaine en douceur.' },
      { jour:'Mardi', type:'EF', titre:'Footing léger', duree:'35 min', pcts:[[60,65]],
        echauff:'', corps:'35 min à {{P}}. Récupération active avant la séance spécifique de mercredi.', retour:'',
        note:'RPE 3/10 · Vraiment facile.' },
      { jour:'Mercredi', type:'Spécifique', titre:'3 × 6 km à allure marathon', duree:'75 min',
        echauff:'20 min de footing EF.', corps:'3 × 6 km exactement à ton allure objectif marathon ({{OBJ}}). Récupération 2 min au trot entre chaque. Tu répètes littéralement ton allure de course.', retour:'10 min de footing léger.',
        note:'RPE 7-8/10 · Si {{OBJ}} semble trop facile sur les 3 blocs, ton objectif est peut-être trop prudent.' },
      { jour:'Jeudi', type:'EF', titre:'Footing de récupération', duree:'35 min', pcts:[[60,65]],
        echauff:'', corps:'35 min à {{P}}. Récupération active après la séance spécifique d\'hier.', retour:'',
        note:'RPE 3/10 · Vraiment facile, sans exception.' },
      { jour:'Samedi', type:'EF', titre:'Footing de récupération', duree:'40 min', pcts:[[60,65]],
        echauff:'', corps:'40 min à {{P}}. Active la circulation avant la sortie longue spécifique de demain. Vraiment détendu.', retour:'',
        note:'RPE 3/10 · Jambes fraîches pour demain.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue avec encart allure marathon', duree:'2h20', pcts:[[65,70]],
        echauff:'', corps:'80 min à {{P}}, puis 10 km à ton allure objectif marathon ({{OBJ}}), puis retour à l\'allure EF. Gel à 1h et à 1h20.', retour:'',
        note:'RPE 6/10 en EF · 7-8/10 sur les 10 km · Mémorise cette sensation.' },
    ]},
  { num:10, phase:'Spécificité marathon', charge:'Très élevée, pic de spécificité',
    objectif:'Ta dernière vraie semaine de charge. Les 4 × 6 km + les 15 km en sortie longue + la séance supplémentaire de renforcement t\'apportent la confiance maximale pour le jour J.',
    conseil:'Sur les 4 × 6 km, la quatrième répétition est la plus précieuse : jambes déjà chargées, tu dois maintenir {{OBJ}}/km. C\'est ta répétition générale avant le marathon.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Endurance Fondamentale', duree:'50 min', pcts:[[65,70]],
        echauff:'', corps:'50 min à {{P}}. Volume avant la semaine la plus spécifique. Très facile.', retour:'',
        note:'RPE 4-5/10 · Lance la semaine en douceur.' },
      { jour:'Mardi', type:'EF', titre:'Footing léger', duree:'35 min', pcts:[[60,65]],
        echauff:'', corps:'35 min à {{P}}. Récupération active avant la séance spécifique de mercredi.', retour:'',
        note:'RPE 3/10 · Vraiment facile.' },
      { jour:'Mercredi', type:'Spécifique', titre:'4 × 6 km à allure marathon', duree:'90 min',
        echauff:'20 min de footing EF.', corps:'4 × 6 km exactement à ton allure objectif marathon ({{OBJ}}). Récupération 2 min au trot entre chaque. La quatrième est ta répétition générale avant le jour J.', retour:'10 min de footing léger.',
        note:'RPE 7-8/10 · 24 km à l\'allure objectif. Si tu les tiens sur 4 blocs, tu peux tenir 42 km.' },
      { jour:'Jeudi', type:'EF', titre:'Footing de récupération', duree:'35 min', pcts:[[60,65]],
        echauff:'', corps:'35 min à {{P}}. Récupération active après la séance spécifique d\'hier.', retour:'',
        note:'RPE 3/10 · Indispensable.' },
      { jour:'Samedi', type:'EF', titre:'Footing de récupération', duree:'40 min', pcts:[[60,65]],
        echauff:'', corps:'40 min à {{P}}. Active la circulation avant la sortie longue finale. Vraiment détendu.', retour:'',
        note:'RPE 3/10 · Jambes fraîches pour la sortie longue finale.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue avec long encart allure marathon', duree:'2h20', pcts:[[65,70]],
        echauff:'', corps:'50 min à {{P}}, puis 15 km à ton allure objectif marathon ({{OBJ}}), puis retour à l\'allure EF pour finir. Gel à 45 min, à 1h15, à 1h45.', retour:'',
        note:'RPE 6/10 en EF · 8/10 sur les 15 km · Après cette séance, les séances dures sont terminées.' },
    ]},
  { num:11, phase:'Consolidation', charge:'Réduite, affûtage',
    objectif:'La consolidation préserve ta forme sans t\'épuiser. Volume réduit de 40%, intensité maintenue sur une séance clé. Aborder la semaine de course avec les jambes fraîches.',
    conseil:'Cette semaine allégée laisse les adaptations s\'installer. Dors 8 heures, mange bien, évite le stress inutile. Ne rajoute pas de séances : la forme arrive.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Footing léger', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min très faciles à {{P}}. Garder les jambes en mouvement sans les fatiguer. Cours au ressenti, sans montre.', retour:'',
        note:'RPE 3/10 · Tu dois finir comme si tu venais de te promener.' },
      { jour:'Jeudi', type:'Tempo', titre:'2 × 12 minutes au seuil, volume réduit', duree:'55 min', pcts:[[65,70],[84,84]],
        echauff:'25 min de footing progressif à {{P}}.', corps:'2 × 12 min à {{P}}. Volume réduit de 50% mais intensité maintenue. Récupération 3 min. Termine par 1 km à {{OBJ}}.', retour:'10 min de footing léger.',
        note:'RPE 7/10 · Ces répétitions maintiennent tes sensations sans te fatiguer.' },
      { jour:'Samedi', type:'EF', titre:'Footing de 35 minutes', duree:'35 min', pcts:[[65,65]],
        echauff:'', corps:'35 min à {{P}}. Garde les jambes en mouvement. Cours au ressenti, détendu et régulier.', retour:'',
        note:'RPE 3/10 · Tu dois finir frais et légèrement dynamisé, jamais fatigué.' },
    ]},
  { num:12, phase:'Semaine de course', charge:'Conserve, tu es prêt',
    objectif:'Arriver au départ reposé, confiant, les jambes fraîches. Tout a été construit en 11 semaines. Il ne reste qu\'à exécuter.',
    conseil:'Pars à {{OBJ}}/km dès le départ. L\'adrénaline va te pousser à aller plus vite, résiste. Chaque seconde gagnée trop tôt peut coûter une minute à la fin.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing très léger', duree:'35 min', pcts:[[60,65]],
        echauff:'', corps:'35 min à {{P}}. Maintenir la circulation sanguine. Vraiment facile. Si tu te sens fatigué, réduis à 25 minutes.', retour:'',
        note:'RPE 3/10 · Aucun effort. Juste des jambes qui bougent.' },
      { jour:'Mercredi', type:'Fractionné', titre:'6 × 30/30 à allure marathon', duree:'30 min',
        echauff:'15 min de footing EF très léger.',
        corps:'6 × 30 secondes à ton allure objectif marathon ({{OBJ}}) / 30 secondes au trot. Les jambes retrouvent la sensation d\'allure avant le grand jour.',
        retour:'10 min de jogging léger.',
        note:'RPE 6/10 · Ces relances maintiennent les sensations sans t\'épuiser.' },
      { jour:'Samedi', type:'Activation', titre:'Activation J-1 + accélérations', duree:'30 min', pcts:[[60,65]],
        echauff:'', corps:'20 min de trot à {{P}}. Puis 6 à 8 accélérations progressives de 80m jusqu\'à ton allure objectif ({{OBJ}}) sur les 20 derniers mètres. Récupère 60 sec en marchant entre chaque.', retour:'',
        note:'Prépare tes affaires ce soir. Visualise les premiers kilomètres à {{OBJ}}/km.' },
      { jour:'Dimanche', type:'Course', titre:'MARATHON', duree:'Jour J',
        echauff:'10-15 min de jogging très léger avant le départ.',
        corps:'KM 1-8 : pars à {{OBJ}}/km exactement. KM 9-21 : régularité absolue, gel à chaque ravitaillement. KM 22-30 : maintiens {{OBJ}}, écoute ton corps. KM 31-35 : raccourcis la foulée. KM 36-42 : donne absolument tout.',
        retour:'20-30 min de marche. Ravitaillement dans les 30 min.',
        note:'La douleur aux km 30-35 est normale. C\'est là que se gagne un marathon. Tiens bon.' },
    ]},
]
