// Marathon 12 semaines · 4 séances/semaine · Palier Intermédiaire (VMA 13.5 à 18.5)
// Palette : EF 60min, FP 3 phases, FL-07 3×3000m, FL-12 2×5000m, FL-13 progressif, FL-14 mixte, T-04/05, SP-05 3×5km, SL jusqu'à 2h30
// {{P}} remplacé séquentiellement · {{OBJ}} = allure objectif marathon (80% VMA)
module.exports = [
  { num:1, phase:'Adaptation', charge:'Légère',
    objectif:'Poser les bases. Un footing long de 60 min dès la semaine 1 : le marathon se construit sur des volumes plus élevés que le semi. Les 5×1000m servent à calibrer les allures et réveiller les jambes.',
    conseil:'Sur les 5×1000m, ne cherche pas la performance, calibre ton allure à 85-90% VMA et sens la régularité. Si le dernier est plus lent de plus de 10 secondes, tu es parti trop vite.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Endurance fondamentale 60 minutes', duree:'60 min', pcts:[[65,72]],
        echauff:'', corps:'60 min à {{P}}. Allure conversation, tu dois pouvoir parler en phrases complètes. Plus long qu\'un footing de semi : le marathon se bâtit sur des volumes plus importants.', retour:'',
        note:'RPE 5/10 · 60 min de base dès la semaine 1, c\'est l\'un des marqueurs du plan marathon.' },
      { jour:'Mercredi', type:'Fractionné', titre:'5 × 1000 mètres', duree:'65 min', pcts:[[65,65],[85,90]],
        echauff:'25 min progressif à {{P}}, terminer par 4 accélérations de 80m.', corps:'5 × 1000m à {{P}}. Récupération 2 min au trot entre chaque. Maintiens la même allure sur les 5. Dernier 1000m : finir à allure objectif marathon ({{OBJ}}) pour graver la sensation.', retour:'10 min footing très lent.',
        note:'RPE 7-8/10 · La régularité sur les 5 répétitions vaut plus que la vitesse du premier.' },
      { jour:'Vendredi', type:'EF', titre:'Récupération active', duree:'35 min', pcts:[[60,65]],
        echauff:'', corps:'35 min à {{P}}. Très lent, sans montre, jambes légères. Relance la circulation avant la sortie longue de dimanche.', retour:'',
        note:'RPE 3/10 · Indispensable entre les 1000m et la sortie longue.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 80 minutes', duree:'80 min', pcts:[[65,72]],
        echauff:'', corps:'80 min à {{P}}. La sortie longue est la séance pilier du marathon. Hydrate-toi toutes les 20-25 min. Régulier et contrôlé du début à la fin.', retour:'',
        note:'RPE 5/10 · La durée prime sur l\'allure.' },
    ]},
  { num:2, phase:'Adaptation', charge:'Légère à modérée',
    objectif:'Introduire le footing progressif, une séance spécifique marathon qui développe la sensation d\'allure sur 3 zones de travail. Les 4×2000m en vendredi posent les bases du travail long.',
    conseil:'Sur le footing progressif, chaque transition entre les zones doit être douce : tu accélères naturellement, pas sur un coup de sifflet. La dernière phase à 80-85% VMA doit être maîtrisée, pas subie.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing progressif 3 phases', duree:'60 min', pcts:[[65,68],[72,75],[80,85]],
        echauff:'10 min trot très lent à {{P}}.', corps:'20 min à {{P}} (aisé) → 20 min à {{P}} (modéré) → 20 min à {{P}} (soutenu). La progression se fait naturellement. Le dernier bloc à allure seuil bas développe ton sens de l\'allure marathon.', retour:'10 min trot très lent.',
        note:'RPE 5-7/10 progressif · Cette séance développe ton sens de l\'allure, clé du marathon.' },
      { jour:'Mercredi', type:'Côtes', titre:'8 côtes de 80 mètres, puissance neuromusculaire', duree:'55 min', pcts:[[65,70]],
        echauff:'25 min progressif à {{P}}, finir par 4 lignes droites.', corps:'8 montées de 80m à RPE 8-9/10, genoux hauts, bras actifs, appuis dynamiques. Descente en marchant pour récupération complète entre chaque montée.', retour:'10 min footing léger.',
        note:'RPE 8-9/10 sur les montées · Les côtes renforcent les appuis et améliorent l\'économie de course sans charge cardio excessive.' },
      { jour:'Vendredi', type:'Fractionné', titre:'4 × 2000 mètres, seuil aérobie long', duree:'70 min', pcts:[[65,65],[80,87]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations 80m.', corps:'4 × 2000m à {{P}}. Récupération 3 min au trot entre chaque. Les 2000m sont la distance marathonienne par excellence : plus longue que les 1000m du semi, elle développe l\'endurance de tempo.', retour:'10 min footing très lent.',
        note:'RPE 7-8/10 · Régularité sur les 4 blocs. Le dernier doit être aussi rapide que le premier.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 90 minutes', duree:'90 min', pcts:[[65,72]],
        echauff:'', corps:'90 min à {{P}}. 10 min de plus que la semaine 1. Gère ton allure sur les 30 premières minutes. Hydrate-toi toutes les 20-25 min.', retour:'',
        note:'RPE 5-6/10 · La sortie longue est la séance la plus importante du plan marathon.' },
    ]},
  { num:3, phase:'Développement aérobie', charge:'Modérée, première séance tempo longue',
    objectif:'20 minutes de seuil en continu, plus spécifique marathon que des blocs courts. La sortie longue de 95 min avec 15 min à allure marathon est le premier contact avec l\'allure cible sur jambes fatiguées.',
    conseil:'Sur le 20 min continu, pars légèrement en dessous de ta zone cible les 5 premières minutes. Si tu es encore dans la zone à la 18ème minute, tu as bien géré le départ.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Endurance fondamentale 60 minutes', duree:'60 min', pcts:[[65,72]],
        echauff:'', corps:'60 min à {{P}}. Long, régulier, conversation possible. Ce volume de footing est la base silencieuse du marathon, il construit ton moteur aérobie semaine après semaine.', retour:'',
        note:'RPE 5/10 · Volume de base. Ne rogne pas sur cette séance.' },
      { jour:'Mercredi', type:'Tempo', titre:'Tempo 20 minutes en continu', duree:'65 min', pcts:[[65,72],[82,88]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations 80m.', corps:'20 min continus à {{P}}. Effort soutenu et régulier sans rupture. Tu dois pouvoir prononcer des mots isolés. Différent des blocs fractionnés : la régularité sur 20 min en continu est la clé.', retour:'10 min footing très lent.',
        note:'RPE 7-8/10 · 20 min en continu au seuil est plus exigeant mentalement qu\'en intervalles.' },
      { jour:'Vendredi', type:'EF', titre:'Footing de récupération 40 minutes', duree:'40 min', pcts:[[60,65]],
        echauff:'', corps:'40 min à {{P}}. Récupération active entre le tempo de mercredi et la sortie longue de dimanche. Vraiment léger, au ressenti.', retour:'',
        note:'RPE 3/10 · Ce footing de récup est essentiel, il protège les jambes pour la sortie longue.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 95 minutes + fin allure marathon', duree:'95 min', pcts:[[65,72]],
        echauff:'', corps:'80 min à {{P}}, puis les 15 dernières minutes à ton allure objectif marathon ({{OBJ}}). Premier contact avec l\'allure cible sur jambes fatiguées, mémorise cette sensation.', retour:'',
        note:'RPE 5-6/10 puis 6-7/10 · La fin à {{OBJ}} est un repère précieux sur ta forme actuelle.' },
    ]},
  { num:4, phase:'Développement aérobie', charge:'Élevée, volume seuil',
    objectif:'2×20 min au seuil : le double des blocs standards habituels. Associé à une sortie longue qui franchit les 100 minutes avec 20 min à allure marathon, la semaine installe une charge aérobie sérieuse.',
    conseil:'Sur les 2×20 min, le deuxième bloc est intentionnellement plus difficile. Maintiens l\'allure sans ralentir, c\'est l\'inconfort du deuxième bloc qui produit le progrès.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing progressif 3 phases', duree:'60 min', pcts:[[65,68],[72,75],[80,85]],
        echauff:'10 min trot très lent à {{P}}.', corps:'20 min à {{P}} (aisé) → 20 min à {{P}} (modéré) → 20 min à {{P}} (soutenu). La dernière phase à allure seuil bas est la plus utile pour le marathon.', retour:'10 min trot très lent.',
        note:'RPE 5-7/10 progressif · Développe la capacité à changer de zone en course, décisive sur marathon.' },
      { jour:'Mercredi', type:'Tempo', titre:'2 × 20 minutes au seuil', duree:'80 min', pcts:[[65,72],[82,88]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations 80m.', corps:'2 × 20 min à {{P}} avec 5 min de récupération entre les 2 blocs. 40 min totales au seuil. La séance tempo la plus longue de la phase de développement.', retour:'10 min footing très lent.',
        note:'RPE 8/10 · Si le deuxième bloc est nettement plus lent, note-le, info précieuse sur ta forme.' },
      { jour:'Vendredi', type:'EF', titre:'Footing de récupération 40 minutes', duree:'40 min', pcts:[[60,65]],
        echauff:'', corps:'40 min à {{P}}. Récupération active entre les 2×20 min de mercredi et la sortie longue de dimanche. Léger et détendu.', retour:'',
        note:'RPE 3/10 · Ce footing de récup est essentiel, il protège les jambes pour la sortie longue.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 100 minutes + 20 min allure marathon', duree:'100 min', pcts:[[65,72]],
        echauff:'', corps:'80 min à {{P}}, puis 20 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h de course. Les 20 dernières minutes à allure cible sont le vrai test de la semaine.', retour:'',
        note:'RPE 6/10 puis 7/10 · Si {{OBJ}} semble gérable sur les 20 dernières minutes, c\'est bon signe.' },
    ]},
  { num:5, phase:'Volume marathon', charge:'Élevée, premier cap à 2 heures',
    objectif:'30 min de tempo en continu, la séance tempo la plus longue et la plus marathonienne du plan. La sortie longue de 2h avec 30 min à allure marathon constitue une semaine de volume réel.',
    conseil:'Sur le 30 min continu, gère le départ : pars à la limite basse de la zone (82% VMA). À la 20ème minute tu te sens limité, c\'est normal, c\'est là que l\'adaptation se produit.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Endurance fondamentale 60 minutes', duree:'60 min', pcts:[[65,72]],
        echauff:'', corps:'60 min à {{P}}. Allure confortable, régulier, conversation possible. Pose les bases avant la semaine la plus chargée du premier bloc.', retour:'',
        note:'RPE 5/10 · Ne force pas. Le volume de base est aussi important que les séances de qualité.' },
      { jour:'Mercredi', type:'Tempo', titre:'Tempo 30 minutes en continu', duree:'75 min', pcts:[[65,72],[82,88]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations 80m.', corps:'30 min continus à {{P}}. Ta séance tempo de référence : 30 min en continu au seuil est un marqueur de condition physique marathon. Pars à la limite basse de la zone, tiens les 30 min complets sans réduire l\'allure.', retour:'10 min footing très lent.',
        note:'RPE 8/10 · 30 min en continu est significativement plus dur mentalement que 2×15 min.' },
      { jour:'Vendredi', type:'EF', titre:'Footing de récupération 40 minutes', duree:'40 min', pcts:[[60,65]],
        echauff:'', corps:'40 min à {{P}}. Récupération après le tempo de 30 min. La sortie longue de dimanche (2h avec 30 min à allure marathon) est la séance clé, arrive-y avec les jambes fraîches.', retour:'',
        note:'RPE 3/10 · La qualité de dimanche dépend de ta récupération ce vendredi.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 2 heures avec 30 min allure marathon', duree:'2h', pcts:[[65,72]],
        echauff:'', corps:'90 min à {{P}}, puis 30 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h et à 1h20. Les 30 dernières minutes à {{OBJ}} simulent le dernier tiers du marathon, en termes de sensations de fin de course.', retour:'',
        note:'RPE 6/10 puis 7-8/10 · Après cette séance, tu as une référence directe sur ta capacité à tenir {{OBJ}}.' },
    ]},
  { num:6, phase:'Volume marathon', charge:'Très élevée, séance 2×5000m',
    objectif:'La séance 2×5000m est la plus marathon-spécifique du plan : 10 km à intensité modérée-haute simulant les conditions de course. La sortie longue de 2h15 consolide le volume.',
    conseil:'Sur les 2×5000m, les 3 premières minutes du premier bloc doivent sembler trop faciles. Le 5000m est long, ceux qui partent bien finissent fort. Ceux qui partent trop vite craquent à 3500m.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing progressif 3 phases', duree:'60 min', pcts:[[65,68],[72,75],[80,85]],
        echauff:'10 min trot très lent à {{P}}.', corps:'20 min à {{P}} (aisé) → 20 min à {{P}} (modéré) → 20 min à {{P}} (soutenu). Prépare mentalement les séances de qualité des jours suivants.', retour:'10 min trot très lent.',
        note:'RPE 5-7/10 progressif · Le footing progressif prépare le corps aux changements de rythme en course.' },
      { jour:'Mercredi', type:'Fractionné', titre:'2 × 5000 mètres, long spécifique marathon', duree:'90 min', pcts:[[65,65],[78,83]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations 80m.', corps:'2 × 5000m à {{P}}. Récupération 5 min au trot entre les 2 blocs. 10 km à intensité, le deuxième 5000m est le vrai test. Les 3 premières minutes doivent sembler trop faciles, tiens bon jusqu\'au bout.', retour:'10 min footing très lent.',
        note:'RPE 8/10 · Les 2×5000m sont une séance exclusivement marathon. Réserve-toi mentalement pour le deuxième bloc.' },
      { jour:'Vendredi', type:'EF', titre:'Récupération active 40 minutes', duree:'40 min', pcts:[[60,65]],
        echauff:'', corps:'40 min à {{P}}. Récupération active après les 5000m de mercredi. Vraiment très lent, sans chrono. Prépare les jambes pour la sortie longue.', retour:'',
        note:'RPE 3/10 · Cette séance de récup est aussi importante que les séances intenses.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 2h10 avec 30 min allure marathon', duree:'2h10', pcts:[[65,72]],
        echauff:'', corps:'100 min à {{P}}, puis 30 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h et à 1h30. Ces 30 min à {{OBJ}} après 1h40 de course testent ta capacité à tenir l\'allure en état de fatigue.', retour:'',
        note:'RPE 6/10 en EF · 7-8/10 sur les 30 min · Note ton ressenti toutes les 5 min sur le bloc marathon.' },
    ]},
  { num:7, phase:'Intensification', charge:'Élevée, séance progressive complexe',
    objectif:'La séance 3000/5000/3000 à intensité croissante est la grande séance marathon du plan : 11 km en 3 blocs progressifs, le dernier plus vite que le premier. Exigeante mentalement et physiquement.',
    conseil:'Sur la séance 3000/5000/3000, le 5000m central doit être tenu à l\'allure définie, ni plus lent ni plus vite. La régularité sur le bloc du milieu est la clé. Le dernier 3000m doit être le plus fort des 3.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Endurance fondamentale 60 minutes', duree:'60 min', pcts:[[65,72]],
        echauff:'', corps:'60 min à {{P}}. Long et facile avant la semaine très chargée. Régulier, hydraté, sans effort excessif.', retour:'',
        note:'RPE 5/10 · Prépare les jambes aux deux séances de qualité de la semaine.' },
      { jour:'Mercredi', type:'Fractionné', titre:'3000m / 5000m / 3000m progressif, séance marathon clé', duree:'90 min', pcts:[[65,65],[80,82],[82,85],[85,88]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations 80m.', corps:'3000m à {{P}} → récup 4 min trot → 5000m à {{P}} → récup 5 min trot → 3000m à {{P}}. Progression sur les 3 blocs : tu dois finir le dernier 3000m plus fort que le premier. 11 km à intensité croissante.', retour:'10 min footing très lent.',
        note:'RPE 8-9/10 sur le dernier bloc · La progression sur les 3 blocs est le vrai test de ta condition marathon.' },
      { jour:'Vendredi', type:'EF', titre:'Footing de récupération 40 minutes', duree:'40 min', pcts:[[60,65]],
        echauff:'', corps:'40 min à {{P}}. Récupération après la séance 3000/5000/3000 de mercredi. Léger et détendu, prépare les jambes pour la sortie longue de dimanche.', retour:'',
        note:'RPE 3/10 · La sortie longue de dimanche nécessite des jambes fraîches.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 2h15 avec 35 min allure marathon', duree:'2h15', pcts:[[65,72]],
        echauff:'', corps:'100 min à {{P}}, puis 35 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h, à 1h20, à 1h45. Ces 35 min à {{OBJ}} après 1h40 de course simulent la deuxième partie d\'un marathon réel.', retour:'',
        note:'RPE 6/10 en EF · 7-8/10 sur les 35 min · Ta répétition la plus fidèle du marathon jusqu\'ici.' },
    ]},
  { num:8, phase:'Intensification', charge:'Élevée, pic de charge du plan',
    objectif:'La semaine la plus chargée. La séance mixte (3×2000m seuil + 2×2000m allure marathon) est la séance de transition la plus spécifique. La sortie longue de 2h30 atteint le volume maximal du plan.',
    conseil:'Sur la séance 5×2000m mixte, les 3 premiers blocs au seuil te fatiguent pour que les 2 derniers à allure marathon soient courus sur jambes chargées. C\'est exactement ce que tu vivras aux km 30-42.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing progressif 3 phases', duree:'60 min', pcts:[[65,68],[72,75],[80,85]],
        echauff:'10 min trot très lent à {{P}}.', corps:'20 min à {{P}} (aisé) → 20 min à {{P}} (modéré) → 20 min à {{P}} (soutenu). Long et progressif avant la semaine de charge maximale.', retour:'10 min trot très lent.',
        note:'RPE 5-7/10 progressif · Prépare les jambes aux deux séances dures de la semaine.' },
      { jour:'Mercredi', type:'Fractionné', titre:'3×2000m seuil + 2×2000m allure marathon, séance de transition', duree:'85 min', pcts:[[65,65],[82,87],[80,80]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations 80m.', corps:'3 × 2000m à {{P}} (seuil) → récup 3 min trot → 2 × 2000m à ton allure objectif marathon ({{OBJ}}). La transition vers l\'allure marathon sur les 2 derniers blocs, après 6 km de seuil, est l\'élément clé.', retour:'10 min footing très lent.',
        note:'RPE 8-9/10 · Cette séance simule le passage entre effort soutenu et gestion du marathon.' },
      { jour:'Vendredi', type:'EF', titre:'Footing de récupération 40 minutes', duree:'40 min', pcts:[[60,65]],
        echauff:'', corps:'40 min à {{P}}. Récupération après la séance de transition de mercredi. La sortie longue de 2h30 dimanche est le pic du plan, arrive-y avec les jambes fraîches.', retour:'',
        note:'RPE 3/10 · Cette récupération est indispensable avant le pic du plan dimanche.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 2h30 avec 40 min allure marathon', duree:'2h30', pcts:[[65,72]],
        echauff:'', corps:'110 min à {{P}}, puis 40 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h, à 1h30, à 1h55. Ces 40 min à {{OBJ}} après 1h50 de course sont ta répétition générale. Tiens {{OBJ}} jusqu\'au bout.', retour:'',
        note:'RPE 6/10 en EF · 8/10 sur les 40 min · Après cette semaine, l\'entraînement dur est terminé. Récupère sérieusement.' },
    ]},
  { num:9, phase:'Spécificité marathon', charge:'Élevée, travail à l\'allure objectif',
    objectif:'Les séances s\'alignent sur ton allure de course. Les 3×5km à allure marathon sont la séance de spécificité absolue : 15 km à {{OBJ}}, répétés en 3 blocs pour construire la confiance.',
    conseil:'Sur les 3×5km, chaque bloc doit être exactement à {{OBJ}}, pas plus vite, pas plus lentement. La régularité parfaite des 3 blocs prouve que tu maîtrises l\'allure marathon.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Endurance fondamentale 50 minutes', duree:'50 min', pcts:[[65,72]],
        echauff:'', corps:'50 min à {{P}}. Légèrement réduit par rapport aux semaines précédentes, le corps entre dans la phase de spécificité. Facile et régulier.', retour:'',
        note:'RPE 5/10 · Volume légèrement réduit pour préserver les jambes pour les séances clés.' },
      { jour:'Mercredi', type:'Spécifique', titre:'3 × 5 km à allure marathon', duree:'90 min', pcts:[[65,65]],
        echauff:'25 min footing EF à {{P}}, finir par 4 accélérations 80m.', corps:'3 × 5 km exactement à ton allure objectif marathon ({{OBJ}}). Récupération 4 min au trot entre chaque. 15 km à l\'allure de ta course, la séance de référence pour valider ton objectif.', retour:'10 min footing léger.',
        note:'RPE 7-8/10 · Si les 3 blocs sont réguliers et {{OBJ}} semble gérable, ton objectif est validé.' },
      { jour:'Vendredi', type:'EF', titre:'Récupération active 40 minutes', duree:'40 min', pcts:[[60,65]],
        echauff:'', corps:'40 min très lents à {{P}}. Récupération pure après les 3×5km. Sans montre, au ressenti. Prépare les jambes pour la sortie longue spécifique de dimanche.', retour:'',
        note:'RPE 3/10 · Cette récupération est aussi importante que les séances de qualité.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 1h50 avec 30 min allure marathon', duree:'1h50', pcts:[[65,72]],
        echauff:'', corps:'80 min à {{P}}, puis 30 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h et à 1h10. Ces 30 min à {{OBJ}} après 80 min de course consolident la mémoire de l\'allure cible.', retour:'',
        note:'RPE 6/10 en EF · 7-8/10 sur les 30 min · Note ton ressenti toutes les 5 min sur le bloc marathon.' },
    ]},
  { num:10, phase:'Spécificité marathon', charge:'Très élevée, pic de spécificité',
    objectif:'Ta dernière vraie semaine de charge. La séance finisher du mercredi + les 4×3km du vendredi, deux séances distinctes des semaines précédentes pour un dernier stimulus varié. La semaine 10 doit te surprendre, pas te répéter.',
    conseil:'Sur la séance finisher, pars conservateur sur le seuil : tu dois arriver aux 3km allure marathon avec encore de l\'énergie. Sur les 4×3km, récupération courte : c\'est volontaire, c\'est différent de la semaine 9.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing progressif 3 phases', duree:'50 min', pcts:[[65,68],[72,75],[80,85]],
        echauff:'10 min trot très lent à {{P}}.', corps:'15 min à {{P}} (aisé) → 15 min à {{P}} (modéré) → 20 min à {{P}} (soutenu). Version légèrement réduite avant la semaine de charge spécifique.', retour:'10 min trot très lent.',
        note:'RPE 5-7/10 progressif · Activation avant les deux séances de référence de la semaine.' },
      { jour:'Mercredi', type:'Tempo', titre:'Séance de finisher, 5 km seuil + 3 × 3 km allure marathon', duree:'90 min', pcts:[[65,65],[80,85]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations 80m.', corps:'5 km à {{P}} (effort seuil, régulier) → 5 min de récupération au trot → 3 × 3 km exactement à ton allure objectif marathon ({{OBJ}}), récupération 2 min trot entre chaque. Transition seuil → allure marathon : une séance unique qui n\'a aucun équivalent dans le plan.', retour:'10 min footing très lent.',
        note:'RPE 8/10 sur le seuil · 7-8/10 sur les 3km · La régularité des 3 blocs à {{OBJ}} valide ta préparation finale.' },
      { jour:'Vendredi', type:'Spécifique', titre:'4 × 3 km à allure marathon', duree:'75 min', pcts:[[65,65]],
        echauff:'20 min footing EF à {{P}}.', corps:'4 × 3 km exactement à ton allure objectif marathon ({{OBJ}}). Récupération 2 min au trot, volontairement plus courte que les 4 min des 3×5km. 12 km à {{OBJ}} en blocs plus courts : un stimulus différent pour finir la semaine.', retour:'10 min footing léger.',
        note:'RPE 7-8/10 · Récupération courte et blocs plus courts : différent de la semaine 9. Après cette séance, les séances dures sont terminées.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 1h50 avec 30 min allure marathon', duree:'1h50', pcts:[[65,72]],
        echauff:'', corps:'80 min à {{P}}, puis 30 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h et à 1h10. Dernière sortie longue chargée, garde les jambes fraîches pour les deux dernières semaines.', retour:'',
        note:'RPE 6/10 en EF · 7-8/10 sur les 30 min · Après cette sortie, les séances dures sont terminées.' },
    ]},
  { num:11, phase:'Consolidation', charge:'Réduite, affûtage',
    objectif:'La consolidation préserve ta forme sans t\'épuiser. Volume réduit de 45%, intensité maintenue sur une séance clé. Arrive à la semaine de course avec les jambes fraîches et la tête légère.',
    conseil:'Cette semaine allégée n\'est pas du repos, c\'est le moment où les adaptations des 10 semaines précédentes s\'installent. Ne rajoute pas de séances. Dors 8h.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Footing léger 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min très faciles à {{P}}. Garder les jambes en mouvement sans les fatiguer. Cours au ressenti, sans montre.', retour:'',
        note:'RPE 3/10 · Tu dois finir comme si tu venais de te promener.' },
      { jour:'Jeudi', type:'Tempo', titre:'2 × 15 minutes au seuil, volume réduit', duree:'55 min', pcts:[[65,72],[82,88]],
        echauff:'25 min progressif à {{P}}.', corps:'2 × 15 min à {{P}}. Volume réduit de 50% mais intensité maintenue. Récupération 4 min. Termine par 1 km à ton allure marathon ({{OBJ}}).', retour:'10 min footing très lent.',
        note:'RPE 7/10 · Ces répétitions maintiennent tes sensations sans te fatiguer.' },
      { jour:'Samedi', type:'EF', titre:'Footing de 35 minutes', duree:'35 min', pcts:[[65,65]],
        echauff:'', corps:'35 min à {{P}}. Garde les jambes en mouvement. Cours au ressenti, détendu. Inclus 4 à 6 accélérations de 60m à allure marathon pour réveiller les sensations.', retour:'',
        note:'RPE 3/10 · Tu dois finir frais et légèrement dynamisé, jamais fatigué.' },
    ]},
  { num:12, phase:'Semaine de course', charge:'Conserve, tu es prêt',
    objectif:'Arriver au départ reposé, confiant, les jambes fraîches. 11 semaines de travail ont été faites. Il ne reste qu\'à exécuter.',
    conseil:'Pars à {{OBJ}}/km dès le départ. L\'adrénaline va te pousser à aller plus vite, résiste. Chaque seconde gagnée trop tôt peut coûter une minute à la fin.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing très léger 30 minutes', duree:'30 min', pcts:[[60,65]],
        echauff:'', corps:'30 min à {{P}}. Maintenir la circulation sanguine. Vraiment facile. Si tu te sens fatigué, réduis à 20 minutes.', retour:'',
        note:'RPE 3/10 · Aucun effort. Juste des jambes qui bougent.' },
      { jour:'Mercredi', type:'Fractionné', titre:'8 × 1 min / 1 min à allure marathon', duree:'40 min',
        echauff:'15 min de footing très léger.',
        corps:'8 × 1 minute à ton allure objectif marathon ({{OBJ}}) / 1 minute au trot. Plus long que le 30/30, le stimulus réveille les jambes sans les fatiguer avant le grand jour.',
        retour:'10 min de jogging léger.',
        note:'RPE 6/10 · Ces répétitions maintiennent les sensations sans t\'épuiser.' },
      { jour:'Samedi', type:'Activation', titre:'Activation J-1 + accélérations', duree:'30 min', pcts:[[60,65]],
        echauff:'', corps:'20 min de trot à {{P}}. Puis 6 à 8 accélérations progressives de 80m jusqu\'à ton allure objectif ({{OBJ}}) sur les 20 derniers mètres. Récupère 60 sec en marchant entre chaque.', retour:'',
        note:'Prépare tes affaires ce soir. Visualise les premiers kilomètres à {{OBJ}}/km.' },
      { jour:'Dimanche', type:'Course', titre:'MARATHON', duree:'Jour J',
        echauff:'10-15 min de jogging très léger avant le départ.',
        corps:'KM 1-8 : pars à {{OBJ}}/km exactement. KM 9-21 : régularité absolue, gel à chaque ravitaillement. KM 22-30 : maintiens {{OBJ}}, écoute ton corps. KM 31-35 : raccourcis la foulée, garde les bras actifs. KM 36-42 : donne absolument tout.',
        retour:'20-30 min de marche. Ravitaillement dans les 30 min.',
        note:'La douleur aux km 30-35 est normale. C\'est là que se gagne un marathon. Tiens bon.' },
    ]},
]
