// Marathon 12 semaines · 5 séances/semaine · Palier Avancé (VMA > 18.5)
// Surcharges : intervalles plus longs, allures plus élevées, SL plus longues, blocs spécifiques plus longs
const { applyOverrides } = require('../../lib/tier-overrides')
const base = require('./semaines-5-i.js')

module.exports = applyOverrides(base, {
  1: { replace: { Mercredi: {
    titre:'8 × 1000 mètres', pcts:[[65,65],[90,95]],
    echauff:'25 min progressif à {{P}}, terminer par 4 accélérations de 80m.',
    corps:'8 × 1000m à {{P}}. Trois de plus que la trame. Récupération 90 sec au trot. Le palier avancé démarre avec un volume VMA élevé.',
    retour:'10 min footing très lent.',
    note:'RPE 7-8/10 · 8×1000m pour le palier avancé — régularité sur les 8 blocs.' },
    Dimanche: { duree:'80 min',
    corps:'80 min à {{P}}. Légèrement plus long que la trame. Régulier et contrôlé.',
    note:'RPE 5/10 · Durée allongée pour le palier avancé.' } } },
  2: { replace: { Vendredi: {
    titre:'5 × 2000 mètres — volume seuil élevé', pcts:[[65,65],[82,88]],
    echauff:'25 min progressif à {{P}}, finir par 4 accélérations 80m.',
    corps:'5 × 2000m à {{P}}. Une répétition de plus que la trame. Récupération 3 min. 10 km à intensité. Régularité sur les 5.',
    retour:'10 min footing très lent.',
    note:'RPE 8/10 · 5×2000m = 10 km à intensité pour le palier avancé.' },
    Dimanche: { duree:'95 min',
    corps:'95 min à {{P}}. Légèrement plus long que la trame. Hydrate-toi toutes les 20-25 min.',
    note:'RPE 5/10 · Sortie longue allongée pour le palier avancé.' } } },
  3: { replace: { Mercredi: {
    titre:'Tempo 25 minutes en continu', duree:'70 min', pcts:[[65,70],[84,88]],
    echauff:'25 min progressif à {{P}}, finir par 4 accélérations 80m.',
    corps:'25 min continus à {{P}}. 5 min de plus que la trame. Allure légèrement plus haute.',
    retour:'10 min footing très lent.',
    note:'RPE 8/10 · 25 min en continu à allure haute — le cap du coureur avancé.' },
    Vendredi: {
    titre:'4 × 3000 mètres — volume fractionné long', pcts:[[65,65],[82,87]],
    echauff:'25 min progressif à {{P}}, finir par 4 accélérations 80m.',
    corps:'4 × 3000m à {{P}}. Une répétition de plus que la trame. Récupération 4 min. 12 km à intensité.',
    retour:'10 min footing très lent.',
    note:'RPE 8/10 · 4×3000m en complément du tempo. Semaine de qualité élevée.' },
    Dimanche: { duree:'110 min',
    corps:'90 min à {{P}}, puis 20 min à ton allure objectif marathon ({{OBJ}}). Bloc OBJ allongé.',
    note:'RPE 5-6/10 puis 6-7/10 · Bloc OBJ allongé pour le palier avancé.' } } },
  4: { replace: { Mercredi: {
    titre:'2 × 25 minutes au seuil', pcts:[[65,70],[84,88]],
    echauff:'25 min progressif à {{P}}, finir par 4 accélérations 80m.',
    corps:'2 × 25 min à {{P}} avec 3 min de récupération. 50 min totales au seuil. Allure légèrement plus haute que la trame.',
    retour:'10 min footing très lent.',
    note:'RPE 8/10 · 50 min au seuil à allure avancée.' },
    Vendredi: {
    titre:'4 × 3000 mètres + 2 km allure marathon', pcts:[[65,65],[82,87]],
    echauff:'25 min progressif à {{P}}, finir par 4 accélérations 80m.',
    corps:'4 × 3000m à {{P}}. Récupération 4 min. Après le dernier et 2 min de récup, 2 km à ton allure objectif marathon ({{OBJ}}).',
    retour:'10 min footing très lent.',
    note:'RPE 8-9/10 · 4×3000m + bloc OBJ — semaine de double qualité.' },
    Dimanche: { duree:'115 min',
    corps:'95 min à {{P}}, puis 20 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h. Bloc OBJ allongé.',
    note:'RPE 6/10 puis 7-8/10 · Bloc OBJ allongé par rapport à la trame.' } } },
  5: { replace: { Mercredi: {
    titre:'Tempo 35 minutes en continu', duree:'80 min', pcts:[[65,70],[84,88]],
    echauff:'25 min progressif à {{P}}, finir par 4 accélérations 80m.',
    corps:'35 min continus à {{P}}. 5 min de plus que la trame. Pars à la limite basse, tiens les 35 min.',
    retour:'10 min footing très lent.',
    note:'RPE 8-9/10 · 35 min en continu est le pic du palier avancé au seuil.' },
    Dimanche: { duree:'2h10',
    corps:'2h10 à {{P}}, avec 30 min à allure marathon ({{OBJ}}) sur la fin. Gel à 1h et à 1h30. Bloc OBJ à volume complet.',
    note:'RPE 6/10 puis 7-8/10 · Sortie allongée + bloc OBJ à volume complet.' } } },
  6: { replace: { Mercredi: {
    titre:'3 × 5000 mètres — volume marathon extrême', pcts:[[65,65],[78,83]],
    echauff:'25 min progressif à {{P}}, finir par 4 accélérations 80m.',
    corps:'3 × 5000m à {{P}}. Récupération 5 min. Une répétition de plus que la trame. 15 km à intensité. Pars très conservateur sur les deux premiers.',
    retour:'10 min footing très lent.',
    note:'RPE 8-9/10 · 3×5000m = 15 km à intensité. Séance marathon de référence avancée.' },
    Dimanche: { duree:'2h30',
    corps:'2h à {{P}}, puis 10 km à ton allure objectif marathon ({{OBJ}}). Gel à 1h, à 1h30, à 1h50.',
    note:'RPE 6/10 en EF · 7-8/10 sur les 10 km · Sortie longue allongée pour ce palier.' } } },
  7: { replace: {
    Vendredi: {
    titre:'2 × 25 minutes au seuil', pcts:[[65,70],[84,88]],
    echauff:'25 min progressif à {{P}}, finir par 4 accélérations 80m.',
    corps:'2 × 25 min à {{P}} avec 3 min de récupération entre les 2 blocs. 50 min totales au seuil à allure avancée.',
    retour:'10 min footing très lent.',
    note:'RPE 8-9/10 · 50 min au seuil avancé avec la fatigue de mercredi dans les jambes.' },
    Dimanche: { duree:'2h35',
    corps:'1h55 à {{P}}, puis 18 km à ton allure objectif marathon ({{OBJ}}). Gel à 1h, à 1h20, à 2h.',
    note:'RPE 6/10 en EF · 7-8/10 sur les 18 km · 18 km à {{OBJ}} après 1h55 — répétition générale avancée.' } } },
  8: { replace: {
    Vendredi: {
    titre:'10 × 1000 mètres — volume VMA élevé', pcts:[[65,65],[88,93]],
    echauff:'25 min progressif à {{P}}, finir par 4 accélérations 80m.',
    corps:'10 × 1000m à {{P}}. Deux de plus que la trame. Récupération 90 sec au trot. Volume élevé mais allure maîtrisée.',
    retour:'10 min footing très lent.',
    note:'RPE 8/10 · Semaine de charge maximale avancée.' },
    Dimanche: { duree:'2h45',
    corps:'2h à {{P}}, puis 18 km à ton allure objectif marathon ({{OBJ}}). Gel à 1h, à 1h30, à 2h.',
    note:'RPE 6/10 en EF · 8/10 sur les 18 km · Après cette semaine, l\'entraînement dur est terminé.' } } },
  9: { replace: { Mercredi: {
    titre:'4 × 5 km à allure marathon', duree:'100 min', pcts:[[65,65]],
    echauff:'20 min footing EF à {{P}}.',
    corps:'4 × 5 km exactement à ton allure objectif marathon ({{OBJ}}). Récupération 4 min. Un bloc de plus que la trame. 20 km à l\'allure de ta course.',
    retour:'10 min footing léger.',
    note:'RPE 7-8/10 · 4×5km = 20 km à {{OBJ}}. Si les 4 blocs sont réguliers, ton objectif est validé.' },
    Dimanche: { duree:'2h20',
    corps:'1h45 à {{P}}, puis 15 km à ton allure objectif marathon ({{OBJ}}). Gel à 1h, à 1h15, à 1h45.',
    note:'RPE 6/10 en EF · 7-8/10 sur les 15 km · Sortie spécifique allongée pour ce palier.' } } },
  10: { replace: { Mercredi: {
    titre:'3 × 5000 mètres — pic de spécificité', pcts:[[65,65],[78,83]],
    echauff:'25 min progressif à {{P}}, finir par 4 accélérations 80m.',
    corps:'3 × 5000m à {{P}}. Récupération 5 min. Une répétition de plus que la trame. Le troisième 5000m est ta répétition générale absolue.',
    retour:'10 min footing très lent.',
    note:'RPE 8/10 · 3×5000m — après cette séance, les séances dures sont terminées.' },
    Vendredi: {
    titre:'4 × 5 km à allure marathon — version finale', duree:'100 min', pcts:[[65,65]],
    echauff:'20 min footing EF à {{P}}.',
    corps:'4 × 5 km exactement à ton allure objectif marathon ({{OBJ}}). Récupération 4 min. Si les 4 blocs tiennent avec la fatigue de mercredi, la préparation est terminée.',
    retour:'10 min footing léger.',
    note:'RPE 7-8/10 · Après cette séance, les séances dures sont terminées.' },
    Dimanche: { duree:'2h10',
    corps:'1h35 à {{P}}, puis 12 km à ton allure objectif marathon ({{OBJ}}). Gel à 1h et à 1h10.',
    note:'RPE 6/10 en EF · 7-8/10 sur les 12 km · Dernière sortie longue chargée.' } } },
})
