// Marathon 12 semaines · 4 séances/semaine · Palier Débutant (VMA ≤ 13.5)
// Surcharges : fractionnés raccourcis, tempo réduit, SL plus courtes, blocs OBJ réduits
const { applyOverrides } = require('../../lib/tier-overrides')
const base = require('./semaines-4-i.js')

module.exports = applyOverrides(base, {
  1: { replace: { Mercredi: {
    titre:'6 × 400 mètres', pcts:[[65,65],[85,90]],
    echauff:'25 min progressif à {{P}}, terminer par 4 accélérations de 80m.',
    corps:'6 × 400m à {{P}}. Effort soutenu mais confortable. Récupération 90 sec au trot entre chaque. Régularité avant vitesse.',
    retour:'10 min footing très lent.',
    note:'RPE 6-7/10 · Pour un premier plan marathon, 400m est la distance idéale pour construire la résistance.' },
    Dimanche: { duree:'65 min',
    corps:'65 min à {{P}}. Plus court que la trame. Régulier et contrôlé. Hydrate-toi toutes les 20 min.',
    note:'RPE 4-5/10 · La durée prime sur l\'allure. Aucun effort excessif.' } } },
  2: { replace: { Vendredi: {
    titre:'4 × 1000 mètres', pcts:[[65,65],[85,90]],
    echauff:'25 min progressif à {{P}}, finir par 4 accélérations 80m.',
    corps:'4 × 1000m à {{P}}. Distance plus courte que 4×2000m — adapté pour progresser vers les longs intervalles. Récupération 2 min au trot entre chaque.',
    retour:'10 min footing très lent.',
    note:'RPE 7/10 · La progression vers les 2000m se fera dans les semaines suivantes.' },
    Dimanche: { duree:'80 min',
    corps:'80 min à {{P}}. Régulier, hydraté. 10 min de plus qu\'en semaine 1.',
    note:'RPE 4-5/10 · La sortie longue est la séance pilier du marathon débutant.' } } },
  3: { replace: { Mercredi: {
    titre:'Tempo 15 minutes en continu', duree:'50 min', pcts:[[65,70],[80,82]],
    echauff:'20 min progressif à {{P}}, finir par 4 accélérations 80m.',
    corps:'15 min continus à {{P}}. Allure légèrement plus douce que la trame. Premier contact avec l\'effort soutenu. Tu dois pouvoir prononcer quelques mots.',
    retour:'10 min footing très lent.',
    note:'RPE 6/10 · 15 min en continu au seuil léger est un premier cap important.' },
    Dimanche: { duree:'85 min',
    corps:'85 min à {{P}}. Régulier, hydraté. Pas de bloc marathon cette semaine.',
    note:'RPE 5/10 · La fatigue en fin de semaine est normale. Récupère bien.' } } },
  4: { replace: { Mercredi: {
    titre:'2 × 10 minutes au seuil', pcts:[[65,70],[82,82]],
    echauff:'25 min progressif à {{P}}, finir par 4 accélérations 80m.',
    corps:'2 × 10 min à {{P}} avec 3 min de récupération. Allure légèrement plus douce que la trame. La deuxième répétition se termine fatigué, c\'est voulu.',
    retour:'10 min footing très lent.',
    note:'RPE 6-7/10 · 20 min totales au seuil léger, adapté au palier débutant.' },
    Dimanche: { duree:'95 min',
    corps:'85 min à {{P}}, puis 10 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h. Mémorise cette sensation.',
    note:'RPE 5-6/10 puis 6-7/10 · Bloc OBJ raccourci pour ce palier.' } } },
  5: { replace: { Mercredi: {
    titre:'2 × 15 minutes au seuil', pcts:[[65,70],[80,83]],
    echauff:'25 min progressif à {{P}}, finir par 4 accélérations 80m.',
    corps:'2 × 15 min à {{P}} avec 4 min de récupération. 30 min totales au seuil. Allure adaptée à ce palier.',
    retour:'10 min footing très lent.',
    note:'RPE 7/10 · 30 min au seuil léger — premier grand cap tempo.' },
    Dimanche: { duree:'1h50',
    corps:'1h50 à {{P}}. Premier cap proche des 2 heures pour ce palier. Gel à 1h. Hydratation toutes les 20 min. Pas de bloc marathon cette semaine.',
    note:'RPE 5-6/10 · Le palier débutant atteint 1h50 au lieu de 2h+30min.' } } },
  6: { replace: { Mercredi: {
    titre:'2 × 2000 mètres — premier contact avec le long fractionné', pcts:[[65,65],[77,82]],
    echauff:'25 min progressif à {{P}}, finir par 4 accélérations 80m.',
    corps:'2 × 2000m à {{P}}. Récupération 5 min au trot. Version raccourcie de 2×5000m. Pars conservateur sur le premier.',
    retour:'10 min footing très lent.',
    note:'RPE 7/10 · 2×2000m avant d\'attaquer les 5000m dans les semaines suivantes.' },
    Dimanche: { duree:'2h',
    corps:'100 min à {{P}}, puis 20 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h et à 1h20. Bloc allure marathon raccourci pour ce palier.',
    note:'RPE 5-6/10 en EF · 6-7/10 sur les 20 min · Mémorise la sensation de {{OBJ}}.' } } },
  7: { replace: { Mercredi: {
    titre:'2000m / 3000m / 2000m progressif', pcts:[[65,65],[80,82],[82,84],[84,87]],
    echauff:'25 min progressif à {{P}}, finir par 4 accélérations 80m.',
    corps:'2000m à {{P}} → récup 4 min → 3000m à {{P}} → récup 4 min → 2000m à {{P}}. Version raccourcie de la séance 3000/5000/3000. Progression sur les 3 blocs.',
    retour:'10 min footing très lent.',
    note:'RPE 7-8/10 · Même progression mais distances raccourcies pour ce palier.' },
    Dimanche: { duree:'2h10',
    corps:'2h10 à {{P}}. Sortie longue sans bloc allure marathon — volume pur.',
    note:'RPE 6/10 · Le palier débutant consolide le volume sans bloc OBJ cette semaine.' } } },
  8: { replace: { Mercredi: {
    titre:'3 × 1500 mètres + 1 × 2 km allure marathon', pcts:[[65,65],[80,85]],
    echauff:'25 min progressif à {{P}}, finir par 4 accélérations 80m.',
    corps:'3 × 1500m à {{P}} → récup 3 min trot → 2 km à ton allure objectif marathon ({{OBJ}}). La transition finale vers {{OBJ}} après 4,5 km de seuil — même concept que FL-14 mais distances adaptées.',
    retour:'10 min footing très lent.',
    note:'RPE 7-8/10 · Séance mixte adaptée au palier débutant.' },
    Dimanche: { duree:'2h20',
    corps:'1h50 à {{P}}, puis 30 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h et à 1h20. Le pic de charge du plan débutant.',
    note:'RPE 5-6/10 en EF · 7/10 sur les 30 min · Le pic de charge du plan débutant.' } } },
  9: { replace: { Mercredi: {
    titre:'2 × 4 km à allure marathon', duree:'65 min', pcts:[[65,65]],
    echauff:'20 min footing EF à {{P}}.',
    corps:'2 × 4 km exactement à ton allure objectif marathon ({{OBJ}}). Récupération 3 min au trot. 2 blocs adaptés au palier débutant au lieu de 3.',
    retour:'10 min footing léger.',
    note:'RPE 6-7/10 · La régularité sur les 2 blocs est l\'objectif.' },
    Dimanche: { duree:'1h55',
    corps:'80 min à {{P}}, puis 35 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h et à 1h10.',
    note:'RPE 5-6/10 en EF · 6-7/10 sur les 35 min · Mémorise cette sensation.' } } },
  10: { replace: { Mercredi: {
    titre:'1 × 5000 mètres — répétition générale', duree:'65 min', pcts:[[65,65],[78,83]],
    echauff:'25 min progressif à {{P}}, finir par 4 accélérations 80m.',
    corps:'1 × 5000m à {{P}}. Un seul bloc tenu de bout en bout — ta répétition générale. Après 4 min de récup, 2 km à {{OBJ}}.',
    retour:'10 min footing très lent.',
    note:'RPE 7-8/10 · Un 5000m complet est le pic spécifique adapté à ce palier.' },
    Vendredi: {
    titre:'3 × 2 km à allure marathon — blocs courts', duree:'50 min', pcts:[[65,65]],
    echauff:'20 min footing EF à {{P}}.',
    corps:'3 × 2 km exactement à ton allure objectif marathon ({{OBJ}}). Récupération 90 sec au trot — plus serrée que les 3 min des 2×4km. 6 km à {{OBJ}} en blocs courts : stimulus différent de la semaine 9.',
    retour:'10 min footing léger.',
    note:'RPE 7/10 · Blocs courts, récup serrée : le stimulus différent de la semaine 9. Après cette séance, les séances dures sont terminées.' },
    Dimanche: { duree:'1h50',
    corps:'80 min à {{P}}, puis 30 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h et à 1h10. Dernière sortie longue chargée.',
    note:'RPE 5-6/10 en EF · 7/10 sur les 30 min · Après cette sortie, les séances dures sont terminées.' } } },
})
