// Marathon 12 semaines · 4 séances/semaine · Palier Intermédiaire (VMA 13.5 à 18.5)
// {{P}} remplacé séquentiellement sur la queue de pcts · {{OBJ}} = allure objectif marathon (80% VMA)
module.exports = [
  { num:1, phase:'Adaptation', charge:'Légère',
    objectif:'Installer le rythme sur 4 séances et prendre ses repères sur les allures. Aucune pression de performance : finir chaque séance en se sentant bien est le seul objectif.',
    conseil:'Sur les 6 × 800m, l\'allure doit être régulière du premier au dernier. Si les deux derniers sont nettement plus lents, tu es parti trop vite. Le marathon récompense la patience.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Endurance Fondamentale', duree:'45 min', pcts:[[65,70]],
        echauff:'', corps:'Course continue à {{P}}. Allure conversation, tu dois pouvoir parler en phrases complètes. Régulier et relâché, aucun effort perçu.', retour:'',
        note:'RPE 4-5/10 · Finis en te sentant bien, comme si tu pouvais encore courir 20 min.' },
      { jour:'Jeudi', type:'Fractionné', titre:'6 × 800 mètres', duree:'60 min', pcts:[[65,65],[88,92]],
        echauff:'20 min de footing EF à {{P}}.', corps:'6 × 800m à {{P}}. Effort soutenu mais maîtrisé. Récupération 90 sec au trot entre chaque. Maintiens la même allure sur les 6.', retour:'10 min de jogging léger.',
        note:'RPE 7-8/10 · Ces 800m posent les fondations de ta résistance à l\'effort.' },
      { jour:'Samedi', type:'EF', titre:'Footing de récupération', duree:'35 min', pcts:[[60,65]],
        echauff:'', corps:'35 min à {{P}}. Active la circulation et prépare la sortie longue du lendemain. Cours vraiment détendu, aucun effort.', retour:'',
        note:'RPE 3/10 · Vraiment facile, tu dois finir comme si tu venais de marcher.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue', duree:'75 min', pcts:[[65,70]],
        echauff:'', corps:'Course continue à {{P}} pendant 75 minutes. Hydrate-toi. La sortie longue est la séance pilier du marathon, elle se construit semaine après semaine sans jamais être bâclée.', retour:'',
        note:'RPE 5/10 · Régulier et contrôlé. La durée prime toujours sur l\'allure.' },
    ]},
  { num:2, phase:'Adaptation', charge:'Légère à modérée',
    objectif:'Confirmer les bases. Deux répétitions de plus sur le fractionné, la sortie longue progresse de 10 minutes. Le plan commence à sembler naturel.',
    conseil:'Sur les 8 × 800m, la régularité sur les 8 répétitions est plus importante que la vitesse. Un écart de plus de 10 secondes entre le premier et le dernier signale un départ trop rapide.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Endurance Fondamentale', duree:'50 min', pcts:[[65,70]],
        echauff:'', corps:'50 min à {{P}}. Même principe que la semaine passée. Allure conversation, régulière du début à la fin. Tu dois pouvoir parler en phrases complètes.', retour:'',
        note:'RPE 4-5/10 · Léger et régulier. Ces séances construisent ton moteur aérobie.' },
      { jour:'Jeudi', type:'Fractionné', titre:'8 × 800 mètres', duree:'65 min', pcts:[[65,65],[88,92]],
        echauff:'25 min de footing EF à {{P}}.', corps:'8 × 800m à {{P}}. Deux répétitions de plus qu\'en semaine 1. Récupération 90 sec au trot. Maintiens la même allure sur les 8.', retour:'10 min de footing léger.',
        note:'RPE 7-8/10 · La régularité est plus importante que la vitesse maximale.' },
      { jour:'Samedi', type:'EF', titre:'Footing de récupération', duree:'35 min', pcts:[[60,65]],
        echauff:'', corps:'35 min à {{P}}. Active la circulation et prépare la sortie longue du lendemain. Cours vraiment détendu.', retour:'',
        note:'RPE 3/10 · Vraiment facile.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue', duree:'85 min', pcts:[[65,70]],
        echauff:'', corps:'85 min à {{P}}. La sortie longue augmente de 10 minutes. Continue à bâtir ta base aérobie. Hydrate-toi toutes les 20-25 min.', retour:'',
        note:'RPE 5/10 · La sortie longue est la séance la plus importante du plan marathon.' },
    ]},
  { num:3, phase:'Développement aérobie', charge:'Modérée, première séance tempo',
    objectif:'Introduire le travail au seuil anaérobie. Le tempo développe directement la résistance à la fatigue qui fera la différence entre le km 30 et le km 40 le jour J.',
    conseil:'Sur le tempo de 20 min, tu dois pouvoir prononcer des mots isolés mais pas tenir une conversation. C\'est la zone seuil parfaite : difficile mais contrôlée, difficile mais soutenable.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Footing long EF', duree:'55 min', pcts:[[70,70],[65,65]],
        echauff:'', corps:'55 min à {{P}}. Long et facile avant la semaine à deux séances de qualité. Travaille ta technique : légère bascule vers l\'avant, attaque milieu du pied. Si tu te sens fatigué, passe à {{P}}.', retour:'',
        note:'RPE 5/10 · Ce footing long développe ton économie de course.' },
      { jour:'Mercredi', type:'Tempo', titre:'Tempo continu, 20 minutes', duree:'55 min', pcts:[[65,70],[84,84]],
        echauff:'25 min de footing progressif à {{P}}.', corps:'20 minutes continues à {{P}}. Première séance au seuil anaérobie. Difficile mais tenable sur toute la durée. Allure régulière du début à la fin.', retour:'12 min de jogging très lent.',
        note:'RPE 7-8/10 · Cette zone repousse ton seuil lactique et développe ta capacité marathon.' },
      { jour:'Vendredi', type:'Fractionné', titre:'4 × 1000 mètres', duree:'65 min', pcts:[[65,65],[88,92]],
        echauff:'25 min de footing EF à {{P}}.', corps:'4 × 1000m à {{P}}. Intervalles plus longs que les 800m précédents. Récupération 2 min au trot. Termine par 800m à ton allure objectif marathon ({{OBJ}}) pour sentir l\'allure cible.', retour:'10 min de footing léger.',
        note:'RPE 7-8/10 · Ces 1000m augmentent ta capacité à soutenir des efforts prolongés.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue', duree:'95 min', pcts:[[65,70]],
        echauff:'', corps:'95 min à {{P}}. Régulier, hydraté, concentré sur ta foulée. Semaine chargée, la sortie longue reste volontairement facile en allure pour cumuler le volume sans fatigue excessive.', retour:'',
        note:'RPE 5-6/10 · La fatigue en fin de semaine est normale. Récupère bien.' },
    ]},
  { num:4, phase:'Développement aérobie', charge:'Élevée, consolidation seuil',
    objectif:'Consolider le travail de seuil et franchir le cap des 100 minutes en sortie longue. La deuxième semaine avec deux séances de qualité : les allures commencent à se naturaliser.',
    conseil:'Sur les 2 × 15 min au seuil, la deuxième répétition est intentionnellement plus difficile. Si tu maintiens l\'allure sur les deux, ta base est solide. Ne ralentis pas : c\'est l\'inconfort qui produit le progrès.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Footing long EF', duree:'60 min', pcts:[[70,70],[65,65]],
        echauff:'', corps:'60 min à {{P}}. Long, régulier, facile. Si tu te sens fatigué, passe à {{P}}. Volume avant la semaine chargée.', retour:'',
        note:'RPE 5/10 · Récupération active et volume de base.' },
      { jour:'Mercredi', type:'Tempo', titre:'2 × 15 minutes au seuil', duree:'60 min', pcts:[[65,70],[85,85]],
        echauff:'25 min de footing progressif à {{P}}.', corps:'2 × 15 min à {{P}} avec 3 min de récupération entre chaque. La deuxième répétition se termine fatigué, c\'est voulu. Maintiens l\'allure sur les deux blocs.', retour:'10 min de footing léger.',
        note:'RPE 7-8/10 · 30 min totales au seuil, la charge la plus importante depuis le début.' },
      { jour:'Vendredi', type:'Fractionné', titre:'5 × 1000 mètres', duree:'70 min', pcts:[[65,65],[88,92]],
        echauff:'25 min de footing EF à {{P}}.', corps:'5 × 1000m à {{P}}. Une répétition de plus. Récupération 2 min au trot. Termine par 1 km à ton allure objectif marathon ({{OBJ}}).', retour:'10 min de footing léger.',
        note:'RPE 8/10 · C\'est normal si les dernières sont difficiles, tu construis ta résistance.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue avec fin allure marathon', duree:'105 min', pcts:[[65,70]],
        echauff:'', corps:'95 min à {{P}}, puis les 10 dernières minutes à ton allure objectif marathon ({{OBJ}}). Tu apprends à finir sur la bonne allure quand les jambes sont déjà sollicitées.', retour:'',
        note:'RPE 6/10 puis 7/10 · Mémorise la sensation de l\'allure marathon sur jambes fatiguées.' },
    ]},
  { num:5, phase:'Volume', charge:'Élevée, cap des 2 heures',
    objectif:'Le volume hebdomadaire monte significativement. La sortie longue de 2 heures est un premier cap psychologique important : tu entres dans la dimension marathon.',
    conseil:'Sur les 3 × 12 min au seuil, chaque répétition doit finir à la même allure. Si tu accélères sur la troisième, c\'est que tu es parti trop doucement. La régularité est le signe d\'une bonne maîtrise de zone.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Endurance Fondamentale', duree:'50 min', pcts:[[65,70]],
        echauff:'', corps:'50 min à {{P}}. Volume de base avant la séance tempo du jeudi. Très facile, jamais fatigant. Récupération active après les deux semaines de charge élevée.', retour:'',
        note:'RPE 4/10 · Garde les jambes fraîches pour le jeudi.' },
      { jour:'Jeudi', type:'Tempo', titre:'3 × 12 minutes au seuil', duree:'65 min', pcts:[[65,70],[85,85]],
        echauff:'25 min de footing progressif à {{P}}.', corps:'3 × 12 min à {{P}} avec 3 min de récupération entre chaque. La troisième répétition est la plus difficile. Maintiens l\'allure coûte que coûte.', retour:'10 min de footing léger.',
        note:'RPE 8/10 · 36 min totales au seuil, ton record depuis le début du plan.' },
      { jour:'Samedi', type:'EF', titre:'Footing de récupération', duree:'40 min', pcts:[[60,65]],
        echauff:'', corps:'40 min à {{P}}. Récupération active indispensable avant la grande sortie longue du dimanche. Cours vraiment détendu, sans jamais forcer.', retour:'',
        note:'RPE 3/10 · Ce footing te fera récupérer plus vite que le repos complet.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 2 heures', duree:'2h', pcts:[[65,70]],
        echauff:'', corps:'2 heures à {{P}}. Ton premier cap à 2 heures. Régularité, respiration, hydratation toutes les 20 min. Emporte de l\'eau. À partir d\'aujourd\'hui, prends un gel à 1h de course.', retour:'',
        note:'RPE 5-6/10 · À 2h, tu touches aux exigences physiques du marathon. Récupère bien.' },
    ]},
  { num:6, phase:'Volume', charge:'Très élevée, sortie longue avec allure marathon',
    objectif:'La sortie longue avec un bloc à allure marathon est la répétition la plus précieuse du plan. Elle te donne une référence directe sur ta capacité à tenir {{OBJ}}/km en conditions réelles.',
    conseil:'Sur les 8 km à allure marathon dans la sortie longue, si {{OBJ}} te semble trop facile, ton objectif est peut-être trop prudent. Si tu galères, c\'est que la base n\'est pas encore assez solide : continue à construire.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Footing long EF', duree:'55 min', pcts:[[70,70],[65,65]],
        echauff:'', corps:'55 min à {{P}}. Long et facile avant la semaine très chargée. Si tu te sens fatigué, passe à {{P}}.', retour:'',
        note:'RPE 5/10 · Récupération active avant les deux séances de qualité.' },
      { jour:'Mercredi', type:'Tempo', titre:'2 × 20 minutes au seuil', duree:'70 min', pcts:[[65,70],[86,86]],
        echauff:'25 min de footing progressif à {{P}}.', corps:'2 × 20 min à {{P}} avec 3 min de récupération entre chaque. 40 min totales au seuil. Ta séance tempo la plus longue à ce stade. Gère l\'allure du premier au dernier kilomètre.', retour:'10 min de footing léger.',
        note:'RPE 8/10 · 40 min au seuil, charge sérieuse. Récupère bien les jours suivants.' },
      { jour:'Samedi', type:'EF', titre:'Footing de récupération', duree:'40 min', pcts:[[60,65]],
        echauff:'', corps:'40 min à {{P}}. Deux séances intenses cette semaine. Ce footing reste léger pour ne pas accumuler de fatigue avant la sortie longue.', retour:'',
        note:'RPE 3/10 · Le footing de récupération est aussi important que les séances intenses.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue avec encart allure marathon', duree:'2h20', pcts:[[65,70]],
        echauff:'', corps:'90 min à {{P}}, puis 8 km à ton allure objectif marathon ({{OBJ}}), puis retour à l\'allure EF pour finir. Gel à 1h et à 1h30. Cet encart t\'apprend à tenir l\'allure course sur des jambes déjà sollicitées.', retour:'',
        note:'RPE 6/10 en EF · 7-8/10 sur les 8 km · Note ton ressenti, c\'est un indicateur fiable.' },
    ]},
  { num:7, phase:'Intensification', charge:'Très élevée, charge maximale approche',
    objectif:'Tempo et fractionnés dans la même semaine, plus la sortie longue la plus longue jusqu\'ici. Cette combinaison seuil + vitesse + durée est ce qui te rapproche le plus des exigences du jour J.',
    conseil:'Sur les 3 × 15 min au seuil, l\'allure doit être tenue sur les trois répétitions. Si tu dois ralentir en fin de troisième répétition, réduis légèrement l\'allure la prochaine fois. Mieux vaut finir fort que terminer à bout.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Footing long EF', duree:'60 min', pcts:[[70,70],[65,65]],
        echauff:'', corps:'60 min à {{P}}. Long et facile avant la semaine la plus chargée. Si tu te sens fatigué, passe à {{P}}.', retour:'',
        note:'RPE 5/10 · Ce footing prépare les séances du mercredi et vendredi.' },
      { jour:'Mercredi', type:'Tempo', titre:'3 × 15 minutes au seuil', duree:'70 min', pcts:[[65,70],[86,86]],
        echauff:'25 min de footing progressif à {{P}}.', corps:'3 × 15 min à {{P}} avec 3 min de récupération entre chaque. La troisième répétition est la plus difficile du plan jusqu\'ici. Maintiens l\'allure.', retour:'10 min de footing léger.',
        note:'RPE 8-9/10 · 45 min totales au seuil, ton record absolu. Récupère bien le jeudi.' },
      { jour:'Vendredi', type:'Fractionné', titre:'6 × 1000 mètres', duree:'70 min', pcts:[[65,65],[88,92]],
        echauff:'25 min de footing EF à {{P}}.', corps:'6 × 1000m à {{P}}. Allure plus haute que sur les 1500m des semaines précédentes. Récupération 2 min au trot. Régulier sur les 6 répétitions.', retour:'10 min de footing léger.',
        note:'RPE 8/10 · Ces 1000m développent ta VMA tout en préservant ton endurance de base.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 2h35', duree:'2h35', pcts:[[65,70]],
        echauff:'', corps:'2h35 à {{P}}. Ta sortie longue la plus longue jusqu\'ici. Gel à 1h, à 1h30 et à 2h. Régularité, respiration, hydratation toutes les 20 min. Garde quelque chose en réserve.', retour:'',
        note:'RPE 6/10 · Après cette semaine, la forme monte d\'un cran. Récupère sérieusement.' },
    ]},
  { num:8, phase:'Intensification', charge:'Maximale, pic de charge du plan',
    objectif:'Le pic de ta préparation. La sortie longue la plus longue du plan avec un bloc à allure marathon. C\'est la séance qui préfigure le mieux les exigences du jour J.',
    conseil:'C\'est ta semaine de charge maximale. N\'ajoute rien, n\'improvise rien. Mange des glucides complexes les soirs avant les séances clés. Dors 8 heures. Après cette semaine, l\'intensité diminue progressivement.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Footing long EF', duree:'60 min', pcts:[[70,70],[65,65]],
        echauff:'', corps:'60 min à {{P}}. Long et facile avant la semaine la plus chargée du plan. Si tu te sens fatigué, passe à {{P}}.', retour:'',
        note:'RPE 5/10 · Ce footing prépare les deux séances dures de la semaine.' },
      { jour:'Mercredi', type:'Tempo', titre:'4 × 12 minutes au seuil', duree:'75 min', pcts:[[65,70],[87,87]],
        echauff:'25 min de footing progressif à {{P}}.', corps:'4 × 12 min à {{P}} avec 3 min de récupération entre chaque. Légèrement plus intense que la semaine 7. La quatrième répétition est la plus difficile, maintiens l\'allure.', retour:'10 min de footing léger.',
        note:'RPE 8-9/10 · 48 min au seuil. Ton pic de charge sur cette séance. Mange bien après.' },
      { jour:'Vendredi', type:'Fractionné', titre:'8 × 1000 mètres', duree:'80 min', pcts:[[65,65],[88,92]],
        echauff:'25 min de footing EF à {{P}}.', corps:'8 × 1000m à {{P}}. Deux répétitions de plus que la semaine dernière. Récupération 2 min au trot. Maintiens la même allure sur les 8.', retour:'10 min de footing léger.',
        note:'RPE 8-9/10 · Semaine de charge maximale. La fatigue en fin de séance est normale.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue avec encart allure marathon', duree:'2h50', pcts:[[65,70]],
        echauff:'', corps:'2h à {{P}}, puis 12 km à ton allure objectif marathon ({{OBJ}}), puis retour à l\'allure EF. Gel à 1h, à 1h30, à 2h. Ces 12 km à allure objectif après 2h de course simulent directement la 2e partie du marathon.', retour:'',
        note:'RPE 6/10 en EF · 8/10 sur les 12 km · Après cette semaine, l\'entraînement dur est terminé.' },
    ]},
  { num:9, phase:'Spécificité marathon', charge:'Élevée, travail à l\'allure objectif',
    objectif:'Les séances s\'alignent sur ton allure de course. Tu répètes littéralement l\'allure que tu devras tenir 42 km le jour J. La spécificité est ce qui construit la confiance.',
    conseil:'Sur les 3 × 6 km, chaque bloc doit être exactement à {{OBJ}}. Ni plus vite — tu épuiserais les réserves, ni plus lentement — tu perdrais le bénéfice. L\'objectif est la répétabilité parfaite de cette allure.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Endurance Fondamentale', duree:'50 min', pcts:[[65,70]],
        echauff:'', corps:'50 min à {{P}}. Volume de base avant la séance spécifique du jeudi. Très facile, jamais fatigant. Les jambes doivent être fraîches pour le jeudi.', retour:'',
        note:'RPE 4/10 · Garde les jambes fraîches pour le jeudi.' },
      { jour:'Jeudi', type:'Spécifique', titre:'3 × 6 km à allure marathon', duree:'75 min',
        echauff:'20 min de footing EF.', corps:'3 × 6 km exactement à ton allure objectif marathon ({{OBJ}}). Récupération 2 min au trot entre chaque. Tu répètes littéralement ton allure de course sur des jambes fraîches.', retour:'10 min de footing léger.',
        note:'RPE 7-8/10 · Si {{OBJ}} te semble trop facile sur les 3, ton objectif est peut-être trop prudent.' },
      { jour:'Samedi', type:'EF', titre:'Footing de récupération', duree:'40 min', pcts:[[60,65]],
        echauff:'', corps:'40 min à {{P}}. Séance chargée cette semaine. Ce footing absorbe la charge et prépare la sortie longue du lendemain. Cours détendu, sans jamais forcer.', retour:'',
        note:'RPE 3/10 · Facile, sans exception.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue avec encart allure marathon', duree:'2h20', pcts:[[65,70]],
        echauff:'', corps:'80 min à {{P}}, puis 10 km à ton allure objectif marathon ({{OBJ}}), puis retour à l\'allure EF pour finir. Gel à 1h et à 1h20. Ces 10 km après 80 min reproduisent directement la 2e partie du marathon.', retour:'',
        note:'RPE 6/10 en EF · 7-8/10 sur les 10 km · Mémorise cette sensation, tu la retrouveras en course.' },
    ]},
  { num:10, phase:'Spécificité marathon', charge:'Très élevée, pic de spécificité',
    objectif:'Ta dernière vraie semaine de charge à l\'allure marathon. Les 4 × 6 km + les 15 km dans la sortie longue t\'apportent la confiance nécessaire pour aborder le jour J sereinement.',
    conseil:'Sur les 4 × 6 km, la quatrième répétition est la plus précieuse : elle simule la fin de course avec des jambes déjà chargées. Maintiens {{OBJ}}/km coûte que coûte sur ces derniers 6 km.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Endurance Fondamentale', duree:'55 min', pcts:[[65,70]],
        echauff:'', corps:'55 min à {{P}}. Volume avant la semaine la plus spécifique du plan. Très facile, allure conversation.', retour:'',
        note:'RPE 4-5/10 · Garde les jambes fraîches pour le jeudi.' },
      { jour:'Jeudi', type:'Spécifique', titre:'4 × 6 km à allure marathon', duree:'90 min',
        echauff:'20 min de footing EF.', corps:'4 × 6 km exactement à ton allure objectif marathon ({{OBJ}}). Récupération 2 min au trot entre chaque. Une répétition de plus qu\'en semaine 9. La quatrième est ta répétition générale avant le jour J.', retour:'10 min de footing léger.',
        note:'RPE 7-8/10 · 24 km à l\'allure objectif. Si tu les tiens sur 4 blocs, tu peux tenir 42 km.' },
      { jour:'Samedi', type:'EF', titre:'Footing de récupération', duree:'40 min', pcts:[[60,65]],
        echauff:'', corps:'40 min à {{P}}. Indispensable pour absorber la charge des deux séances de qualité. Cours détendu, sans jamais forcer.', retour:'',
        note:'RPE 3/10 · Le footing de récupération est aussi important que les séances intenses.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue avec long encart allure marathon', duree:'2h20', pcts:[[65,70]],
        echauff:'', corps:'50 min à {{P}}, puis 15 km à ton allure objectif marathon ({{OBJ}}), puis retour à l\'allure EF. Gel à 45 min, à 1h15, à 1h45. Ta dernière sortie longue spécifique.', retour:'',
        note:'RPE 6/10 en EF · 8/10 sur les 15 km · Après cette séance, les séances dures sont terminées.' },
    ]},
  { num:11, phase:'Consolidation', charge:'Réduite, affûtage',
    objectif:'La consolidation préserve ta forme sans t\'épuiser. Volume réduit de 40%, intensité maintenue sur une séance clé. L\'objectif : aborder la semaine de course avec les jambes fraîches et l\'esprit confiant.',
    conseil:'Cette semaine allégée laisse les adaptations des 10 semaines de travail s\'installer pleinement. Dors 8 heures, mange bien, évite le stress inutile. Ne rajoute pas de séances : la forme arrive.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Footing léger', duree:'45 min', pcts:[[65,65]],
        echauff:'', corps:'45 min très faciles à {{P}}. Garder les jambes en mouvement sans les fatiguer. Cours au ressenti, sans montre. Profite de cette semaine allégée pour te ressourcer.', retour:'',
        note:'RPE 3/10 · Tu dois finir comme si tu venais de te promener.' },
      { jour:'Jeudi', type:'Tempo', titre:'2 × 12 minutes au seuil, volume réduit', duree:'55 min', pcts:[[65,70],[84,84]],
        echauff:'25 min de footing progressif à {{P}}.', corps:'2 × 12 min à {{P}}. Volume réduit de 50% mais intensité maintenue. Récupération 3 min entre chaque. Termine par 1 km à ton allure objectif marathon ({{OBJ}}).', retour:'10 min de footing léger.',
        note:'RPE 7/10 · Ces répétitions maintiennent tes sensations sans te fatiguer.' },
      { jour:'Samedi', type:'EF', titre:'Footing de 35 minutes', duree:'35 min', pcts:[[65,65]],
        echauff:'', corps:'35 min à {{P}}. Garde les jambes en mouvement. Cours au ressenti, détendu et régulier. Ton corps se recharge pour le jour J.', retour:'',
        note:'RPE 3/10 · Tu dois finir frais et légèrement dynamisé, jamais fatigué.' },
    ]},
  { num:12, phase:'Semaine de course', charge:'Conserve, tu es prêt',
    objectif:'Rien ne se gagne à l\'entraînement cette semaine. L\'objectif unique : arriver au départ reposé, confiant, les jambes fraîches. Tout a été construit, il ne reste qu\'à exécuter.',
    conseil:'Pars à ton allure objectif {{OBJ}}/km dès le départ. Ne te laisse pas griser par l\'adrénaline. La patience des 8 premiers kilomètres fait les 8 derniers. Chaque seconde gagnée trop tôt coûte une minute à la fin.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing très léger', duree:'35 min', pcts:[[60,65]],
        echauff:'', corps:'35 min à {{P}}. Maintenir la circulation sanguine. Vraiment facile. Si tu te sens fatigué, réduis à 25 minutes.', retour:'',
        note:'RPE 3/10 · Aucun effort. Juste des jambes qui bougent.' },
      { jour:'Mercredi', type:'Fractionné', titre:'6 × 30/30 à allure marathon', duree:'30 min',
        echauff:'15 min de footing EF très léger.',
        corps:'6 × 30 secondes à ton allure objectif marathon ({{OBJ}}) / 30 secondes au trot. Effort court et ciblé. Les jambes retrouvent la sensation d\'allure avant le grand jour.',
        retour:'10 min de jogging léger.',
        note:'RPE 6/10 · Ces relances maintiennent les sensations sans t\'épuiser avant le jour J.' },
      { jour:'Samedi', type:'Activation', titre:'Activation J-1 + accélérations', duree:'30 min', pcts:[[60,65]],
        echauff:'', corps:'20 min de trot à {{P}}. Puis 6 à 8 accélérations progressives de 80m : démarre doucement et accélère jusqu\'à ton allure objectif marathon ({{OBJ}}) sur les 20 derniers mètres. Récupère 60 sec en marchant entre chaque.', retour:'',
        note:'Ces accélérations réveillent tes fibres rapides. Prépare tes affaires ce soir.' },
      { jour:'Dimanche', type:'Course', titre:'MARATHON', duree:'Jour J',
        echauff:'10-15 min de jogging très léger avant le départ.',
        corps:'KM 1-8 : pars à {{OBJ}}/km, ne pars surtout pas plus vite. KM 9-21 : maintiens {{OBJ}}, régularité absolue, gel à chaque ravitaillement prévu. KM 22-30 : reste à {{OBJ}}, écoute ton corps. KM 31-35 : le mur arrive, raccourcis la foulée, augmente la cadence. KM 36-42 : donne absolument tout.',
        retour:'20-30 min de marche. Ravitaillement dans les 30 min. Tu as mérité ça.',
        note:'La douleur aux km 30-35 est normale. C\'est là que se gagne un marathon. Tiens bon.' },
    ]},
]
