// Marathon 12 semaines · 3 séances/semaine · Palier Avancé (VMA > 18.5)
// Surcharges : intervalles plus longs, allures plus hautes, SL plus longues, blocs allure marathon plus longs
const { applyOverrides } = require('../../lib/tier-overrides')
const base = require('./semaines-3-i.js')

module.exports = applyOverrides(base, {
  1: { replace: { Jeudi: {
    titre:'8 × 1000 mètres', pcts:[[65,65],[90,95]],
    echauff:'25 min progressif à {{P}}, finir par 4 accélérations 80m.',
    corps:'8 × 1000m à {{P}}. Trois répétitions de plus que la trame. Récupération 90 sec au trot. Régularité sur les 8. Le palier avancé démarre directement sur un volume VMA soutenu.',
    retour:'10 min footing très lent.',
    note:'RPE 7-8/10 · 8×1000m pour le palier avancé — volume VMA élevé dès la semaine 1.' },
    Dimanche: { duree:'100 min',
    corps:'100 min à {{P}}. Plus long que la trame (90 min). Hydrate-toi toutes les 20 min. Le palier avancé démarre avec plus de volume sur la SL.',
    note:'RPE 5/10 · Sortie longue allongée pour le palier avancé.' } } },
  2: { replace: { Jeudi: {
    titre:'5 × 2000 mètres — volume seuil élevé', pcts:[[65,65],[82,88]],
    echauff:'25 min progressif à {{P}}, finir par 4 accélérations 80m.',
    corps:'5 × 2000m à {{P}}. Une répétition de plus que la trame (4×2000m). Récupération 3 min au trot. 10 km à intensité. Régularité sur les 5.',
    retour:'10 min footing très lent.',
    note:'RPE 8/10 · Le palier avancé ajoute une répétition — 5×2000m = 10 km à intensité.' },
    Dimanche: { duree:'115 min',
    corps:'115 min à {{P}}. 15 min de plus que la trame. Hydrate-toi toutes les 20-25 min.',
    note:'RPE 5-6/10 · Sortie longue allongée pour le palier avancé.' } } },
  3: { replace: { Jeudi: {
    titre:'Tempo 25 minutes en continu', duree:'70 min', pcts:[[65,72],[84,88]],
    echauff:'25 min progressif à {{P}}, finir par 4 accélérations 80m.',
    corps:'25 min continus à {{P}}. 5 min de plus que la trame. Allure légèrement plus haute. À 25 min, tu entres dans la zone d\'adaptation spécifique du seuil marathon.',
    retour:'10 min footing très lent.',
    note:'RPE 8/10 · 25 min en continu à allure haute est le palier de référence du coureur avancé.' },
    Dimanche: { duree:'2h',
    corps:'1h40 à {{P}}, puis 20 min à ton allure objectif marathon ({{OBJ}}). Bloc OBJ allongé pour le palier avancé.',
    note:'RPE 6/10 puis 7-8/10 · Bloc OBJ allongé par rapport à la trame.' } } },
  4: { replace: { Jeudi: {
    titre:'4 × 3000 mètres — volume fractionné long', pcts:[[65,65],[82,87]],
    echauff:'25 min progressif à {{P}}, finir par 4 accélérations 80m.',
    corps:'4 × 3000m à {{P}}. Une répétition de plus que la trame (3×3000m). Récupération 4 min au trot. 12 km à intensité. Régularité sur les 4.',
    retour:'10 min footing très lent.',
    note:'RPE 8/10 · 4×3000m = 12 km à intensité. Volume de qualité élevé.' },
    Dimanche: { duree:'2h10',
    corps:'1h45 à {{P}}, puis 25 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h. Bloc OBJ allongé par rapport à la trame.',
    note:'RPE 6/10 puis 7-8/10 · 25 min à {{OBJ}} après 1h45 — test de forme sérieux.' } } },
  5: { replace: { Jeudi: {
    titre:'Tempo 35 minutes en continu', duree:'80 min', pcts:[[65,72],[84,88]],
    echauff:'25 min progressif à {{P}}, finir par 4 accélérations 80m.',
    corps:'35 min continus à {{P}}. 5 min de plus que la trame. La distance critique du marathonien avancé. Pars à la limite basse, tiens les 35 min complets.',
    retour:'10 min footing très lent.',
    note:'RPE 8-9/10 · 35 min en continu est le pic du palier avancé au seuil.' },
    Dimanche: { duree:'2h30',
    corps:'2h à {{P}}, puis 30 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h et à 1h30. Bloc OBJ à plein volume pour ce palier.',
    note:'RPE 6/10 puis 7-8/10 · 30 min à {{OBJ}} après 2h — répétition sérieuse de la deuxième moitié.' } } },
  6: { replace: { Jeudi: {
    titre:'3 × 5000 mètres — volume marathon extrême', pcts:[[65,65],[78,83]],
    echauff:'25 min progressif à {{P}}, finir par 4 accélérations 80m.',
    corps:'3 × 5000m à {{P}}. Une répétition de plus que la trame (2×5000m). Récupération 5 min au trot. 15 km à intensité — séance marathon de haut volume. Pars très conservateur sur les deux premiers.',
    retour:'10 min footing très lent.',
    note:'RPE 8-9/10 · 3×5000m = 15 km à intensité. Séance de référence du marathonien avancé.' },
    Dimanche: { duree:'2h45',
    corps:'2h15 à {{P}}, puis 12 km à ton allure objectif marathon ({{OBJ}}). Gel à 1h, à 1h30, à 2h.',
    note:'RPE 6/10 en EF · 7-8/10 sur les 12 km · Ta sortie longue la plus longue.' } } },
  7: { replace: {
    Dimanche: { duree:'2h50',
    corps:'2h10 à {{P}}, puis 18 km à ton allure objectif marathon ({{OBJ}}). Gel à 1h, à 1h20, à 2h. Ces 18 km après 2h10 sont la répétition la plus fidèle du marathon pour le palier avancé.',
    note:'RPE 6/10 en EF · 7-8/10 sur les 18 km · Après cette séance, tu connais ta vraie forme.' } } },
  8: { replace: { Jeudi: {
    titre:'3×2000m seuil + 2×2000m allure marathon — intensité avancée', pcts:[[65,65],[85,90],[82,82]],
    echauff:'25 min progressif à {{P}}, finir par 4 accélérations 80m.',
    corps:'3 × 2000m à {{P}} (seuil haut) → récup 3 min trot → 2 × 2000m à ton allure objectif marathon ({{OBJ}}). Allure seuil plus haute que la trame pour le palier avancé.',
    retour:'10 min footing très lent.',
    note:'RPE 9/10 sur les premiers blocs · Allure seuil plus haute que la trame — séance de charge maximale.' },
    Dimanche: { duree:'3h',
    corps:'2h25 à {{P}}, puis 18 km à ton allure objectif marathon ({{OBJ}}). Gel à 1h, à 1h30, à 2h. Ces 18 km après 2h25 sont ta répétition générale.',
    note:'RPE 6/10 en EF · 8/10 sur les 18 km · 3h totales : ta plus longue sortie.' } } },
  9: { replace: { Jeudi: {
    titre:'4 × 5 km à allure marathon', duree:'100 min', pcts:[[65,65]],
    echauff:'20 min footing EF à {{P}}.',
    corps:'4 × 5 km exactement à ton allure objectif marathon ({{OBJ}}). Récupération 4 min au trot entre chaque. Un bloc de plus que la trame. 20 km à l\'allure de ta course.',
    retour:'10 min footing léger.',
    note:'RPE 7-8/10 · 4×5km = 20 km à {{OBJ}}. Si les 4 blocs sont réguliers, l\'objectif est validé.' },
    Dimanche: { duree:'2h30',
    corps:'1h50 à {{P}}, puis 15 km à ton allure objectif marathon ({{OBJ}}). Gel à 1h, à 1h15, à 1h45.',
    note:'RPE 6/10 en EF · 7-8/10 sur les 15 km · Sortie longue spécifique allongée pour ce palier.' } } },
  10: { replace: { Jeudi: {
    titre:'3 × 5000 mètres — pic de spécificité', pcts:[[65,65],[78,83]],
    echauff:'25 min progressif à {{P}}, finir par 4 accélérations 80m.',
    corps:'3 × 5000m à {{P}}. Récupération 5 min au trot. Une répétition de plus que la trame (2×5000m). Le troisième 5000m est ta répétition générale absolue.',
    retour:'10 min footing très lent.',
    note:'RPE 8/10 · 3×5000m = 15 km à intensité. Après cette séance, les séances dures sont terminées.' },
    Dimanche: { duree:'2h15',
    corps:'1h40 à {{P}}, puis 12 km à ton allure objectif marathon ({{OBJ}}). Gel à 1h et à 1h15.',
    note:'RPE 6/10 en EF · 7-8/10 sur les 12 km · Dernière sortie longue chargée pour le palier avancé.' } } },
})
