// Marathon 12 semaines · 3 séances/semaine · Palier Débutant (VMA ≤ 13.5)
// Surcharges : fractionnés raccourcis, tempo réduit, SL plus courtes, blocs OBJ réduits
const { applyOverrides } = require('../../lib/tier-overrides')
const base = require('./semaines-3-i.js')

module.exports = applyOverrides(base, {
  1: { replace: { Jeudi: {
    titre:'5 × 800 mètres', pcts:[[65,65],[85,90]],
    echauff:'25 min progressif à {{P}}, finir par 4 accélérations 80m.',
    corps:'5 × 800m à {{P}}. Distance plus courte que la trame — adapté pour construire la résistance progressivement. Récupération 2 min au trot entre chaque. Régularité sur les 5.',
    retour:'10 min footing très lent.',
    note:'RPE 6-7/10 · 800m est la distance d\'entrée idéale pour un premier plan marathon.' },
    Dimanche: { duree:'70 min',
    corps:'70 min à {{P}}. Plus court que la trame. Régulier et contrôlé. Hydrate-toi toutes les 20 min. 3 séances seulement : chaque séance compte.',
    note:'RPE 4-5/10 · La durée prime sur l\'allure. Aucun effort excessif.' } } },
  2: { replace: { Jeudi: {
    titre:'3 × 1000 mètres', pcts:[[65,65],[85,90]],
    echauff:'25 min progressif à {{P}}, finir par 4 accélérations 80m.',
    corps:'3 × 1000m à {{P}}. Moins de blocs que la trame (4×2000m) mais des distances adaptées. Récupération 2 min au trot entre chaque. Maintiens la même allure sur les 3.',
    retour:'10 min footing très lent.',
    note:'RPE 6-7/10 · La progression vers les 2000m se fera semaine après semaine.' },
    Dimanche: { duree:'85 min',
    corps:'85 min à {{P}}. 15 min de plus qu\'en semaine 1. Hydrate-toi toutes les 20-25 min.',
    note:'RPE 4-5/10 · La sortie longue est le pilier du plan marathon débutant.' } } },
  3: { replace: { Jeudi: {
    titre:'Tempo 15 minutes en continu', duree:'50 min', pcts:[[65,70],[80,82]],
    echauff:'20 min progressif à {{P}}, finir par 4 accélérations 80m.',
    corps:'15 min continus à {{P}}. Allure légèrement plus douce que la trame. Tu dois pouvoir prononcer quelques mots. Premier contact avec l\'effort soutenu.',
    retour:'10 min footing très lent.',
    note:'RPE 6/10 · 15 min en continu au seuil léger est un cap pour ce palier.' },
    Dimanche: { duree:'90 min',
    corps:'90 min à {{P}}. Régulier, hydraté, concentré sur ta foulée.',
    note:'RPE 5/10 · Pas de bloc allure marathon cette semaine pour ce palier.' } } },
  4: { replace: { Jeudi: {
    titre:'4 × 1000 mètres + 1 km allure marathon', pcts:[[65,65],[80,85]],
    echauff:'25 min progressif à {{P}}, finir par 4 accélérations 80m.',
    corps:'4 × 1000m à {{P}}. Récupération 2 min. Beaucoup plus court que 3×3000m mais progression cohérente. Après le dernier 1000m et 2 min de récup, 1 km à {{OBJ}}.',
    retour:'10 min footing très lent.',
    note:'RPE 7/10 · Pour ce palier, 4×1000m est la distance de progression vers les 2000-3000m.' },
    Dimanche: { duree:'100 min',
    corps:'90 min à {{P}}, puis 10 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h. Mémorise cette sensation sur les 10 dernières minutes.',
    note:'RPE 5-6/10 puis 6-7/10 · Bloc OBJ raccourci pour ce palier.' } } },
  5: { replace: { Jeudi: {
    titre:'2 × 15 minutes au seuil', duree:'65 min', pcts:[[65,70],[80,83]],
    echauff:'25 min progressif à {{P}}, finir par 4 accélérations 80m.',
    corps:'2 × 15 min à {{P}}. Récupération 4 min entre les 2 blocs. Allure adaptée ce palier. Le deuxième bloc se termine fatigué — c\'est voulu.',
    retour:'10 min footing très lent.',
    note:'RPE 7/10 · 30 min totales au seuil léger, adapté au palier débutant.' },
    Dimanche: { duree:'2h',
    corps:'2h à {{P}}. Cap des 2 heures pour ce palier. Gel à 1h. Hydratation toutes les 20 min. Pas de bloc marathon cette semaine.',
    note:'RPE 5-6/10 · Le palier débutant atteint 2h au lieu de 2h15+30min.' } } },
  6: { replace: { Jeudi: {
    titre:'2 × 2000 mètres — premier contact avec le long fractionné', pcts:[[65,65],[77,82]],
    echauff:'25 min progressif à {{P}}, finir par 4 accélérations 80m.',
    corps:'2 × 2000m à {{P}}. Récupération 5 min au trot entre les 2 blocs. Volume réduit par rapport à 2×5000m. Pars conservateur sur le premier.',
    retour:'10 min footing très lent.',
    note:'RPE 7/10 · Premier contact avec les longs fractionnnés. 2×2000m avant d\'aller vers les 5000m.' },
    Dimanche: { duree:'2h10',
    corps:'2h10 à {{P}}, puis 6 km à ton allure objectif marathon ({{OBJ}}). Gel à 1h et à 1h20. Bloc allure marathon raccourci pour ce palier.',
    note:'RPE 5-6/10 en EF · 6-7/10 sur les 6 km · Mémorise la sensation de {{OBJ}}.' } } },
  7: { replace: { Jeudi: {
    titre:'2000m / 3000m / 2000m progressif', pcts:[[65,65],[80,82],[82,84],[84,87]],
    echauff:'25 min progressif à {{P}}, finir par 4 accélérations 80m.',
    corps:'2000m à {{P}} → récup 4 min → 3000m à {{P}} → récup 4 min → 2000m à {{P}}. Version raccourcie de la séance 3000/5000/3000 de la trame. Progression sur les 3 blocs.',
    retour:'10 min footing très lent.',
    note:'RPE 7-8/10 · La version raccourcie mais la même philosophie de progression.' },
    Dimanche: { duree:'2h15',
    corps:'2h15 à {{P}}. Ta sortie longue la plus longue jusqu\'ici. Gel à 1h et à 1h35. Pas de bloc allure marathon cette semaine pour ce palier.',
    note:'RPE 6/10 · Durée maximale sans bloc marathon pour consolider le volume.' } } },
  8: { replace: { Jeudi: {
    titre:'3 × 1500 mètres + 1 × 2 km allure marathon', pcts:[[65,65],[80,85]],
    echauff:'25 min progressif à {{P}}, finir par 4 accélérations 80m.',
    corps:'3 × 1500m à {{P}} → récup 3 min trot → 2 km à ton allure objectif marathon ({{OBJ}}). Version simplifiée de FL-14. La transition finale vers {{OBJ}} est l\'élément clé.',
    retour:'10 min footing très lent.',
    note:'RPE 7-8/10 · Même concept que FL-14 mais avec des distances adaptées à ce palier.' },
    Dimanche: { duree:'2h25',
    corps:'1h50 à {{P}}, puis 10 km à ton allure objectif marathon ({{OBJ}}). Gel à 1h et à 1h20. 10 km à {{OBJ}} après 1h50 — c\'est ta grande séance de la semaine.',
    note:'RPE 5-6/10 en EF · 7/10 sur les 10 km · Le pic de charge du plan débutant.' } } },
  9: { replace: { Jeudi: {
    titre:'2 × 4 km à allure marathon', duree:'70 min', pcts:[[65,65]],
    echauff:'20 min footing EF à {{P}}.',
    corps:'2 × 4 km exactement à ton allure objectif marathon ({{OBJ}}). Récupération 3 min au trot entre les 2 blocs. Version raccourcie de SP-05 avec 2 blocs au lieu de 3.',
    retour:'10 min footing léger.',
    note:'RPE 6-7/10 · 2 blocs de 4 km : 8 km à l\'allure cible. Régularité parfaite entre les 2.' },
    Dimanche: { duree:'1h55',
    corps:'1h20 à {{P}}, puis 8 km à ton allure objectif marathon ({{OBJ}}). Gel à 1h et à 1h10.',
    note:'RPE 5-6/10 en EF · 6-7/10 sur les 8 km · Mémorise cette sensation.' } } },
  10: { replace: { Jeudi: {
    titre:'1 × 5000 mètres — répétition générale', duree:'65 min', pcts:[[65,65],[78,83]],
    echauff:'25 min progressif à {{P}}, finir par 4 accélérations 80m.',
    corps:'1 × 5000m à {{P}}. Un seul bloc mais tenu de bout en bout — c\'est ta répétition générale. Après 4 min de récup, 2 km à {{OBJ}} pour graver l\'allure avant la course.',
    retour:'10 min footing très lent.',
    note:'RPE 7-8/10 sur le 5000m · Un seul bloc de 5000m est le pic spécifique adapté à ce palier.' },
    Dimanche: { duree:'2h',
    corps:'1h30 à {{P}}, puis 8 km à ton allure objectif marathon ({{OBJ}}). Gel à 1h et à 1h10. Après cette séance, les séances dures sont terminées.',
    note:'RPE 5-6/10 en EF · 7/10 sur les 8 km · Dernière sortie longue chargée.' } } },
})
