// Marathon 12 semaines · 3 séances/semaine · Palier Intermédiaire (VMA 13.5 à 18.5)
// {{P}} remplacé séquentiellement · {{OBJ}} = allure objectif marathon (80% VMA)
module.exports = [
  { num:1, phase:'Adaptation', charge:'Légère',
    objectif:'Installer le rythme sur 3 séances et prendre ses repères sur les allures. Avec 3 séances par semaine, chaque séance compte double : ne bâcle rien, ne saute rien.',
    conseil:'Sur les 6 × 800m, la régularité sur les 6 répétitions est plus importante que la vitesse. Un écart de plus de 10 secondes entre la première et la dernière indique un départ trop rapide.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Endurance Fondamentale', duree:'50 min', pcts:[[65,70]],
        echauff:'', corps:'Course continue à {{P}}. Allure conversation, tu dois pouvoir parler en phrases complètes. Régulier et relâché du début à la fin.', retour:'',
        note:'RPE 4-5/10 · Avec 3 séances/semaine, ce footing est long pour compenser le volume.' },
      { jour:'Jeudi', type:'Fractionné', titre:'6 × 800 mètres', duree:'60 min', pcts:[[65,65],[88,92]],
        echauff:'20 min de footing EF à {{P}}.', corps:'6 × 800m à {{P}}. Effort soutenu mais maîtrisé. Récupération 90 sec au trot entre chaque. Même allure sur les 6.', retour:'10 min de jogging léger.',
        note:'RPE 7-8/10 · Ces 800m posent les fondations de ta résistance à l\'effort.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue', duree:'75 min', pcts:[[65,70]],
        echauff:'', corps:'75 min à {{P}}. La sortie longue est la séance pilier du marathon. Hydrate-toi toutes les 20-25 min. Régulier et contrôlé du début à la fin.', retour:'',
        note:'RPE 5/10 · La durée prime sur l\'allure. Ne t\'emballe pas.' },
    ]},
  { num:2, phase:'Adaptation', charge:'Légère à modérée',
    objectif:'Confirmer les bases. Deux répétitions de plus sur le fractionné, la sortie longue progresse de 10 minutes. Chaque séance doit être exécutée proprement.',
    conseil:'Sur les 8 × 800m, si les deux dernières sont nettement plus lentes, tu es parti trop vite. Réduis l\'allure d\'objectif et maintiens la régularité sur les 8.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Endurance Fondamentale', duree:'55 min', pcts:[[65,70]],
        echauff:'', corps:'55 min à {{P}}. Même principe que la semaine passée. Allure conversation, régulière du début à la fin.', retour:'',
        note:'RPE 4-5/10 · 5 minutes de plus que la semaine 1, la progression est volontairement douce.' },
      { jour:'Jeudi', type:'Fractionné', titre:'8 × 800 mètres', duree:'65 min', pcts:[[65,65],[88,92]],
        echauff:'25 min de footing EF à {{P}}.', corps:'8 × 800m à {{P}}. Deux répétitions de plus qu\'en semaine 1. Récupération 90 sec au trot. Maintiens la même allure sur les 8.', retour:'10 min de footing léger.',
        note:'RPE 7-8/10 · La régularité est plus importante que la vitesse maximale.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue', duree:'85 min', pcts:[[65,70]],
        echauff:'', corps:'85 min à {{P}}. 10 minutes de plus qu\'en semaine 1. Continue à bâtir ta base aérobie. Hydrate-toi toutes les 20-25 min.', retour:'',
        note:'RPE 5/10 · Avec 3 séances/semaine, la sortie longue porte beaucoup du volume.' },
    ]},
  { num:3, phase:'Développement aérobie', charge:'Modérée, première séance tempo',
    objectif:'Introduire le travail au seuil. Le tempo repousse ton seuil lactique et développe directement ta capacité à maintenir l\'allure marathon sur 42 km.',
    conseil:'Sur le tempo de 20 min, tu dois pouvoir prononcer des mots isolés mais pas tenir une conversation. C\'est exactement la bonne intensité. Trop facile, tu perds le bénéfice. Trop difficile, tu ne tiens pas.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Footing long EF', duree:'60 min', pcts:[[70,70],[65,65]],
        echauff:'', corps:'60 min à {{P}}. Long et facile avant la semaine chargée. Travaille ta technique : légère bascule vers l\'avant, attaque milieu du pied. Si tu te sens fatigué, passe à {{P}}.', retour:'',
        note:'RPE 5/10 · Ce footing long porte une grande partie de ton volume hebdomadaire.' },
      { jour:'Jeudi', type:'Tempo', titre:'Tempo continu, 20 minutes', duree:'55 min', pcts:[[65,70],[84,84]],
        echauff:'25 min de footing progressif à {{P}}.', corps:'20 minutes continues à {{P}}. Première séance au seuil anaérobie. Difficile mais tenable sur toute la durée. Allure régulière du début à la fin.', retour:'12 min de jogging très lent.',
        note:'RPE 7-8/10 · Cette zone développe directement ta capacité à tenir l\'allure marathon.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue', duree:'95 min', pcts:[[65,70]],
        echauff:'', corps:'95 min à {{P}}. Régulier, hydraté, concentré sur ta foulée. La sortie longue reste facile en allure pour cumuler le volume sans fatigue excessive.', retour:'',
        note:'RPE 5-6/10 · La fatigue en fin de semaine est normale. Récupère bien.' },
    ]},
  { num:4, phase:'Développement aérobie', charge:'Élevée, consolidation seuil',
    objectif:'Consolider le travail de seuil et franchir le cap des 100 minutes en sortie longue. La deuxième semaine avec un tempo : les allures commencent à se naturaliser.',
    conseil:'Sur les 2 × 15 min, la deuxième répétition est intentionnellement plus difficile. Ne ralentis pas : c\'est l\'inconfort qui produit le progrès. Récupère sérieusement le vendredi et le samedi.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Footing long EF', duree:'65 min', pcts:[[70,70],[65,65]],
        echauff:'', corps:'65 min à {{P}}. Long, régulier, facile. Ton footing le plus long jusqu\'ici. Si tu te sens fatigué, passe à {{P}}.', retour:'',
        note:'RPE 5/10 · 3 séances/semaine signifie que les footings sont plus longs pour compenser.' },
      { jour:'Jeudi', type:'Tempo', titre:'2 × 15 minutes au seuil', duree:'60 min', pcts:[[65,70],[85,85]],
        echauff:'25 min de footing progressif à {{P}}.', corps:'2 × 15 min à {{P}} avec 3 min de récupération entre chaque. La deuxième répétition se termine fatigué, c\'est voulu. Maintiens l\'allure sur les deux blocs.', retour:'10 min de footing léger.',
        note:'RPE 7-8/10 · 30 min totales au seuil, ton record depuis le début du plan.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue avec fin allure marathon', duree:'105 min', pcts:[[65,70]],
        echauff:'', corps:'95 min à {{P}}, puis les 10 dernières minutes à ton allure objectif marathon ({{OBJ}}). Tu apprends à finir sur la bonne allure quand les jambes sont déjà sollicitées.', retour:'',
        note:'RPE 6/10 puis 7/10 · Mémorise la sensation de l\'allure marathon sur jambes fatiguées.' },
    ]},
  { num:5, phase:'Volume', charge:'Élevée, cap des 2 heures',
    objectif:'Le volume monte. La sortie longue de 2 heures est un cap important. Tu entres dans la vraie dimension marathon. L\'EF plus long que d\'habitude compense la réduction à 3 séances.',
    conseil:'Sur les 3 × 12 min au seuil, chaque répétition doit finir à la même allure. La régularité est le signe d\'une bonne maîtrise de zone. Si tu accélères sur la troisième, tu es parti trop doucement.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Endurance Fondamentale', duree:'55 min', pcts:[[65,70]],
        echauff:'', corps:'55 min à {{P}}. Volume de base avant la séance tempo du jeudi. Très facile, jamais fatigant.', retour:'',
        note:'RPE 4/10 · Garde les jambes fraîches pour le jeudi.' },
      { jour:'Jeudi', type:'Tempo', titre:'3 × 12 minutes au seuil', duree:'65 min', pcts:[[65,70],[85,85]],
        echauff:'25 min de footing progressif à {{P}}.', corps:'3 × 12 min à {{P}} avec 3 min de récupération entre chaque. La troisième répétition est la plus difficile. Maintiens l\'allure coûte que coûte.', retour:'10 min de footing léger.',
        note:'RPE 8/10 · 36 min totales au seuil, ton record depuis le début du plan.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 2 heures', duree:'2h', pcts:[[65,70]],
        echauff:'', corps:'2 heures à {{P}}. Ton premier cap à 2 heures. Hydratation toutes les 20 min. Gel à 1h de course. Emporte de l\'eau.', retour:'',
        note:'RPE 5-6/10 · À 2h, tu touches aux exigences physiques du marathon.' },
    ]},
  { num:6, phase:'Volume', charge:'Très élevée, allure marathon en sortie longue',
    objectif:'La sortie longue avec un bloc à allure marathon est la répétition la plus précieuse du plan. Elle te donne une référence directe sur ta capacité à tenir {{OBJ}}/km en conditions réelles.',
    conseil:'Sur les 8 km à allure marathon dans la sortie longue, note ton ressenti à la fin de chaque kilomètre. C\'est l\'indicateur le plus fiable de ta condition réelle à 6 semaines du marathon.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Footing long EF', duree:'65 min', pcts:[[70,70],[65,65]],
        echauff:'', corps:'65 min à {{P}}. Long et facile avant la semaine très chargée. Si tu te sens fatigué, passe à {{P}}.', retour:'',
        note:'RPE 5/10 · Récupération active avant la séance tempo du jeudi.' },
      { jour:'Jeudi', type:'Tempo', titre:'2 × 20 minutes au seuil', duree:'70 min', pcts:[[65,70],[86,86]],
        echauff:'25 min de footing progressif à {{P}}.', corps:'2 × 20 min à {{P}} avec 3 min de récupération entre chaque. 40 min totales au seuil. Ta séance tempo la plus longue à ce stade.', retour:'10 min de footing léger.',
        note:'RPE 8/10 · 40 min au seuil, charge sérieuse. Récupère bien les jours suivants.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue avec encart allure marathon', duree:'2h20', pcts:[[65,70]],
        echauff:'', corps:'90 min à {{P}}, puis 8 km à ton allure objectif marathon ({{OBJ}}), puis retour à l\'allure EF. Gel à 1h et à 1h30. Cet encart t\'apprend à tenir l\'allure sur des jambes déjà sollicitées.', retour:'',
        note:'RPE 6/10 en EF · 7-8/10 sur les 8 km · Note ton ressenti, c\'est un indicateur fiable.' },
    ]},
  { num:7, phase:'Intensification', charge:'Très élevée, pic de charge approche',
    objectif:'Tempo et sortie longue maximale dans la même semaine. Avec 3 séances, chaque session porte plus de poids. Le tempo long de la semaine prépare les muscles au long effort du dimanche.',
    conseil:'Sur les 3 × 15 min au seuil, l\'allure doit être tenue sur les trois répétitions. Si tu dois ralentir sur la troisième, recalibre l\'allure à la baisse et maintiens la régularité.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Footing long EF', duree:'70 min', pcts:[[70,70],[65,65]],
        echauff:'', corps:'70 min à {{P}}. Long et facile avant la semaine la plus chargée. Si tu te sens fatigué, passe à {{P}}.', retour:'',
        note:'RPE 5/10 · Ce footing long compense la réduction à 3 séances par semaine.' },
      { jour:'Jeudi', type:'Tempo', titre:'3 × 15 minutes au seuil', duree:'70 min', pcts:[[65,70],[86,86]],
        echauff:'25 min de footing progressif à {{P}}.', corps:'3 × 15 min à {{P}} avec 3 min de récupération entre chaque. La troisième répétition est la plus difficile. Maintiens l\'allure.', retour:'10 min de footing léger.',
        note:'RPE 8-9/10 · 45 min totales au seuil, ton record absolu. Récupère bien le vendredi.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 2h35', duree:'2h35', pcts:[[65,70]],
        echauff:'', corps:'2h35 à {{P}}. Ta sortie longue la plus longue jusqu\'ici. Gel à 1h, à 1h30 et à 2h. Régularité, respiration, hydratation toutes les 20 min.', retour:'',
        note:'RPE 6/10 · Après cette semaine, la forme monte d\'un cran. Récupère sérieusement.' },
    ]},
  { num:8, phase:'Intensification', charge:'Maximale, pic de charge',
    objectif:'Le pic de ta préparation. La sortie longue la plus longue du plan avec un bloc à allure marathon. C\'est la séance qui préfigure le mieux le jour J.',
    conseil:'C\'est ta semaine de charge maximale. Mange des glucides complexes le soir avant chaque séance. Dors 8 heures. Après cette semaine, l\'intensité diminue progressivement.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Footing long EF', duree:'70 min', pcts:[[70,70],[65,65]],
        echauff:'', corps:'70 min à {{P}}. Long et facile avant la semaine la plus chargée. Si tu te sens fatigué, passe à {{P}}.', retour:'',
        note:'RPE 5/10 · Volume avant la semaine de pic.' },
      { jour:'Jeudi', type:'Tempo', titre:'4 × 12 minutes au seuil', duree:'75 min', pcts:[[65,70],[87,87]],
        echauff:'25 min de footing progressif à {{P}}.', corps:'4 × 12 min à {{P}} avec 3 min de récupération entre chaque. Légèrement plus intense que la semaine 7. La quatrième répétition est la plus difficile.', retour:'10 min de footing léger.',
        note:'RPE 8-9/10 · 48 min au seuil. Ton pic de charge sur cette séance. Mange bien après.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue avec encart allure marathon', duree:'2h50', pcts:[[65,70]],
        echauff:'', corps:'2h à {{P}}, puis 12 km à ton allure objectif marathon ({{OBJ}}), puis retour à l\'allure EF. Gel à 1h, à 1h30, à 2h. Ces 12 km après 2h simulent directement la 2e partie du marathon.', retour:'',
        note:'RPE 6/10 en EF · 8/10 sur les 12 km · Après cette semaine, l\'entraînement dur est terminé.' },
    ]},
  { num:9, phase:'Spécificité marathon', charge:'Élevée, travail à l\'allure objectif',
    objectif:'Les séances s\'alignent sur ton allure de course. Tu répètes littéralement l\'allure que tu devras tenir 42 km le jour J. La spécificité construit la confiance.',
    conseil:'Sur les 3 × 6 km à allure marathon, chaque bloc doit être exactement à {{OBJ}}. Ni plus vite, ni plus lentement. L\'objectif est la répétabilité parfaite de cette allure.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Endurance Fondamentale', duree:'55 min', pcts:[[65,70]],
        echauff:'', corps:'55 min à {{P}}. Volume de base avant la séance spécifique du jeudi. Très facile, jamais fatigant.', retour:'',
        note:'RPE 4/10 · Garde les jambes fraîches pour le jeudi.' },
      { jour:'Jeudi', type:'Spécifique', titre:'3 × 6 km à allure marathon', duree:'75 min',
        echauff:'20 min de footing EF.', corps:'3 × 6 km exactement à ton allure objectif marathon ({{OBJ}}). Récupération 2 min au trot entre chaque. Tu répètes littéralement ton allure de course.', retour:'10 min de footing léger.',
        note:'RPE 7-8/10 · Si {{OBJ}} semble trop facile sur les 3 blocs, ton objectif est peut-être trop prudent.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue avec encart allure marathon', duree:'2h20', pcts:[[65,70]],
        echauff:'', corps:'80 min à {{P}}, puis 10 km à ton allure objectif marathon ({{OBJ}}), puis retour à l\'allure EF pour finir. Gel à 1h et à 1h20.', retour:'',
        note:'RPE 6/10 en EF · 7-8/10 sur les 10 km · Mémorise cette sensation.' },
    ]},
  { num:10, phase:'Spécificité marathon', charge:'Très élevée, pic de spécificité',
    objectif:'Ta dernière vraie semaine de charge à l\'allure course. Les 4 × 6 km + les 15 km en sortie longue t\'apportent la confiance nécessaire pour aborder le jour J sereinement.',
    conseil:'Sur les 4 × 6 km, la quatrième répétition est la plus précieuse : jambes déjà chargées, tu dois maintenir {{OBJ}}/km. C\'est ta répétition générale avant le marathon.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Endurance Fondamentale', duree:'60 min', pcts:[[65,70]],
        echauff:'', corps:'60 min à {{P}}. Volume avant la semaine la plus spécifique du plan. Très facile, allure conversation.', retour:'',
        note:'RPE 4-5/10 · Garde les jambes fraîches pour le jeudi.' },
      { jour:'Jeudi', type:'Spécifique', titre:'4 × 6 km à allure marathon', duree:'90 min',
        echauff:'20 min de footing EF.', corps:'4 × 6 km exactement à ton allure objectif marathon ({{OBJ}}). Récupération 2 min au trot entre chaque. La quatrième est ta répétition générale avant le jour J.', retour:'10 min de footing léger.',
        note:'RPE 7-8/10 · 24 km à l\'allure objectif. Si tu les tiens, tu peux tenir 42 km.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue avec long encart allure marathon', duree:'2h20', pcts:[[65,70]],
        echauff:'', corps:'50 min à {{P}}, puis 15 km à ton allure objectif marathon ({{OBJ}}), puis retour à l\'allure EF pour finir. Gel à 45 min, à 1h15, à 1h45.', retour:'',
        note:'RPE 6/10 en EF · 8/10 sur les 15 km · Après cette séance, les séances dures sont terminées.' },
    ]},
  { num:11, phase:'Consolidation', charge:'Réduite, affûtage',
    objectif:'La consolidation préserve ta forme sans t\'épuiser. Volume réduit, intensité maintenue sur une séance clé. L\'objectif : aborder la semaine de course avec les jambes fraîches.',
    conseil:'Cette semaine allégée laisse les adaptations des 10 semaines s\'installer pleinement. Dors 8 heures, mange bien, évite le stress inutile. La forme arrive maintenant.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Footing léger', duree:'45 min', pcts:[[65,65]],
        echauff:'', corps:'45 min très faciles à {{P}}. Garder les jambes en mouvement sans les fatiguer. Cours au ressenti, sans montre.', retour:'',
        note:'RPE 3/10 · Tu dois finir comme si tu venais de te promener.' },
      { jour:'Jeudi', type:'Tempo', titre:'2 × 12 minutes au seuil, volume réduit', duree:'55 min', pcts:[[65,70],[84,84]],
        echauff:'25 min de footing progressif à {{P}}.', corps:'2 × 12 min à {{P}}. Volume réduit de 50% mais intensité maintenue. Récupération 3 min entre chaque. Termine par 1 km à {{OBJ}}.', retour:'10 min de footing léger.',
        note:'RPE 7/10 · Ces répétitions maintiennent tes sensations sans te fatiguer.' },
      { jour:'Samedi', type:'EF', titre:'Footing de 35 minutes', duree:'35 min', pcts:[[65,65]],
        echauff:'', corps:'35 min à {{P}}. Garde les jambes en mouvement. Cours au ressenti, détendu et régulier. Ton corps se recharge pour le jour J.', retour:'',
        note:'RPE 3/10 · Tu dois finir frais et légèrement dynamisé, jamais fatigué.' },
    ]},
  { num:12, phase:'Semaine de course', charge:'Conserve, tu es prêt',
    objectif:'Arriver au départ reposé, confiant, les jambes fraîches. Tout a été construit en 11 semaines. Il ne reste qu\'à exécuter le plan.',
    conseil:'Pars à {{OBJ}}/km dès le départ. Pas une seconde plus vite. L\'adrénaline va te pousser, résiste. La patience des 8 premiers kilomètres fait les 8 derniers.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing très léger', duree:'35 min', pcts:[[60,65]],
        echauff:'', corps:'35 min à {{P}}. Maintenir la circulation sanguine. Vraiment facile. Si tu te sens fatigué, réduis à 25 minutes.', retour:'',
        note:'RPE 3/10 · Aucun effort. Juste des jambes qui bougent.' },
      { jour:'Mercredi', type:'Fractionné', titre:'6 × 30/30 à allure marathon', duree:'30 min',
        echauff:'15 min de footing EF très léger.',
        corps:'6 × 30 secondes à ton allure objectif marathon ({{OBJ}}) / 30 secondes au trot. Les jambes retrouvent la sensation d\'allure avant le grand jour.',
        retour:'10 min de jogging léger.',
        note:'RPE 6/10 · Ces relances maintiennent les sensations sans t\'épuiser avant le jour J.' },
      { jour:'Samedi', type:'Activation', titre:'Activation J-1 + accélérations', duree:'25 min', pcts:[[60,65]],
        echauff:'', corps:'20 min de trot à {{P}}. Puis 6 accélérations progressives de 80m jusqu\'à ton allure objectif ({{OBJ}}) sur les 20 derniers mètres. Récupère 60 sec en marchant entre chaque.', retour:'',
        note:'Prépare tes affaires ce soir. Visualise les premiers kilomètres à {{OBJ}}/km.' },
      { jour:'Dimanche', type:'Course', titre:'MARATHON', duree:'Jour J',
        echauff:'10-15 min de jogging très léger avant le départ.',
        corps:'KM 1-8 : pars à {{OBJ}}/km exactement. KM 9-21 : régularité absolue, gel à chaque ravitaillement. KM 22-30 : maintiens {{OBJ}}, écoute ton corps. KM 31-35 : raccourcis la foulée, cadence. KM 36-42 : donne absolument tout.',
        retour:'20-30 min de marche. Ravitaillement dans les 30 min.',
        note:'La douleur aux km 30-35 est normale. C\'est là que se gagne un marathon. Tiens bon.' },
    ]},
]
