// Marathon 12 semaines · 3 séances/semaine · Palier Intermédiaire (VMA 13.5 à 18.5)
// 3 séances seulement : chaque session est plus longue. SL jusqu'à 2h45.
// Palette : EF 60min, FP 3 phases, FL-07/12/13/14, T-03/04/05, SP-05, SL jusqu'à 2h45
// {{P}} remplacé séquentiellement · {{OBJ}} = allure objectif marathon (80% VMA)
module.exports = [
  { num:1, phase:'Adaptation', charge:'Légère',
    objectif:'Poser les bases sur 3 séances. Le footing de lundi est déjà long (60 min) : avec 3 séances par semaine, chaque session doit être plus volumineuse pour compenser. La sortie longue démarre à 90 min.',
    conseil:'Sur les 5×1000m, calibre ton allure à 85-90% VMA et sens la régularité. Le dernier doit être aussi rapide que le premier. Si ce n\'est pas le cas, tu es parti trop vite.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Endurance fondamentale 60 minutes', duree:'60 min', pcts:[[65,72]],
        echauff:'', corps:'60 min à {{P}}. Allure conversation, tu dois pouvoir parler en phrases complètes. Avec 3 séances par semaine, chaque footing est plus long que dans un plan à plus de séances.', retour:'',
        note:'RPE 5/10 · 60 min de base dès la semaine 1 — marqueur d\'un plan marathon.' },
      { jour:'Jeudi', type:'Fractionné', titre:'5 × 1000 mètres', duree:'65 min', pcts:[[65,65],[85,90]],
        echauff:'25 min progressif à {{P}}, terminer par 4 accélérations de 80m.', corps:'5 × 1000m à {{P}}. Récupération 2 min au trot entre chaque. Maintiens la même allure sur les 5. Termine par 1 km à allure objectif marathon ({{OBJ}}) pour graver la sensation.', retour:'10 min footing très lent.',
        note:'RPE 7-8/10 · La régularité sur les 5 répétitions vaut plus que la vitesse du premier.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 90 minutes', duree:'90 min', pcts:[[65,72]],
        echauff:'', corps:'90 min à {{P}}. Avec 3 séances, la sortie longue démarre déjà à 90 min — plus longue qu\'un plan à plus de séances. Hydrate-toi toutes les 20-25 min.', retour:'',
        note:'RPE 5/10 · La sortie longue est la séance pilier du plan. Ne négocie pas sa durée.' },
    ]},
  { num:2, phase:'Adaptation', charge:'Légère à modérée',
    objectif:'Introduire le footing progressif — séance spécifique marathon qui développe la sensation d\'allure sur 3 zones. Les 4×2000m apportent la première dose de travail long à allure seuil.',
    conseil:'Sur le footing progressif, la transition entre les zones doit être douce et naturelle. La dernière phase à 80-85% VMA doit être maîtrisée, pas subie.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing progressif 3 phases', duree:'60 min', pcts:[[65,68],[72,75],[80,85]],
        echauff:'10 min trot très lent à {{P}}.', corps:'20 min à {{P}} (aisé) → 20 min à {{P}} (modéré) → 20 min à {{P}} (soutenu). La progression se fait naturellement. Le dernier bloc à allure seuil bas développe ton sens de l\'allure marathon.', retour:'10 min trot très lent.',
        note:'RPE 5-7/10 progressif · Cette séance développe ton sens de l\'allure, clé du marathon.' },
      { jour:'Jeudi', type:'Fractionné', titre:'4 × 2000 mètres — seuil aérobie long', duree:'70 min', pcts:[[65,65],[80,87]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations 80m.', corps:'4 × 2000m à {{P}}. Récupération 3 min au trot entre chaque. Les 2000m sont la distance marathonienne par excellence : plus longue que les 1000m du semi.', retour:'10 min footing très lent.',
        note:'RPE 7-8/10 · Régularité sur les 4 blocs. Le dernier doit être aussi rapide que le premier.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 100 minutes', duree:'100 min', pcts:[[65,72]],
        echauff:'', corps:'100 min à {{P}}. La sortie longue progresse de 10 min. Gère ton allure sur les 30 premières minutes. Hydrate-toi toutes les 20 min.', retour:'',
        note:'RPE 5-6/10 · Avec 3 séances par semaine, la sortie longue monte vite — c\'est voulu.' },
    ]},
  { num:3, phase:'Développement aérobie', charge:'Modérée, premier tempo long',
    objectif:'20 min de seuil en continu — plus spécifique marathon que des blocs courts. Les 3×3000m sont la première séance exclusivement marathon : 9 km à intensité soutenue.',
    conseil:'Sur le 20 min continu, pars légèrement en dessous de ta zone cible les 5 premières minutes. Si tu es encore dans la zone à la 18ème minute, tu as bien géré.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Endurance fondamentale 60 minutes', duree:'60 min', pcts:[[65,72]],
        echauff:'', corps:'60 min à {{P}}. Long, régulier, conversation possible. Ce volume de footing est la base silencieuse du marathon.', retour:'',
        note:'RPE 5/10 · Volume de base. Ne rogne pas sur cette séance.' },
      { jour:'Jeudi', type:'Tempo', titre:'Tempo 20 minutes en continu', duree:'65 min', pcts:[[65,72],[82,88]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations 80m.', corps:'20 min continus à {{P}}. Effort soutenu et régulier sans rupture. Tu dois pouvoir prononcer des mots isolés. 20 min en continu est plus exigeant mentalement que des blocs fractionnés.', retour:'10 min footing très lent.',
        note:'RPE 7-8/10 · 20 min en continu au seuil est le palier clé pour le marathon.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 105 minutes + fin allure marathon', duree:'105 min', pcts:[[65,72]],
        echauff:'', corps:'90 min à {{P}}, puis 15 min à ton allure objectif marathon ({{OBJ}}). Premier contact avec l\'allure cible sur jambes fatiguées — mémorise cette sensation.', retour:'',
        note:'RPE 5-6/10 puis 6-7/10 · La fin à {{OBJ}} est un repère précieux sur ta forme actuelle.' },
    ]},
  { num:4, phase:'Développement aérobie', charge:'Élevée, 3×3000m et cap des 2 heures',
    objectif:'Les 3×3000m sont la séance de développement marathon la plus spécifique : 9 km à allure seuil sur des blocs longs. La sortie longue de 2h avec 20 min à allure marathon constitue un nouveau cap.',
    conseil:'Sur les 3×3000m, pars conservateur sur le premier bloc. Les 3 derniers km du 3ème bloc sont les plus difficiles — c\'est là que se construit la résistance spécifique marathon.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing progressif 3 phases', duree:'60 min', pcts:[[65,68],[72,75],[80,85]],
        echauff:'10 min trot très lent à {{P}}.', corps:'20 min à {{P}} (aisé) → 20 min à {{P}} (modéré) → 20 min à {{P}} (soutenu). La dernière phase à allure seuil bas est la plus utile pour le marathon.', retour:'10 min trot très lent.',
        note:'RPE 5-7/10 progressif · Développe la capacité à changer de zone en course, décisive sur marathon.' },
      { jour:'Jeudi', type:'Fractionné', titre:'3 × 3000 mètres — endurance spécifique marathon', duree:'80 min', pcts:[[65,65],[80,85]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations 80m.', corps:'3 × 3000m à {{P}}. Récupération 4 min au trot entre chaque. 9 km à intensité — c\'est là que se construit l\'endurance spécifique marathon. Régularité sur les 3 blocs.', retour:'10 min footing très lent.',
        note:'RPE 8/10 · Les 3×3000m sont une séance exclusivement marathon. Si tu t\'effondres sur le 3ème, tu es parti trop vite.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 2 heures + 20 min allure marathon', duree:'2h', pcts:[[65,72]],
        echauff:'', corps:'100 min à {{P}}, puis 20 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h de course. Les 20 dernières minutes à allure cible sont le vrai test de la semaine.', retour:'',
        note:'RPE 6/10 puis 7/10 · Si {{OBJ}} semble gérable sur les 20 dernières minutes, c\'est bon signe.' },
    ]},
  { num:5, phase:'Volume marathon', charge:'Élevée, tempo 30 min et SL 2h15',
    objectif:'30 min de tempo en continu — la séance tempo la plus longue et la plus marathonienne du plan. La sortie longue de 2h15 avec 30 min à allure marathon constitue la plus grande charge de volume jusqu\'ici.',
    conseil:'Sur le 30 min continu, gère le départ : pars à la limite basse de la zone (82% VMA). À la 20ème minute tu te sens limité — c\'est normal, c\'est là que l\'adaptation se produit.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Endurance fondamentale 60 minutes', duree:'60 min', pcts:[[65,72]],
        echauff:'', corps:'60 min à {{P}}. Allure confortable, régulier, conversation possible. Volume de base avant la semaine chargée.', retour:'',
        note:'RPE 5/10 · Ne force pas. Le volume de base est aussi important que les séances de qualité.' },
      { jour:'Jeudi', type:'Tempo', titre:'Tempo 30 minutes en continu', duree:'75 min', pcts:[[65,72],[82,88]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations 80m.', corps:'30 min continus à {{P}}. Ta séance tempo de référence : 30 min en continu au seuil est un marqueur de condition physique marathon. Pars à la limite basse de la zone, tiens les 30 min complets.', retour:'10 min footing très lent.',
        note:'RPE 8/10 · 30 min en continu est significativement plus dur mentalement que 2×15 min.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 2h15 avec 30 min allure marathon', duree:'2h15', pcts:[[65,72]],
        echauff:'', corps:'105 min à {{P}}, puis 30 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h et à 1h30. Les 30 dernières minutes à {{OBJ}} simulent le dernier tiers du marathon.', retour:'',
        note:'RPE 6/10 puis 7-8/10 · Avec 3 séances par semaine, la sortie longue porte toute la spécificité marathon.' },
    ]},
  { num:6, phase:'Volume marathon', charge:'Très élevée, 2×5000m et SL 2h30',
    objectif:'La séance 2×5000m est la plus marathon-spécifique du plan. La sortie longue de 2h30 atteint un volume difficile à atteindre avec 3 séances — mais c\'est précisément l\'adaptation recherchée.',
    conseil:'Sur les 2×5000m, les 3 premières minutes du premier bloc doivent sembler trop faciles. Le 5000m est long — ceux qui partent bien finissent fort. Ceux qui partent trop vite craquent à 3500m.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing progressif 3 phases', duree:'60 min', pcts:[[65,68],[72,75],[80,85]],
        echauff:'10 min trot très lent à {{P}}.', corps:'20 min à {{P}} (aisé) → 20 min à {{P}} (modéré) → 20 min à {{P}} (soutenu). Prépare mentalement la semaine très chargée.', retour:'10 min trot très lent.',
        note:'RPE 5-7/10 progressif · Le footing progressif prépare le corps aux changements de rythme en course.' },
      { jour:'Jeudi', type:'Fractionné', titre:'2 × 5000 mètres — long spécifique marathon', duree:'90 min', pcts:[[65,65],[78,83]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations 80m.', corps:'2 × 5000m à {{P}}. Récupération 5 min au trot entre les 2 blocs. 10 km à intensité — le deuxième 5000m est le vrai test. Les 3 premières minutes doivent sembler trop faciles.', retour:'10 min footing très lent.',
        note:'RPE 8/10 · Les 2×5000m sont une séance exclusivement marathon. Réserve-toi pour le deuxième bloc.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 2h30 avec encart allure marathon', duree:'2h30', pcts:[[65,72]],
        echauff:'', corps:'2h à {{P}}, puis 10 km à ton allure objectif marathon ({{OBJ}}). Gel à 1h, à 1h30, à 2h. Les 10 km à {{OBJ}} après 2h de course testent ta capacité à tenir l\'allure en état de fatigue avancée.', retour:'',
        note:'RPE 6/10 en EF · 7-8/10 sur les 10 km · Avec 3 séances, la sortie longue est la séance la plus spécifique du plan.' },
    ]},
  { num:7, phase:'Intensification', charge:'Très élevée, séance progressive complexe',
    objectif:'La séance 3000/5000/3000 progressif est la grande séance marathon du plan : 11 km en 3 blocs à intensité croissante, le dernier plus vite que le premier.',
    conseil:'Sur la séance 3000/5000/3000, le 5000m central doit être tenu régulièrement — ni plus lent ni plus vite. La régularité sur le bloc du milieu est la clé. Le dernier 3000m doit être le plus fort des 3.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Endurance fondamentale 60 minutes', duree:'60 min', pcts:[[65,72]],
        echauff:'', corps:'60 min à {{P}}. Long et facile avant la semaine très chargée. Régulier, hydraté, sans effort excessif.', retour:'',
        note:'RPE 5/10 · Prépare les jambes à la grande séance de jeudi.' },
      { jour:'Jeudi', type:'Fractionné', titre:'3000m / 5000m / 3000m progressif — séance marathon clé', duree:'90 min', pcts:[[65,65],[80,82],[82,85],[85,88]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations 80m.', corps:'3000m à {{P}} → récup 4 min trot → 5000m à {{P}} → récup 5 min trot → 3000m à {{P}}. Progression sur les 3 blocs : tu dois finir le dernier 3000m plus fort que le premier.', retour:'10 min footing très lent.',
        note:'RPE 8-9/10 sur le dernier bloc · La progression sur les 3 blocs est le vrai test de ta condition marathon.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 2h35 avec 15 km allure marathon', duree:'2h35', pcts:[[65,72]],
        echauff:'', corps:'95 min à {{P}}, puis 15 km à ton allure objectif marathon ({{OBJ}}). Gel à 1h, à 1h20, à 1h50. Ces 15 km après 95 min simulent exactement la deuxième moitié d\'un marathon réel.', retour:'',
        note:'RPE 6/10 en EF · 7-8/10 sur les 15 km · Ta répétition la plus fidèle du marathon jusqu\'ici.' },
    ]},
  { num:8, phase:'Intensification', charge:'Maximale, pic de charge du plan',
    objectif:'La semaine la plus chargée du plan. La séance mixte (3×2000m seuil + 2×2000m allure marathon) est la séance de transition la plus spécifique. La sortie longue de 2h45 est la plus longue du plan.',
    conseil:'Sur la séance 5×2000m mixte, les 3 premiers blocs au seuil te fatiguent pour que les 2 derniers à allure marathon soient courus sur jambes chargées. C\'est exactement ce que tu vivras aux km 30-42.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing progressif 3 phases', duree:'60 min', pcts:[[65,68],[72,75],[80,85]],
        echauff:'10 min trot très lent à {{P}}.', corps:'20 min à {{P}} (aisé) → 20 min à {{P}} (modéré) → 20 min à {{P}} (soutenu). Long et progressif avant la semaine de charge maximale.', retour:'10 min trot très lent.',
        note:'RPE 5-7/10 progressif · Prépare les jambes à la grande séance de jeudi.' },
      { jour:'Jeudi', type:'Fractionné', titre:'3×2000m seuil + 2×2000m allure marathon — séance de transition', duree:'85 min', pcts:[[65,65],[82,87],[80,80]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations 80m.', corps:'3 × 2000m à {{P}} (seuil) → récup 3 min trot → 2 × 2000m à ton allure objectif marathon ({{OBJ}}). La transition vers l\'allure marathon sur les 2 derniers blocs — après 6 km de seuil — est l\'élément clé.', retour:'10 min footing très lent.',
        note:'RPE 8-9/10 · Cette séance simule le passage entre effort soutenu et gestion du marathon.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 2h45 avec 15 km allure marathon', duree:'2h45', pcts:[[65,72]],
        echauff:'', corps:'105 min à {{P}}, puis 15 km à ton allure objectif marathon ({{OBJ}}). Gel à 1h, à 1h30, à 2h. Ces 15 km après 1h45 de course sont ta répétition générale. Tiens {{OBJ}} jusqu\'au bout.', retour:'',
        note:'RPE 6/10 en EF · 8/10 sur les 15 km · Après cette semaine, l\'entraînement dur est terminé. Récupère sérieusement.' },
    ]},
  { num:9, phase:'Spécificité marathon', charge:'Élevée, travail à l\'allure objectif',
    objectif:'Les séances s\'alignent sur ton allure de course. Les 3×5km à allure marathon sont la séance de spécificité absolue : 15 km à {{OBJ}} en 3 blocs pour construire la confiance.',
    conseil:'Sur les 3×5km, chaque bloc doit être exactement à {{OBJ}} — pas plus vite, pas plus lentement. La régularité parfaite des 3 blocs prouve que tu maîtrises l\'allure marathon.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Endurance fondamentale 50 minutes', duree:'50 min', pcts:[[65,72]],
        echauff:'', corps:'50 min à {{P}}. Légèrement réduit par rapport aux semaines précédentes — le corps entre dans la phase de spécificité. Facile et régulier.', retour:'',
        note:'RPE 5/10 · Volume légèrement réduit pour préserver les jambes.' },
      { jour:'Jeudi', type:'Spécifique', titre:'3 × 5 km à allure marathon', duree:'90 min', pcts:[[65,65]],
        echauff:'25 min footing EF à {{P}}, finir par 4 accélérations 80m.', corps:'3 × 5 km exactement à ton allure objectif marathon ({{OBJ}}). Récupération 4 min au trot entre chaque. 15 km à l\'allure de ta course — la séance de référence pour valider ton objectif.', retour:'10 min footing léger.',
        note:'RPE 7-8/10 · Si les 3 blocs sont réguliers et {{OBJ}} semble gérable, ton objectif est validé.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 2h15 avec 12 km allure marathon', duree:'2h15', pcts:[[65,72]],
        echauff:'', corps:'80 min à {{P}}, puis 12 km à ton allure objectif marathon ({{OBJ}}). Gel à 1h et à 1h20. Ces 12 km après 80 min de course consolident la mémoire de l\'allure cible.', retour:'',
        note:'RPE 6/10 en EF · 7-8/10 sur les 12 km · Note ton ressenti sur chaque km du bloc marathon.' },
    ]},
  { num:10, phase:'Spécificité marathon', charge:'Très élevée, pic de spécificité',
    objectif:'Ta dernière vraie semaine de charge. Les 2×5000m + les 3×5km en sortie longue constituent la préparation spécifique finale. La confiance se construit cette semaine.',
    conseil:'Sur les 2×5000m, le deuxième bloc est le plus précieux : tu es fatigué et tu dois tenir la même allure. C\'est exactement ce que tu feras aux km 25-35 du marathon.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing progressif 3 phases', duree:'50 min', pcts:[[65,68],[72,75],[80,85]],
        echauff:'10 min trot très lent à {{P}}.', corps:'15 min à {{P}} (aisé) → 15 min à {{P}} (modéré) → 20 min à {{P}} (soutenu). Version légèrement réduite avant la semaine de charge spécifique.', retour:'10 min trot très lent.',
        note:'RPE 5-7/10 progressif · Activation avant les deux séances de référence de la semaine.' },
      { jour:'Jeudi', type:'Fractionné', titre:'2 × 5000 mètres — répétition générale', duree:'90 min', pcts:[[65,65],[78,83]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations 80m.', corps:'2 × 5000m à {{P}}. Récupération 5 min au trot entre les 2 blocs. Le deuxième 5000m est ta répétition générale avant le marathon : jambes chargées, tu dois tenir. Si tu y arrives, tu es prêt.', retour:'10 min footing très lent.',
        note:'RPE 8/10 · Le deuxième 5000m aussi régulier que le premier = signe de préparation solide.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 2h10 avec 10 km allure marathon', duree:'2h10', pcts:[[65,72]],
        echauff:'', corps:'80 min à {{P}}, puis 10 km à ton allure objectif marathon ({{OBJ}}). Gel à 1h et à 1h10. Dernière sortie longue chargée — garde les jambes fraîches pour les deux dernières semaines.', retour:'',
        note:'RPE 6/10 en EF · 7-8/10 sur les 10 km · Après cette sortie, les séances dures sont terminées.' },
    ]},
  { num:11, phase:'Consolidation', charge:'Réduite, affûtage',
    objectif:'La consolidation préserve ta forme sans t\'épuiser. Volume réduit de 45%. Avec 3 séances, la semaine 11 ne comporte que 2 séances de volume réduit et un léger EF.',
    conseil:'Cette semaine allégée laisse les adaptations s\'installer. Dors 8h, mange bien, évite le stress inutile. Ne rajoute pas de séances.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Footing léger 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min très faciles à {{P}}. Garder les jambes en mouvement sans les fatiguer. Sans montre, au ressenti.', retour:'',
        note:'RPE 3/10 · Tu dois finir comme si tu venais de te promener.' },
      { jour:'Jeudi', type:'Tempo', titre:'2 × 15 minutes au seuil — volume réduit', duree:'55 min', pcts:[[65,72],[82,88]],
        echauff:'25 min progressif à {{P}}.', corps:'2 × 15 min à {{P}}. Volume réduit de 50% mais intensité maintenue. Récupération 4 min. Termine par 1 km à ton allure marathon ({{OBJ}}).', retour:'10 min footing très lent.',
        note:'RPE 7/10 · Ces répétitions maintiennent tes sensations sans te fatiguer.' },
      { jour:'Samedi', type:'EF', titre:'Footing de 35 minutes', duree:'35 min', pcts:[[65,65]],
        echauff:'', corps:'35 min à {{P}}. Garde les jambes en mouvement. Cours au ressenti, détendu. Inclus 4 à 6 accélérations de 60m à allure marathon pour réveiller les sensations.', retour:'',
        note:'RPE 3/10 · Tu dois finir frais et légèrement dynamisé, jamais fatigué.' },
    ]},
  { num:12, phase:'Semaine de course', charge:'Conserve, tu es prêt',
    objectif:'Arriver au départ reposé, confiant, les jambes fraîches. 11 semaines de travail ont été faites. Il ne reste qu\'à exécuter.',
    conseil:'Pars à {{OBJ}}/km dès le départ. L\'adrénaline va te pousser à aller plus vite — résiste. Chaque seconde gagnée trop tôt peut coûter une minute à la fin.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing très léger 30 minutes', duree:'30 min', pcts:[[60,65]],
        echauff:'', corps:'30 min à {{P}}. Maintenir la circulation sanguine. Vraiment facile. Si tu te sens fatigué, réduis à 20 minutes.', retour:'',
        note:'RPE 3/10 · Aucun effort. Juste des jambes qui bougent.' },
      { jour:'Mercredi', type:'Fractionné', titre:'6 × 30/30 à allure marathon', duree:'30 min',
        echauff:'15 min de footing très léger.',
        corps:'6 × 30 secondes à ton allure objectif marathon ({{OBJ}}) / 30 secondes au trot. Les jambes retrouvent la sensation d\'allure avant le grand jour.',
        retour:'10 min de jogging léger.',
        note:'RPE 6/10 · Ces relances maintiennent les sensations sans t\'épuiser.' },
      { jour:'Samedi', type:'Activation', titre:'Activation J-1 + accélérations', duree:'30 min', pcts:[[60,65]],
        echauff:'', corps:'20 min de trot à {{P}}. Puis 6 à 8 accélérations progressives de 80m jusqu\'à ton allure objectif ({{OBJ}}) sur les 20 derniers mètres. Récupère 60 sec en marchant entre chaque.', retour:'',
        note:'Prépare tes affaires ce soir. Visualise les premiers kilomètres à {{OBJ}}/km.' },
      { jour:'Dimanche', type:'Course', titre:'MARATHON', duree:'Jour J',
        echauff:'10-15 min de jogging très léger avant le départ.',
        corps:'KM 1-8 : pars à {{OBJ}}/km exactement. KM 9-21 : régularité absolue, gel à chaque ravitaillement. KM 22-30 : maintiens {{OBJ}}, écoute ton corps. KM 31-35 : raccourcis la foulée, garde les bras actifs. KM 36-42 : donne absolument tout.',
        retour:'20-30 min de marche. Ravitaillement dans les 30 min.',
        note:'La douleur aux km 30-35 est normale. C\'est là que se gagne un marathon. Tiens bon.' },
    ]},
]
