// Trame 4 séances/semaine — Ebook Semi-marathon, 12 semaines · Palier Intermédiaire.
// {{P}} remplacé séquentiellement sur la queue de pcts, {{OBJ}} = allure objectif semi (87% VMA).
module.exports = [
  { num:1, phase:'Adaptation', charge:'Légère',
    objectif:'Prendre ses repères sur les allures du plan et installer le rythme sur 4 séances. Aucune pression de performance, juste finir chaque séance en se sentant bien.',
    conseil:'Sur les 6 × 800m, l\'allure doit rester régulière du premier au dernier. Cette séance est volontairement courte pour t\'habituer à l\'effort fractionné sans accumulation.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Endurance Fondamentale', duree:'45 min', pcts:[[65,70]],
        echauff:'', corps:'Course continue à {{P}}. Allure conversation, tu dois pouvoir parler en phrases complètes. Régulier et relâché.', retour:'',
        note:'RPE 4-5/10 · Finis en te sentant bien, comme si tu pouvais encore courir.' },
      { jour:'Jeudi', type:'Fractionné', titre:'6 × 800 mètres', duree:'60 min', pcts:[[65,65],[88,92]],
        echauff:'20 min de footing EF à {{P}}.', corps:'6 × 800m à {{P}}. Effort soutenu mais maîtrisé. Récupération 90 sec au trot entre chaque. Maintiens la même allure du premier au dernier.', retour:'10 min de jogging léger.',
        note:'RPE 7-8/10 · Ces 800m construisent ta résistance à l\'effort. Garde la récupération complète.' },
      { jour:'Samedi', type:'EF', titre:'Footing de récupération', duree:'35 min', pcts:[[60,65]],
        echauff:'', corps:'35 min à {{P}}. Active la circulation et prépare la sortie longue du lendemain. Cours vraiment détendu, aucun effort.', retour:'',
        note:'RPE 3/10 · Vraiment facile, aucun effort.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue', duree:'65 min', pcts:[[65,70]],
        echauff:'', corps:'Course continue à {{P}} pendant 65 minutes. Hydrate-toi. Cette sortie longue est la pierre angulaire de ta préparation au semi. Elle se construit semaine après semaine.', retour:'',
        note:'RPE 5/10 · Régulier et contrôlé. La durée prime sur l\'allure.' },
    ]},
  { num:2, phase:'Adaptation', charge:'Légère à modérée',
    objectif:'Confirmer les bases. Deux répétitions de plus sur le fractionné, volume légèrement augmenté sur la sortie longue. Le plan doit commencer à sembler naturel.',
    conseil:'Sur les 8 × 800m, maintiens la même allure sur les 8 répétitions. Si les dernières sont nettement plus lentes, tu es parti trop vite.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Endurance Fondamentale', duree:'50 min', pcts:[[65,70]],
        echauff:'', corps:'50 min à {{P}}. Même principe que la semaine passée. Allure conversation, régulière du début à la fin.', retour:'',
        note:'RPE 4-5/10 · Léger et régulier.' },
      { jour:'Jeudi', type:'Fractionné', titre:'8 × 800 mètres', duree:'65 min', pcts:[[65,65],[88,92]],
        echauff:'25 min de footing EF à {{P}}.', corps:'8 × 800m à {{P}}. Deux répétitions de plus. Récupération 90 sec au trot. Maintiens la même allure sur les 8.', retour:'10 min de footing léger.',
        note:'RPE 7-8/10 · La régularité est plus importante que la vitesse maximale.' },
      { jour:'Samedi', type:'EF', titre:'Footing de récupération', duree:'35 min', pcts:[[60,65]],
        echauff:'', corps:'35 min à {{P}}. Active la circulation et prépare la sortie longue du lendemain. Cours très détendu.', retour:'',
        note:'RPE 3/10 · Vraiment facile.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue', duree:'70 min', pcts:[[65,70]],
        echauff:'', corps:'70 min à {{P}}. La sortie longue augmente de 5 minutes par rapport à la semaine dernière. Continue à bâtir ta base aérobie. Hydrate-toi toutes les 25 min.', retour:'',
        note:'RPE 5/10 · La sortie longue est la séance la plus importante du plan semi-marathon.' },
    ]},
  { num:3, phase:'Développement aérobie', charge:'Modérée, première séance tempo',
    objectif:'Introduire le travail au seuil anaérobie. Le tempo est la séance la plus importante pour le semi-marathon : il repousse ta limite lactique et détermine l\'allure que tu peux tenir sur 21km.',
    conseil:'Sur le tempo, tu dois pouvoir prononcer des mots isolés mais pas tenir une conversation. C\'est la zone parfaite : difficile mais contrôlée. Difficile mais soutenable.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Footing long EF', duree:'55 min', pcts:[[70,70],[65,65]],
        echauff:'', corps:'55 min à {{P}}. Long et facile avant la semaine à deux séances de qualité. Travaille ta technique : légère bascule vers l\'avant, attaque milieu du pied. Si tu te sens fatigué, passe à {{P}}.', retour:'',
        note:'RPE 5/10 · Ce footing long est la base de ton volume hebdomadaire.' },
      { jour:'Mercredi', type:'Tempo', titre:'Tempo continu, 18 minutes', duree:'55 min', pcts:[[65,70],[84,84]],
        echauff:'25 min de footing progressif à {{P}}.', corps:'18 minutes continues à {{P}}. Première séance au seuil anaérobie. Difficile mais tenable sur toute la durée. Tu peux prononcer des mots mais pas tenir une conversation.', retour:'12 min de jogging très lent.',
        note:'RPE 7-8/10 · Cette zone développe directement ta capacité à tenir l\'allure sur 21km.' },
      { jour:'Vendredi', type:'Fractionné', titre:'4 × 1500 mètres', duree:'65 min', pcts:[[65,65],[83,86]],
        echauff:'25 min de footing EF à {{P}}.', corps:'4 × 1500m à {{P}}. Intervalles longs pour développer ta résistance. Récupération 2 min au trot. Termine par 1 km à ton allure objectif semi-marathon ({{OBJ}}), pour sentir l\'allure.', retour:'10 min de footing léger.',
        note:'RPE 7-8/10 · Ces 1500m sont plus longs que les 800m précédents. Ton corps est prêt.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue', duree:'80 min', pcts:[[65,70]],
        echauff:'', corps:'80 min à {{P}}. Régulier, hydraté, concentré sur ta foulée. Cette semaine est chargée — la sortie longue reste volontairement facile en allure.', retour:'',
        note:'RPE 5-6/10 · La fatigue de fin de semaine est normale. Récupère bien.' },
    ]},
  { num:4, phase:'Développement aérobie', charge:'Élevée, consolidation du travail au seuil',
    objectif:'Consolider le travail de seuil et allonger la sortie longue. La deuxième semaine avec deux séances de qualité — les allures commencent à se naturaliser.',
    conseil:'Sur les 2 × 15 min, la deuxième répétition est intentionnellement plus difficile car les jambes sont déjà chargées. Ne ralentis pas — c\'est ce qui te fait progresser.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Footing long EF', duree:'60 min', pcts:[[70,70],[65,65]],
        echauff:'', corps:'60 min à {{P}}. Long, régulier, facile. Volume avant la semaine chargée. Si tu te sens fatigué, passe à {{P}}.', retour:'',
        note:'RPE 5/10 · Si tu te sens fatigué, passe à la version lente.' },
      { jour:'Mercredi', type:'Tempo', titre:'2 × 15 minutes au seuil', duree:'60 min', pcts:[[65,70],[85,85]],
        echauff:'25 min de footing progressif EF.', corps:'2 × 15 min à {{P}} avec 3 min de récupération entre chaque. La deuxième répétition se termine fatigué — c\'est voulu, ne ralentis pas.', retour:'10 min de footing léger.',
        note:'RPE 7-8/10 · 30 min totales au seuil, la charge la plus importante de ces 4 premières semaines.' },
      { jour:'Vendredi', type:'Fractionné', titre:'5 × 1500 mètres', duree:'70 min', pcts:[[65,65],[84,87]],
        echauff:'25 min de footing EF.', corps:'5 × 1500m à {{P}}. Une répétition de plus que la semaine dernière, allure légèrement plus haute. Récupération 2 min au trot. Termine par 1 km à ton allure objectif semi ({{OBJ}}).', retour:'10 min de footing léger.',
        note:'RPE 8/10 · C\'est normal si les dernières sont dures, tu construis ta résistance.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue avec fin à allure semi', duree:'85 min', pcts:[[65,70]],
        echauff:'', corps:'75 min à {{P}}, puis les 10 dernières minutes à ton allure objectif semi-marathon ({{OBJ}}). Tu apprends à finir sur la bonne allure quand les jambes sont déjà chargées.', retour:'',
        note:'RPE 6/10 puis 7/10 · Mémorise cette sensation de l\'allure semi sur des jambes fatiguées.' },
    ]},
  { num:5, phase:'Volume', charge:'Élevée, pic de volume',
    objectif:'Le volume hebdomadaire atteint son plus haut niveau. La sortie longue de 90 min est un premier cap important — beaucoup de coureurs préparant un semi ne la font jamais. Toi si.',
    conseil:'Sur les 3 × 12 min au seuil, chaque répétition doit être exactement à la même allure. La régularité est le signe que tu es bien dans la zone.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Endurance Fondamentale', duree:'50 min', pcts:[[65,70]],
        echauff:'', corps:'50 min à {{P}}. Volume de base avant la séance tempo du jeudi. Très facile, jamais fatigant.', retour:'',
        note:'RPE 4/10 · Garde les jambes fraîches pour le jeudi.' },
      { jour:'Jeudi', type:'Tempo', titre:'3 × 12 minutes au seuil', duree:'65 min', pcts:[[65,70],[85,85]],
        echauff:'25 min de footing progressif à {{P}}.', corps:'3 × 12 min à {{P}} avec 3 min de récupération entre chaque. La troisième répétition est la plus difficile, maintiens l\'allure.', retour:'10 min de footing léger.',
        note:'RPE 8/10 · 36 min totales au seuil, ton record depuis le début du plan.' },
      { jour:'Samedi', type:'EF', titre:'Footing de récupération', duree:'40 min', pcts:[[60,65]],
        echauff:'', corps:'40 min à {{P}}. Fondamentale avant la grande sortie longue du dimanche. Cours vraiment détendu.', retour:'',
        note:'RPE 3/10 · Cette séance te fait récupérer plus vite.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 90 minutes', duree:'90 min', pcts:[[65,70]],
        echauff:'', corps:'90 min à {{P}}. Ton premier cap à 90 minutes. Régularité, respiration, hydratation toutes les 20-25 min. Emporte de l\'eau.', retour:'',
        note:'RPE 5-6/10 · À 90 min, tu commences à toucher aux exigences physiques du semi-marathon.' },
    ]},
  { num:6, phase:'Volume', charge:'Très élevée, sortie longue avec encart allure semi',
    objectif:'La sortie longue de 100 minutes avec un bloc à allure semi est la répétition la plus précieuse du plan. Elle te donne une référence précise sur ta capacité à tenir {{OBJ}} en course.',
    conseil:'Sur les 5 km à allure semi au sein de la sortie longue, l\'allure {{OBJ}} doit se sentir soutenable mais difficile. Si c\'est trop facile, ton objectif est peut-être trop prudent.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Footing long EF', duree:'55 min', pcts:[[70,70],[65,65]],
        echauff:'', corps:'55 min à {{P}}. Long et facile avant la semaine très chargée. Si tu te sens fatigué, passe à {{P}}.', retour:'',
        note:'RPE 5/10 · Ce footing long est ta récupération active.' },
      { jour:'Jeudi', type:'Tempo', titre:'2 × 20 minutes au seuil', duree:'70 min', pcts:[[65,70],[86,86]],
        echauff:'25 min de footing progressif à {{P}}.', corps:'2 × 20 min à {{P}} avec 3 min de récupération entre chaque. Difficile mais tenable. 40 min totales au seuil — ta séance tempo la plus longue à ce jour.', retour:'10 min de footing léger.',
        note:'RPE 8/10 · 40 min au seuil, une charge sérieuse. Récupère bien les jours suivants.' },
      { jour:'Samedi', type:'EF', titre:'Footing de récupération', duree:'40 min', pcts:[[60,65]],
        echauff:'', corps:'40 min à {{P}}. Deux séances intenses cette semaine — ce footing reste léger pour ne pas accumuler de fatigue avant la sortie longue.', retour:'',
        note:'RPE 3/10 · Le footing de récupération est aussi important que les séances intenses.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue avec encart allure semi', duree:'100 min', pcts:[[65,70]],
        echauff:'', corps:'80 min à {{P}}, puis 5 km à ton allure objectif semi-marathon ({{OBJ}}), puis retour à l\'allure EF pour finir. Cet encart t\'apprend à tenir l\'allure quand les jambes sont déjà sollicitées.', retour:'',
        note:'RPE 6/10 en EF · 7-8/10 sur les 5 km · Note ton allure, c\'est un indicateur fiable de ta forme.' },
    ]},
  { num:7, phase:'Intensification', charge:'Très élevée, tempo et longs intervalles',
    objectif:'La charge atteint son niveau le plus difficile. Tempo et 1000m en même semaine + sortie longue maximale : la combinaison seuil + vitesse + durée est ce qui te rapproche le plus du jour J.',
    conseil:'Sur les 3 × 15 min, l\'allure doit être tenue du début à la fin des trois répétitions. Si tu dois lever le pied en fin de troisième répétition, recalibre pour la prochaine fois.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Footing long EF', duree:'60 min', pcts:[[70,70],[65,65]],
        echauff:'', corps:'60 min à {{P}}. Long et facile avant la semaine très chargée. Si tu te sens fatigué, passe à {{P}}.', retour:'',
        note:'RPE 5/10 · Ce footing prépare les séances du mercredi et vendredi.' },
      { jour:'Mercredi', type:'Tempo', titre:'3 × 15 minutes au seuil', duree:'70 min', pcts:[[65,70],[86,86]],
        echauff:'25 min de footing progressif EF.', corps:'3 × 15 min à {{P}} avec 3 min de récupération entre chaque. La troisième répétition est la plus difficile, maintiens l\'allure.', retour:'10 min de footing léger.',
        note:'RPE 8-9/10 · 45 min totales au seuil, ton record absolu. Récupère bien le jeudi.' },
      { jour:'Vendredi', type:'Fractionné', titre:'6 × 1000 mètres', duree:'70 min', pcts:[[65,65],[88,92]],
        echauff:'25 min de footing EF à {{P}}.', corps:'6 × 1000m à {{P}}. Allure plus haute que sur les 1500m des semaines précédentes. Récupération 2 min au trot.', retour:'10 min de footing léger.',
        note:'RPE 8/10 · Ces 1000m plus rapides développent ta VMA tout en préservant ton endurance.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 105 minutes', duree:'105 min', pcts:[[65,70]],
        echauff:'', corps:'105 min à {{P}}. Ta sortie longue la plus longue à ce jour. Régularité, respiration, hydratation toutes les 20 min.', retour:'',
        note:'RPE 6/10 · Après cette semaine, la forme monte d\'un cran.' },
    ]},
  { num:8, phase:'Intensification', charge:'Maximale, pic de charge du plan',
    objectif:'Le pic de ta préparation. Sortie longue la plus longue du plan avec un bloc à allure semi : c\'est le test le plus précis de ta forme avant de commencer la spécificité.',
    conseil:'C\'est ta semaine de charge maximale. N\'ajoute rien. Mange des glucides les soirs avant les séances clés. Dors 8 heures. Hydrate-toi toute la journée.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Footing long EF', duree:'60 min', pcts:[[70,70],[65,65]],
        echauff:'', corps:'60 min à {{P}}. Long et facile avant la semaine la plus chargée du plan. Si tu te sens fatigué, passe à {{P}}.', retour:'',
        note:'RPE 5/10 · Ce footing long est ta préparation aux deux séances dures de la semaine.' },
      { jour:'Mercredi', type:'Tempo', titre:'4 × 12 minutes au seuil', duree:'75 min', pcts:[[65,70],[87,87]],
        echauff:'25 min de footing progressif EF.', corps:'4 × 12 min à {{P}} avec 3 min de récupération entre chaque. Légèrement plus intense que la semaine 7. La quatrième répétition est la plus difficile, maintiens l\'allure.', retour:'10 min de footing léger.',
        note:'RPE 8-9/10 · 48 min au seuil, ton pic de charge sur cette séance.' },
      { jour:'Vendredi', type:'Fractionné', titre:'8 × 1000 mètres', duree:'80 min', pcts:[[65,65],[88,92]],
        echauff:'25 min de footing EF à {{P}}.', corps:'8 × 1000m à {{P}}. Deux répétitions de plus que la semaine dernière. Récupération 2 min au trot. Maintiens la même allure sur les 8.', retour:'10 min de footing léger.',
        note:'RPE 8-9/10 · C\'est normal si les dernières sont dures, tu es en semaine de charge maximale.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue avec encart allure semi', duree:'110 min', pcts:[[65,70]],
        echauff:'', corps:'90 min à {{P}}, puis 8 km à ton allure objectif semi-marathon ({{OBJ}}), puis retour à l\'allure EF. Les 8 km à allure objectif après 90 min de course te préparent directement à la fin du semi.', retour:'',
        note:'RPE 6/10 en EF · 8/10 sur les 8 km · Après cette semaine, l\'entraînement dur est terminé.' },
    ]},
  { num:9, phase:'Spécificité semi', charge:'Élevée, travail à l\'allure objectif',
    objectif:'Les séances s\'alignent sur ton allure de course. Tu répètes littéralement l\'allure que tu devras tenir 21km le jour J. La spécificité est ce qui fait la différence entre finir et performer.',
    conseil:'Sur les 3 × 5 km, chaque répétition doit être exactement à {{OBJ}}. Ni plus vite, ni plus lentement. L\'objectif est la répétabilité de cette allure.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Endurance Fondamentale', duree:'50 min', pcts:[[65,70]],
        echauff:'', corps:'50 min à {{P}}. Volume de base avant la séance spécifique du jeudi. Très facile, jamais fatigant.', retour:'',
        note:'RPE 4/10 · Garde les jambes fraîches pour le jeudi.' },
      { jour:'Jeudi', type:'Spécifique', titre:'3 × 5 km à allure objectif', duree:'70 min',
        echauff:'25 min de footing EF.', corps:'3 × 5 km exactement à ton allure objectif semi-marathon ({{OBJ}}). Récupération 2 min au trot entre chaque. Tu répètes littéralement ton allure de course, avec des jambes fraîches.', retour:'10 min de footing léger.',
        note:'RPE 7-8/10 · Si {{OBJ}} te semble trop facile sur les 3, ton objectif est peut-être trop prudent.' },
      { jour:'Samedi', type:'EF', titre:'Footing de récupération', duree:'40 min', pcts:[[60,65]],
        echauff:'', corps:'40 min à {{P}}. Séance chargée cette semaine — ce footing absorbe la charge et prépare la sortie longue du lendemain.', retour:'',
        note:'RPE 3/10 · Facile, sans exception.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue avec encart allure semi', duree:'90 min', pcts:[[65,70]],
        echauff:'', corps:'70 min à {{P}}, puis 8 km à ton allure objectif semi-marathon ({{OBJ}}), puis retour à l\'allure EF. Ces 8 km à allure semi sur des jambes chargées reproduisent exactement la 2e partie du semi le jour J.', retour:'',
        note:'RPE 6/10 en EF · 7-8/10 sur les 8 km · Mémorise cette sensation, tu la retrouveras en course.' },
    ]},
  { num:10, phase:'Spécificité semi', charge:'Très élevée, pic de spécificité',
    objectif:'Ta dernière vraie semaine de charge à l\'allure course. Les 4 × 5 km + le bloc de 10 km sur la sortie longue t\'apportent la confiance nécessaire pour aborder le jour J.',
    conseil:'Sur les 4 × 5 km, la quatrième répétition est la plus précieuse : elle simule la fin de course avec des jambes chargées. Maintiens {{OBJ}} coûte que coûte sur les 5 derniers km.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Endurance Fondamentale', duree:'55 min', pcts:[[65,70]],
        echauff:'', corps:'55 min à {{P}}. Volume avant la semaine la plus spécifique du plan. Très facile.', retour:'',
        note:'RPE 4-5/10 · Garde les jambes fraîches pour le jeudi.' },
      { jour:'Jeudi', type:'Spécifique', titre:'4 × 5 km à allure objectif', duree:'80 min',
        echauff:'25 min de footing EF.', corps:'4 × 5 km exactement à ton allure objectif semi-marathon ({{OBJ}}). Récupération 2 min au trot entre chaque. Une répétition de plus qu\'en semaine 9 — la quatrième est ta répétition générale.', retour:'10 min de footing léger.',
        note:'RPE 7-8/10 · 20 km au total à l\'allure objectif. Si tu les tiens sur 4, tu peux tenir 21km le jour J.' },
      { jour:'Samedi', type:'EF', titre:'Footing de récupération', duree:'40 min', pcts:[[60,65]],
        echauff:'', corps:'40 min à {{P}}. Indispensable pour absorber la charge des deux séances de qualité. Ton corps s\'adapte à un niveau supérieur.', retour:'',
        note:'RPE 3/10 · Le footing de récupération est aussi important que les séances intenses.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue avec encart allure semi', duree:'95 min', pcts:[[65,70]],
        echauff:'', corps:'70 min à {{P}}, puis 10 km à ton allure objectif semi-marathon ({{OBJ}}). Ta dernière sortie longue spécifique. Ce bloc de 10 km à allure objectif après 70 min de course simule directement la 2e partie du semi.', retour:'',
        note:'RPE 6/10 en EF · 8/10 sur les 10 km · Après cette séance, les séances dures sont terminées.' },
    ]},
  { num:11, phase:'Consolidation', charge:'Réduite, affûtage',
    objectif:'La consolidation préserve ta forme sans t\'épuiser. Volume réduit de 40%, intensité maintenue sur une séance clé. L\'objectif : aborder la semaine de course avec les jambes fraîches.',
    conseil:'Cette semaine allégée laisse les adaptations des 10 semaines de travail s\'installer pleinement. Dors 8 heures, mange bien, évite le stress inutile. La semaine de course sera encore plus légère.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Footing léger', duree:'45 min', pcts:[[65,65]],
        echauff:'', corps:'45 min très faciles à {{P}}. Garder les jambes en mouvement sans les fatiguer. Cours au ressenti, sans montre. Profite de cette semaine allégée.', retour:'',
        note:'RPE 3/10 · Tu dois finir comme si tu venais de te promener.' },
      { jour:'Jeudi', type:'Tempo', titre:'2 × 12 minutes au seuil, volume réduit', duree:'55 min', pcts:[[65,70],[84,84]],
        echauff:'25 min de footing progressif EF.', corps:'2 × 12 min à {{P}}. Volume réduit de 50% mais intensité maintenue. Récupération 3 min entre chaque. Termine par 1 km à ton allure objectif semi-marathon ({{OBJ}}), pour garder la sensation fraîche en tête.', retour:'10 min de footing léger.',
        note:'RPE 7/10 · Ces répétitions maintiennent tes sensations sans te fatiguer.' },
      { jour:'Samedi', type:'EF', titre:'Footing de 35 minutes', duree:'35 min', pcts:[[65,65]],
        echauff:'', corps:'35 min à {{P}}. Garde les jambes en mouvement sans les fatiguer. Cours au ressenti, détendu et régulier. Ton corps se recharge pour le jour J.', retour:'',
        note:'RPE 3/10 · Tu dois finir frais et légèrement dynamisé, jamais fatigué.' },
    ]},
  { num:12, phase:'Semaine de course', charge:'Conserve, tu es prêt',
    objectif:'Rien ne se gagne à l\'entraînement cette semaine. L\'objectif unique : arriver au départ reposé, confiant, les jambes fraîches. Tout a été construit — il ne reste qu\'à exécuter.',
    conseil:'Fais confiance à tes 11 semaines de travail. Pars à ton allure objectif {{OBJ}} dès le départ, ne te laisse pas griser par l\'adrénaline. La patience des 5 premiers kilomètres fait les 5 derniers.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing très léger', duree:'35 min', pcts:[[60,65]],
        echauff:'', corps:'35 min à {{P}}. Maintenir la circulation sanguine. Vraiment facile, si tu te sens fatigué, réduis à 25 minutes.', retour:'',
        note:'RPE 3/10 · Aucun effort. Juste des jambes qui bougent.' },
      { jour:'Mercredi', type:'Fractionné', titre:'6 × 30/30 à allure objectif', duree:'30 min',
        echauff:'15 min de footing EF très léger.',
        corps:'6 × 30 secondes à ton allure objectif semi ({{OBJ}}) / 30 secondes au trot. Effort court et ciblé, les jambes retrouvent la sensation d\'allure avant la course.',
        retour:'10 min de jogging léger.',
        note:'RPE 6/10 · Ces relances maintiennent les sensations sans t\'épuiser avant le jour J.' },
      { jour:'Samedi', type:'Activation', titre:'Activation J-1 + accélérations', duree:'30 min', pcts:[[60,65]],
        echauff:'', corps:'20 min de trot à {{P}}. Puis 6 à 8 accélérations progressives de 80m, démarre doucement et accélère jusqu\'à passer sous ton allure objectif {{OBJ}} sur les 20 derniers mètres. Récupère 60 sec en marchant entre chaque.', retour:'',
        note:'Ces accélérations réveillent tes fibres rapides. Efficace la veille d\'une course.' },
      { jour:'Dimanche', type:'Course', titre:'COURSE SEMI-MARATHON', duree:'Jour J',
        echauff:'10 min de jogging léger avant le départ.', corps:'KM 1-5 : pars à ton allure objectif {{OBJ}}, ne pars surtout pas plus vite. KM 6-15 : maintiens {{OBJ}} exactement, régularité absolue, hydrate-toi à chaque ravitaillement. KM 16-18 : évaluation honnête — si tu as des réserves, accélère légèrement. KM 19-21 : donne absolument tout.', retour:'15-20 min de marche. Ravitaillement dans les 30 min.',
        note:'Les sensations difficiles aux km 14-17 sont normales. C\'est là que se gagne un semi-marathon.' },
    ]},
]
