// Trame 3 séances/semaine, Ebook Semi-marathon, 12 semaines · Palier Intermédiaire.
// Une seule séance de qualité par semaine (Jeudi). Semaine 12 = 4 séances (course).
module.exports = [
  { num:1, phase:'Adaptation', charge:'Légère',
    objectif:'Prendre ses repères sur les allures du plan sur 3 séances. Aucune pression de performance, juste finir chaque séance en se sentant bien.',
    conseil:'Sur les 6 × 800m, maintiens une allure régulière. Ce n\'est pas encore l\'heure de pousser fort. La récupération complète entre chaque est non négociable.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Endurance Fondamentale', duree:'45 min', pcts:[[65,70]],
        echauff:'', corps:'Course continue à {{P}}. Allure conversation, tu dois pouvoir parler en phrases complètes. Régulier et relâché.', retour:'',
        note:'RPE 4-5/10 · Finis en te sentant bien, comme si tu pouvais encore courir.' },
      { jour:'Jeudi', type:'Fractionné', titre:'6 × 800 mètres', duree:'60 min', pcts:[[65,65],[88,92]],
        echauff:'20 min de footing EF à {{P}}.', corps:'6 × 800m à {{P}}. Effort soutenu mais maîtrisé. Récupération 90 sec au trot entre chaque. Maintiens la même allure du premier au dernier.', retour:'10 min de jogging léger.',
        note:'RPE 7-8/10 · Ces 800m construisent ta résistance à l\'effort.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue', duree:'65 min', pcts:[[65,70]],
        echauff:'', corps:'Course continue à {{P}} pendant 65 minutes. Hydrate-toi. La sortie longue est la séance la plus importante de la semaine dans ce plan.', retour:'',
        note:'RPE 5/10 · Régulier et contrôlé. La durée prime sur l\'allure.' },
    ]},
  { num:2, phase:'Adaptation', charge:'Légère à modérée',
    objectif:'Confirmer les bases. Deux répétitions de plus, sortie longue légèrement allongée.',
    conseil:'Sur les 8 × 800m, maintiens la même allure sur les 8. Si les dernières sont nettement plus lentes, tu es parti trop vite.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Endurance Fondamentale', duree:'50 min', pcts:[[65,70]],
        echauff:'', corps:'50 min à {{P}}. Allure conversation, régulière du début à la fin.', retour:'',
        note:'RPE 4-5/10 · Léger et régulier.' },
      { jour:'Jeudi', type:'Fractionné', titre:'8 × 800 mètres', duree:'65 min', pcts:[[65,65],[88,92]],
        echauff:'25 min de footing EF à {{P}}.', corps:'8 × 800m à {{P}}. Deux répétitions de plus. Récupération 90 sec au trot. Maintiens la même allure sur les 8.', retour:'10 min de footing léger.',
        note:'RPE 7-8/10 · La régularité est plus importante que la vitesse maximale.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue', duree:'70 min', pcts:[[65,70]],
        echauff:'', corps:'70 min à {{P}}. La sortie longue augmente de 5 minutes. Continue à bâtir ta base aérobie. Hydrate-toi toutes les 25 min.', retour:'',
        note:'RPE 5/10 · La sortie longue est la séance la plus importante du plan semi-marathon.' },
    ]},
  { num:3, phase:'Développement aérobie', charge:'Modérée, première séance tempo',
    objectif:'Introduire le travail au seuil anaérobie. Sur 3 séances, le tempo remplace le fractionné du jeudi, c\'est la séance prioritaire pour progresser sur semi.',
    conseil:'Sur le tempo, tu dois pouvoir prononcer des mots isolés mais pas tenir une conversation. La régularité de l\'allure prime sur la vitesse.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Footing long EF', duree:'55 min', pcts:[[70,70],[65,65]],
        echauff:'', corps:'55 min à {{P}}. Long et facile avant le tempo du jeudi. Si tu te sens fatigué, passe à {{P}}.', retour:'',
        note:'RPE 5/10 · Ce footing long est la base de ton volume hebdomadaire.' },
      { jour:'Jeudi', type:'Tempo', titre:'Tempo continu, 22 minutes', duree:'60 min', pcts:[[65,70],[84,84]],
        echauff:'25 min de footing progressif à {{P}}.', corps:'22 minutes continues à {{P}}. Légèrement plus long que la version 4 séances car c\'est ta seule séance de qualité de la semaine. Tu dois pouvoir prononcer des mots mais pas tenir une conversation.', retour:'13 min de jogging très lent.',
        note:'RPE 7-8/10 · Cette zone développe directement ta capacité à tenir l\'allure sur 21km.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue', duree:'80 min', pcts:[[65,70]],
        echauff:'', corps:'80 min à {{P}}. Régulier, hydraté, concentré sur ta foulée.', retour:'',
        note:'RPE 5-6/10 · La fatigue de fin de semaine est normale. Récupère bien.' },
    ]},
  { num:4, phase:'Développement aérobie', charge:'Élevée, consolidation du tempo',
    objectif:'Consolider le travail de seuil et allonger la sortie longue. Les 2 × 18 min sont plus longues que la version 4 séances car tu n\'as pas de fractionné cette semaine.',
    conseil:'Sur les 2 × 18 min, la deuxième répétition est intentionnellement plus difficile. Ne ralentis pas, c\'est ce qui te fait progresser.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Footing long EF', duree:'60 min', pcts:[[70,70],[65,65]],
        echauff:'', corps:'60 min à {{P}}. Long, régulier, facile. Si tu te sens fatigué, passe à {{P}}.', retour:'',
        note:'RPE 5/10 · Si tu te sens fatigué, passe à la version lente.' },
      { jour:'Jeudi', type:'Tempo', titre:'2 × 18 minutes au seuil', duree:'65 min', pcts:[[65,70],[85,85]],
        echauff:'25 min de footing progressif à {{P}}.', corps:'2 × 18 min à {{P}} avec 3 min de récupération entre chaque. Plus long que la version standard car c\'est ta seule séance de qualité. La deuxième se termine fatigué, c\'est voulu.', retour:'10 min de footing léger.',
        note:'RPE 7-8/10 · 36 min totales au seuil, la charge la plus importante depuis le début.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue avec fin à allure semi', duree:'85 min', pcts:[[65,70]],
        echauff:'', corps:'75 min à {{P}}, puis les 10 dernières minutes à ton allure objectif semi-marathon ({{OBJ}}). Tu apprends à finir sur la bonne allure quand les jambes sont déjà chargées.', retour:'',
        note:'RPE 6/10 puis 7/10 · Mémorise la sensation de l\'allure semi sur des jambes fatiguées.' },
    ]},
  { num:5, phase:'Volume', charge:'Élevée, pic de volume',
    objectif:'Le volume hebdomadaire atteint son plus haut niveau. La sortie longue de 90 min est un premier cap important. Le tempo du jeudi est long et exigeant sur 3 séances.',
    conseil:'Sur les 3 × 13 min au seuil, chaque répétition doit être exactement à la même allure. La régularité est le signe que tu es bien dans ta zone.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Endurance Fondamentale', duree:'50 min', pcts:[[65,70]],
        echauff:'', corps:'50 min à {{P}}. Volume de base avant la séance tempo du jeudi.', retour:'',
        note:'RPE 4/10 · Garde les jambes fraîches pour le jeudi.' },
      { jour:'Jeudi', type:'Tempo', titre:'3 × 13 minutes au seuil', duree:'70 min', pcts:[[65,70],[85,85]],
        echauff:'25 min de footing progressif à {{P}}.', corps:'3 × 13 min à {{P}} avec 3 min de récupération entre chaque. La troisième répétition est la plus difficile, maintiens l\'allure.', retour:'10 min de footing léger.',
        note:'RPE 8/10 · 39 min totales au seuil, ton record depuis le début du plan.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 90 minutes', duree:'90 min', pcts:[[65,70]],
        echauff:'', corps:'90 min à {{P}}. Ton premier cap à 90 minutes. Régularité, respiration, hydratation toutes les 20-25 min. Emporte de l\'eau.', retour:'',
        note:'RPE 5-6/10 · À 90 min, tu commences à toucher aux exigences physiques du semi-marathon.' },
    ]},
  { num:6, phase:'Volume', charge:'Très élevée, sortie longue avec encart allure semi',
    objectif:'La sortie longue de 100 min avec un bloc à allure semi est la répétition la plus précieuse du plan. Le tempo du jeudi est ton pic de charge sur cette séance.',
    conseil:'Sur les 5 km à allure semi au sein de la sortie longue, l\'allure {{OBJ}} doit se sentir soutenable mais difficile.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Footing long EF', duree:'55 min', pcts:[[70,70],[65,65]],
        echauff:'', corps:'55 min à {{P}}. Long et facile avant la semaine très chargée. Si tu te sens fatigué, passe à {{P}}.', retour:'',
        note:'RPE 5/10 · Ce footing long est ta récupération active.' },
      { jour:'Jeudi', type:'Tempo', titre:'2 × 22 minutes au seuil', duree:'75 min', pcts:[[65,70],[86,86]],
        echauff:'25 min de footing progressif à {{P}}.', corps:'2 × 22 min à {{P}} avec 3 min de récupération entre chaque. Plus long que la version 4 séances car c\'est ta seule séance de qualité. 44 min totales au seuil, ton pic absolu sur cette séance.', retour:'10 min de footing léger.',
        note:'RPE 8-9/10 · 44 min au seuil, une charge sérieuse. Récupère bien les jours suivants.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue avec encart allure semi', duree:'100 min', pcts:[[65,70]],
        echauff:'', corps:'80 min à {{P}}, puis 5 km à ton allure objectif semi-marathon ({{OBJ}}), puis retour à l\'allure EF pour finir. Cet encart t\'apprend à tenir l\'allure quand les jambes sont déjà sollicitées.', retour:'',
        note:'RPE 6/10 en EF · 7-8/10 sur les 5 km · Note ton allure réelle, c\'est un indicateur fiable de ta forme.' },
    ]},
  { num:7, phase:'Intensification', charge:'Très élevée, tempo long',
    objectif:'La charge atteint son niveau le plus difficile. Un tempo très long + sortie longue maximale : la durée au seuil est ce qui te rapproche le plus du jour J sur 3 séances.',
    conseil:'Sur les 3 × 17 min, l\'allure doit être tenue du début à la fin des trois répétitions. Plus long que la version 4 séances, mais c\'est ta seule qualité de la semaine.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Footing long EF', duree:'60 min', pcts:[[70,70],[65,65]],
        echauff:'', corps:'60 min à {{P}}. Long et facile avant le tempo du jeudi. Si tu te sens fatigué, passe à {{P}}.', retour:'',
        note:'RPE 5/10 · Ce footing prépare la séance du jeudi.' },
      { jour:'Jeudi', type:'Tempo', titre:'3 × 17 minutes au seuil', duree:'75 min', pcts:[[65,70],[86,86]],
        echauff:'25 min de footing progressif à {{P}}.', corps:'3 × 17 min à {{P}} avec 3 min de récupération entre chaque. La troisième répétition est la plus difficile, maintiens l\'allure. Plus long que la version 4 séances car c\'est ta seule qualité de la semaine.', retour:'10 min de footing léger.',
        note:'RPE 8-9/10 · 51 min totales au seuil, ton record absolu. Récupère bien le lendemain.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 105 minutes', duree:'105 min', pcts:[[65,70]],
        echauff:'', corps:'105 min à {{P}}. Ta sortie longue la plus longue à ce jour. Régularité, respiration, hydratation toutes les 20 min.', retour:'',
        note:'RPE 6/10 · Après cette semaine, la forme monte d\'un cran.' },
    ]},
  { num:8, phase:'Intensification', charge:'Maximale, pic de charge du plan',
    objectif:'Le pic de ta préparation. Tempo maximal + sortie longue la plus longue du plan avec un bloc à allure semi : c\'est le test le plus précis de ta forme.',
    conseil:'C\'est ta semaine de charge maximale. N\'ajoute rien. Mange des glucides les soirs avant les séances. Dors 8 heures.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Footing long EF', duree:'60 min', pcts:[[70,70],[65,65]],
        echauff:'', corps:'60 min à {{P}}. Long et facile avant la semaine la plus chargée du plan. Si tu te sens fatigué, passe à {{P}}.', retour:'',
        note:'RPE 5/10 · Ce footing long est ta préparation à la séance du jeudi.' },
      { jour:'Jeudi', type:'Tempo', titre:'4 × 14 minutes au seuil', duree:'80 min', pcts:[[65,70],[87,87]],
        echauff:'25 min de footing progressif à {{P}}.', corps:'4 × 14 min à {{P}} avec 3 min de récupération entre chaque. Légèrement plus intense que la semaine 7. La quatrième répétition est la plus difficile, maintiens l\'allure.', retour:'10 min de footing léger.',
        note:'RPE 8-9/10 · 56 min au seuil, ton pic absolu de la préparation.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue avec encart allure semi', duree:'110 min', pcts:[[65,70]],
        echauff:'', corps:'90 min à {{P}}, puis 8 km à ton allure objectif semi-marathon ({{OBJ}}), puis retour à l\'allure EF. Ces 8 km à allure objectif après 90 min de course te préparent directement à la fin du semi.', retour:'',
        note:'RPE 6/10 en EF · 8/10 sur les 8 km · Après cette semaine, l\'entraînement dur est terminé.' },
    ]},
  { num:9, phase:'Spécificité semi', charge:'Élevée, travail à l\'allure objectif',
    objectif:'Les séances s\'alignent sur ton allure de course. Tu répètes littéralement l\'allure que tu devras tenir 21km le jour J.',
    conseil:'Sur les 3 × 5 km, chaque répétition doit être exactement à {{OBJ}}. Ni plus vite, ni plus lentement.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Endurance Fondamentale', duree:'50 min', pcts:[[65,70]],
        echauff:'', corps:'50 min à {{P}}. Volume de base avant la séance spécifique du jeudi. Très facile.', retour:'',
        note:'RPE 4/10 · Garde les jambes fraîches pour le jeudi.' },
      { jour:'Jeudi', type:'Spécifique', titre:'3 × 5 km à allure objectif', duree:'70 min',
        echauff:'25 min de footing EF.', corps:'3 × 5 km exactement à ton allure objectif semi-marathon ({{OBJ}}). Récupération 2 min au trot entre chaque. Tu répètes littéralement ton allure de course.', retour:'10 min de footing léger.',
        note:'RPE 7-8/10 · Si {{OBJ}} te semble trop facile sur les 3, ton objectif est peut-être trop prudent.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue avec encart allure semi', duree:'90 min', pcts:[[65,70]],
        echauff:'', corps:'70 min à {{P}}, puis 8 km à ton allure objectif semi-marathon ({{OBJ}}), puis retour à l\'allure EF. Ces 8 km reproduisent exactement la 2e partie du semi.', retour:'',
        note:'RPE 6/10 en EF · 7-8/10 sur les 8 km · Mémorise cette sensation, tu la retrouveras en course.' },
    ]},
  { num:10, phase:'Spécificité semi', charge:'Très élevée, pic de spécificité',
    objectif:'Ta dernière vraie semaine de charge à l\'allure course. Les 4 × 5 km + le bloc de 10 km sur la sortie longue t\'apportent la confiance nécessaire pour le jour J.',
    conseil:'Sur les 4 × 5 km, la quatrième est la plus précieuse : elle simule la fin de course avec des jambes chargées.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Endurance Fondamentale', duree:'55 min', pcts:[[65,70]],
        echauff:'', corps:'55 min à {{P}}. Volume avant la semaine la plus spécifique du plan.', retour:'',
        note:'RPE 4-5/10 · Garde les jambes fraîches pour le jeudi.' },
      { jour:'Jeudi', type:'Spécifique', titre:'4 × 5 km à allure objectif', duree:'80 min',
        echauff:'25 min de footing EF.', corps:'4 × 5 km exactement à ton allure objectif semi-marathon ({{OBJ}}). Récupération 2 min au trot. La quatrième est ta répétition générale.', retour:'10 min de footing léger.',
        note:'RPE 7-8/10 · 20 km à l\'allure objectif. Si tu les tiens sur 4, tu peux tenir 21km le jour J.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue avec encart allure semi', duree:'95 min', pcts:[[65,70]],
        echauff:'', corps:'70 min à {{P}}, puis 10 km à ton allure objectif semi-marathon ({{OBJ}}). Ta dernière sortie longue spécifique. Ces 10 km à allure objectif simulent directement la 2e partie du semi.', retour:'',
        note:'RPE 6/10 en EF · 8/10 sur les 10 km · Après cette séance, les séances dures sont terminées.' },
    ]},
  { num:11, phase:'Consolidation', charge:'Réduite, affûtage',
    objectif:'La consolidation préserve ta forme sans t\'épuiser. Volume réduit de 40%, intensité maintenue. L\'objectif : aborder la semaine de course avec les jambes fraîches.',
    conseil:'Cette semaine allégée laisse les adaptations des 10 semaines de travail s\'installer pleinement. Dors 8 heures, mange bien, évite le stress.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Footing léger', duree:'45 min', pcts:[[65,65]],
        echauff:'', corps:'45 min très faciles à {{P}}. Garder les jambes en mouvement sans les fatiguer. Cours au ressenti, sans montre.', retour:'',
        note:'RPE 3/10 · Tu dois finir comme si tu venais de te promener.' },
      { jour:'Jeudi', type:'Tempo', titre:'2 × 12 minutes au seuil, volume réduit', duree:'55 min', pcts:[[65,70],[84,84]],
        echauff:'25 min de footing progressif à {{P}}.', corps:'2 × 12 min à {{P}}. Volume réduit mais intensité maintenue. Récupération 3 min entre chaque. Termine par 1 km à ton allure objectif semi-marathon ({{OBJ}}).', retour:'10 min de footing léger.',
        note:'RPE 7/10 · Ces répétitions maintiennent tes sensations sans te fatiguer.' },
      { jour:'Samedi', type:'EF', titre:'Footing de 35 minutes', duree:'35 min', pcts:[[65,65]],
        echauff:'', corps:'35 min à {{P}}. Garde les jambes en mouvement sans les fatiguer. Ton corps se recharge pour le jour J.', retour:'',
        note:'RPE 3/10 · Tu dois finir frais et légèrement dynamisé, jamais fatigué.' },
    ]},
  { num:12, phase:'Semaine de course', charge:'Conserve, tu es prêt',
    objectif:'Rien ne se gagne à l\'entraînement cette semaine. L\'objectif unique : arriver au départ reposé, confiant, les jambes fraîches.',
    conseil:'Fais confiance à tes 11 semaines de travail. Pars à ton allure objectif {{OBJ}} dès le départ, ne te laisse pas griser par l\'adrénaline.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing très léger', duree:'35 min', pcts:[[60,65]],
        echauff:'', corps:'35 min à {{P}}. Maintenir la circulation sanguine. Vraiment facile.', retour:'',
        note:'RPE 3/10 · Aucun effort. Juste des jambes qui bougent.' },
      { jour:'Mercredi', type:'Fractionné', titre:'6 × 30/30 à allure objectif', duree:'30 min',
        echauff:'15 min de footing EF très léger.',
        corps:'6 × 30 secondes à ton allure objectif semi ({{OBJ}}) / 30 secondes au trot. Effort court et ciblé, les jambes retrouvent la sensation d\'allure avant la course.',
        retour:'10 min de jogging léger.',
        note:'RPE 6/10 · Ces relances maintiennent les sensations sans t\'épuiser avant le jour J.' },
      { jour:'Samedi', type:'Activation', titre:'Activation J-1 + accélérations', duree:'30 min', pcts:[[60,65]],
        echauff:'', corps:'20 min de trot à {{P}}. Puis 6 à 8 accélérations progressives de 80m, démarre doucement et accélère jusqu\'à passer sous ton allure objectif {{OBJ}} sur les 20 derniers mètres. Récupère 60 sec en marchant entre chaque.', retour:'',
        note:'Ces accélérations réveillent tes fibres rapides. Efficace la veille d\'une course.' },
      { jour:'Dimanche', type:'Course', titre:'COURSE SEMI-MARATHON', duree:'Jour J',
        echauff:'10 min de jogging léger avant le départ.', corps:'KM 1-5 : pars à ton allure objectif {{OBJ}}, ne pars surtout pas plus vite. KM 6-15 : maintiens {{OBJ}} exactement, régularité absolue, hydrate-toi à chaque ravitaillement. KM 16-18 : évaluation honnête, si tu as des réserves, accélère légèrement. KM 19-21 : donne absolument tout.', retour:'15-20 min de marche. Ravitaillement dans les 30 min.',
        note:'Les sensations difficiles aux km 14-17 sont normales. C\'est là que se gagne un semi-marathon.' },
    ]},
]
