// Marathon 16 semaines · 3 séances/semaine · Palier Débutant (VMA ≤ 13.5)
// Fractionnés raccourcis, seuil réduit, SL plus courtes, blocs OBJ réduits
const { applyOverrides } = require('../../lib/tier-overrides')
const base = require('./semaines-3-i.js')

module.exports = applyOverrides(base, {
  1: { replace: { Jeudi: {
    titre:'4 × 400 mètres, réveil neuromusculaire', pcts:[[65,65],[88,92]],
    echauff:'20 min progressif à {{P}}, finir par 4 accélérations de 60m.',
    corps:'4 × 400 mètres à {{P}}. Récupération 2 min au trot. Effort régulier. Mémorise la sensation sur chaque répétition.',
    retour:'10 min footing très lent.',
    note:'RPE 6/10 · 4×400m est la distance d\'entrée idéale pour ce palier.' },
    Dimanche: { duree:'60 min',
    corps:'60 min à {{P}}. Rythme conversationnel. Hydrate-toi. Mécanise la foulée. Premier jalon posé.',
    note:'RPE 4/10 · La durée prime. Si tu dois ralentir, ralentis.' } } },
  2: { replace: { Jeudi: {
    titre:'6 côtes de 80 mètres', pcts:[[65,65],[100,105]],
    echauff:'20 min progressif à {{P}}, finir par 4 foulées bondissantes.',
    corps:'6 côtes de 80 mètres à effort maximal. Récupération : redescente en marchant. Appui avant-pied, genoux hauts.',
    retour:'10 min footing très lent.',
    note:'RPE 8/10 sur chaque côte · 6 côtes au lieu de 8. Qualité sur chacune.' },
    Dimanche: { duree:'65 min',
    corps:'65 min à {{P}}. Terrain plat de préférence. Mécanise la foulée.',
    note:'RPE 4/10.' } } },
  3: { replace: { Jeudi: {
    titre:'1 × 12 minutes au seuil aérobie, premier contact', duree:'45 min', pcts:[[65,70],[78,82]],
    echauff:'20 min progressif à {{P}}, finir par 4 accélérations de 60m.',
    corps:'12 min continus à {{P}}. Allure légèrement plus douce que la trame. Tu dois pouvoir prononcer quelques mots. Premier contact avec l\'effort soutenu.',
    retour:'10 min footing très lent.',
    note:'RPE 6/10 · 12 min en continu au seuil léger est un cap pour ce palier.' },
    Dimanche: { duree:'75 min',
    corps:'75 min à {{P}}. Régulier, hydraté.',
    note:'RPE 4/10.' } } },
  4: { replace: { Jeudi: {
    titre:'3 × 1000 mètres, développement VMA', pcts:[[65,65],[83,90]],
    echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
    corps:'3 × 1000 mètres à {{P}}. Récupération 2 min au trot. Un de moins que la trame. Régularité sur les 3.',
    retour:'10 min footing très lent.',
    note:'RPE 7/10 · 3×1000m, progression vers les 4-5 répétitions des semaines à venir.' },
    Dimanche: { duree:'80 min',
    corps:'80 min à {{P}}. Gel recommandé à 1h pour t\'habituer à la nutrition.',
    note:'RPE 4-5/10 · Hydratation systématique.' } } },
  5: { replace: { Jeudi: {
    titre:'4 × 1000 mètres', pcts:[[65,65],[83,90]],
    echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
    corps:'4 × 1000 mètres à {{P}}. Récupération 2 min. Un de moins que la trame. Même allure du 1er au 4e.',
    retour:'10 min footing très lent.',
    note:'RPE 7/10 · Progression régulière vers les 5000m.' },
    Dimanche: { duree:'90 min',
    corps:'90 min à {{P}}. Gel à 1h. Pas de bloc marathon encore pour ce palier.',
    note:'RPE 4-5/10.' } } },
  6: { replace: { Jeudi: {
    titre:'2 × 10 minutes au seuil aérobie', duree:'50 min', pcts:[[65,70],[80,84]],
    echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
    corps:'2 × 10 min à {{P}} avec 3 min de récupération. Volume réduit vs la trame (2×15min). Allure adaptée à ce palier.',
    retour:'10 min footing très lent.',
    note:'RPE 6-7/10 · 20 min au seuil léger. Adapté au palier débutant.' },
    Dimanche: { duree:'1h40',
    corps:'1h40 à {{P}}. Gel à 1h. Pas de bloc OBJ pour ce palier.',
    note:'RPE 5/10.' } } },
  7: { replace: { Jeudi: {
    titre:'2 × 2000 mètres, premiers longs fractionnés', pcts:[[65,65],[78,83]],
    echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
    corps:'2 × 2000 mètres à {{P}}. Récupération 4 min. Volume réduit vs la trame (3×2000m). Pars conservateur.',
    retour:'10 min footing très lent.',
    note:'RPE 7/10 · Premier contact avec les 2000m. 2 blocs avant d\'aller vers les 3000m.' },
    Dimanche: { duree:'1h50',
    corps:'1h50 à {{P}}. Gel à 1h. Sortie longue sans bloc OBJ pour ce palier.',
    note:'RPE 5/10.' } } },
  8: { replace: { Jeudi: {
    titre:'2 × 3000 mètres progressifs', pcts:[[65,65],[78,80],[80,83],[83,85]],
    echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
    corps:'2 × 3000 mètres à {{P}}. Récupération 5 min. Chaque 3000m en progression : 1er km à {{P}}, 2e km à {{P}}, 3e km à {{P}}.',
    retour:'10 min footing très lent.',
    note:'RPE 7-8/10 · La trame : 2×3000m est la même. Ce palier utilise des allures légèrement plus basses.' },
    Dimanche: { duree:'2h',
    corps:'2h à {{P}}. Gel à 1h et 1h20. Pas de bloc OBJ. Le palier débutant atteint 2h sans bloc allure marathon.',
    note:'RPE 5/10 · 2h : cap symbolique pour ce palier.' } } },
  9: { replace: { Jeudi: {
    titre:'8 côtes de 80 mètres, puissance marathon', pcts:[[65,65],[100,105]],
    echauff:'20 min progressif à {{P}}, finir par 4 foulées bondissantes.',
    corps:'8 côtes de 80 mètres à effort maximal. Récupération : redescente en marchant.',
    retour:'10 min footing très lent.',
    note:'RPE 8/10 · 8 côtes au lieu de 10. Qualité sur chacune.' },
    Dimanche: { duree:'1h55',
    corps:'95 min à {{P}}, puis 15 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h. Bloc OBJ raccourci pour ce palier.',
    note:'RPE 5/10 en EF · 6-7/10 sur les 15 min · Premier bloc OBJ, mémorise cette allure.' } } },
  10: { replace: { Jeudi: {
    titre:'2 × 15 minutes au seuil', duree:'60 min', pcts:[[65,70],[80,84]],
    echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
    corps:'2 × 15 min à {{P}} avec 4 min de récupération. Réduit vs la trame (3×15min). 30 min au seuil. Régularité sur les 2 blocs.',
    retour:'10 min footing très lent.',
    note:'RPE 7/10 · 30 min au seuil, adapté au palier débutant.' },
    Dimanche: { duree:'2h',
    corps:'100 min à {{P}}, puis 20 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h et 1h10. Bloc OBJ adapté.',
    note:'RPE 5/10 en EF · 7/10 sur les 20 min.' } } },
  11: { replace: { Jeudi: {
    titre:'1 × 5000 mètres à allure marathon, répétition de référence', duree:'60 min', pcts:[[65,65],[78,82]],
    echauff:'20 min progressif à {{P}}, finir par 4 accélérations de 80m.',
    corps:'1 × 5000 mètres à {{P}}. Un seul bloc tenu de bout en bout. Après 4 min de récup, 2 km à {{OBJ}} pour graver l\'allure.',
    retour:'10 min footing très lent.',
    note:'RPE 7-8/10 · 1×5000m est le pic spécifique adapté à ce palier.' },
    Dimanche: { duree:'2h10',
    corps:'105 min à {{P}}, puis 25 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h et 1h20. Bloc OBJ adapté.',
    note:'RPE 5/10 en EF · 7/10 sur les 25 min.' } } },
  12: { replace: { Jeudi: {
    titre:'3 × 3 km à allure marathon', duree:'65 min', pcts:[[65,65],[78,82]],
    echauff:'20 min footing EF à {{P}}.',
    corps:'3 × 3 km à ton allure objectif marathon ({{OBJ}}). Récupération 3 min au trot. Version simplifiée de la séance finisher. Régularité sur les 3 blocs.',
    retour:'10 min footing léger.',
    note:'RPE 7/10 · Séance spécifique sans la partie seuil. Adapté au palier débutant.' },
    Dimanche: { duree:'2h20',
    corps:'110 min à {{P}}, puis 30 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h, 1h20, 1h40. Grande SL adaptée à ce palier.',
    note:'RPE 5-6/10 en EF · 7/10 sur les 30 min.' } } },
  13: { replace: { Jeudi: {
    titre:'3 × 3 km à allure marathon', duree:'65 min', pcts:[[65,65],[78,82]],
    echauff:'20 min footing EF à {{P}}.',
    corps:'3 × 3 km à ton allure objectif marathon ({{OBJ}}). Récupération 3 min. Maintien de la mémoire allure. Volume identique à S12 pour ce palier.',
    retour:'10 min footing léger.',
    note:'RPE 7/10.' },
    Dimanche: { duree:'2h10',
    corps:'100 min à {{P}}, puis 30 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h et 1h20.',
    note:'RPE 5-6/10 en EF · 7/10 sur les 30 min.' } } },
  14: { replace: { Jeudi: {
    titre:'3 × 1500 mètres, maintien VMA pré-affûtage', pcts:[[65,65],[82,88]],
    echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
    corps:'3 × 1500 mètres à {{P}}. Récupération 3 min. Intervalles courts : maintien des qualités sans fatigue. Un de moins que la trame.',
    retour:'10 min footing très lent.',
    note:'RPE 6-7/10 · Maintien des sensations sans épuisement.' },
    Dimanche: { duree:'1h45',
    corps:'90 min à {{P}}, puis 10 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h. Sortie longue allégée pour l\'affûtage.',
    note:'RPE 5/10 en EF · 6/10 sur les 10 min.' } } },
})
