// Marathon 16 semaines · 3 séances/semaine · Palier Avancé (VMA > 18.5)
// Intervalles plus longs, SL allongées, blocs OBJ plus longs, séances plus intenses
const { applyOverrides } = require('../../lib/tier-overrides')
const base = require('./semaines-3-i.js')

module.exports = applyOverrides(base, {
  1: { replace: { Jeudi: {
    titre:'8 × 400 mètres, volume VMA élevé', pcts:[[65,65],[92,97]],
    echauff:'20 min progressif à {{P}}, finir par 4 accélérations de 60m.',
    corps:'8 × 400 mètres à {{P}}. Récupération 90 sec au trot. Deux de plus que la trame. Volume VMA élevé dès la semaine 1 pour ce palier.',
    retour:'10 min footing très lent.',
    note:'RPE 7-8/10 · 8×400m pour ancrer les qualités neuromusculaires dès S1.' },
    Dimanche: { duree:'80 min',
    corps:'80 min à {{P}}. Plus long que la trame (70 min). Hydrate-toi toutes les 20 min.',
    note:'RPE 4-5/10 · SL allongée pour le palier avancé.' } } },
  2: { replace: { Jeudi: {
    titre:'12 côtes de 80 mètres, puissance maximale', pcts:[[65,65],[100,107]],
    echauff:'20 min progressif à {{P}}, finir par 4 foulées bondissantes.',
    corps:'12 côtes de 80 mètres à effort maximal. Récupération : redescente en marchant. 4 de plus que la trame. Renforcement neuromusculaire maximal.',
    retour:'10 min footing très lent.',
    note:'RPE 8/10 sur chaque côte · 12 côtes pour ce palier.' },
    Dimanche: { duree:'90 min',
    corps:'90 min à {{P}}. 10 min de plus que la trame.',
    note:'RPE 4-5/10.' } } },
  3: { replace: { Jeudi: {
    titre:'2 × 15 minutes au seuil aérobie, montée rapide', duree:'60 min', pcts:[[65,70],[83,88]],
    echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
    corps:'2 × 15 min à {{P}} avec 4 min de récupération. 5 min de plus par bloc que la trame. Allure légèrement plus haute pour le palier avancé.',
    retour:'10 min footing très lent.',
    note:'RPE 8/10 · 30 min au seuil dès S3 pour ce palier.' },
    Dimanche: { duree:'95 min',
    corps:'75 min à {{P}}, puis 20 min à ton allure objectif marathon ({{OBJ}}). Bloc OBJ introduit dès S3 pour ce palier.',
    note:'RPE 5/10 en EF · 7/10 sur les 20 min · Mémorise {{OBJ}} tôt dans le plan.' } } },
  4: { replace: { Jeudi: {
    titre:'6 × 1000 mètres, volume VMA', pcts:[[65,65],[87,93]],
    echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
    corps:'6 × 1000 mètres à {{P}}. Récupération 2 min. Deux de plus que la trame. Volume VMA élevé. Régularité sur les 6.',
    retour:'10 min footing très lent.',
    note:'RPE 8/10 · 6×1000m = 6 km à intensité VMA.' },
    Dimanche: { duree:'1h45',
    corps:'75 min à {{P}}, puis 30 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h. Bloc OBJ allongé par rapport à la trame.',
    note:'RPE 5/10 en EF · 7-8/10 sur les 30 min.' } } },
  5: { replace: { Jeudi: {
    titre:'6 × 1000 mètres, maintien volume VMA', pcts:[[65,65],[87,93]],
    echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
    corps:'6 × 1000 mètres à {{P}}. Récupération 2 min. Un de plus que la trame. Maintien du volume VMA élevé.',
    retour:'10 min footing très lent.',
    note:'RPE 8/10.' },
    Dimanche: { duree:'1h55',
    corps:'85 min à {{P}}, puis 30 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h.',
    note:'RPE 5/10 en EF · 7-8/10 sur les 30 min.' } } },
  6: { replace: { Jeudi: {
    titre:'3 × 15 minutes au seuil, volume élevé', duree:'75 min', pcts:[[65,70],[83,88]],
    echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
    corps:'3 × 15 min à {{P}} avec 4 min de récupération. 45 min au seuil. Un bloc de plus que la trame.',
    retour:'10 min footing très lent.',
    note:'RPE 8/10 · 45 min au seuil dès S6 pour ce palier.' },
    Dimanche: { duree:'2h',
    corps:'100 min à {{P}}, puis 20 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h. Bloc OBJ allongé vs la trame.',
    note:'RPE 5/10 en EF · 7/10 sur les 20 min.' } } },
  7: { replace: { Jeudi: {
    titre:'4 × 2000 mètres, volume fractionné long', pcts:[[65,65],[82,87]],
    echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
    corps:'4 × 2000 mètres à {{P}}. Récupération 4 min. Un de plus que la trame. 8 km à intensité.',
    retour:'10 min footing très lent.',
    note:'RPE 8/10 · 4×2000m = 8 km à intensité pour ce palier.' },
    Dimanche: { duree:'2h20',
    corps:'100 min à {{P}}, puis 40 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h et 1h20.',
    note:'RPE 5/10 en EF · 7-8/10 sur les 40 min.' } } },
  8: { replace: { Jeudi: {
    titre:'3 × 3000 mètres progressifs, volume élevé', pcts:[[65,65],[80,82],[82,85],[85,88]],
    echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
    corps:'3 × 3000 mètres à {{P}}. Récupération 5 min. Un de plus que la trame. Chaque 3000m en progression : 1er km à {{P}}, 2e à {{P}}, 3e à {{P}}.',
    retour:'10 min footing très lent.',
    note:'RPE 8-9/10 · 3×3000m = 9 km à intensité croissante.' },
    Dimanche: { duree:'2h30',
    corps:'110 min à {{P}}, puis 40 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h, 1h20, 1h50.',
    note:'RPE 5/10 en EF · 7-8/10 sur les 40 min · Grosse sortie avancée.' } } },
  9: { replace: { Jeudi: {
    titre:'12 côtes de 80 mètres, maintien puissance en phase spécifique', pcts:[[65,65],[100,107]],
    echauff:'20 min progressif à {{P}}, finir par 4 foulées bondissantes.',
    corps:'12 côtes de 80 mètres à effort maximal. Récupération : redescente en marchant. 2 de plus que la trame.',
    retour:'10 min footing très lent.',
    note:'RPE 8/10 · Puissance neuromusculaire maximale en phase spécifique.' },
    Dimanche: { duree:'2h15',
    corps:'95 min à {{P}}, puis 40 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h et 1h20. Bloc OBJ allongé pour ce palier.',
    note:'RPE 6/10 en EF · 7-8/10 sur les 40 min.' } } },
  10: { replace: { Jeudi: {
    titre:'Séance finisher avancée, 6 km seuil + 3 × 3 km allure marathon', duree:'90 min', pcts:[[65,65],[82,87],[78,82]],
    echauff:'20 min footing EF à {{P}}.',
    corps:'6 km à {{P}} (effort seuil élevé) → 5 min récupération → 3 × 3 km à ton allure objectif marathon ({{OBJ}}), récup 3 min. Plus de volume au seuil que la trame.',
    retour:'10 min footing léger.',
    note:'RPE 9/10 sur le seuil · 8/10 sur les blocs OBJ · Séance de référence marathon avancé.' },
    Dimanche: { duree:'2h25',
    corps:'105 min à {{P}}, puis 40 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h, 1h20, 1h45.',
    note:'RPE 6/10 en EF · 8/10 sur les 40 min.' } } },
  11: { replace: { Jeudi: {
    titre:'3 × 5000 mètres à allure marathon, volume élevé', duree:'90 min', pcts:[[65,65],[78,82]],
    echauff:'20 min progressif à {{P}}, finir par 4 accélérations de 80m.',
    corps:'3 × 5000 mètres à {{P}}. Récupération 5 min. Un de plus que la trame. 15 km à allure marathon avec récupération. Pars très conservateur.',
    retour:'10 min footing très lent.',
    note:'RPE 8-9/10 · 3×5000m = 15 km à {{OBJ}}. Séance phare du marathon avancé.' },
    Dimanche: { duree:'2h40',
    corps:'120 min à {{P}}, puis 40 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h, 1h20, 1h50.',
    note:'RPE 6/10 en EF · 8/10 sur les 40 min · Sortie longue maximale avancée.' } } },
  12: { replace: { Jeudi: {
    titre:'Séance finisher avancée, 8 km seuil + 4 × 3 km allure marathon', duree:'100 min', pcts:[[65,65],[83,87],[78,82]],
    echauff:'20 min footing EF à {{P}}.',
    corps:'8 km à {{P}} (effort seuil élevé) → 5 min récupération → 4 × 3 km à ton allure objectif marathon ({{OBJ}}), récup 3 min. Plus de volume que la trame.',
    retour:'10 min footing léger.',
    note:'RPE 9/10 sur le seuil · 8/10 sur les 4 blocs OBJ · Pic de charge absolu du palier avancé.' },
    Dimanche: { duree:'2h50',
    corps:'130 min à {{P}}, puis 40 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h, 1h30, 2h. LA grande sortie du plan avancé.',
    note:'RPE 6/10 en EF · 8/10 sur les 40 min · 2h50 totales : la sortie de référence.' } } },
  13: { replace: { Jeudi: {
    titre:'5 × 3 km à allure marathon, consolidation', duree:'85 min', pcts:[[65,65],[78,82]],
    echauff:'20 min footing EF à {{P}}.',
    corps:'5 × 3 km à ton allure objectif marathon ({{OBJ}}). Récupération 3 min. Un de plus que la trame. 15 km à {{OBJ}} en blocs.',
    retour:'10 min footing léger.',
    note:'RPE 7-8/10 · 5×3km pour le palier avancé vs 4×3km pour la trame.' },
    Dimanche: { duree:'2h30',
    corps:'110 min à {{P}}, puis 40 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h, 1h20, 1h50.',
    note:'RPE 6/10 en EF · 8/10 sur les 40 min.' } } },
  14: { replace: { Jeudi: {
    titre:'5 × 1500 mètres, maintien VMA pré-affûtage', pcts:[[65,65],[85,92]],
    echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
    corps:'5 × 1500 mètres à {{P}}. Récupération 3 min. Un de plus que la trame. Maintien des qualités VMA.',
    retour:'10 min footing très lent.',
    note:'RPE 7-8/10 · Plus de volume que la trame sur cette séance d\'entretien.' },
    Dimanche: { duree:'2h10',
    corps:'95 min à {{P}}, puis 35 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h. Bloc OBJ allongé pour l\'affûtage avancé.',
    note:'RPE 5/10 en EF · 7-8/10 sur les 35 min · Le palier avancé maintient un bloc OBJ plus long même en pré-affûtage.' } } },
})
