// Marathon 16 semaines · 3 séances/semaine · Palier Intermédiaire (VMA 13.5 à 18.5)
// Plus progressif que le 12sem : 4 semaines de fondamentaux avant la construction spécifique
// {{P}} remplacé séquentiellement · {{OBJ}} = allure objectif marathon (80% VMA)
module.exports = [
  { num:1, phase:'Fondamentaux', charge:'Légère',
    objectif:'Poser les bases. Semaine d\'entrée en matière : endurance fondamentale et premiers intervalles courts pour réveiller les jambes.',
    conseil:'Ne cherche pas à te prouver quoi que ce soit cette semaine. Cours à l\'aise, apprécie les sensations. Le marathon se construit patiemment sur 16 semaines.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Footing fondamental 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}. Allure vraiment légère, tu dois pouvoir chanter. Découverte ou reprise du rythme hebdomadaire. Cours en nature si possible.', retour:'',
        note:'RPE 3-4/10 · Si tu sens la moindre gêne, réduis à 30 min.' },
      { jour:'Jeudi', type:'Fractionné', titre:'6 × 400 mètres, réveil neuromusculaire', duree:'45 min', pcts:[[65,65],[90,95]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 60m.',
        corps:'6 × 400 mètres à {{P}}. Récupération 90 sec au trot entre chaque. Effort soutenu et régulier sur les 6. Tu dois tenir la même allure du 1er au 6e.',
        retour:'10 min footing très lent.',
        note:'RPE 6-7/10 · Ces 400m révèlent tes sensations actuelles. Ne force pas.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 70 minutes', duree:'70 min', pcts:[[65,65]],
        echauff:'', corps:'70 min réguliers à {{P}}. Rythme conversationnel. Hydrate-toi. Première sortie longue de la préparation, pose les bases mentales.', retour:'',
        note:'RPE 4/10 · La durée prime sur l\'allure. Si tu dois ralentir, ralentis.' },
    ]},

  { num:2, phase:'Fondamentaux', charge:'Légère',
    objectif:'Introduire les côtes pour développer la puissance musculaire dès le début. La SL allonge légèrement.',
    conseil:'Les côtes ne font pas mal si tu les fais correctement : appui avant-pied, corps penché légèrement vers la colline, bras actifs. Concentre-toi sur la forme.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Footing fondamental 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}. Récupération active après les 400m de jeudi. Aucune pression. Cours relâché.', retour:'',
        note:'RPE 3/10 · Tu dois finir aussi frais qu\'au départ.' },
      { jour:'Jeudi', type:'Côtes', titre:'8 côtes de 80 mètres, puissance neuromusculaire', duree:'45 min', pcts:[[65,65],[100,105]],
        echauff:'25 min progressif à {{P}}, finir par 4 foulées bondissantes.',
        corps:'8 côtes de 80 mètres à effort maximal contrôlé. Récupération : redescente en marchant (2 min). Appui avant-pied, genoux hauts, bras dynamiques. Les côtes recrutent les fibres rapides sans la fatigue du piste.',
        retour:'10 min footing très lent.',
        note:'RPE 8/10 sur chaque côte · Effort bref et explosif. Récupération complète entre chaque.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 80 minutes', duree:'80 min', pcts:[[65,65]],
        echauff:'', corps:'80 min à {{P}}. 10 min de plus que la semaine passée. Terrain varié si possible. Mécanise la foulée sur du plat.', retour:'',
        note:'RPE 4/10 · Un peu plus long, même effort ressenti.' },
    ]},

  { num:3, phase:'Fondamentaux', charge:'Modérée',
    objectif:'Première séance tempo. Introduction au seuil en douceur avec 2 blocs courts. La SL progresse régulièrement.',
    conseil:'Le seuil aérobie se situe à une allure où tu peux prononcer quelques mots mais pas tenir une vraie conversation. C\'est inconfortable mais tenable sur 10-15 min.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Footing fondamental 45 minutes', duree:'45 min', pcts:[[65,65]],
        echauff:'', corps:'45 min à {{P}}. Premier allongement des footings. Rythme identique aux semaines précédentes, juste un peu plus long.', retour:'',
        note:'RPE 4/10 · Régulier et relâché.' },
      { jour:'Jeudi', type:'Tempo', titre:'2 × 10 minutes au seuil aérobie', duree:'50 min', pcts:[[65,70],[80,84]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 60m.',
        corps:'2 × 10 min à {{P}} avec 3 min de récupération au trot entre les 2 blocs. Maintiens une allure régulière du début à la fin. Premier contact sérieux avec le seuil.',
        retour:'10 min footing très lent.',
        note:'RPE 7/10 · 20 min totales au seuil léger. N\'augmente pas l\'allure sur le 2e bloc.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 85 minutes', duree:'85 min', pcts:[[65,65]],
        echauff:'', corps:'85 min à {{P}}. Régulier, hydraté. La SL progresse de 5 min chaque semaine. Cours sur des surfaces variées.', retour:'',
        note:'RPE 4/10 · Aucun effort excessif. La régularité fait la différence.' },
    ]},

  { num:4, phase:'Fondamentaux', charge:'Modérée',
    objectif:'Introduction aux longs intervalles avec 4 × 1000m. Fin de la phase fondamentaux avec une SL à 90 min.',
    conseil:'Les 1000m sont la colonne vertébrale du développement VMA. Pars conservateur sur le 1er, tu dois finir plus fort qu\'au départ.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Footing fondamental 45 minutes', duree:'45 min', pcts:[[65,65]],
        echauff:'', corps:'45 min à {{P}}. Consolidation de la base aérobie. Cours en nature, terrain souple de préférence.', retour:'',
        note:'RPE 4/10 · C\'est la semaine la plus chargée des fondamentaux. Récupère bien après jeudi.' },
      { jour:'Jeudi', type:'Fractionné', titre:'4 × 1000 mètres, développement VMA', duree:'55 min', pcts:[[65,65],[85,92]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
        corps:'4 × 1000 mètres à {{P}}. Récupération 2 min au trot. Premier contact avec les longs intervalles. Régularité entre les répétitions. Ne pars pas trop vite sur le 1er.',
        retour:'10 min footing très lent.',
        note:'RPE 7-8/10 · La régularité sur les 4 intervalles est l\'objectif principal.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 90 minutes', duree:'90 min', pcts:[[65,65]],
        echauff:'', corps:'90 min à {{P}}. Premier cap symbolique : l\'heure et demie. Hydrate-toi toutes les 20 min. Si le terrain te le permet, teste tes chaussures de course.', retour:'',
        note:'RPE 4-5/10 · Cap des 90 min franchi. La phase de développement commence la semaine prochaine.' },
    ]},

  { num:5, phase:'Développement', charge:'Moyenne',
    objectif:'Passage en phase développement. La VMA se travaille davantage avec 5 × 1000m. La SL passe le cap des 100 min.',
    conseil:'Augmenter progressivement les distances des intervalles est la clé de la progression. Tu viens de faire 4 × 1000m la semaine dernière. Un rep de plus cette semaine.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Footing fondamental 50 minutes', duree:'50 min', pcts:[[65,65]],
        echauff:'', corps:'50 min à {{P}}. Les footings s\'allongent avec le plan. Tu accumules du temps sur pieds. Reste à l\'aise.', retour:'',
        note:'RPE 4/10 · Début de phase développement. Les charges augmentent.' },
      { jour:'Jeudi', type:'Fractionné', titre:'5 × 1000 mètres, montée en charge VMA', duree:'60 min', pcts:[[65,65],[85,92]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
        corps:'5 × 1000 mètres à {{P}}. Récupération 2 min au trot. Un intervalle de plus que la semaine dernière. Maintiens la même allure sur les 5.',
        retour:'10 min footing très lent.',
        note:'RPE 7-8/10 · Si le 5e répétition te semble trop facile, tu n\'es pas allé assez vite.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 100 minutes', duree:'100 min', pcts:[[65,65]],
        echauff:'', corps:'100 min à {{P}}. Première sortie au-delà de la fenêtre des 90 min. Gel recommandé à 1h pour t\'habituer à la nutrition en course. Hydratation toutes les 20 min.', retour:'',
        note:'RPE 5/10 · Dès que tu dépasses 90 min, la nutrition entre en jeu. Teste maintenant.' },
    ]},

  { num:6, phase:'Développement', charge:'Moyenne',
    objectif:'Le seuil monte en puissance avec 2 × 15 min. La SL atteint 1h50 pour ancrer l\'endurance de base.',
    conseil:'2 × 15 min au seuil est un cap important. Si tu tiens les 2 blocs avec régularité, ta forme est au rendez-vous. Si tu craques sur le 2e, tu pars trop vite sur le 1er.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Footing fondamental 50 minutes', duree:'50 min', pcts:[[65,65]],
        echauff:'', corps:'50 min à {{P}}. Jour de récupération active après les 5 × 1000m. Vital pour assimiler le travail de la semaine dernière.', retour:'',
        note:'RPE 4/10 · Récupération active. Ne force pas.' },
      { jour:'Jeudi', type:'Tempo', titre:'2 × 15 minutes au seuil aérobie', duree:'60 min', pcts:[[65,70],[82,87]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
        corps:'2 × 15 min à {{P}} avec 4 min de récupération au trot. 30 min totales au seuil. Régularité absolue : la 2e répétition doit être aussi rapide que la 1re.',
        retour:'10 min footing très lent.',
        note:'RPE 7-8/10 · 30 min au seuil est un cap majeur. Pars conservateur sur le 1er bloc.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 1h50', duree:'1h50', pcts:[[65,65]],
        echauff:'', corps:'1h50 à {{P}}. La sortie longue s\'approche des 2h. Gel à 1h. Hydratation toutes les 20 min. Simule la gestion de la nutrition de course.', retour:'',
        note:'RPE 5/10 · Tu commences à sentir la longueur dans les jambes après 1h20. C\'est normal.' },
    ]},

  { num:7, phase:'Développement', charge:'Élevée',
    objectif:'Les longs intervalles s\'imposent avec 3 × 2000m. La SL atteint 2h pour la première fois. Grosse semaine.',
    conseil:'3 × 2000m est différent des 1000m : la gestion de l\'allure sur une plus grande distance est cruciale. Commence le 1er 2000m plus prudemment que tu ne le sens.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Footing fondamental 55 minutes', duree:'55 min', pcts:[[65,65]],
        echauff:'', corps:'55 min à {{P}}. Les footings de milieu de semaine s\'allongent légèrement. Reste relâché. Tu as un 2000m jeudi et une 2h dimanche.', retour:'',
        note:'RPE 4/10 · Pas de fioriture. Juste du temps sur pieds à allure fondamentale.' },
      { jour:'Jeudi', type:'Fractionné', titre:'3 × 2000 mètres, fractionnés longs', duree:'65 min', pcts:[[65,65],[80,85]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
        corps:'3 × 2000 mètres à {{P}}. Récupération 4 min au trot. Rythme soutenu et régulier sur les 3 blocs. Si tu progresses bien sur les 2000m, tu as une bonne base.',
        retour:'10 min footing très lent.',
        note:'RPE 8/10 · Gère le 1er prudemment. Le 3e doit être aussi bon que le 2e.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 2 heures', duree:'2h', pcts:[[65,65]],
        echauff:'', corps:'2h à {{P}}. Premier cap psychologique majeur. Gel à 1h et à 1h20. Hydratation systématique. Si tu cours sur route, repère des points de ravitaillement.', retour:'',
        note:'RPE 5/10 · 2h de course est la distance à partir de laquelle la nutrition devient déterminante.' },
    ]},

  { num:8, phase:'Développement', charge:'Élevée',
    objectif:'Consolidation du volume avec 2 × 3000m progressifs. La SL monte à 2h10 avec un départ soutenu.',
    conseil:'Les 3000m sont la distance qui construit le plus la résistance au seuil. Tu dois terminer chaque 3000m plus vite que tu n\'as commencé.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Footing fondamental 55 minutes', duree:'55 min', pcts:[[65,65]],
        echauff:'', corps:'55 min à {{P}}. Régulier, relâché. Deux grosses séances t\'attendent cette semaine. Préserve-toi.', retour:'',
        note:'RPE 4/10 · Conserve de l\'énergie pour jeudi et dimanche.' },
      { jour:'Jeudi', type:'Fractionné', titre:'2 × 3000 mètres progressifs', duree:'65 min', pcts:[[65,65],[80,82],[82,85],[85,88]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
        corps:'2 × 3000 mètres à {{P}}. Récupération 5 min au trot. Chaque 3000m en 3 blocs de 1000m progressifs : 1er km à {{P}}, 2e km à {{P}}, 3e km à {{P}}. Accélère légèrement sur chaque km.',
        retour:'10 min footing très lent.',
        note:'RPE 8/10 · La progression interne est la vraie difficulté de cette séance.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 2h10', duree:'2h10', pcts:[[65,65]],
        echauff:'', corps:'2h10 à {{P}}. Gel à 1h et à 1h25. Hydratation systématique. Commence à te représenter mentalement la gestion de la seconde heure de marathon.', retour:'',
        note:'RPE 5-6/10 · La phase développement se termine. La phase spécifique commence la semaine prochaine.' },
    ]},

  { num:9, phase:'Spécificité marathon', charge:'Élevée',
    objectif:'Entrée en phase spécifique marathon. Côtes pour la puissance, première intégration de blocs à allure marathon en fin de SL.',
    conseil:'Tu vas courir pour la première fois des blocs à ton allure objectif marathon après 1h40 de course. C\'est l\'entraînement le plus spécifique qui soit. Mémorise cette allure.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Footing fondamental 55 minutes', duree:'55 min', pcts:[[65,65]],
        echauff:'', corps:'55 min à {{P}}. Début de la phase spécifique. Le travail change de nature : tu vas désormais courir à l\'allure marathon. Savoure ces footings calmes.', retour:'',
        note:'RPE 4/10 · Récupération mentale autant que physique.' },
      { jour:'Jeudi', type:'Côtes', titre:'10 côtes de 80 mètres, puissance marathon', duree:'50 min', pcts:[[65,65],[100,105]],
        echauff:'25 min progressif à {{P}}, finir par 4 foulées bondissantes.',
        corps:'10 côtes de 80 mètres à effort maximal. Récupération : redescente en marchant. Ces côtes renforcent les extenseurs de hanche et les mollets, musculature critique aux km 30-35 du marathon.',
        retour:'10 min footing très lent.',
        note:'RPE 8/10 sur chaque côte · 10 côtes c\'est 2 de plus que S2. Qualité d\'effort sur chacune.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 2h avec 20 min allure marathon', duree:'2h', pcts:[[65,72],[75,80]],
        echauff:'', corps:'100 min à {{P}}, puis 20 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h. Premier bloc allure marathon en fin de sortie. Mémorise cette sensation.', retour:'',
        note:'RPE 6/10 en EF · 7/10 sur les 20 min · Le bloc OBJ te révèle où tu en es physiquement.' },
    ]},

  { num:10, phase:'Spécificité marathon', charge:'Élevée',
    objectif:'Le seuil monte à 3 × 15 min. La SL intègre 25 min à allure marathon. La semaine la plus complète jusqu\'ici.',
    conseil:'3 × 15 min au seuil est une séance de référence marathon. Si tu arrives à tenir les 3 blocs avec régularité, tu as les bases pour courir ton marathon à l\'allure objectif.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Footing fondamental 55 minutes', duree:'55 min', pcts:[[65,65]],
        echauff:'', corps:'55 min à {{P}}. Tu vas faire 3 × 15 min jeudi et 2h10 dimanche. Ce footing doit te garder frais.', retour:'',
        note:'RPE 4/10 · Ne transforme pas ce footing en autre chose.' },
      { jour:'Jeudi', type:'Tempo', titre:'3 × 15 minutes au seuil, montée en puissance', duree:'75 min', pcts:[[65,70],[82,87]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
        corps:'3 × 15 min à {{P}} avec 4 min de récupération. 45 min totales au seuil. Le 1er bloc à {{P}} constamment, le 2e au même niveau, le 3e légèrement au-dessus si tu te sens bien.',
        retour:'10 min footing très lent.',
        note:'RPE 8/10 · Cette séance révèle ta forme marathon actuelle. 45 min au seuil, c\'est sérieux.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 2h10 avec 25 min allure marathon', duree:'2h10', pcts:[[65,72],[75,80]],
        echauff:'', corps:'105 min à {{P}}, puis 25 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h et à 1h20. Maintiens {{OBJ}} jusqu\'à la fin.', retour:'',
        note:'RPE 6/10 en EF · 7-8/10 sur les 25 min · Tu dois finir le bloc OBJ sur un effort contrôlé mais soutenu.' },
    ]},

  { num:11, phase:'Spécificité marathon', charge:'Maximale',
    objectif:'Première grosse séance spécifique avec 2 × 5000m. La SL intègre 30 min à allure marathon. Semaine de charge maximale.',
    conseil:'2 × 5000m à allure marathon est la séance reine de la préparation. Chaque 5000m simule l\'effort cible du jour J, les jambes apprennent à répéter l\'allure sur distance.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Footing fondamental 55 minutes', duree:'55 min', pcts:[[65,65]],
        echauff:'', corps:'55 min à {{P}}. Semaine de charge maximale. Ce footing est vital : il maintient le volume sans entamer les réserves pour la séance spécifique et la grande sortie.', retour:'',
        note:'RPE 4/10 · Conserve absolument ton énergie pour jeudi et dimanche.' },
      { jour:'Jeudi', type:'Fractionné', titre:'2 × 5000 mètres à allure marathon', duree:'80 min', pcts:[[65,65],[78,82]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
        corps:'2 × 5000 mètres à {{P}}. Récupération 5 min au trot. Chaque 5000m représente 1/8e de ton marathon. Pars conservateur sur le 1er et accélère légèrement sur le 2e si tu te sens bien.',
        retour:'10 min footing très lent.',
        note:'RPE 7-8/10 · 10 km à allure marathon avec récupération. La séance la plus spécifique du plan.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 2h20 avec 30 min allure marathon', duree:'2h20', pcts:[[65,72],[75,80]],
        echauff:'', corps:'110 min à {{P}}, puis 30 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h, 1h20, 1h40. Hydratatation systématique. La plus grande sortie long depuis le début du plan.', retour:'',
        note:'RPE 6/10 en EF · 8/10 sur les 30 min · Ce bloc OBJ final est l\'épreuve de vérité de ta forme actuelle.' },
    ]},

  { num:12, phase:'Spécificité marathon', charge:'Maximale',
    objectif:'LE pic de charge. La grande sortie longue à 2h30 avec 30 min OBJ. Séance finisher jeudi. La semaine la plus importante du plan.',
    conseil:'Après cette semaine, le plus dur est fait. La sortie longue à 2h30 est la séance référence du marathon. Elle ancre la confiance et la mémoire musculaire de l\'effort long.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Footing fondamental 55 minutes', duree:'55 min', pcts:[[65,65]],
        echauff:'', corps:'55 min à {{P}}. Dernière grosse semaine. Ce footing prépare le corps avant deux séances majeures. Reste léger et régulier.', retour:'',
        note:'RPE 4/10 · Prépare-toi mentalement pour la grande sortie dimanche.' },
      { jour:'Jeudi', type:'Tempo', titre:'Séance finisher, 5 km seuil + 3 × 3 km allure marathon', duree:'90 min', pcts:[[65,65],[80,85],[78,82]],
        echauff:'25 min footing EF à {{P}}.',
        corps:'5 km à {{P}} (effort seuil, régulier) → 5 min de récupération au trot → 3 × 3 km à ton allure objectif marathon ({{OBJ}}), récupération 3 min entre chaque. La transition seuil vers allure marathon est la clé de la réussite le jour J.',
        retour:'10 min footing léger.',
        note:'RPE 8/10 · Séance de référence marathon. Si tu tiens les 3 blocs à {{OBJ}}, tu es en forme.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Grande sortie longue 2h30 avec 30 min allure marathon', duree:'2h30', pcts:[[65,72],[75,80]],
        echauff:'', corps:'120 min à {{P}}, puis 30 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h, 1h20, 1h40, 2h. Hydratation toutes les 20 min. LA grande sortie longue du plan. Après 2h de course, les 30 min à {{OBJ}} sont l\'épreuve ultime de ta préparation.', retour:'',
        note:'RPE 6/10 en EF · 8/10 sur les 30 min · Le pic de charge est atteint. La récupération commence maintenant.' },
    ]},

  { num:13, phase:'Pic de charge', charge:'Élevée (légère réduction)',
    objectif:'Volume légèrement réduit (-15%) mais intensité maintenue. Blocs OBJ pour ancrer l\'allure marathon dans la mémoire musculaire.',
    conseil:'Après S12, une légère réduction évite le surentraînement tout en maintenant les sensations de course. Ce n\'est pas un affûtage, c\'est une consolidation.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Footing fondamental 50 minutes', duree:'50 min', pcts:[[65,65]],
        echauff:'', corps:'50 min à {{P}}. Légèrement plus court que les semaines précédentes. Le corps récupère de la S12 tout en restant actif.', retour:'',
        note:'RPE 4/10 · Récupération active après le pic de charge de S12.' },
      { jour:'Jeudi', type:'Fractionné', titre:'4 × 3 km à allure marathon', duree:'80 min', pcts:[[65,65],[78,82]],
        echauff:'25 min footing EF à {{P}}.',
        corps:'4 × 3 km exactement à ton allure objectif marathon ({{OBJ}}). Récupération 3 min au trot. 12 km à {{OBJ}} en blocs : maintien de la mémoire musculaire de l\'allure cible.',
        retour:'10 min footing léger.',
        note:'RPE 7-8/10 · Dernière grosse séance allure marathon. Après cette semaine, les séances dures s\'allègent.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 2h15 avec 30 min allure marathon', duree:'2h15', pcts:[[65,72],[75,80]],
        echauff:'', corps:'105 min à {{P}}, puis 30 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h, 1h20, 1h40. Légèrement plus court que S12 mais même intensité sur le bloc OBJ.', retour:'',
        note:'RPE 6/10 en EF · 8/10 sur les 30 min · Consolidation de la forme acquise en S12.' },
    ]},

  { num:14, phase:'Pic de charge', charge:'Réduite, pré-affûtage',
    objectif:'Volume réduit (-30%). Maintien des sensations VMA avec des intervalles courts. SL plus légère pour laisser récupérer.',
    conseil:'Cette semaine amorce l\'affûtage. Moins de volume mais les séances de qualité restent là pour maintenir les adaptations. Le corps commence à se recharger.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Footing fondamental 45 minutes', duree:'45 min', pcts:[[65,65]],
        echauff:'', corps:'45 min à {{P}}. L\'affûtage commence. Les footings raccourcissent progressivement. Reste relâché et régulier.', retour:'',
        note:'RPE 3-4/10 · Le corps entre en phase de super-compensation. Laisse-le se recharger.' },
      { jour:'Jeudi', type:'Fractionné', titre:'4 × 1500 mètres, maintien VMA pré-affûtage', duree:'60 min', pcts:[[65,65],[83,90]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
        corps:'4 × 1500 mètres à {{P}}. Récupération 3 min au trot. Intervalles plus courts que les semaines précédentes : maintien des sensations VMA sans générer de fatigue. Plus rapide que l\'allure marathon, moins long que les 2000m-3000m.',
        retour:'10 min footing très lent.',
        note:'RPE 7/10 · Maintien des qualités. Moins de volume, mêmes sensations.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 1h50 avec 15 min allure marathon', duree:'1h50', pcts:[[65,72],[75,80]],
        echauff:'', corps:'95 min à {{P}}, puis 15 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h. Sortie longue allégée, bloc OBJ court pour maintenir la sensation.', retour:'',
        note:'RPE 5/10 en EF · 7/10 sur les 15 min · Sortie longue réduite. La SL principale est derrière toi.' },
    ]},

  { num:15, phase:'Consolidation', charge:'Réduite, affûtage',
    objectif:'La consolidation préserve ta forme sans t\'épuiser. Volume réduit de 45%, intensité maintenue sur une séance clé.',
    conseil:'Cette semaine allégée laisse les adaptations s\'installer. Dors 8h, mange bien. Les jambes doivent commencer à fourmiller d\'impatience.',
    seances:[
      { jour:'Mardi', type:'EF', titre:'Footing léger 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min très faciles à {{P}}. Garder les jambes en mouvement sans les fatiguer. Cours au ressenti, sans montre.', retour:'',
        note:'RPE 3/10 · Tu dois finir comme si tu venais de te promener.' },
      { jour:'Jeudi', type:'Tempo', titre:'2 × 15 minutes au seuil, volume réduit', duree:'55 min', pcts:[[65,72],[82,88]],
        echauff:'25 min progressif à {{P}}.', corps:'2 × 15 min à {{P}}. Volume réduit de 50% mais intensité maintenue. Récupération 4 min. Termine par 1 km à ton allure marathon ({{OBJ}}).', retour:'10 min footing très lent.',
        note:'RPE 7/10 · Ces répétitions maintiennent tes sensations sans te fatiguer.' },
      { jour:'Samedi', type:'EF', titre:'Footing de 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}, allure vraiment légère. Dans les 10 dernières minutes, place 4 à 6 accélérations de 60m à ton allure marathon pour réveiller les sensations neuromusculaires. Les jambes doivent fourmiller d\'impatience, pas de fatigue.', retour:'',
        note:'RPE 3/10 · Tu dois finir frais et légèrement dynamisé, jamais fatigué.' },
    ]},

  { num:16, phase:'Semaine de course', charge:'Conserve, tu es prêt',
    objectif:'Arriver au départ reposé, confiant, les jambes fraîches. 15 semaines de travail ont été faites. Il ne reste qu\'à exécuter.',
    conseil:'Pars à {{OBJ}}/km dès le départ. L\'adrénaline va te pousser à aller plus vite, résiste. Chaque seconde gagnée trop tôt peut coûter une minute à la fin.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing très léger 30 minutes', duree:'30 min', pcts:[[60,65]],
        echauff:'', corps:'30 min à {{P}}. Maintenir la circulation sanguine. Vraiment facile. Si tu te sens fatigué, réduis à 20 minutes.', retour:'',
        note:'RPE 3/10 · Aucun effort. Juste des jambes qui bougent.' },
      { jour:'Mercredi', type:'Fractionné', titre:'8 × 1 min / 1 min à allure marathon', duree:'40 min',
        echauff:'15 min de footing très léger.',
        corps:'8 × 1 minute à ton allure objectif marathon ({{OBJ}}) / 1 minute au trot. Plus long que le 30/30, le stimulus réveille les jambes sans les fatiguer avant le grand jour.',
        retour:'10 min de jogging léger.',
        note:'RPE 6/10 · Ces répétitions maintiennent les sensations sans t\'épuiser.' },
      { jour:'Samedi', type:'Activation', titre:'Activation J-1 + accélérations', duree:'30 min', pcts:[[60,65]],
        echauff:'', corps:'20 min de trot à {{P}}. Puis 6 à 8 accélérations progressives de 80m jusqu\'à ton allure objectif ({{OBJ}}) sur les 20 derniers mètres. Récupère 60 sec en marchant entre chaque.', retour:'',
        note:'Prépare tes affaires ce soir. Visualise les premiers kilomètres à {{OBJ}}/km.' },
      { jour:'Dimanche', type:'Course', titre:'MARATHON', duree:'Jour J',
        echauff:'10-15 min de jogging très léger avant le départ.',
        corps:'KM 1-8 : pars à {{OBJ}}/km exactement. KM 9-21 : régularité absolue, gel à chaque ravitaillement. KM 22-30 : maintiens {{OBJ}}, écoute ton corps. KM 31-35 : raccourcis la foulée, garde les bras actifs. KM 36-42 : donne absolument tout.',
        retour:'20-30 min de marche. Ravitaillement dans les 30 min.',
        note:'La douleur aux km 30-35 est normale. C\'est là que se gagne un marathon. Tiens bon.' },
    ]},
]
