// Marathon 16 semaines · 4 séances/semaine · Palier Intermédiaire (VMA 13.5 à 18.5)
// {{P}} remplacé séquentiellement · {{OBJ}} = allure objectif marathon (80% VMA)
module.exports = [
  { num:1, phase:'Fondamentaux', charge:'Légère',
    objectif:'4 séances pour poser les bases : deux EF encadrant la qualité et une SL pour ancrer le rythme hebdomadaire.',
    conseil:'La 4e séance est un second EF le vendredi. Garder ces deux footings vraiment faciles te permet de te concentrer sur la qualité du jeudi.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}. Début de préparation. Rythme conversationnel. Poser les jalons mentaux de la semaine.', retour:'',
        note:'RPE 3/10 · Légèreté absolue.' },
      { jour:'Mercredi', type:'Fractionné', titre:'6 × 400 mètres, réveil neuromusculaire', duree:'45 min', pcts:[[65,65],[90,95]],
        echauff:'20 min progressif à {{P}}, finir par 4 accélérations de 60m.',
        corps:'6 × 400 mètres à {{P}}. Récupération 90 sec au trot. Effort soutenu et régulier. Mémorise tes sensations sur chaque répétition.',
        retour:'10 min footing très lent.',
        note:'RPE 6-7/10 · Première séance de qualité. Découverte des allures.' },
      { jour:'Vendredi', type:'EF', titre:'Footing de récupération 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}. Récupération active après les 400m. Corps en mouvement, jambes qui roulent.', retour:'',
        note:'RPE 3/10 · Ce footing prépare la SL de dimanche.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 70 minutes', duree:'70 min', pcts:[[65,65]],
        echauff:'', corps:'70 min à {{P}}. Rythme conversationnel. Hydrate-toi. Mécanise la foulée.', retour:'',
        note:'RPE 4/10 · La durée prime. Si tu dois ralentir, ralentis.' },
    ]},

  { num:2, phase:'Fondamentaux', charge:'Légère',
    objectif:'Côtes jeudi, SL qui progresse. Volume total légèrement en hausse.',
    conseil:'Les côtes renforcent la puissance spécifique course. Tu en feras régulièrement tout au long du plan. Maitriser la technique dès maintenant.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}. Début de semaine, corps en mouvement.', retour:'',
        note:'RPE 3/10 · Léger.' },
      { jour:'Mercredi', type:'Côtes', titre:'8 côtes de 80 mètres', duree:'45 min', pcts:[[65,65],[100,105]],
        echauff:'20 min progressif à {{P}}, finir par 4 foulées bondissantes.',
        corps:'8 côtes de 80 mètres à effort maximal. Récupération : redescente en marchant. Appui avant-pied, genoux hauts, bras dynamiques.',
        retour:'10 min footing très lent.',
        note:'RPE 8/10 sur chaque côte · Effort bref. Récupération complète.' },
      { jour:'Vendredi', type:'EF', titre:'Footing de récupération 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}. Corps en mouvement après les côtes.', retour:'',
        note:'RPE 3/10 · Active la récupération.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 80 minutes', duree:'80 min', pcts:[[65,65]],
        echauff:'', corps:'80 min à {{P}}. Terrain varié. Mécanise la foulée.', retour:'',
        note:'RPE 4/10 · 10 min de plus que S1.' },
    ]},

  { num:3, phase:'Fondamentaux', charge:'Modérée',
    objectif:'Première séance tempo. Introduction seuil en douceur avec 2 × 10 min.',
    conseil:'Le seuil : inconfortable mais tenable 10-15 min. Si tu ne peux pas prononcer un mot, tu vas trop vite.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}. Corps en mouvement en début de semaine.', retour:'',
        note:'RPE 3/10 · Léger.' },
      { jour:'Mercredi', type:'Tempo', titre:'2 × 10 minutes au seuil aérobie', duree:'50 min', pcts:[[65,70],[80,84]],
        echauff:'20 min progressif à {{P}}, finir par 4 accélérations de 60m.',
        corps:'2 × 10 min à {{P}} avec 3 min de récupération au trot. Maintiens une allure régulière. Premier vrai contact avec le seuil.',
        retour:'10 min footing très lent.',
        note:'RPE 7/10 · 20 min totales au seuil. N\'accélère pas sur le 2e bloc.' },
      { jour:'Vendredi', type:'EF', titre:'Footing de récupération 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}. Récupération active.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 85 minutes', duree:'85 min', pcts:[[65,65]],
        echauff:'', corps:'85 min à {{P}}. Régulier, hydraté.', retour:'',
        note:'RPE 4/10 · Progression régulière.' },
    ]},

  { num:4, phase:'Fondamentaux', charge:'Modérée',
    objectif:'4 × 1000m pour développer la VMA. La SL atteint 90 min. Fin de la phase fondamentaux.',
    conseil:'Pars conservateur sur le 1er 1000m. La régularité sur les 4 répétitions prime sur la vitesse.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}. Semaine chargée. Récupère bien après mercredi.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mercredi', type:'Fractionné', titre:'4 × 1000 mètres, développement VMA', duree:'55 min', pcts:[[65,65],[85,92]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
        corps:'4 × 1000 mètres à {{P}}. Récupération 2 min au trot. Régularité entre les répétitions. Même allure du 1er au 4e.',
        retour:'10 min footing très lent.',
        note:'RPE 7-8/10 · Régularité sur les 4 avant tout.' },
      { jour:'Vendredi', type:'EF', titre:'Footing de récupération 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}. Récupération après les 1000m.', retour:'',
        note:'RPE 3/10 · Prépare la SL.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 90 minutes', duree:'90 min', pcts:[[65,65]],
        echauff:'', corps:'90 min à {{P}}. Premier cap symbolique. Hydrate-toi toutes les 20 min.', retour:'',
        note:'RPE 4-5/10 · Cap des 90 min franchi.' },
    ]},

  { num:5, phase:'Développement', charge:'Moyenne',
    objectif:'5 × 1000m et la SL passe le cap des 100 min. Le développement VMA monte d\'un cran.',
    conseil:'Un intervalle de plus que la semaine passée. La progression est intentionnelle. Tiens la même allure sur les 5.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 45 minutes', duree:'45 min', pcts:[[65,65]],
        echauff:'', corps:'45 min à {{P}}.', retour:'',
        note:'RPE 4/10.' },
      { jour:'Mercredi', type:'Fractionné', titre:'5 × 1000 mètres, montée en charge VMA', duree:'60 min', pcts:[[65,65],[85,92]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
        corps:'5 × 1000 mètres à {{P}}. Récupération 2 min au trot. Un de plus que S4. Maintiens la même allure du 1er au 5e.',
        retour:'10 min footing très lent.',
        note:'RPE 7-8/10 · Si le 5e est trop facile, tu n\'es pas allé assez vite.' },
      { jour:'Vendredi', type:'EF', titre:'Footing fondamental 45 minutes', duree:'45 min', pcts:[[65,65]],
        echauff:'', corps:'45 min à {{P}}.', retour:'',
        note:'RPE 4/10.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 100 minutes', duree:'100 min', pcts:[[65,65]],
        echauff:'', corps:'100 min à {{P}}. Gel recommandé à 1h pour t\'habituer à la nutrition.', retour:'',
        note:'RPE 5/10 · Dès 90 min, la nutrition entre en jeu. Teste maintenant.' },
    ]},

  { num:6, phase:'Développement', charge:'Moyenne',
    objectif:'2 × 15 min au seuil, SL à 1h50. La construction tempo prend de l\'ampleur.',
    conseil:'2 × 15 min au seuil : le 1er bloc à {{P}} conservateur, le 2e au même niveau. Pas d\'accélération intempestive.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 45 minutes', duree:'45 min', pcts:[[65,65]],
        echauff:'', corps:'45 min à {{P}}.', retour:'',
        note:'RPE 4/10.' },
      { jour:'Mercredi', type:'Tempo', titre:'2 × 15 minutes au seuil aérobie', duree:'60 min', pcts:[[65,70],[82,87]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
        corps:'2 × 15 min à {{P}} avec 4 min de récupération. 30 min au seuil. Régularité sur les 2 blocs.',
        retour:'10 min footing très lent.',
        note:'RPE 7-8/10 · 30 min au seuil. Pars conservateur.' },
      { jour:'Vendredi', type:'EF', titre:'Footing fondamental 45 minutes', duree:'45 min', pcts:[[65,65]],
        echauff:'', corps:'45 min à {{P}}.', retour:'',
        note:'RPE 4/10.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 1h50', duree:'1h50', pcts:[[65,65]],
        echauff:'', corps:'1h50 à {{P}}. Gel à 1h. Hydratation systématique.', retour:'',
        note:'RPE 5/10.' },
    ]},

  { num:7, phase:'Développement', charge:'Élevée',
    objectif:'3 × 2000m fractionnés longs. SL à 2h pour la première fois. Grosse semaine.',
    conseil:'Les 2000m sont différents des 1000m : la gestion d\'allure sur 2000m est cruciale. Pars plus prudemment.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 50 minutes', duree:'50 min', pcts:[[65,65]],
        echauff:'', corps:'50 min à {{P}}. Grosse semaine, reste conservateur sur ce footing.', retour:'',
        note:'RPE 4/10.' },
      { jour:'Mercredi', type:'Fractionné', titre:'3 × 2000 mètres, fractionnés longs', duree:'65 min', pcts:[[65,65],[80,85]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
        corps:'3 × 2000 mètres à {{P}}. Récupération 4 min au trot. Régulier et soutenu sur les 3 blocs.',
        retour:'10 min footing très lent.',
        note:'RPE 8/10 · Gère le 1er prudemment.' },
      { jour:'Vendredi', type:'EF', titre:'Footing de récupération 45 minutes', duree:'45 min', pcts:[[65,65]],
        echauff:'', corps:'45 min à {{P}}. Récupération active entre les 2000m et la SL.', retour:'',
        note:'RPE 4/10.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 2 heures', duree:'2h', pcts:[[65,65]],
        echauff:'', corps:'2h à {{P}}. Gel à 1h et à 1h20. Hydratation systématique.', retour:'',
        note:'RPE 5/10 · 2h de course, premier cap majeur.' },
    ]},

  { num:8, phase:'Développement', charge:'Élevée',
    objectif:'2 × 3000m progressifs. SL à 2h10. Fin de phase développement.',
    conseil:'Les 3000m se courent en progression interne : commence le 1er km plus doucement, accélère sur le 2e et 3e.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 50 minutes', duree:'50 min', pcts:[[65,65]],
        echauff:'', corps:'50 min à {{P}}. Deux grosses séances t\'attendent. Préserve-toi.', retour:'',
        note:'RPE 4/10.' },
      { jour:'Mercredi', type:'Fractionné', titre:'2 × 3000 mètres progressifs', duree:'65 min', pcts:[[65,65],[80,82],[82,85],[85,88]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
        corps:'2 × 3000 mètres à {{P}}. Récupération 5 min. Chaque 3000m en progression : 1er km à {{P}}, 2e km à {{P}}, 3e km à {{P}}. Accélère légèrement à chaque km.',
        retour:'10 min footing très lent.',
        note:'RPE 8/10 · La progression interne est la vraie difficulté.' },
      { jour:'Vendredi', type:'EF', titre:'Footing de récupération 45 minutes', duree:'45 min', pcts:[[65,65]],
        echauff:'', corps:'45 min à {{P}}. Récupération active. Prépare la SL.', retour:'',
        note:'RPE 4/10.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 2h10', duree:'2h10', pcts:[[65,65]],
        echauff:'', corps:'2h10 à {{P}}. Gel à 1h et à 1h25. La phase spécifique commence la semaine prochaine.', retour:'',
        note:'RPE 5-6/10 · Dernière grande SL sans bloc OBJ.' },
    ]},

  { num:9, phase:'Spécificité marathon', charge:'Élevée',
    objectif:'Entrée spécifique : côtes + premier bloc OBJ en SL. Les jambes apprennent l\'allure marathon.',
    conseil:'Le bloc OBJ en fin de SL est l\'entraînement le plus spécifique du marathon. Mémorise l\'allure : c\'est celle que tu devras tenir 42 km le jour J.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 50 minutes', duree:'50 min', pcts:[[65,65]],
        echauff:'', corps:'50 min à {{P}}. Début de la phase spécifique. Les footings maintiennent le volume de base.', retour:'',
        note:'RPE 4/10.' },
      { jour:'Mercredi', type:'Côtes', titre:'10 côtes de 80 mètres, puissance marathon', duree:'50 min', pcts:[[65,65],[100,105]],
        echauff:'20 min progressif à {{P}}, finir par 4 foulées bondissantes.',
        corps:'10 côtes de 80 mètres à effort maximal. Récupération : redescente en marchant. Renforcement des extenseurs de hanche et mollets.',
        retour:'10 min footing très lent.',
        note:'RPE 8/10 · 10 côtes. Qualité sur chacune.' },
      { jour:'Vendredi', type:'EF', titre:'Footing de récupération 45 minutes', duree:'45 min', pcts:[[65,65]],
        echauff:'', corps:'45 min à {{P}}. Récupération après les côtes. Prépare la grande SL.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 2h avec 20 min allure marathon', duree:'2h', pcts:[[65,72],[75,80]],
        echauff:'', corps:'100 min à {{P}}, puis 20 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h. Mémorise la sensation de {{OBJ}}.', retour:'',
        note:'RPE 6/10 en EF · 7/10 sur les 20 min.' },
    ]},

  { num:10, phase:'Spécificité marathon', charge:'Élevée',
    objectif:'3 × 15 min au seuil + SL 2h10 avec 25 min OBJ. Double pression qualité et volume.',
    conseil:'3 × 15 min au seuil est une séance de référence. Si les 3 blocs tiennent avec régularité, la forme marathon est au rendez-vous.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 50 minutes', duree:'50 min', pcts:[[65,65]],
        echauff:'', corps:'50 min à {{P}}. Deux séances majeures t\'attendent cette semaine.', retour:'',
        note:'RPE 4/10.' },
      { jour:'Mercredi', type:'Tempo', titre:'3 × 15 minutes au seuil', duree:'75 min', pcts:[[65,70],[82,87]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
        corps:'3 × 15 min à {{P}} avec 4 min de récupération. 45 min totales au seuil. Régularité sur les 3 blocs.',
        retour:'10 min footing très lent.',
        note:'RPE 8/10 · 45 min au seuil. Séance de référence marathon.' },
      { jour:'Vendredi', type:'EF', titre:'Footing de récupération 45 minutes', duree:'45 min', pcts:[[65,65]],
        echauff:'', corps:'45 min à {{P}}. Récupération active avant la grande SL.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 2h10 avec 25 min allure marathon', duree:'2h10', pcts:[[65,72],[75,80]],
        echauff:'', corps:'105 min à {{P}}, puis 25 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h et à 1h20.', retour:'',
        note:'RPE 6/10 en EF · 7-8/10 sur les 25 min.' },
    ]},

  { num:11, phase:'Spécificité marathon', charge:'Maximale',
    objectif:'2 × 5000m spécifique marathon + SL 2h20 avec 30 min OBJ. Semaine de charge maximale.',
    conseil:'Le 2 × 5000m est la séance reine du plan. 10 km à allure marathon avec récupération. Si tu le tiens, tu es en route vers ton objectif.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 50 minutes', duree:'50 min', pcts:[[65,65]],
        echauff:'', corps:'50 min à {{P}}. Semaine de charge maximale. Ce footing maintient le volume sans entamer les réserves.', retour:'',
        note:'RPE 4/10 · Conserve l\'énergie pour les séances clés.' },
      { jour:'Mercredi', type:'Fractionné', titre:'2 × 5000 mètres à allure marathon', duree:'80 min', pcts:[[65,65],[78,82]],
        echauff:'20 min progressif à {{P}}, finir par 4 accélérations de 80m.',
        corps:'2 × 5000 mètres à {{P}}. Récupération 5 min au trot. Pars conservateur sur le 1er. Le 2e doit être aussi régulier que le 1er, ou légèrement plus rapide.',
        retour:'10 min footing très lent.',
        note:'RPE 7-8/10 · 10 km à allure marathon avec récupération. La séance la plus spécifique du plan.' },
      { jour:'Vendredi', type:'EF', titre:'Footing de récupération 45 minutes', duree:'45 min', pcts:[[65,65]],
        echauff:'', corps:'45 min à {{P}}. Récupération avant la grande sortie dimanche.', retour:'',
        note:'RPE 3/10 · Vital avant la SL 2h20.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 2h20 avec 30 min allure marathon', duree:'2h20', pcts:[[65,72],[75,80]],
        echauff:'', corps:'110 min à {{P}}, puis 30 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h, 1h20, 1h40.', retour:'',
        note:'RPE 6/10 en EF · 8/10 sur les 30 min · Le bloc OBJ final révèle ta forme.' },
    ]},

  { num:12, phase:'Spécificité marathon', charge:'Maximale',
    objectif:'LE pic de charge. Séance finisher + grande SL 2h30 avec 30 min OBJ. La semaine la plus importante du plan.',
    conseil:'Après cette semaine, le plus dur est derrière toi. La SL 2h30 est la sortie de référence. Elle ancre la confiance pour le jour J.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 50 minutes', duree:'50 min', pcts:[[65,65]],
        echauff:'', corps:'50 min à {{P}}. Dernière grosse semaine. Ce footing prépare le corps avant deux séances majeures.', retour:'',
        note:'RPE 4/10.' },
      { jour:'Mercredi', type:'Tempo', titre:'Séance finisher, 5 km seuil + 3 × 3 km allure marathon', duree:'90 min', pcts:[[65,65],[80,85],[78,82]],
        echauff:'20 min footing EF à {{P}}.',
        corps:'5 km à {{P}} (effort seuil) → 5 min de récupération → 3 × 3 km à ton allure objectif marathon ({{OBJ}}), récupération 3 min. La transition seuil vers allure marathon simule les exigences de la course.',
        retour:'10 min footing léger.',
        note:'RPE 8/10 · Si tu tiens les 3 blocs à {{OBJ}} après le seuil, tu es en parfaite forme.' },
      { jour:'Vendredi', type:'EF', titre:'Footing de récupération 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}. Récupération légère avant la grande SL.', retour:'',
        note:'RPE 3/10 · Ménage-toi pour la SL de dimanche.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Grande sortie longue 2h30 avec 30 min allure marathon', duree:'2h30', pcts:[[65,72],[75,80]],
        echauff:'', corps:'120 min à {{P}}, puis 30 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h, 1h20, 1h40, 2h. LA grande sortie du plan.', retour:'',
        note:'RPE 6/10 en EF · 8/10 sur les 30 min · Le pic est atteint. La récupération commence maintenant.' },
    ]},

  { num:13, phase:'Pic de charge', charge:'Élevée (légère réduction)',
    objectif:'Volume légèrement réduit (-15%). Maintien de l\'intensité avec 4 × 3 km OBJ. Consolidation.',
    conseil:'Pas d\'affûtage encore. C\'est une consolidation. L\'intensité reste là pour ancrer les adaptations de S12.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 45 minutes', duree:'45 min', pcts:[[65,65]],
        echauff:'', corps:'45 min à {{P}}.', retour:'',
        note:'RPE 4/10.' },
      { jour:'Mercredi', type:'Fractionné', titre:'4 × 3 km à allure marathon', duree:'80 min', pcts:[[65,65],[78,82]],
        echauff:'20 min footing EF à {{P}}.',
        corps:'4 × 3 km à ton allure objectif marathon ({{OBJ}}). Récupération 3 min au trot. 12 km à {{OBJ}} en blocs.',
        retour:'10 min footing léger.',
        note:'RPE 7-8/10 · Maintien de la mémoire allure marathon.' },
      { jour:'Vendredi', type:'EF', titre:'Footing de récupération 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 2h15 avec 30 min allure marathon', duree:'2h15', pcts:[[65,72],[75,80]],
        echauff:'', corps:'105 min à {{P}}, puis 30 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h, 1h20, 1h40.', retour:'',
        note:'RPE 6/10 en EF · 8/10 sur les 30 min.' },
    ]},

  { num:14, phase:'Pic de charge', charge:'Réduite, pré-affûtage',
    objectif:'Volume réduit (-30%). Maintien VMA avec 4 × 1500m. SL allégée. Début de la super-compensation.',
    conseil:'L\'affûtage commence. Le corps entre en phase de recharge. Laisse-le récupérer activement.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}.', retour:'',
        note:'RPE 3-4/10.' },
      { jour:'Mercredi', type:'Fractionné', titre:'4 × 1500 mètres, maintien VMA pré-affûtage', duree:'60 min', pcts:[[65,65],[83,90]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
        corps:'4 × 1500 mètres à {{P}}. Récupération 3 min. Intervalles plus courts : maintien des sensations VMA sans fatigue excessive.',
        retour:'10 min footing très lent.',
        note:'RPE 7/10 · Moins de volume, mêmes sensations.' },
      { jour:'Vendredi', type:'EF', titre:'Footing de récupération 35 minutes', duree:'35 min', pcts:[[65,65]],
        echauff:'', corps:'35 min à {{P}}. Corps en mouvement, jambes légères.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 1h50 avec 15 min allure marathon', duree:'1h50', pcts:[[65,72],[75,80]],
        echauff:'', corps:'95 min à {{P}}, puis 15 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h.', retour:'',
        note:'RPE 5/10 en EF · 7/10 sur les 15 min · Allégée mais maintien des sensations.' },
    ]},

  { num:15, phase:'Consolidation', charge:'Réduite, affûtage',
    objectif:'4 séances légères pour laisser les adaptations s\'installer. Volume réduit de 45%.',
    conseil:'Dors 8h, mange bien. Les jambes doivent commencer à fourmiller d\'impatience. Ne rajoute pas de séances.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing léger 35 minutes', duree:'35 min', pcts:[[65,65]],
        echauff:'', corps:'35 min très faciles à {{P}}. Corps en mouvement en début de semaine d\'affûtage.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mercredi', type:'Tempo', titre:'2 × 15 minutes au seuil, volume réduit', duree:'55 min', pcts:[[65,72],[82,88]],
        echauff:'25 min progressif à {{P}}.', corps:'2 × 15 min à {{P}}. Volume réduit de 50% mais intensité maintenue. Récupération 4 min. Termine par 1 km à ton allure marathon ({{OBJ}}).', retour:'10 min footing très lent.',
        note:'RPE 7/10 · Maintien des sensations sans épuisement.' },
      { jour:'Vendredi', type:'EF', titre:'Footing léger 35 minutes', duree:'35 min', pcts:[[65,65]],
        echauff:'', corps:'35 min à {{P}}. Inclus 4 à 6 accélérations de 60m à allure marathon.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Dimanche', type:'EF', titre:'Footing léger 30 minutes', duree:'30 min', pcts:[[60,65]],
        echauff:'', corps:'30 min très légers à {{P}}. Dernier footing de l\'affûtage. Jambes légères.', retour:'',
        note:'RPE 3/10 · Tu dois finir frais et dynamisé.' },
    ]},

  { num:16, phase:'Semaine de course', charge:'Conserve, tu es prêt',
    objectif:'Arriver au départ reposé, confiant, les jambes fraîches. 15 semaines de travail ont été faites.',
    conseil:'Pars à {{OBJ}}/km dès le départ. L\'adrénaline va te pousser à aller plus vite, résiste.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing très léger 30 minutes', duree:'30 min', pcts:[[60,65]],
        echauff:'', corps:'30 min à {{P}}. Maintenir la circulation. Si tu te sens fatigué, réduis à 20 min.', retour:'',
        note:'RPE 3/10 · Aucun effort.' },
      { jour:'Mercredi', type:'Fractionné', titre:'8 × 1 min / 1 min à allure marathon', duree:'40 min',
        echauff:'15 min de footing très léger.',
        corps:'8 × 1 minute à ton allure objectif marathon ({{OBJ}}) / 1 minute au trot. Réveille les jambes sans les fatiguer.',
        retour:'10 min de jogging léger.',
        note:'RPE 6/10 · Maintien des sensations avant le marathon.' },
      { jour:'Samedi', type:'Activation', titre:'Activation J-1 + accélérations', duree:'30 min', pcts:[[60,65]],
        echauff:'', corps:'20 min de trot à {{P}}. Puis 6 à 8 accélérations progressives de 80m jusqu\'à ton allure objectif ({{OBJ}}). Récupère 60 sec en marchant.', retour:'',
        note:'Prépare tes affaires ce soir. Visualise les premiers kilomètres à {{OBJ}}/km.' },
      { jour:'Dimanche', type:'Course', titre:'MARATHON', duree:'Jour J',
        echauff:'10-15 min de jogging très léger avant le départ.',
        corps:'KM 1-8 : pars à {{OBJ}}/km exactement. KM 9-21 : régularité absolue, gel à chaque ravitaillement. KM 22-30 : maintiens {{OBJ}}, écoute ton corps. KM 31-35 : raccourcis la foulée, garde les bras actifs. KM 36-42 : donne absolument tout.',
        retour:'20-30 min de marche. Ravitaillement dans les 30 min.',
        note:'La douleur aux km 30-35 est normale. C\'est là que se gagne un marathon. Tiens bon.' },
    ]},
]
