// Marathon 16 semaines · 5 séances/semaine · Palier Intermédiaire (VMA 13.5 à 18.5)
// 5 séances : 2 qualités + EF récupération + EF long + SL
// {{P}} remplacé séquentiellement · {{OBJ}} = allure objectif marathon (80% VMA)
module.exports = [
  { num:1, phase:'Fondamentaux', charge:'Légère',
    objectif:'5 séances pour initier le rythme. Deux EF encadrent la qualité, la SL fonde l\'endurance de base.',
    conseil:'Ne cherche pas à te prouver quoi que ce soit. La première semaine d\'un plan à 5 séances peut sembler intense. Les deux EF doivent être vraiment faciles.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}. Coup d\'envoi de 16 semaines de préparation. Sur 5 séances hebdomadaires, ce lundi EF est la fondation silencieuse de chaque semaine. Corps en mouvement, allure conversationnelle, jambes légères. Aucune pression physique — l\'objectif est de créer l\'habitude.', retour:'',
        note:'RPE 3/10 · Légèreté absolue.' },
      { jour:'Mardi', type:'EF', titre:'Footing de récupération 35 minutes', duree:'35 min', pcts:[[60,62]],
        echauff:'', corps:'35 min à {{P}}, plus lentement que l\'allure fondamentale. Ce footing de récupération actif prépare les jambes pour les 400m de mercredi. Moins vite tu cours ici, plus tu seras frais sur la qualité. Circulation sanguine, foulée décontractée.', retour:'',
        note:'RPE 3/10 · Préserve-toi pour le mercredi.' },
      { jour:'Mercredi', type:'Fractionné', titre:'6 × 400 mètres, réveil neuromusculaire', duree:'45 min', pcts:[[65,65],[90,95]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 60m.',
        corps:'6 × 400 mètres à {{P}}. Récupération 90 sec au trot entre chaque. Effort soutenu et régulier sur les 6 répétitions. Première prise de contact avec les allures rapides : ne cherche pas à performer, cherche à ressentir la régularité.',
        retour:'10 min footing très lent.',
        note:'RPE 6-7/10 · Découverte des allures.' },
      { jour:'Vendredi', type:'EF', titre:'Footing fondamental 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}. Récupération active entre les 400m de mercredi et la SL de dimanche. Ce footing léger du vendredi est essentiel pour arriver frais sur la première sortie longue. Foulée souple, respiration naturelle, aucune ambition de vitesse.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 70 minutes', duree:'70 min', pcts:[[65,65]],
        echauff:'', corps:'70 min à {{P}}, rythme conversationnel tout au long. Première sortie longue du plan — la durée prime sur l\'allure, ralentis si tu dois parler. Hydrate-toi même si tu n\'as pas soif. Ces 70 min posent les bases mentales de l\'endurance marathon.', retour:'',
        note:'RPE 4/10 · La durée prime sur l\'allure.' },
    ]},

  { num:2, phase:'Fondamentaux', charge:'Légère',
    objectif:'Côtes + 2e qualité vendredi. Le plan à 5 séances introduit une 2e qualité dès S2.',
    conseil:'La 2e qualité vendredi est intentionnellement légère : accélérations et seuil court. Ne transforme pas ce vendredi en séance dure.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}. Les côtes arrivent mercredi — garde ce lundi vraiment facile pour arriver frais sur les 8 côtes. Deux qualités t\'attendent cette semaine. Ce footing lundi est le carburant silencieux qui les rend possibles.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mardi', type:'EF', titre:'Footing de récupération 35 minutes', duree:'35 min', pcts:[[60,62]],
        echauff:'', corps:'35 min à {{P}}, plus lentement que l\'EF standard. Les côtes mercredi demandent de l\'explosivité sur chaque montée — arrive frais. Ce footing très doux du mardi préserve les fibres musculaires pour l\'effort maximal de demain.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mercredi', type:'Côtes', titre:'8 côtes de 80 mètres', duree:'45 min', pcts:[[65,65],[100,105]],
        echauff:'25 min progressif à {{P}}, finir par 4 foulées bondissantes.',
        corps:'8 côtes de 80 mètres à effort maximal. Récupération : redescente en marchant (2 min). Appui avant-pied, genoux hauts, bras dynamiques. Les côtes recrutent les fibres rapides sans la fatigue de la piste — 8 sprints brefs et explosifs.',
        retour:'10 min footing très lent.',
        note:'RPE 8/10 sur chaque côte.' },
      { jour:'Vendredi', type:'Tempo', titre:'2 × 8 minutes au seuil, introduction légère', duree:'45 min', pcts:[[65,70],[80,83]],
        echauff:'25 min progressif à {{P}}.',
        corps:'2 × 8 min à {{P}} avec 3 min de récupération au trot. Introduction progressive au seuil — 16 min totales. Tu dois pouvoir prononcer quelques mots mais pas tenir une vraie conversation. 2e qualité de la semaine, intentionnellement légère.',
        retour:'10 min footing très lent.',
        note:'RPE 6-7/10 · Introduction légère au seuil. 2e qualité de la semaine.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 80 minutes', duree:'80 min', pcts:[[65,65]],
        echauff:'', corps:'80 min à {{P}}, 10 min de plus que S1. Terrain varié si possible — les changements de surface renforcent les appuis. Mécanise la foulée sur les parties plates. Hydrate-toi toutes les 20-25 min.', retour:'',
        note:'RPE 4/10.' },
    ]},

  { num:3, phase:'Fondamentaux', charge:'Modérée',
    objectif:'Séance seuil mercredi + 4 × 1000m vendredi. La 2e qualité gagne en intensité.',
    conseil:'Deux qualités dans la semaine exigent une gestion de l\'énergie rigoureuse. Les EF lundi et mardi sont vraiment légers.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}. Deux qualités t\'attendent cette semaine : 2 × 10 min seuil mercredi et 4 × 1000m vendredi. Ce lundi léger pose la fondation de ta gestion d\'énergie. Vraiment facile, foulée économique, sans montre si tu veux.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mardi', type:'EF', titre:'Footing de récupération 35 minutes', duree:'35 min', pcts:[[60,62]],
        echauff:'', corps:'35 min à {{P}}, allure très douce. La séance seuil mercredi est ta première vraie qualité tempo — arrive bien reposé. Ce footing lent du mardi est une récupération active, pas un entraînement.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mercredi', type:'Tempo', titre:'2 × 10 minutes au seuil', duree:'50 min', pcts:[[65,70],[80,84]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 60m.',
        corps:'2 × 10 min à {{P}} avec 3 min de récupération au trot. Effort soutenu et régulier sur les 2 blocs. Le seuil : l\'allure où tu peux prononcer quelques mots mais plus tenir une vraie conversation. Pas d\'accélération intempestive sur le 2e bloc.',
        retour:'10 min footing très lent.',
        note:'RPE 7/10 · 20 min au seuil.' },
      { jour:'Vendredi', type:'Fractionné', titre:'4 × 1000 mètres', duree:'55 min', pcts:[[65,65],[85,92]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
        corps:'4 × 1000 mètres à {{P}}. Récupération 2 min au trot entre chaque. Même allure du 1er au 4e. Après le seuil de mercredi, pars conservateur sur le 1er intervalle — mieux finir fort que partir trop vite.',
        retour:'10 min footing très lent.',
        note:'RPE 7-8/10 · 2e qualité de la semaine.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 85 minutes', duree:'85 min', pcts:[[65,65]],
        echauff:'', corps:'85 min à {{P}}, 5 min de plus que S2. La progression est régulière et volontaire — ne cherche pas à aller plus vite. Hydrate-toi toutes les 20-25 min. La constance sur les sorties longues hebdomadaires construit le marathonien.', retour:'',
        note:'RPE 4/10.' },
    ]},

  { num:4, phase:'Fondamentaux', charge:'Modérée',
    objectif:'Montée en charge : 2 × 15 min seuil mercredi + 5 × 1000m vendredi. La SL à 90 min.',
    conseil:'Semaine la plus chargée des fondamentaux. Les deux qualités doivent être séparées de 2 jours (mercredi/vendredi) pour permettre une récupération suffisante.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}. Semaine la plus chargée des fondamentaux : 2 × 15 min seuil + 5 × 1000m + SL 90 min. Ce lundi léger pose les fondations de ta gestion d\'énergie de la semaine. Terrain souple, effort invisible, rythme de croisière économique.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mardi', type:'EF', titre:'Footing de récupération 35 minutes', duree:'35 min', pcts:[[60,62]],
        echauff:'', corps:'35 min à {{P}}, allure vraiment douce. Le 2 × 15 min seuil mercredi est la séance la plus exigeante jusqu\'ici. Arrive bien reposé. Ce footing léger prépare les fibres musculaires à l\'effort soutenu.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mercredi', type:'Tempo', titre:'2 × 15 minutes au seuil aérobie', duree:'60 min', pcts:[[65,70],[82,87]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
        corps:'2 × 15 min à {{P}} avec 4 min de récupération au trot. 30 min totales au seuil. Régularité absolue sur les 2 blocs — le 2e doit être aussi régulier que le 1er. Si tu craques sur le 2e, tu es parti trop vite sur le 1er.',
        retour:'10 min footing très lent.',
        note:'RPE 7-8/10 · 30 min au seuil. Pars conservateur.' },
      { jour:'Vendredi', type:'Fractionné', titre:'5 × 1000 mètres', duree:'60 min', pcts:[[65,65],[85,92]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
        corps:'5 × 1000 mètres à {{P}}. Récupération 2 min au trot. Même allure du 1er au 5e. Après le seuil de mercredi, pars conservateur — la régularité sur les 5 répétitions est l\'objectif principal.',
        retour:'10 min footing très lent.',
        note:'RPE 7-8/10 · Semaine à 2 qualités ambitieuses. Gère bien l\'énergie.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 90 minutes', duree:'90 min', pcts:[[65,65]],
        echauff:'', corps:'90 min à {{P}}, premier cap symbolique de la préparation. Hydrate-toi toutes les 20 min. Gel recommandé à 1h pour commencer à habituer le corps à la nutrition en course. La phase développement commence la semaine prochaine.', retour:'',
        note:'RPE 4-5/10 · Cap des 90 min.' },
    ]},

  { num:5, phase:'Développement', charge:'Moyenne',
    objectif:'3 × 2000m mercredi + 2 × 15 min seuil vendredi. La 2e qualité renforce le seuil pendant que la 1re monte vers les longs intervalles.',
    conseil:'3 × 2000m est une étape clé. Les 2000m demandent plus de gestion d\'allure que les 1000m. Pars plus prudemment.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 45 minutes', duree:'45 min', pcts:[[65,65]],
        echauff:'', corps:'45 min à {{P}}. Phase développement : les footings s\'allongent légèrement. Les 3 × 2000m mercredi marquent un cap — 2 km en continu demandent plus de gestion d\'allure. Ce lundi léger est la fondation de la semaine.', retour:'',
        note:'RPE 4/10.' },
      { jour:'Mardi', type:'EF', titre:'Footing de récupération 40 minutes', duree:'40 min', pcts:[[60,62]],
        echauff:'', corps:'40 min à {{P}}, plus lentement que l\'allure EF. Les 3 × 2000m arrivent mercredi — des jambes fraîches font toute la différence sur les longs intervalles. Ce footing très doux du mardi protège les réserves énergétiques.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mercredi', type:'Fractionné', titre:'3 × 2000 mètres, fractionnés longs', duree:'65 min', pcts:[[65,65],[80,85]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
        corps:'3 × 2000 mètres à {{P}}. Récupération 4 min au trot. Régulier sur les 3 blocs. Les 2000m sont plus longs que les 1000m — la gestion de l\'allure sur 2 km est un nouveau défi. Commence prudemment sur le 1er.',
        retour:'10 min footing très lent.',
        note:'RPE 8/10 · Premier cap des 2000m.' },
      { jour:'Vendredi', type:'Tempo', titre:'2 × 15 minutes au seuil', duree:'60 min', pcts:[[65,70],[82,87]],
        echauff:'25 min progressif à {{P}}.',
        corps:'2 × 15 min à {{P}} avec 4 min de récupération. 30 min totales au seuil. Maintien du travail seuil pendant la phase développement. Après les 2000m de mercredi, la récupération de jeudi est critique pour tenir la régularité sur les 2 blocs.',
        retour:'10 min footing très lent.',
        note:'RPE 7-8/10 · 2e qualité. La récupération entre mercredi et vendredi est critique.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 100 minutes', duree:'100 min', pcts:[[65,65]],
        echauff:'', corps:'100 min à {{P}}. Première sortie au-delà de 90 min. Gel recommandé à 1h pour habituer le corps à la nutrition en course. Hydratation toutes les 20 min. À partir de maintenant, la nutrition fait partie intégrante de l\'entraînement.', retour:'',
        note:'RPE 5/10 · Dès 90 min, tester la nutrition.' },
    ]},

  { num:6, phase:'Développement', charge:'Moyenne',
    objectif:'Côtes mercredi + 2 × 3000m vendredi. Variation des stimuli pour un développement complet.',
    conseil:'Les côtes et les 3000m sollicitent des systèmes différents. Cette complémentarité est intentionnelle.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 45 minutes', duree:'45 min', pcts:[[65,65]],
        echauff:'', corps:'45 min à {{P}}. Côtes mercredi + 2 × 3000m vendredi — deux stimuli puissants. Ce lundi EF maintient le volume sans entamer les réserves. Terrain plat de préférence, foulée économique, aucune intensité voulue.', retour:'',
        note:'RPE 4/10.' },
      { jour:'Mardi', type:'EF', titre:'Footing de récupération 40 minutes', duree:'40 min', pcts:[[60,62]],
        echauff:'', corps:'40 min à {{P}}, allure très douce. Les côtes mercredi demandent une explosivité maximale — les jambes doivent être fraîches. Ce footing lent du mardi limite la fatigue résiduelle et prépare les fibres rapides pour l\'effort maximal.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mercredi', type:'Côtes', titre:'10 côtes de 80 mètres', duree:'50 min', pcts:[[65,65],[100,105]],
        echauff:'25 min progressif à {{P}}, finir par 4 foulées bondissantes.',
        corps:'10 côtes de 80 mètres à effort maximal. Récupération : redescente en marchant (2 min). Appui avant-pied, genoux hauts, bras dynamiques. 10 côtes développent la puissance des extenseurs de hanche — muscles clés aux km 30-35 du marathon.',
        retour:'10 min footing très lent.',
        note:'RPE 8/10 · 10 côtes. Qualité d\'effort sur chacune.' },
      { jour:'Vendredi', type:'Fractionné', titre:'2 × 3000 mètres progressifs', duree:'65 min', pcts:[[65,65],[80,82],[82,85],[85,88]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
        corps:'2 × 3000 mètres à {{P}}. Récupération 5 min. Chaque 3000m en progression interne : 1er km à {{P}}, 2e à {{P}}, 3e à {{P}}. Accélère légèrement à chaque km. La progression interne est la vraie difficulté de cette séance.',
        retour:'10 min footing très lent.',
        note:'RPE 8/10 · La progression interne est la clé.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 1h50', duree:'1h50', pcts:[[65,65]],
        echauff:'', corps:'1h50 à {{P}}. La SL progresse régulièrement. Gel à 1h. Hydratation toutes les 20 min. Après 2 qualités difficiles cette semaine, la SL doit rester à allure EF — ne cède pas à la tentation d\'accélérer en fin de sortie.', retour:'',
        note:'RPE 5/10.' },
    ]},

  { num:7, phase:'Développement', charge:'Élevée',
    objectif:'3 × 15 min seuil mercredi + 2 × 3000m progressifs vendredi. Double qualité intensive. Grosse semaine.',
    conseil:'Semaine la plus chargée de la phase développement. Les 2 EF (lundi/mardi) doivent être vraisemblablement faciles pour préserver l\'énergie.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 50 minutes', duree:'50 min', pcts:[[65,65]],
        echauff:'', corps:'50 min à {{P}}. Grosse semaine : 3 × 15 min seuil mercredi + 2 × 3000m progressifs vendredi. Ce footing lundi maintient le volume sans entamer les réserves pour les deux qualités majeures. Reste strictement à allure fondamentale.', retour:'',
        note:'RPE 4/10.' },
      { jour:'Mardi', type:'EF', titre:'Footing de récupération 40 minutes', duree:'40 min', pcts:[[60,62]],
        echauff:'', corps:'40 min à {{P}}, allure très douce. Le 3 × 15 min seuil mercredi — 45 min totales au seuil. Arrive frais. Ce footing très léger du mardi préserve chaque énergie disponible pour les deux qualités de la semaine.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mercredi', type:'Tempo', titre:'3 × 15 minutes au seuil', duree:'75 min', pcts:[[65,70],[82,87]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
        corps:'3 × 15 min à {{P}} avec 4 min de récupération. 45 min totales au seuil. Régularité sur les 3 blocs : le 3e doit être aussi fort que le 1er. Si tu craques sur le 3e, tu partais trop vite sur le 1er — le piège classique du seuil.',
        retour:'10 min footing très lent.',
        note:'RPE 8/10 · 45 min au seuil. Séance de référence.' },
      { jour:'Vendredi', type:'Fractionné', titre:'2 × 3000 mètres + 1 km allure marathon', duree:'70 min', pcts:[[65,65],[80,82],[82,85],[85,88],[78,82]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
        corps:'2 × 3000m à {{P}} (progressifs, récup 5 min), puis 3 min de récup et 1 km à ton allure objectif marathon ({{OBJ}}). Ce km à {{OBJ}} en fin de séance révèle comment ton allure cible se ressent sur des jambes fatiguées. Mémorise cette sensation.',
        retour:'10 min footing très lent.',
        note:'RPE 8/10 · Le km à {{OBJ}} en fin de séance révèle la sensation de l\'allure cible fatigué.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 2 heures', duree:'2h', pcts:[[65,65]],
        echauff:'', corps:'2h à {{P}}. Premier cap psychologique majeur. Gel à 1h et 1h20. Hydratation systématique. La deuxième heure est différente de la première : la concentration doit rester active. Mémorise comment ton corps gère cet effort long.', retour:'',
        note:'RPE 5/10 · 2h de course, cap majeur.' },
    ]},

  { num:8, phase:'Développement', charge:'Élevée',
    objectif:'2 × 5000m à allure marathon mercredi + 3 × 15 min seuil vendredi. Double qualité marathon et seuil.',
    conseil:'2 × 5000m à allure marathon est une séance de référence du plan. Pars prudemment : tu dois tenir la même allure sur les 2 × 5000m.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 50 minutes', duree:'50 min', pcts:[[65,65]],
        echauff:'', corps:'50 min à {{P}}. Deux séances majeures cette semaine : 2 × 5000m marathon mercredi et 3 × 15 min seuil vendredi. Ce lundi EF maintient le volume sans entamer les réserves. Allure vraiment fondamentale, aucune dérive de rythme.', retour:'',
        note:'RPE 4/10.' },
      { jour:'Mardi', type:'EF', titre:'Footing de récupération 40 minutes', duree:'40 min', pcts:[[60,62]],
        echauff:'', corps:'40 min à {{P}}, allure très douce. Les 2 × 5000m à allure marathon mercredi sont la première grande séance spécifique du plan — arrive frais. Ce footing très lent du mardi protège l\'énergie disponible pour l\'effort de demain.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mercredi', type:'Fractionné', titre:'2 × 5000 mètres à allure marathon', duree:'80 min', pcts:[[65,65],[78,82]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
        corps:'2 × 5000 mètres à {{P}}. Récupération 5 min au trot entre les 2 blocs. 10 km à allure marathon avec récupération. Pars conservateur sur le 1er — les sensations doivent sembler faciles les 3 premières minutes. Le 2e bloc est le vrai test.',
        retour:'10 min footing très lent.',
        note:'RPE 7-8/10 · La séance la plus spécifique jusqu\'ici.' },
      { jour:'Vendredi', type:'Tempo', titre:'3 × 15 minutes au seuil', duree:'75 min', pcts:[[65,70],[82,87]],
        echauff:'25 min progressif à {{P}}.',
        corps:'3 × 15 min à {{P}} avec 4 min de récupération. 45 min au seuil en complément des 2 × 5000m de mercredi. Semaine dense. Pars à l\'allure basse de la zone — le corps est déjà sollicité. Régularité sur les 3 blocs.',
        retour:'10 min footing très lent.',
        note:'RPE 7-8/10 · 2e qualité de la semaine. Gère l\'effort après les 5000m.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 2h10', duree:'2h10', pcts:[[65,65]],
        echauff:'', corps:'2h10 à {{P}}, dernière grande SL sans bloc OBJ. Gel à 1h et 1h25. Hydratation systématique. À partir de la semaine prochaine, les SL intègreront des blocs à allure marathon. Profite de cette SL fondamentale pure pour consolider tes bases.', retour:'',
        note:'RPE 5-6/10.' },
    ]},

  { num:9, phase:'Spécificité marathon', charge:'Élevée',
    objectif:'Côtes mercredi + SL 2h avec 20 min OBJ. Entrée en phase spécifique avec maintien de la puissance.',
    conseil:'La phase spécifique commence. Chaque SL intègre maintenant des blocs à allure marathon. Mémorise cette allure : c\'est celle du jour J.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 50 minutes', duree:'50 min', pcts:[[65,65]],
        echauff:'', corps:'50 min à {{P}}. Début de la phase spécifique. Côtes mercredi et première SL avec bloc OBJ dimanche. Ce footing lundi est le carburant silencieux de la semaine — reste strictement à allure fondamentale, sans dérive de rythme.', retour:'',
        note:'RPE 4/10.' },
      { jour:'Mardi', type:'EF', titre:'Footing de récupération 40 minutes', duree:'40 min', pcts:[[60,62]],
        echauff:'', corps:'40 min à {{P}}, allure vraiment douce. 12 côtes explosives mercredi demandent des jambes fraîches et des fibres musculaires disponibles. Ce footing lent du mardi limite la fatigue résiduelle. Cours à l\'aise, sans effort conscient.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mercredi', type:'Côtes', titre:'12 côtes de 80 mètres, puissance marathon', duree:'55 min', pcts:[[65,65],[100,105]],
        echauff:'25 min progressif à {{P}}, finir par 4 foulées bondissantes.',
        corps:'12 côtes de 80 mètres à effort maximal. Récupération : redescente en marchant. Appui avant-pied, genoux hauts, bras actifs. La puissance neuromusculaire construite ici résiste aux km 30-35 du marathon. Qualité sur chaque montée.',
        retour:'10 min footing très lent.',
        note:'RPE 8/10 · 12 côtes. Maintien de la qualité sur toutes.' },
      { jour:'Vendredi', type:'EF', titre:'Footing de récupération 40 minutes', duree:'40 min', pcts:[[60,62]],
        echauff:'', corps:'40 min à {{P}}, allure récupération maximale. Les côtes de mercredi ont intensément sollicité les fibres rapides des mollets et fessiers. Ce footing lent prépare tes jambes pour la grande SL de dimanche avec son premier bloc à allure marathon.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 2h avec 20 min allure marathon', duree:'2h', pcts:[[65,72],[75,80]],
        echauff:'', corps:'100 min à {{P}}, puis 20 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h. Ces 20 min à {{OBJ}} après 100 min d\'EF simulent le dernier quart du marathon sur des jambes déjà fatiguées. Mémorise cette sensation — c\'est ce que tu vivras au km 30.', retour:'',
        note:'RPE 6/10 en EF · 7/10 sur les 20 min · Mémorise la sensation de {{OBJ}}.' },
    ]},

  { num:10, phase:'Spécificité marathon', charge:'Élevée',
    objectif:'3 × 15 min seuil mercredi + 4 × 3 km OBJ vendredi + SL 2h10 avec 25 min OBJ. Semaine complète.',
    conseil:'Le vendredi introduit les blocs OBJ en séance de qualité pure. Différent des blocs en fin de SL : tu es frais, l\'allure doit être bien calée.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 50 minutes', duree:'50 min', pcts:[[65,65]],
        echauff:'', corps:'50 min à {{P}}. Trois séances majeures cette semaine : seuil mercredi, 4 × 3 km OBJ vendredi, SL avec 25 min OBJ dimanche. Ce lundi EF maintient le volume de base sans entamer les réserves. Vraiment léger, foulée économique.', retour:'',
        note:'RPE 4/10.' },
      { jour:'Mardi', type:'EF', titre:'Footing de récupération 40 minutes', duree:'40 min', pcts:[[60,62]],
        echauff:'', corps:'40 min à {{P}}, allure très douce. Le 3 × 15 min seuil mercredi est une séance de référence — 45 min au seuil total. Arrive frais. Ce footing très lent du mardi est une récupération active, pas un entraînement.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mercredi', type:'Tempo', titre:'3 × 15 minutes au seuil', duree:'75 min', pcts:[[65,70],[82,87]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
        corps:'3 × 15 min à {{P}} avec 4 min de récupération. 45 min au seuil en phase spécifique. Le seuil reste la base de la vitesse marathon. Régularité absolue sur les 3 blocs — le 3e bloc révèle ta vraie forme du moment.',
        retour:'10 min footing très lent.',
        note:'RPE 8/10 · 45 min au seuil pendant la phase spécifique.' },
      { jour:'Vendredi', type:'Fractionné', titre:'4 × 3 km à allure marathon', duree:'75 min', pcts:[[65,65],[78,82]],
        echauff:'25 min footing EF à {{P}}.',
        corps:'4 × 3 km exactement à ton allure objectif marathon ({{OBJ}}). Récupération 3 min au trot. 12 km à {{OBJ}} en blocs. Pars précisément à {{OBJ}} sur le 1er — ni plus rapide, ni plus lent. La précision de l\'allure est l\'objectif principal.',
        retour:'10 min footing léger.',
        note:'RPE 7-8/10 · Blocs OBJ purs. La régularité sur les 4 blocs est l\'objectif.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 2h10 avec 25 min allure marathon', duree:'2h10', pcts:[[65,72],[75,80]],
        echauff:'', corps:'105 min à {{P}}, puis 25 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h et 1h20. Hydratation systématique. 5 minutes de plus que S9 sur le bloc OBJ. Ces 25 min à {{OBJ}} après 1h45 de course simulent les conditions du km 28 au km 35.', retour:'',
        note:'RPE 6/10 en EF · 7-8/10 sur les 25 min.' },
    ]},

  { num:11, phase:'Spécificité marathon', charge:'Maximale',
    objectif:'Séance finisher mercredi + 2 × 5000m vendredi + SL 2h20 avec 30 min OBJ. Triple charge spécifique.',
    conseil:'Semaine de charge maximale. Les 3 séances de qualité sont à la limite du tolérable. Gère l\'énergie entre chaque.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 50 minutes', duree:'50 min', pcts:[[65,65]],
        echauff:'', corps:'50 min à {{P}}. Semaine de charge maximale : finisher mercredi, 2 × 5000m vendredi, SL 2h20 dimanche. Ce footing lundi maintient le volume de base sans entamer les réserves pour les 3 séances majeures. Vraiment conservateur.', retour:'',
        note:'RPE 4/10.' },
      { jour:'Mardi', type:'EF', titre:'Footing de récupération 35 minutes', duree:'35 min', pcts:[[60,62]],
        echauff:'', corps:'35 min à {{P}}, allure très douce. Le finisher mercredi est la séance la plus complexe du plan. Ces 35 min très lentes du mardi préparent les jambes à encaisser l\'enchaînement seuil + blocs OBJ. Reste vraiment à l\'aise.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mercredi', type:'Tempo', titre:'Séance finisher, 5 km seuil + 3 × 3 km allure marathon', duree:'90 min', pcts:[[65,65],[80,85],[78,82]],
        echauff:'25 min footing EF à {{P}}.',
        corps:'5 km à {{P}} (effort seuil, régulier) → 5 min récupération → 3 × 3 km à ton allure objectif marathon ({{OBJ}}), récup 3 min entre chaque. La transition seuil → allure marathon est la clé de la réussite le jour J. Pars conservateur sur le 5 km.',
        retour:'10 min footing léger.',
        note:'RPE 8/10 · Séance de référence marathon.' },
      { jour:'Vendredi', type:'Fractionné', titre:'2 × 5000 mètres à allure marathon', duree:'80 min', pcts:[[65,65],[78,82]],
        echauff:'25 min progressif à {{P}}.',
        corps:'2 × 5000 mètres à {{P}}. Récupération 5 min au trot. Après le finisher de mercredi, pars conservateur sur le 1er 5000m. Cette séance développe la capacité à répéter l\'effort marathon — la qualité prime sur la vitesse pure.',
        retour:'10 min footing très lent.',
        note:'RPE 7/10 · Volume maintenu, intensité légèrement réduite après mercredi.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 2h20 avec 30 min allure marathon', duree:'2h20', pcts:[[65,72],[75,80]],
        echauff:'', corps:'110 min à {{P}}, puis 30 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h, 1h20, 1h40. Hydratation systématique. Ces 30 min à {{OBJ}} après 1h50 de course simulent le dernier tiers du marathon en termes de fatigue musculaire.', retour:'',
        note:'RPE 6/10 en EF · 8/10 sur les 30 min · Gros bloc OBJ en fin de longue semaine.' },
    ]},

  { num:12, phase:'Spécificité marathon', charge:'Maximale',
    objectif:'LE pic de charge. Grande SL 2h30 avec 30 min OBJ. La semaine la plus difficile du plan.',
    conseil:'Cette semaine est intense. Après, le plus dur est derrière toi. Récupère bien entre chaque séance. La SL de dimanche est la reine.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 50 minutes', duree:'50 min', pcts:[[65,65]],
        echauff:'', corps:'50 min à {{P}}. Dernière grosse semaine du plan. Les 4 × 3 km OBJ + côtes mercredi et la grande SL 2h30 dimanche sont les deux séances majeures. Ce lundi léger préserve chaque joule d\'énergie disponible.', retour:'',
        note:'RPE 4/10.' },
      { jour:'Mardi', type:'EF', titre:'Footing de récupération 35 minutes', duree:'35 min', pcts:[[60,62]],
        echauff:'', corps:'35 min à {{P}}, allure vraiment douce. La grande SL 2h30 avec 30 min OBJ dimanche est la séance ultime du plan. Ces 35 min très lentes du mardi protègent les réserves musculaires. Aucune ambition de performance.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mercredi', type:'Fractionné', titre:'4 × 3 km à allure marathon + côtes', duree:'80 min', pcts:[[65,65],[78,82]],
        echauff:'25 min footing EF à {{P}}.',
        corps:'4 × 3 km à ton allure objectif marathon ({{OBJ}}), récup 3 min. Puis 4 côtes de 80m explosives pour finir. Les blocs OBJ gravent l\'allure marathon, les côtes réveillent les fibres rapides. Séance marathonienne complète avant la grande SL.',
        retour:'10 min footing léger.',
        note:'RPE 7-8/10 · Séance marathonienne complète.' },
      { jour:'Vendredi', type:'EF', titre:'Footing de récupération 35 minutes', duree:'35 min', pcts:[[60,62]],
        echauff:'', corps:'35 min à {{P}}, allure très légère. Récupération active entre les 4 × 3 km OBJ de mercredi et la grande SL 2h30 de dimanche. Ce footing lent est crucial — ménage-toi absolument pour la séance ultime du plan.', retour:'',
        note:'RPE 3/10 · Ménage-toi pour la SL 2h30 de dimanche.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Grande sortie longue 2h30 avec 30 min allure marathon', duree:'2h30', pcts:[[65,72],[75,80]],
        echauff:'', corps:'120 min à {{P}}, puis 30 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h, 1h20, 1h40, 2h. Hydratation toutes les 20 min. LA grande sortie du plan. Ces 30 min à {{OBJ}} après 2h de course sont l\'épreuve de vérité de ta préparation. Après dimanche, tout est derrière toi.', retour:'',
        note:'RPE 6/10 en EF · 8/10 sur les 30 min · Le pic de charge est atteint. Récupération dès maintenant.' },
    ]},

  { num:13, phase:'Pic de charge', charge:'Élevée (légère réduction)',
    objectif:'Volume légèrement réduit (-15%). Maintien de l\'intensité avec 2 qualités différenciées.',
    conseil:'Consolidation après S12. L\'intensité reste mais le volume allège légèrement. Ton corps récupère tout en assimilant les adaptations.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 45 minutes', duree:'45 min', pcts:[[65,65]],
        echauff:'', corps:'45 min à {{P}}. Consolidation post-pic de charge. 5 min de moins qu\'en S11-S12 — le corps assimile les adaptations de S12 tout en restant actif. Terrain souple de préférence, aucune contrainte d\'allure.', retour:'',
        note:'RPE 4/10.' },
      { jour:'Mardi', type:'EF', titre:'Footing de récupération 35 minutes', duree:'35 min', pcts:[[60,62]],
        echauff:'', corps:'35 min à {{P}}, allure très douce. Le 3 × 15 min seuil mercredi maintient l\'intensité malgré la réduction de volume. Arrive frais. Ce footing lent du mardi est une récupération active post-pic S12.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mercredi', type:'Tempo', titre:'3 × 15 minutes au seuil', duree:'75 min', pcts:[[65,70],[82,87]],
        echauff:'25 min progressif à {{P}}.',
        corps:'3 × 15 min à {{P}} avec 4 min de récupération. Maintien de l\'intensité seuil malgré la réduction de volume. Les adaptations de S12 sont en cours d\'assimilation — la régularité sur les 3 blocs confirme et ancre ta progression.',
        retour:'10 min footing très lent.',
        note:'RPE 7-8/10.' },
      { jour:'Vendredi', type:'Fractionné', titre:'4 × 3 km à allure marathon', duree:'75 min', pcts:[[65,65],[78,82]],
        echauff:'25 min footing EF à {{P}}.',
        corps:'4 × 3 km à ton allure objectif marathon ({{OBJ}}). Récupération 3 min au trot entre chaque. 12 km à {{OBJ}} pour maintenir la mémoire musculaire de l\'allure cible. Dernière grande séance OBJ avant le début de l\'affûtage.',
        retour:'10 min footing léger.',
        note:'RPE 7-8/10.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 2h15 avec 30 min allure marathon', duree:'2h15', pcts:[[65,72],[75,80]],
        echauff:'', corps:'105 min à {{P}}, puis 30 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h, 1h20, 1h40. Légèrement plus court que S12 mais le bloc OBJ reste identique. Ces 30 min à {{OBJ}} doivent commencer à sembler naturels et fluides.', retour:'',
        note:'RPE 6/10 en EF · 8/10 sur les 30 min.' },
    ]},

  { num:14, phase:'Pic de charge', charge:'Réduite, pré-affûtage',
    objectif:'Volume réduit (-30%). Maintien des sensations avec des séances plus légères. Début de la super-compensation.',
    conseil:'L\'affûtage commence. Moins de volume mais qualité maintenue. Les jambes commencent à se recharger.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}. L\'affûtage commence. Les footings raccourcissent progressivement. Le corps entre en super-compensation — tu te recharges. Vraiment léger, sans aucune ambition de performance.', retour:'',
        note:'RPE 3-4/10.' },
      { jour:'Mardi', type:'EF', titre:'Footing de récupération 35 minutes', duree:'35 min', pcts:[[60,62]],
        echauff:'', corps:'35 min à {{P}}, allure très douce. L\'affûtage est lancé — les footings de récupération raccourcissent et ralentissent. Le corps entre en super-compensation. Reste très léger, aucune envie de performance.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mercredi', type:'Fractionné', titre:'4 × 1500 mètres, maintien VMA pré-affûtage', duree:'60 min', pcts:[[65,65],[83,90]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
        corps:'4 × 1500 mètres à {{P}}. Récupération 3 min au trot. Plus court que les semaines précédentes — maintien des sensations VMA sans générer de fatigue. Plus rapide que l\'allure marathon, moins long que les 2000m. Qualité d\'effort sur chaque répétition.',
        retour:'10 min footing très lent.',
        note:'RPE 7/10 · Moins de volume, mêmes sensations.' },
      { jour:'Vendredi', type:'Tempo', titre:'2 × 15 minutes au seuil, volume réduit', duree:'55 min', pcts:[[65,70],[82,87]],
        echauff:'25 min progressif à {{P}}.',
        corps:'2 × 15 min à {{P}} avec 4 min de récupération. Réduit de 33% par rapport aux 3 × 15 min habituels. Même intensité, moins de volume — le principe clé de l\'affûtage. Les sensations doivent être vives et les jambes légères.',
        retour:'10 min footing très lent.',
        note:'RPE 7/10 · Moins de blocs, même intensité.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 1h50 avec 15 min allure marathon', duree:'1h50', pcts:[[65,72],[75,80]],
        echauff:'', corps:'95 min à {{P}}, puis 15 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h. Sortie longue allégée — 40 min de moins que S13. Le bloc OBJ court maintient la mémoire de l\'allure marathon pendant l\'affûtage. Ces 15 min à {{OBJ}} doivent sembler fluides.', retour:'',
        note:'RPE 5/10 en EF · 7/10 sur les 15 min · Allégée. Maintien des sensations.' },
    ]},

  { num:15, phase:'Consolidation', charge:'Réduite, affûtage',
    objectif:'5 séances légères pour laisser les adaptations s\'installer. Volume réduit de 45%.',
    conseil:'Semaine d\'affûtage. Les jambes doivent commencer à fourmiller d\'impatience. Dors 8h. Ne rajoute rien.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing léger 50 minutes', duree:'50 min', pcts:[[65,65]],
        echauff:'', corps:'50 min à {{P}}, allure légère. Le footing le plus long de la semaine de consolidation — il maintient l\'endurance de base sans fatiguer. Cours en nature, apprécie la légèreté des jambes après les semaines de charge. La semaine de course approche.', retour:'',
        note:'RPE 3/10 · Tu dois finir comme si tu venais de te promener.' },
      { jour:'Mardi', type:'EF', titre:'Footing de récupération 35 minutes', duree:'35 min', pcts:[[60,62]],
        echauff:'', corps:'35 min à {{P}}, allure très douce. Semaine de consolidation : laisse les adaptations s\'installer. Ce footing lent du mardi complète la récupération avant le seuil du mercredi. Vraiment léger, sans pression.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mercredi', type:'Tempo', titre:'2 × 15 minutes au seuil, volume réduit', duree:'55 min', pcts:[[65,72],[82,88]],
        echauff:'25 min progressif à {{P}}.', corps:'2 × 15 min à {{P}}. Volume réduit mais intensité maintenue. Récup 4 min. Termine par 1 km à {{OBJ}} pour réveiller les sensations de course. Les jambes doivent se sentir légères et vives.', retour:'10 min footing très lent.',
        note:'RPE 7/10 · Maintien des sensations sans épuisement.' },
      { jour:'Vendredi', type:'EF', titre:'Footing léger 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}, allure légère. Dans les 10 dernières minutes, place 4 à 6 accélérations de 60m à ton allure marathon pour garder les sensations neuromusculaires vives. Termine frais et dynamisé.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Dimanche', type:'EF', titre:'Footing léger 35 minutes', duree:'35 min', pcts:[[60,65]],
        echauff:'', corps:'35 min très légers à {{P}}. Dernier footing avant la semaine de course. Laisse les jambes rouler librement, le corps se recharge. Finis avec le sourire — le travail est fait.', retour:'',
        note:'RPE 3/10 · Tu dois finir frais et dynamisé.' },
    ]},

  { num:16, phase:'Semaine de course', charge:'Conserve, tu es prêt',
    objectif:'Arriver au départ reposé, confiant, les jambes fraîches. 15 semaines de travail ont été faites.',
    conseil:'Pars à {{OBJ}}/km dès le départ. L\'adrénaline va te pousser à aller plus vite, résiste.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing très léger 30 minutes', duree:'30 min', pcts:[[60,65]],
        echauff:'', corps:'30 min à {{P}}, vraiment lent. Maintenir la circulation sanguine en début de semaine de course. Pas d\'effort, juste des jambes qui bougent. Si tu te sens fatigué, réduis à 20 min — rester frais est la priorité absolue.', retour:'',
        note:'RPE 3/10 · Aucun effort.' },
      { jour:'Mercredi', type:'Fractionné', titre:'8 × 1 min / 1 min à allure marathon', duree:'40 min',
        echauff:'15 min de footing très léger.',
        corps:'8 × 1 minute à ton allure objectif marathon ({{OBJ}}) / 1 minute au trot. Plus long que le 30/30 : ce stimulus réveille les fibres rapides sans épuiser les jambes. Le grand jour arrive dans 4 jours — reste vraiment frais.',
        retour:'10 min de jogging léger.',
        note:'RPE 6/10 · Maintien des sensations avant le marathon.' },
      { jour:'Samedi', type:'Activation', titre:'Activation J-1 + accélérations', duree:'30 min', pcts:[[60,65]],
        echauff:'', corps:'20 min de trot à {{P}}. Puis 6 à 8 accélérations progressives de 80m jusqu\'à ton allure objectif ({{OBJ}}) sur les 20 derniers mètres. Récupère 60 sec en marchant entre chaque.', retour:'',
        note:'Prépare tes affaires ce soir. Visualise les premiers kilomètres à {{OBJ}}/km.' },
      { jour:'Dimanche', type:'Course', titre:'MARATHON', duree:'Jour J',
        echauff:'10-15 min de jogging très léger avant le départ.',
        corps:'KM 1-8 : pars à {{OBJ}}/km exactement. KM 9-21 : régularité absolue, gel à chaque ravitaillement. KM 22-30 : maintiens {{OBJ}}, écoute ton corps. KM 31-35 : raccourcis la foulée, garde les bras actifs. KM 36-42 : donne absolument tout.',
        retour:'20-30 min de marche. Ravitaillement dans les 30 min.',
        note:'La douleur aux km 30-35 est normale. C\'est là que se gagne un marathon. Tiens bon.' },
    ]},
]
