// Marathon 16 semaines · 4 séances/semaine · Palier Débutant (VMA ≤ 13.5)
// Fractionnés raccourcis, seuil réduit, SL plus courtes, blocs OBJ réduits
const { applyOverrides } = require('../../lib/tier-overrides')
const base = require('./semaines-4-i.js')

module.exports = applyOverrides(base, {
  1: { replace: { Mercredi: {
    titre:'4 × 400 mètres, réveil neuromusculaire', pcts:[[65,65],[88,92]],
    echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 60m.',
    corps:'4 × 400 mètres à {{P}}. Récupération 2 min au trot. Effort régulier sur les 4.',
    retour:'10 min footing très lent.',
    note:'RPE 6/10 · 4×400m adapté à ce palier.' },
    Dimanche: { duree:'60 min',
    corps:'60 min à {{P}}. Rythme conversationnel. Hydrate-toi.',
    note:'RPE 4/10 · La durée prime.' } } },
  2: { replace: { Mercredi: {
    titre:'6 côtes de 80 mètres', pcts:[[65,65],[100,105]],
    echauff:'25 min progressif à {{P}}, finir par 4 foulées bondissantes.',
    corps:'6 côtes de 80 mètres à effort maximal. Récupération : redescente en marchant.',
    retour:'10 min footing très lent.',
    note:'RPE 8/10 · 6 côtes au lieu de 8.' },
    Dimanche: { duree:'65 min',
    corps:'65 min à {{P}}. Terrain varié.',
    note:'RPE 4/10.' } } },
  3: { replace: { Mercredi: {
    titre:'1 × 12 minutes au seuil aérobie', duree:'45 min', pcts:[[65,70],[78,82]],
    echauff:'25 min progressif à {{P}}.',
    corps:'12 min continus à {{P}}. Premier contact avec l\'effort soutenu. Tu dois pouvoir prononcer quelques mots.',
    retour:'10 min footing très lent.',
    note:'RPE 6/10 · Seuil léger adapté à ce palier.' },
    Dimanche: { duree:'75 min',
    corps:'75 min à {{P}}. Régulier.',
    note:'RPE 4/10.' } } },
  4: { replace: { Mercredi: {
    titre:'3 × 1000 mètres', pcts:[[65,65],[83,90]],
    echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
    corps:'3 × 1000 mètres à {{P}}. Récupération 2 min. Un de moins que la trame. Régularité sur les 3.',
    retour:'10 min footing très lent.',
    note:'RPE 7/10 · 3×1000m, progression vers les 4-5 répétitions.' },
    Dimanche: { duree:'80 min',
    corps:'80 min à {{P}}. Gel à 1h. Pas de bloc OBJ encore.',
    note:'RPE 4-5/10.' } } },
  5: { replace: { Mercredi: {
    titre:'4 × 1000 mètres', pcts:[[65,65],[83,90]],
    echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
    corps:'4 × 1000 mètres à {{P}}. Récupération 2 min. Un de moins que la trame.',
    retour:'10 min footing très lent.',
    note:'RPE 7/10.' },
    Dimanche: { duree:'90 min',
    corps:'90 min à {{P}}. Gel à 1h. Pas de bloc marathon.',
    note:'RPE 4-5/10.' } } },
  6: { replace: { Mercredi: {
    titre:'2 × 10 minutes au seuil', duree:'50 min', pcts:[[65,70],[80,84]],
    echauff:'25 min progressif à {{P}}.',
    corps:'2 × 10 min à {{P}} avec 3 min de récupération. 20 min au seuil léger.',
    retour:'10 min footing très lent.',
    note:'RPE 6-7/10 · Adapté au palier débutant.' },
    Dimanche: { duree:'1h40',
    corps:'1h40 à {{P}}. Gel à 1h. Pas de bloc OBJ.',
    note:'RPE 5/10.' } } },
  7: { replace: { Mercredi: {
    titre:'2 × 2000 mètres, premiers longs fractionnés', pcts:[[65,65],[78,83]],
    echauff:'25 min progressif à {{P}}.',
    corps:'2 × 2000 mètres à {{P}}. Récupération 4 min. Un de moins que la trame.',
    retour:'10 min footing très lent.',
    note:'RPE 7/10 · Premier contact avec les 2000m.' },
    Dimanche: { duree:'1h50',
    corps:'1h50 à {{P}}. Gel à 1h.',
    note:'RPE 5/10.' } } },
  8: { replace: { Mercredi: {
    titre:'2 × 3000 mètres progressifs', pcts:[[65,65],[78,80],[80,83],[83,85]],
    echauff:'25 min progressif à {{P}}.',
    corps:'2 × 3000 mètres à {{P}}. Récupération 5 min. Chaque 3000m en progression : 1er km à {{P}}, 2e à {{P}}, 3e à {{P}}.',
    retour:'10 min footing très lent.',
    note:'RPE 7-8/10 · Allures légèrement plus basses que la trame.' },
    Dimanche: { duree:'2h',
    corps:'2h à {{P}}. Gel à 1h et 1h20. Pas de bloc OBJ.',
    note:'RPE 5/10.' } } },
  9: { replace: { Mercredi: {
    titre:'8 côtes de 80 mètres, puissance marathon', pcts:[[65,65],[100,105]],
    echauff:'25 min progressif à {{P}}, finir par 4 foulées bondissantes.',
    corps:'8 côtes de 80 mètres à effort maximal. Récupération : redescente en marchant. 2 de moins que la trame.',
    retour:'10 min footing très lent.',
    note:'RPE 8/10.' },
    Dimanche: { duree:'1h55',
    corps:'95 min à {{P}}, puis 15 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h. Bloc OBJ raccourci.',
    note:'RPE 5/10 en EF · 6-7/10 sur les 15 min.' } } },
  10: { replace: { Mercredi: {
    titre:'2 × 15 minutes au seuil', duree:'60 min', pcts:[[65,70],[80,84]],
    echauff:'25 min progressif à {{P}}.',
    corps:'2 × 15 min à {{P}} avec 4 min de récupération. 30 min au seuil adapté.',
    retour:'10 min footing très lent.',
    note:'RPE 7/10 · Réduit vs la trame (3×15min).' },
    Dimanche: { duree:'2h',
    corps:'100 min à {{P}}, puis 20 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h.',
    note:'RPE 5/10 en EF · 7/10 sur les 20 min.' } } },
  11: { replace: { Mercredi: {
    titre:'1 × 5000 mètres à allure marathon', duree:'60 min', pcts:[[65,65],[78,82]],
    echauff:'25 min progressif à {{P}}.',
    corps:'1 × 5000 mètres à {{P}}. Après 4 min de récup, 2 km à {{OBJ}}.',
    retour:'10 min footing très lent.',
    note:'RPE 7-8/10 · 1×5000m adapté à ce palier.' },
    Dimanche: { duree:'2h10',
    corps:'105 min à {{P}}, puis 25 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h et 1h20.',
    note:'RPE 5/10 en EF · 7/10 sur les 25 min.' } } },
  12: { replace: { Mercredi: {
    titre:'3 × 3 km à allure marathon', duree:'65 min', pcts:[[65,65],[78,82]],
    echauff:'25 min footing EF à {{P}}.',
    corps:'3 × 3 km à ton allure objectif marathon ({{OBJ}}). Récupération 3 min. Version simplifiée du finisher.',
    retour:'10 min footing léger.',
    note:'RPE 7/10 · Séance spécifique adaptée à ce palier.' },
    Dimanche: { duree:'2h20',
    corps:'110 min à {{P}}, puis 30 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h, 1h20, 1h40.',
    note:'RPE 5-6/10 en EF · 7/10 sur les 30 min.' } } },
  13: { replace: { Mercredi: {
    titre:'3 × 3 km à allure marathon', duree:'65 min', pcts:[[65,65],[78,82]],
    echauff:'25 min footing EF à {{P}}.',
    corps:'3 × 3 km à ton allure objectif marathon ({{OBJ}}). Récupération 3 min.',
    retour:'10 min footing léger.',
    note:'RPE 7/10.' },
    Dimanche: { duree:'2h10',
    corps:'100 min à {{P}}, puis 30 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h et 1h20.',
    note:'RPE 5-6/10 en EF · 7/10 sur les 30 min.' } } },
  14: { replace: { Mercredi: {
    titre:'3 × 1500 mètres pré-affûtage', pcts:[[65,65],[82,88]],
    echauff:'25 min progressif à {{P}}.',
    corps:'3 × 1500 mètres à {{P}}. Récupération 3 min. Un de moins que la trame.',
    retour:'10 min footing très lent.',
    note:'RPE 6-7/10.' },
    Dimanche: { duree:'1h45',
    corps:'90 min à {{P}}, puis 10 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h.',
    note:'RPE 5/10 en EF · 6/10 sur les 10 min.' } } },
})
