// Marathon 16 semaines · 5 séances/semaine · Palier Avancé (VMA > 18.5)
// Intervalles plus longs, 2e qualité plus exigeante, SL allongées, blocs OBJ plus longs
const { applyOverrides } = require('../../lib/tier-overrides')
const base = require('./semaines-5-i.js')

module.exports = applyOverrides(base, {
  1: { replace: { Mercredi: {
    titre:'8 × 400 mètres, volume VMA élevé', pcts:[[65,65],[92,97]],
    echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 60m.',
    corps:'8 × 400 mètres à {{P}}. Récupération 90 sec. Deux de plus que la trame.',
    retour:'10 min footing très lent.',
    note:'RPE 7-8/10 · Volume VMA élevé dès S1.' },
    Vendredi: {
    titre:'2 × 10 minutes au seuil, introduction avancée', duree:'50 min', pcts:[[65,70],[83,88]],
    echauff:'25 min progressif à {{P}}.',
    corps:'2 × 10 min à {{P}} avec 3 min de récupération. Allure seuil plus haute que la trame pour ce palier.',
    retour:'10 min footing très lent.',
    note:'RPE 7-8/10 · 2e qualité avancée dès S1.' },
    Dimanche: { duree:'80 min',
    corps:'80 min à {{P}}. 10 min de plus que la trame.',
    note:'RPE 4-5/10.' } } },
  2: { replace: { Mercredi: {
    titre:'12 côtes de 80 mètres', pcts:[[65,65],[100,107]],
    echauff:'25 min progressif à {{P}}, finir par 4 foulées bondissantes.',
    corps:'12 côtes de 80 mètres à effort maximal. Récupération : redescente en marchant. 4 de plus que la trame.',
    retour:'10 min footing très lent.',
    note:'RPE 8/10.' },
    Vendredi: {
    titre:'2 × 15 minutes au seuil', duree:'60 min', pcts:[[65,70],[83,88]],
    echauff:'25 min progressif à {{P}}.',
    corps:'2 × 15 min à {{P}} avec 4 min de récupération. 30 min au seuil. Plus que la trame (2×8min).',
    retour:'10 min footing très lent.',
    note:'RPE 8/10.' },
    Dimanche: { duree:'90 min',
    corps:'90 min à {{P}}. Plus long que la trame.',
    note:'RPE 4-5/10.' } } },
  3: { replace: { Mercredi: {
    titre:'2 × 15 minutes au seuil', duree:'60 min', pcts:[[65,70],[83,88]],
    echauff:'25 min progressif à {{P}}.',
    corps:'2 × 15 min à {{P}} avec 4 min de récupération. 30 min au seuil. Plus que la trame (2×10min).',
    retour:'10 min footing très lent.',
    note:'RPE 8/10.' },
    Vendredi: {
    titre:'6 × 1000 mètres', pcts:[[65,65],[87,93]],
    echauff:'25 min progressif à {{P}}.',
    corps:'6 × 1000 mètres à {{P}}. Récupération 2 min. Deux de plus que la trame.',
    retour:'10 min footing très lent.',
    note:'RPE 8/10 · 6×1000m en 2e qualité pour ce palier.' },
    Dimanche: { duree:'95 min',
    corps:'75 min à {{P}}, puis 20 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h. Bloc OBJ dès S3.',
    note:'RPE 5/10 en EF · 7/10 sur les 20 min.' } } },
  4: { replace: { Mercredi: {
    titre:'3 × 15 minutes au seuil', duree:'75 min', pcts:[[65,70],[83,88]],
    echauff:'25 min progressif à {{P}}.',
    corps:'3 × 15 min à {{P}} avec 4 min de récupération. 45 min au seuil. Un bloc de plus que la trame.',
    retour:'10 min footing très lent.',
    note:'RPE 8/10 · 45 min au seuil dès S4 pour ce palier.' },
    Vendredi: {
    titre:'6 × 1000 mètres', pcts:[[65,65],[87,93]],
    echauff:'25 min progressif à {{P}}.',
    corps:'6 × 1000 mètres à {{P}}. Récupération 2 min. Un de plus que la trame (5×1000m).',
    retour:'10 min footing très lent.',
    note:'RPE 8/10.' },
    Dimanche: { duree:'1h45',
    corps:'75 min à {{P}}, puis 30 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h.',
    note:'RPE 5/10 en EF · 7-8/10 sur les 30 min.' } } },
  5: { replace: { Mercredi: {
    titre:'4 × 2000 mètres', pcts:[[65,65],[82,87]],
    echauff:'25 min progressif à {{P}}.',
    corps:'4 × 2000 mètres à {{P}}. Récupération 4 min. Un de plus que la trame (3×2000m).',
    retour:'10 min footing très lent.',
    note:'RPE 8/10.' },
    Vendredi: {
    titre:'3 × 15 minutes au seuil', duree:'75 min', pcts:[[65,70],[83,88]],
    echauff:'25 min progressif à {{P}}.',
    corps:'3 × 15 min à {{P}} avec 4 min de récupération. 45 min au seuil. Un bloc de plus que la trame.',
    retour:'10 min footing très lent.',
    note:'RPE 8/10 · 45 min au seuil en 2e qualité.' },
    Dimanche: { duree:'1h55',
    corps:'85 min à {{P}}, puis 30 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h.',
    note:'RPE 5/10 en EF · 7-8/10 sur les 30 min.' } } },
  6: { replace: { Mercredi: {
    titre:'12 côtes de 80 mètres + 2 km allure marathon', pcts:[[65,65],[100,107],[78,82]],
    echauff:'25 min progressif à {{P}}, finir par 4 foulées bondissantes.',
    corps:'12 côtes de 80 mètres à effort maximal, puis après 3 min de récup, 2 km à ton allure objectif marathon ({{OBJ}}). Combiner puissance et spécificité marathon.',
    retour:'10 min footing très lent.',
    note:'RPE 8/10 · 12 côtes + bloc OBJ pour ce palier avancé.' },
    Vendredi: {
    titre:'3 × 3000 mètres progressifs', pcts:[[65,65],[80,82],[82,85],[85,88]],
    echauff:'25 min progressif à {{P}}.',
    corps:'3 × 3000 mètres à {{P}}. Récupération 5 min. Un de plus que la trame. Chaque 3000m en progression.',
    retour:'10 min footing très lent.',
    note:'RPE 8-9/10.' },
    Dimanche: { duree:'2h',
    corps:'100 min à {{P}}, puis 20 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h. Bloc OBJ allongé.',
    note:'RPE 5/10 en EF · 7/10 sur les 20 min.' } } },
  7: { replace: { Mercredi: {
    titre:'3 × 15 minutes au seuil', duree:'75 min', pcts:[[65,70],[83,88]],
    echauff:'25 min progressif à {{P}}.',
    corps:'3 × 15 min à {{P}} avec 4 min de récupération. 45 min au seuil.',
    retour:'10 min footing très lent.',
    note:'RPE 8/10.' },
    Vendredi: {
    titre:'4 × 3 km à allure marathon + 1 km accélération', duree:'80 min', pcts:[[65,65],[78,82],[75,78]],
    echauff:'25 min footing EF à {{P}}.',
    corps:'4 × 3 km à {{P}}, récup 3 min. Puis après 3 min de récup totale, 1 km en accélération progressive à {{P}} (sous-allure marathon). Complétion avancée.',
    retour:'10 min footing léger.',
    note:'RPE 7-8/10.' },
    Dimanche: { duree:'2h20',
    corps:'100 min à {{P}}, puis 40 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h et 1h20.',
    note:'RPE 5/10 en EF · 7-8/10 sur les 40 min.' } } },
  8: { replace: { Mercredi: {
    titre:'3 × 5000 mètres à allure marathon', duree:'90 min', pcts:[[65,65],[78,82]],
    echauff:'25 min progressif à {{P}}.',
    corps:'3 × 5000 mètres à {{P}}. Récupération 5 min. Un de plus que la trame. 15 km à allure marathon.',
    retour:'10 min footing très lent.',
    note:'RPE 8-9/10 · 3×5000m pour ce palier.' },
    Vendredi: {
    titre:'3 × 15 minutes au seuil', duree:'75 min', pcts:[[65,70],[83,88]],
    echauff:'25 min progressif à {{P}}.',
    corps:'3 × 15 min à {{P}} avec 4 min de récupération. 45 min au seuil.',
    retour:'10 min footing très lent.',
    note:'RPE 7-8/10.' },
    Dimanche: { duree:'2h30',
    corps:'110 min à {{P}}, puis 40 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h, 1h20, 1h50.',
    note:'RPE 5/10 en EF · 7-8/10 sur les 40 min.' } } },
  9: { replace: { Mercredi: {
    titre:'12 côtes de 80 mètres', pcts:[[65,65],[100,107]],
    echauff:'25 min progressif à {{P}}, finir par 4 foulées bondissantes.',
    corps:'12 côtes de 80 mètres à effort maximal. Récupération : redescente en marchant. Plus que la trame.',
    retour:'10 min footing très lent.',
    note:'RPE 8/10.' },
    Vendredi: {
    titre:'5 × 3 km à allure marathon', duree:'85 min', pcts:[[65,65],[78,82]],
    echauff:'25 min footing EF à {{P}}.',
    corps:'5 × 3 km à ton allure objectif marathon ({{OBJ}}). Récupération 3 min. Un de plus que la trame.',
    retour:'10 min footing léger.',
    note:'RPE 7-8/10 · 15 km à {{OBJ}} en blocs.' },
    Dimanche: { duree:'2h15',
    corps:'95 min à {{P}}, puis 40 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h et 1h20.',
    note:'RPE 6/10 en EF · 7-8/10 sur les 40 min.' } } },
  10: { replace: { Mercredi: {
    titre:'Séance finisher avancée, 6 km seuil + 3 × 3 km allure marathon', duree:'90 min', pcts:[[65,65],[82,87],[78,82]],
    echauff:'25 min footing EF à {{P}}.',
    corps:'6 km à {{P}} (effort seuil élevé) → 5 min récupération → 3 × 3 km à ton allure objectif marathon ({{OBJ}}), récup 3 min.',
    retour:'10 min footing léger.',
    note:'RPE 9/10 sur le seuil · 8/10 sur les blocs OBJ.' },
    Vendredi: {
    titre:'5 × 3 km à allure marathon', duree:'85 min', pcts:[[65,65],[78,82]],
    echauff:'25 min footing EF à {{P}}.',
    corps:'5 × 3 km à ton allure objectif marathon ({{OBJ}}). Récupération 3 min. Un de plus que la trame.',
    retour:'10 min footing léger.',
    note:'RPE 7-8/10.' },
    Dimanche: { duree:'2h25',
    corps:'105 min à {{P}}, puis 40 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h, 1h20, 1h45.',
    note:'RPE 6/10 en EF · 8/10 sur les 40 min.' } } },
  11: { replace: { Mercredi: {
    titre:'Séance finisher avancée, 8 km seuil + 4 × 3 km allure marathon', duree:'100 min', pcts:[[65,65],[83,87],[78,82]],
    echauff:'25 min footing EF à {{P}}.',
    corps:'8 km à {{P}} (effort seuil élevé) → 5 min récupération → 4 × 3 km à ton allure objectif marathon ({{OBJ}}), récup 3 min.',
    retour:'10 min footing léger.',
    note:'RPE 9/10 sur le seuil · 8/10 sur les blocs OBJ · Pic de charge qualité avancé.' },
    Vendredi: {
    titre:'3 × 5000 mètres à allure marathon', duree:'90 min', pcts:[[65,65],[78,82]],
    echauff:'25 min progressif à {{P}}.',
    corps:'3 × 5000 mètres à {{P}}. Récupération 5 min. Un de plus que la trame.',
    retour:'10 min footing très lent.',
    note:'RPE 7-8/10 · Après le finisher, pars prudemment.' },
    Dimanche: { duree:'2h40',
    corps:'120 min à {{P}}, puis 40 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h, 1h20, 1h50.',
    note:'RPE 6/10 en EF · 8/10 sur les 40 min.' } } },
  12: { replace: { Mercredi: {
    titre:'5 × 3 km à allure marathon + côtes', duree:'85 min', pcts:[[65,65],[78,82]],
    echauff:'25 min footing EF à {{P}}.',
    corps:'5 × 3 km à ton allure objectif marathon ({{OBJ}}), récup 3 min. Puis 4 côtes de 80m explosives. Séance spécifique complète.',
    retour:'10 min footing léger.',
    note:'RPE 8/10 · Un bloc de plus que la trame + côtes.' },
    Dimanche: { duree:'2h50',
    corps:'130 min à {{P}}, puis 40 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h, 1h30, 2h. LA grande sortie avancée.',
    note:'RPE 6/10 en EF · 8/10 sur les 40 min.' } } },
  13: { replace: { Mercredi: {
    titre:'Séance finisher avancée, 6 km seuil + 3 × 3 km allure marathon', duree:'90 min', pcts:[[65,65],[82,87],[78,82]],
    echauff:'25 min footing EF à {{P}}.',
    corps:'6 km à {{P}} → 5 min récupération → 3 × 3 km à {{OBJ}}, récup 3 min. Consolidation en phase de charge réduite.',
    retour:'10 min footing léger.',
    note:'RPE 8/10.' },
    Vendredi: {
    titre:'5 × 3 km à allure marathon', duree:'85 min', pcts:[[65,65],[78,82]],
    echauff:'25 min footing EF à {{P}}.',
    corps:'5 × 3 km à ton allure objectif marathon ({{OBJ}}). Récupération 3 min.',
    retour:'10 min footing léger.',
    note:'RPE 7-8/10.' },
    Dimanche: { duree:'2h30',
    corps:'110 min à {{P}}, puis 40 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h, 1h20, 1h50.',
    note:'RPE 6/10 en EF · 8/10 sur les 40 min.' } } },
  14: { replace: { Mercredi: {
    titre:'5 × 1500 mètres pré-affûtage', pcts:[[65,65],[85,92]],
    echauff:'25 min progressif à {{P}}.',
    corps:'5 × 1500 mètres à {{P}}. Récupération 3 min. Un de plus que la trame.',
    retour:'10 min footing très lent.',
    note:'RPE 7-8/10.' },
    Vendredi: {
    titre:'3 × 15 minutes au seuil, volume réduit', duree:'75 min', pcts:[[65,70],[83,88]],
    echauff:'25 min progressif à {{P}}.',
    corps:'3 × 15 min à {{P}} avec 4 min de récupération. Maintien du volume seuil plus élevé en affûtage.',
    retour:'10 min footing très lent.',
    note:'RPE 7-8/10.' },
    Dimanche: { duree:'2h10',
    corps:'95 min à {{P}}, puis 35 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h.',
    note:'RPE 5/10 en EF · 7-8/10 sur les 35 min.' } } },
})
