// Marathon 16 semaines · 4 séances/semaine · Palier Intermédiaire (VMA 13.5 à 18.5)
// {{P}} remplacé séquentiellement · {{OBJ}} = allure objectif marathon (80% VMA)
module.exports = [
  { num:1, phase:'Fondamentaux', charge:'Légère',
    objectif:'4 séances pour poser les bases : deux EF encadrant la qualité et une SL pour ancrer le rythme hebdomadaire.',
    conseil:'La 4e séance est un second EF le vendredi. Garder ces deux footings vraiment faciles te permet de te concentrer sur la qualité du jeudi.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}. Premier footing de la préparation marathon — allure vraiment légère, tu dois pouvoir parler sans effort. Ce lundi pose les jalons mentaux de la semaine et ancre le rythme des 4 séances hebdomadaires. Aucune pression physique : l\'objectif est de créer l\'habitude. Cours en nature si possible.', retour:'',
        note:'RPE 3/10 · Légèreté absolue.' },
      { jour:'Mercredi', type:'Fractionné', titre:'6 × 400 mètres, réveil neuromusculaire', duree:'45 min', pcts:[[65,65],[90,95]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 60m.',
        corps:'6 × 400 mètres à {{P}}. Récupération 90 sec au trot. Effort soutenu et régulier. Mémorise tes sensations sur chaque répétition.',
        retour:'10 min footing très lent.',
        note:'RPE 6-7/10 · Première séance de qualité. Découverte des allures.' },
      { jour:'Vendredi', type:'EF', titre:'Footing de récupération 40 minutes', duree:'40 min', pcts:[[60,62]],
        echauff:'', corps:'40 min à {{P}}, bien plus lentement que ton EF habituel — c\'est intentionnel. Ce footing de récupération efface la fatigue des 400m du mercredi et prépare tes jambes pour la SL de dimanche. Si les cuisses sont encore un peu lourdes, c\'est bon signe : les fibres musculaires se reconstruisent. Cours détendu, sans montre.', retour:'',
        note:'RPE 3/10 · Ce footing prépare la SL de dimanche.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 70 minutes', duree:'70 min', pcts:[[65,65]],
        echauff:'', corps:'70 min à {{P}}, rythme conversationnel tout du long. Première sortie longue du plan — la durée prime sur l\'allure, ralentis si tu dois. Hydrate-toi régulièrement même si tu n\'as pas soif. Mécanise la foulée sur du plat : cadence régulière, bras décontractés. Ces 70 min posent les bases mentales de la préparation.', retour:'',
        note:'RPE 4/10 · La durée prime. Si tu dois ralentir, ralentis.' },
    ]},

  { num:2, phase:'Fondamentaux', charge:'Légère',
    objectif:'Côtes jeudi, SL qui progresse. Volume total légèrement en hausse.',
    conseil:'Les côtes renforcent la puissance spécifique course. Tu en feras régulièrement tout au long du plan. Maitriser la technique dès maintenant.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}. Les côtes t\'attendent mercredi et la SL dimanche — ce lundi léger prépare l\'organisme sans entamer les réserves. Cours à cadence régulière, effort imperceptible. C\'est ce type de footing facile en début de semaine qui permet de tenir les séances de qualité et de progresser sur la durée.', retour:'',
        note:'RPE 3/10 · Léger.' },
      { jour:'Mercredi', type:'Côtes', titre:'8 côtes de 80 mètres', duree:'45 min', pcts:[[65,65],[100,105]],
        echauff:'25 min progressif à {{P}}, finir par 4 foulées bondissantes.',
        corps:'8 côtes de 80 mètres à effort maximal. Récupération : redescente en marchant. Appui avant-pied, genoux hauts, bras dynamiques.',
        retour:'10 min footing très lent.',
        note:'RPE 8/10 sur chaque côte · Effort bref. Récupération complète.' },
      { jour:'Vendredi', type:'EF', titre:'Footing de récupération 40 minutes', duree:'40 min', pcts:[[60,62]],
        echauff:'', corps:'40 min à {{P}}, allure récupération — encore plus lentement que ton EF standard. Les côtes de mercredi ont sollicité intensément les fibres rapides des mollets et des fessiers. Ce footing doux libère les tensions accumulées et prépare tes jambes pour la SL de dimanche. Une légère raideur musculaire est normale.', retour:'',
        note:'RPE 3/10 · Active la récupération.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 80 minutes', duree:'80 min', pcts:[[65,65]],
        echauff:'', corps:'80 min à {{P}}, 10 minutes de plus que la semaine passée. Terrain varié si possible : sols souples, légères déclivités. Sur le plat, concentre-toi sur la qualité de foulée — appui médio-pied, bras à 90°. La progression régulière de la SL est le pilier de ton endurance marathon. Reste à allure conversationnelle.', retour:'',
        note:'RPE 4/10 · 10 min de plus que S1.' },
    ]},

  { num:3, phase:'Fondamentaux', charge:'Modérée',
    objectif:'Première séance tempo. Introduction seuil en douceur avec 2 × 10 min.',
    conseil:'Le seuil : inconfortable mais tenable 10-15 min. Si tu ne peux pas prononcer un mot, tu vas trop vite.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}. Corps en mouvement en début de semaine. Ta première vraie séance seuil arrive mercredi — ce lundi vraiment léger garantit que tu y arriveras frais pour tenir les 2 × 10 min. Foulée économique, respiration libre, aucune ambition de performance. Terrain souple de préférence pour ménager les articulations.', retour:'',
        note:'RPE 3/10 · Léger.' },
      { jour:'Mercredi', type:'Tempo', titre:'2 × 10 minutes au seuil aérobie', duree:'50 min', pcts:[[65,70],[80,84]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 60m.',
        corps:'2 × 10 min à {{P}} avec 3 min de récupération au trot. Maintiens une allure régulière. Premier vrai contact avec le seuil.',
        retour:'10 min footing très lent.',
        note:'RPE 7/10 · 20 min totales au seuil. N\'accélère pas sur le 2e bloc.' },
      { jour:'Vendredi', type:'EF', titre:'Footing de récupération 40 minutes', duree:'40 min', pcts:[[60,62]],
        echauff:'', corps:'40 min à {{P}}, allure vraiment douce — en dessous de ton EF ordinaire. Ce footing de récupération active permet d\'éliminer les déchets métaboliques du seuil de mercredi et de régénérer les fibres sollicitées. La SL de demain sera meilleure si tu cours vraiment lentement aujourd\'hui. Cours sans montre, au ressenti.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 85 minutes', duree:'85 min', pcts:[[65,65]],
        echauff:'', corps:'85 min à {{P}}, 5 minutes de plus que S2. La progression paraît modeste mais représente 20 min de plus sur un mois. Régulier du début à la fin — si l\'allure monte naturellement en fin de footing, laisse-la, mais ne force pas. Hydrate-toi toutes les 20 min même par temps frais. La constance sur les SL fait le marathonien.', retour:'',
        note:'RPE 4/10 · Progression régulière.' },
    ]},

  { num:4, phase:'Fondamentaux', charge:'Modérée',
    objectif:'4 × 1000m pour développer la VMA. La SL atteint 90 min. Fin de la phase fondamentaux.',
    conseil:'Pars conservateur sur le 1er 1000m. La régularité sur les 4 répétitions prime sur la vitesse.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}. Semaine la plus chargée des fondamentaux : 4 × 1000m mercredi, EF récup vendredi, SL 90 min dimanche. Ce lundi léger pose les fondations de ta gestion d\'énergie de la semaine. Terrain souple, effort invisible, rythme de croisière économique. L\'énergie conservée ici sera précieuse sur les 1000m.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mercredi', type:'Fractionné', titre:'4 × 1000 mètres, développement VMA', duree:'55 min', pcts:[[65,65],[85,92]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
        corps:'4 × 1000 mètres à {{P}}. Récupération 2 min au trot. Régularité entre les répétitions. Même allure du 1er au 4e.',
        retour:'10 min footing très lent.',
        note:'RPE 7-8/10 · Régularité sur les 4 avant tout.' },
      { jour:'Vendredi', type:'EF', titre:'Footing de récupération 40 minutes', duree:'40 min', pcts:[[60,62]],
        echauff:'', corps:'40 min à {{P}}, allure récupération — plus lentement que l\'EF standard. Les 4 × 1000m de mercredi ont sollicité le système cardio-vasculaire en profondeur. Ce footing lent du vendredi élimine la fatigue accumulée et prépare tes jambes pour la grande sortie de dimanche. Ni montre, ni objectif de vitesse.', retour:'',
        note:'RPE 3/10 · Prépare la SL.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 90 minutes', duree:'90 min', pcts:[[65,65]],
        echauff:'', corps:'90 min à {{P}}, premier cap symbolique de la préparation marathon. L\'heure et demie marque la fin de la phase fondamentaux — à partir de la semaine prochaine, le plan change de nature. Hydrate-toi toutes les 20 min. Si tu as des chaussures de race day, c\'est le bon moment pour commencer à les tester.', retour:'',
        note:'RPE 4-5/10 · Cap des 90 min franchi.' },
    ]},

  { num:5, phase:'Développement', charge:'Moyenne',
    objectif:'5 × 1000m et la SL passe le cap des 100 min. Le développement VMA monte d\'un cran.',
    conseil:'Un intervalle de plus que la semaine passée. La progression est intentionnelle. Tiens la même allure sur les 5.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 45 minutes', duree:'45 min', pcts:[[65,65]],
        echauff:'', corps:'45 min à {{P}}. Phase développement : les footings s\'allongent avec les semaines. Tu accumules du temps sur pieds — base indispensable pour encaisser les séances de qualité. Reste détendu.', retour:'',
        note:'RPE 4/10.' },
      { jour:'Mercredi', type:'Fractionné', titre:'5 × 1000 mètres, montée en charge VMA', duree:'60 min', pcts:[[65,65],[85,92]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
        corps:'5 × 1000 mètres à {{P}}. Récupération 2 min au trot. Un de plus que S4. Maintiens la même allure du 1er au 5e.',
        retour:'10 min footing très lent.',
        note:'RPE 7-8/10 · Si le 5e est trop facile, tu n\'es pas allé assez vite.' },
      { jour:'Vendredi', type:'EF', titre:'Footing fondamental 45 minutes', duree:'45 min', pcts:[[65,65]],
        echauff:'', corps:'45 min à {{P}}. Footing de milieu de semaine entre les deux qualités. La SL de dimanche est à 100 min — conserve ton énergie. Cours sans montre, juste à l\'aise.', retour:'',
        note:'RPE 4/10.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 100 minutes', duree:'100 min', pcts:[[65,65]],
        echauff:'', corps:'100 min à {{P}}. Première sortie au-delà de l\'heure et demie — un cap important dans la préparation. Prends un gel à 1h pour t\'habituer à la nutrition en mouvement : ton estomac doit apprendre à digérer en courant bien avant le jour J. Hydratation toutes les 20 min. Reste à allure conversationnelle jusqu\'au bout.', retour:'',
        note:'RPE 5/10 · Dès 90 min, la nutrition entre en jeu. Teste maintenant.' },
    ]},

  { num:6, phase:'Développement', charge:'Moyenne',
    objectif:'2 × 15 min au seuil, SL à 1h50. La construction tempo prend de l\'ampleur.',
    conseil:'2 × 15 min au seuil : le 1er bloc à {{P}} conservateur, le 2e au même niveau. Pas d\'accélération intempestive.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 45 minutes', duree:'45 min', pcts:[[65,65]],
        echauff:'', corps:'45 min à {{P}}. Le 2 × 15 min seuil t\'attend mercredi — garde ce footing facile. Cadence régulière, muscles décontractés. Tu prépares la grosse séance du milieu de semaine.', retour:'',
        note:'RPE 4/10.' },
      { jour:'Mercredi', type:'Tempo', titre:'2 × 15 minutes au seuil aérobie', duree:'60 min', pcts:[[65,70],[82,87]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
        corps:'2 × 15 min à {{P}} avec 4 min de récupération au trot entre les 2 blocs. 30 min totales au seuil. Pars conservateur sur le 1er bloc : le seuil, c\'est l\'allure où tu peux prononcer quelques mots mais plus tenir une vraie conversation. Le 2e bloc doit être aussi régulier que le 1er — aucune accélération, juste la constance.',
        retour:'10 min footing très lent.',
        note:'RPE 7-8/10 · 30 min au seuil. Pars conservateur.' },
      { jour:'Vendredi', type:'EF', titre:'Footing fondamental 45 minutes', duree:'45 min', pcts:[[65,65]],
        echauff:'', corps:'45 min à {{P}}. Entre le seuil du mercredi et la SL 1h50 dimanche, ce footing maintient le flux sans générer de fatigue. Respiration libre, foulée économique.', retour:'',
        note:'RPE 4/10.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 1h50', duree:'1h50', pcts:[[65,65]],
        echauff:'', corps:'1h50 à {{P}}, la sortie longue la plus longue de la phase développement jusqu\'ici. Gel à 1h pour alimenter les 50 minutes restantes. Hydratation toutes les 20 min sans exception. À partir de 1h20, si tu sens la fatigue musculaire, raccourcis légèrement la foulée plutôt que de ralentir : ça prolonge la résistance et simule le marathon.', retour:'',
        note:'RPE 5/10.' },
    ]},

  { num:7, phase:'Développement', charge:'Élevée',
    objectif:'3 × 2000m fractionnés longs. SL à 2h pour la première fois. Grosse semaine.',
    conseil:'Les 2000m sont différents des 1000m : la gestion d\'allure sur 2000m est cruciale. Pars plus prudemment.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 50 minutes', duree:'50 min', pcts:[[65,65]],
        echauff:'', corps:'50 min à {{P}}. Grosse semaine : 3 × 2000m mercredi et 2h dimanche pour la première fois. Ce footing de lundi maintient le volume de base sans entamer les réserves pour les deux séances clés. Reste à allure strictement fondamentale, sans dérive de rythme en fin de footing. L\'énergie conservée ici fera la différence.', retour:'',
        note:'RPE 4/10.' },
      { jour:'Mercredi', type:'Fractionné', titre:'3 × 2000 mètres, fractionnés longs', duree:'65 min', pcts:[[65,65],[80,85]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
        corps:'3 × 2000 mètres à {{P}}. Récupération 4 min au trot. Régulier et soutenu sur les 3 blocs.',
        retour:'10 min footing très lent.',
        note:'RPE 8/10 · Gère le 1er prudemment.' },
      { jour:'Vendredi', type:'EF', titre:'Footing de récupération 45 minutes', duree:'45 min', pcts:[[60,62]],
        echauff:'', corps:'45 min à {{P}}, allure récupération — plus lentement que ton EF ordinaire. Les 3 × 2000m du mercredi ont imposé une fatigue musculaire profonde. Ce footing du vendredi accélère l\'élimination des déchets métaboliques et régénère les fibres sollicitées. La SL de 2h arrive dimanche — préserve chaque énergie disponible.', retour:'',
        note:'RPE 4/10.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 2 heures', duree:'2h', pcts:[[65,65]],
        echauff:'', corps:'2h à {{P}}, premier cap psychologique majeur de la préparation. La deuxième heure est différente de la première : le glycogène musculaire commence à s\'épuiser, la concentration doit rester active. Gel à 1h et à 1h20. Hydratation toutes les 20 min. Mémorise comment ton corps gère cet effort long — le marathon te demandera le double.', retour:'',
        note:'RPE 5/10 · 2h de course, premier cap majeur.' },
    ]},

  { num:8, phase:'Développement', charge:'Élevée',
    objectif:'2 × 3000m progressifs. SL à 2h10. Fin de phase développement.',
    conseil:'Les 3000m se courent en progression interne : commence le 1er km plus doucement, accélère sur le 2e et 3e.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 50 minutes', duree:'50 min', pcts:[[65,65]],
        echauff:'', corps:'50 min à {{P}}. Deux grosses séances t\'attendent : 2 × 3000m progressifs mercredi et SL 2h10 dimanche. Ce footing de lundi maintient le volume de base sans grever les réserves. Allure vraiment fondamentale, relâché, aucune ambition de performance. L\'énergie préservée ici sera précieuse sur les 3000m et les 2h10 de dimanche.', retour:'',
        note:'RPE 4/10.' },
      { jour:'Mercredi', type:'Fractionné', titre:'2 × 3000 mètres progressifs', duree:'65 min', pcts:[[65,65],[80,82],[82,85],[85,88]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
        corps:'2 × 3000 mètres à {{P}}. Récupération 5 min. Chaque 3000m en progression : 1er km à {{P}}, 2e km à {{P}}, 3e km à {{P}}. Accélère légèrement à chaque km.',
        retour:'10 min footing très lent.',
        note:'RPE 8/10 · La progression interne est la vraie difficulté.' },
      { jour:'Vendredi', type:'EF', titre:'Footing de récupération 45 minutes', duree:'45 min', pcts:[[60,62]],
        echauff:'', corps:'45 min à {{P}}, allure vraiment douce — en dessous de ton EF habituel. Les 2 × 3000m progressifs de mercredi ont sollicité l\'ensemble du système aérobie en profondeur. Ce footing lent du vendredi libère les tensions musculaires et régénère les réserves de glycogène. La SL de dimanche exige des jambes régénérées, pas épuisées.', retour:'',
        note:'RPE 4/10.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 2h10', duree:'2h10', pcts:[[65,65]],
        echauff:'', corps:'2h10 à {{P}}, la dernière grande SL sans bloc OBJ. Gel à 1h et à 1h25. Hydratation systématique toutes les 20 min. À partir de dimanche prochain, les sorties longues intègreront des blocs à allure marathon — profite de cette SL en endurance fondamentale pure pour consolider tes bases avant la phase spécifique.', retour:'',
        note:'RPE 5-6/10 · Dernière grande SL sans bloc OBJ.' },
    ]},

  { num:9, phase:'Spécificité marathon', charge:'Élevée',
    objectif:'Entrée spécifique : côtes + premier bloc OBJ en SL. Les jambes apprennent l\'allure marathon.',
    conseil:'Le bloc OBJ en fin de SL est l\'entraînement le plus spécifique du marathon. Mémorise l\'allure : c\'est celle que tu devras tenir 42 km le jour J.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 50 minutes', duree:'50 min', pcts:[[65,65]],
        echauff:'', corps:'50 min à {{P}}. Début de la phase spécifique marathon — la nature du travail change. Les côtes arrivent mercredi, la première SL avec bloc OBJ dimanche. Ce footing de lundi est vital : il maintient l\'accumulation de volume sans entamer les réserves pour les deux séances exigeantes qui suivent. Reste dans ta zone de confort absolu.', retour:'',
        note:'RPE 4/10.' },
      { jour:'Mercredi', type:'Côtes', titre:'10 côtes de 80 mètres, puissance marathon', duree:'50 min', pcts:[[65,65],[100,105]],
        echauff:'25 min progressif à {{P}}, finir par 4 foulées bondissantes.',
        corps:'10 côtes de 80 mètres à effort maximal. Récupération : redescente en marchant. Renforcement des extenseurs de hanche et mollets.',
        retour:'10 min footing très lent.',
        note:'RPE 8/10 · 10 côtes. Qualité sur chacune.' },
      { jour:'Vendredi', type:'EF', titre:'Footing de récupération 45 minutes', duree:'45 min', pcts:[[60,62]],
        echauff:'', corps:'45 min à {{P}}, allure récupération maximale. Les côtes de mercredi ont intensément sollicité les fibres rapides des mollets et fessiers — des muscles critiques pour le dernier tiers du marathon. Ce footing lent prépare tes jambes pour la grande SL de dimanche avec son premier bloc à allure marathon. Vraiment léger.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 2h avec 20 min allure marathon', duree:'2h', pcts:[[65,72],[75,80]],
        echauff:'', corps:'100 min à {{P}}, puis 20 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h. Premier bloc à allure marathon en fin de sortie longue : mémorise la sensation de {{OBJ}} sur des jambes déjà fatiguées — c\'est exactement ce que tu vivras au km 30 du marathon. Ce que tu ressens ici révèle ta forme actuelle.', retour:'',
        note:'RPE 6/10 en EF · 7/10 sur les 20 min.' },
    ]},

  { num:10, phase:'Spécificité marathon', charge:'Élevée',
    objectif:'3 × 15 min au seuil + SL 2h10 avec 25 min OBJ. Double pression qualité et volume.',
    conseil:'3 × 15 min au seuil est une séance de référence. Si les 3 blocs tiennent avec régularité, la forme marathon est au rendez-vous.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 50 minutes', duree:'50 min', pcts:[[65,65]],
        echauff:'', corps:'50 min à {{P}}. Deux séances majeures cette semaine : 3 × 15 min au seuil mercredi et SL 2h10 avec 25 min OBJ dimanche. Ce footing doit te garder frais — aucune tentative de pousser le rythme. Économie d\'effort maximale, foulée relâchée, respiration libre. C\'est la régularité des EF qui rend les séances dures possibles.', retour:'',
        note:'RPE 4/10.' },
      { jour:'Mercredi', type:'Tempo', titre:'3 × 15 minutes au seuil', duree:'75 min', pcts:[[65,70],[82,87]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
        corps:'3 × 15 min à {{P}} avec 4 min de récupération. 45 min totales au seuil. Régularité sur les 3 blocs.',
        retour:'10 min footing très lent.',
        note:'RPE 8/10 · 45 min au seuil. Séance de référence marathon.' },
      { jour:'Vendredi', type:'EF', titre:'Footing de récupération 45 minutes', duree:'45 min', pcts:[[60,62]],
        echauff:'', corps:'45 min à {{P}}, allure récupération — encore en dessous de ton EF habituel. Le seuil de mercredi (45 min totales au seuil) a profondément sollicité le système aérobie. Ce footing lent du vendredi prépare tes jambes pour la SL de dimanche avec 25 min à allure marathon en fin de sortie. Relâche complètement.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 2h10 avec 25 min allure marathon', duree:'2h10', pcts:[[65,72],[75,80]],
        echauff:'', corps:'105 min à {{P}}, puis 25 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h et à 1h20. 5 minutes de plus que S9 sur le bloc OBJ. Hydratation systématique. Ces 25 min à {{OBJ}} après 1h45 de course simulent exactement les conditions du marathon entre les km 28 et 35. Maintiens l\'allure jusqu\'à la dernière minute.', retour:'',
        note:'RPE 6/10 en EF · 7-8/10 sur les 25 min.' },
    ]},

  { num:11, phase:'Spécificité marathon', charge:'Maximale',
    objectif:'2 × 5000m spécifique marathon + SL 2h20 avec 30 min OBJ. Semaine de charge maximale.',
    conseil:'Le 2 × 5000m est la séance reine du plan. 10 km à allure marathon avec récupération. Si tu le tiens, tu es en route vers ton objectif.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 50 minutes', duree:'50 min', pcts:[[65,65]],
        echauff:'', corps:'50 min à {{P}}. Semaine de charge maximale : 2 × 5000m mercredi et SL 2h20 avec 30 min OBJ dimanche. Ce footing maintient le volume de base sans entamer les réserves pour les deux séances clés. Vraiment fondamental, aucune dérive d\'allure, effort invisible. L\'énergie conservée ici est directement réinvestie mercredi et dimanche.', retour:'',
        note:'RPE 4/10 · Conserve l\'énergie pour les séances clés.' },
      { jour:'Mercredi', type:'Fractionné', titre:'2 × 5000 mètres à allure marathon', duree:'80 min', pcts:[[65,65],[78,82]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
        corps:'2 × 5000 mètres à {{P}}. Récupération 5 min au trot. Pars conservateur sur le 1er. Le 2e doit être aussi régulier que le 1er, ou légèrement plus rapide.',
        retour:'10 min footing très lent.',
        note:'RPE 7-8/10 · 10 km à allure marathon avec récupération. La séance la plus spécifique du plan.' },
      { jour:'Vendredi', type:'EF', titre:'Footing de récupération 45 minutes', duree:'45 min', pcts:[[60,62]],
        echauff:'', corps:'45 min à {{P}}, allure récupération maximale. Tu viens de faire les 2 × 5000m à allure marathon mercredi — la SL 2h20 avec 30 min OBJ t\'attend dimanche. Ce footing est la charnière entre les deux : léger, sans pression, juste maintenir la circulation et libérer les jambes. Semaine de charge maximale — gère chaque énergie avec soin.', retour:'',
        note:'RPE 3/10 · Vital avant la SL 2h20.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 2h20 avec 30 min allure marathon', duree:'2h20', pcts:[[65,72],[75,80]],
        echauff:'', corps:'110 min à {{P}}, puis 30 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h, 1h20, 1h40. Hydratation systématique. La plus grande sortie longue depuis le début du plan. Ces 30 min à {{OBJ}} après presque 2h de course sont l\'épreuve de vérité de ta forme actuelle : si tu les tiens, tu es en route vers ton objectif.', retour:'',
        note:'RPE 6/10 en EF · 8/10 sur les 30 min · Le bloc OBJ final révèle ta forme.' },
    ]},

  { num:12, phase:'Spécificité marathon', charge:'Maximale',
    objectif:'LE pic de charge. Séance finisher + grande SL 2h30 avec 30 min OBJ. La semaine la plus importante du plan.',
    conseil:'Après cette semaine, le plus dur est derrière toi. La SL 2h30 est la sortie de référence. Elle ancre la confiance pour le jour J.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 50 minutes', duree:'50 min', pcts:[[65,65]],
        echauff:'', corps:'50 min à {{P}}. Dernière grosse semaine du plan. La séance finisher t\'attend mercredi, la grande SL 2h30 avec 30 min OBJ dimanche. Ce footing prépare le corps avant deux séances majeures — reste strictement à allure fondamentale. Prépare-toi mentalement : après cette semaine, le plus dur sera derrière toi.', retour:'',
        note:'RPE 4/10.' },
      { jour:'Mercredi', type:'Tempo', titre:'Séance finisher, 5 km seuil + 3 × 3 km allure marathon', duree:'90 min', pcts:[[65,65],[80,85],[78,82]],
        echauff:'25 min footing EF à {{P}}.',
        corps:'5 km à {{P}} (effort seuil) → 5 min de récupération → 3 × 3 km à ton allure objectif marathon ({{OBJ}}), récupération 3 min. La transition seuil vers allure marathon simule les exigences de la course.',
        retour:'10 min footing léger.',
        note:'RPE 8/10 · Si tu tiens les 3 blocs à {{OBJ}} après le seuil, tu es en parfaite forme.' },
      { jour:'Vendredi', type:'EF', titre:'Footing de récupération 40 minutes', duree:'40 min', pcts:[[60,62]],
        echauff:'', corps:'40 min à {{P}}, allure récupération maximale — plus lentement que tu ne le penses nécessaire. La séance finisher de mercredi a sollicité toutes tes filières. La grande SL 2h30 avec 30 min OBJ t\'attend dimanche, c\'est la séance la plus importante de tout le plan. Ce vendredi léger conditionne directement la qualité de ta performance dimanche.', retour:'',
        note:'RPE 3/10 · Ménage-toi pour la SL de dimanche.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Grande sortie longue 2h30 avec 30 min allure marathon', duree:'2h30', pcts:[[65,72],[75,80]],
        echauff:'', corps:'120 min à {{P}}, puis 30 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h, 1h20, 1h40, 2h. Hydratation toutes les 20 min. LA grande sortie du plan — après 2h de course, les 30 min à {{OBJ}} sont l\'épreuve ultime de ta préparation. Si tu les tiens, tu as les fondations pour réaliser ton objectif marathon.', retour:'',
        note:'RPE 6/10 en EF · 8/10 sur les 30 min · Le pic est atteint. La récupération commence maintenant.' },
    ]},

  { num:13, phase:'Pic de charge', charge:'Élevée (légère réduction)',
    objectif:'Volume légèrement réduit (-15%). Maintien de l\'intensité avec 4 × 3 km OBJ. Consolidation.',
    conseil:'Pas d\'affûtage encore. C\'est une consolidation. L\'intensité reste là pour ancrer les adaptations de S12.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 45 minutes', duree:'45 min', pcts:[[65,65]],
        echauff:'', corps:'45 min à {{P}}. Phase de consolidation post-pic de charge. Le corps assimile les adaptations de S12 — ce footing maintient le flux sans surcharger. Terrain souple, pas de contrainte.', retour:'',
        note:'RPE 4/10.' },
      { jour:'Mercredi', type:'Fractionné', titre:'4 × 3 km à allure marathon', duree:'80 min', pcts:[[65,65],[78,82]],
        echauff:'25 min footing EF à {{P}}.',
        corps:'4 × 3 km exactement à ton allure objectif marathon ({{OBJ}}). Récupération 3 min au trot entre chaque. 12 km totaux à {{OBJ}} en blocs : cette séance ancre la mémoire musculaire de l\'allure cible. Après 12 semaines de construction, tes jambes connaissent ce rythme — l\'objectif est de le rendre naturel et reproductible sur 42 km.',
        retour:'10 min footing léger.',
        note:'RPE 7-8/10 · Maintien de la mémoire allure marathon.' },
      { jour:'Vendredi', type:'EF', titre:'Footing de récupération 40 minutes', duree:'40 min', pcts:[[60,62]],
        echauff:'', corps:'40 min à {{P}}, bien plus lentement que ton allure fondamentale. Consolidation post-S12. Le bloc OBJ dimanche demande des jambes fraîches — ce footing lent en est la clé. Relâche les épaules, laisse le corps récupérer.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 2h15 avec 30 min allure marathon', duree:'2h15', pcts:[[65,72],[75,80]],
        echauff:'', corps:'105 min à {{P}}, puis 30 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h, 1h20, 1h40. Légèrement plus court que S12 mais le bloc OBJ reste identique. Hydratation systématique. Tu consolides la forme acquise au pic de charge sans épuiser davantage les réserves. Ces 30 min à {{OBJ}} doivent commencer à sembler naturels.', retour:'',
        note:'RPE 6/10 en EF · 8/10 sur les 30 min.' },
    ]},

  { num:14, phase:'Pic de charge', charge:'Réduite, pré-affûtage',
    objectif:'Volume réduit (-30%). Maintien VMA avec 4 × 1500m. SL allégée. Début de la super-compensation.',
    conseil:'L\'affûtage commence. Le corps entre en phase de recharge. Laisse-le récupérer activement.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}. L\'affûtage commence. Les footings raccourcissent progressivement. Le corps entre en super-compensation — tu te recharges. Reste vraiment léger, sans aucune envie de performance.', retour:'',
        note:'RPE 3-4/10.' },
      { jour:'Mercredi', type:'Fractionné', titre:'4 × 1500 mètres, maintien VMA pré-affûtage', duree:'60 min', pcts:[[65,65],[83,90]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
        corps:'4 × 1500 mètres à {{P}}. Récupération 3 min. Intervalles plus courts : maintien des sensations VMA sans fatigue excessive.',
        retour:'10 min footing très lent.',
        note:'RPE 7/10 · Moins de volume, mêmes sensations.' },
      { jour:'Vendredi', type:'EF', titre:'Footing de récupération 35 minutes', duree:'35 min', pcts:[[60,62]],
        echauff:'', corps:'35 min à {{P}}, vraiment léger — l\'affûtage est bien lancé. Ce footing court maintient le flux sanguin et entretient la mobilité articulaire sans aucune sollicitation musculaire significative. Tes jambes se rechargent en profondeur. Si tu ressens de l\'impatience de courir plus fort, c\'est bon signe : la super-compensation opère.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 1h50 avec 15 min allure marathon', duree:'1h50', pcts:[[65,72],[75,80]],
        echauff:'', corps:'95 min à {{P}}, puis 15 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h. Sortie longue allégée par rapport aux semaines précédentes — le bloc OBJ est court mais essentiel pour maintenir la mémoire de l\'allure pendant l\'affûtage. Ces 15 min à {{OBJ}} doivent te sembler fluides et naturels maintenant : le signal que tu es prêt.', retour:'',
        note:'RPE 5/10 en EF · 7/10 sur les 15 min · Allégée mais maintien des sensations.' },
    ]},

  { num:15, phase:'Consolidation', charge:'Réduite, affûtage',
    objectif:'4 séances légères pour laisser les adaptations s\'installer. Volume réduit de 45%.',
    conseil:'Dors 8h, mange bien. Les jambes doivent commencer à fourmiller d\'impatience. Ne rajoute pas de séances.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing léger 50 minutes', duree:'50 min', pcts:[[65,65]],
        echauff:'', corps:'50 min à {{P}}, allure légère. Le footing le plus long de la semaine de consolidation : il maintient l\'endurance de base sans fatiguer. Cours en nature, apprécie la légèreté. La semaine de course se profile.', retour:'',
        note:'RPE 3/10 · Tu dois finir comme si tu venais de te promener.' },
      { jour:'Mercredi', type:'Tempo', titre:'2 × 15 minutes au seuil, volume réduit', duree:'55 min', pcts:[[65,72],[82,88]],
        echauff:'25 min progressif à {{P}}.', corps:'2 × 15 min à {{P}}. Volume réduit de 50% mais intensité maintenue. Récupération 4 min. Termine par 1 km à ton allure marathon ({{OBJ}}).', retour:'10 min footing très lent.',
        note:'RPE 7/10 · Maintien des sensations sans épuisement.' },
      { jour:'Vendredi', type:'EF', titre:'Footing léger 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}, allure légère. Dans les 10 dernières minutes, place 4 à 6 accélérations de 60m à ton allure marathon pour garder les sensations neuromusculaires vives. Termine frais et dynamisé.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Dimanche', type:'EF', titre:'Footing léger 35 minutes', duree:'35 min', pcts:[[60,65]],
        echauff:'', corps:'35 min très légers à {{P}}. Dernier footing avant la semaine de course. Laisse les jambes rouler librement, le corps se recharge. Finis avec le sourire.', retour:'',
        note:'RPE 3/10 · Tu dois finir frais et dynamisé.' },
    ]},

  { num:16, phase:'Semaine de course', charge:'Conserve, tu es prêt',
    objectif:'Arriver au départ reposé, confiant, les jambes fraîches. 15 semaines de travail ont été faites.',
    conseil:'Pars à {{OBJ}}/km dès le départ. L\'adrénaline va te pousser à aller plus vite, résiste.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing très léger 30 minutes', duree:'30 min', pcts:[[60,65]],
        echauff:'', corps:'30 min à {{P}}. Maintenir la circulation. Si tu te sens fatigué, réduis à 20 min.', retour:'',
        note:'RPE 3/10 · Aucun effort.' },
      { jour:'Mercredi', type:'Fractionné', titre:'8 × 1 min / 1 min à allure marathon', duree:'40 min',
        echauff:'15 min de footing très léger.',
        corps:'8 × 1 minute à ton allure objectif marathon ({{OBJ}}) / 1 minute au trot. Réveille les jambes sans les fatiguer.',
        retour:'10 min de jogging léger.',
        note:'RPE 6/10 · Maintien des sensations avant le marathon.' },
      { jour:'Samedi', type:'Activation', titre:'Activation J-1 + accélérations', duree:'30 min', pcts:[[60,65]],
        echauff:'', corps:'20 min de trot à {{P}}. Puis 6 à 8 accélérations progressives de 80m jusqu\'à ton allure objectif ({{OBJ}}). Récupère 60 sec en marchant.', retour:'',
        note:'Prépare tes affaires ce soir. Visualise les premiers kilomètres à {{OBJ}}/km.' },
      { jour:'Dimanche', type:'Course', titre:'MARATHON', duree:'Jour J',
        echauff:'10-15 min de jogging très léger avant le départ.',
        corps:'KM 1-8 : pars à {{OBJ}}/km exactement. KM 9-21 : régularité absolue, gel à chaque ravitaillement. KM 22-30 : maintiens {{OBJ}}, écoute ton corps. KM 31-35 : raccourcis la foulée, garde les bras actifs. KM 36-42 : donne absolument tout.',
        retour:'20-30 min de marche. Ravitaillement dans les 30 min.',
        note:'La douleur aux km 30-35 est normale. C\'est là que se gagne un marathon. Tiens bon.' },
    ]},
]
