// Marathon 16 semaines · 6 séances/semaine · Palier Intermédiaire (VMA 13.5 à 18.5)
// 6 séances : 2 qualités + 3 EF/RA + SL. Volume maximum.
// {{P}} remplacé séquentiellement · {{OBJ}} = allure objectif marathon (80% VMA)
module.exports = [
  { num:1, phase:'Fondamentaux', charge:'Légère',
    objectif:'6 séances pour lancer la préparation : 3 EF, 1 qualité légère, 1 EF jeudi, 1 SL. Volume de mise en route.',
    conseil:'Plan à 6 séances : les 3 EF encadrent la qualité et la SL. Garde les EF vraiment faciles. La charge de S1 est délibérément légère.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}. Coup d\'envoi de 16 semaines de préparation. Sur 6 séances hebdomadaires, ce lundi EF est le carburant silencieux de toute la semaine. Corps en mouvement, jambes légères, allure conversation.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mardi', type:'EF', titre:'Footing de récupération 35 minutes', duree:'35 min', pcts:[[60,62]],
        echauff:'', corps:'35 min à {{P}}, bien plus lentement que l\'allure fondamentale. 6 séances par semaine nécessite une gestion fine de l\'énergie : ce mardi lent prépare les qualités du mercredi. Circulation sanguine, jambes décontractées.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mercredi', type:'Fractionné', titre:'6 × 400 mètres, réveil neuromusculaire', duree:'45 min', pcts:[[65,65],[90,95]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 60m.',
        corps:'6 × 400 mètres à {{P}}. Récupération 90 sec au trot entre chaque. Effort régulier et contrôlé sur les 6 répétitions. Première prise de contact avec les allures rapides : ne cherche pas à performer, cherche à ressentir la régularité.',
        retour:'10 min footing très lent.',
        note:'RPE 6-7/10 · Première qualité. Découverte des allures.' },
      { jour:'Jeudi', type:'EF', titre:'Footing fondamental 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}. Récupération active après les 400m. Ce jeudi léger est indispensable pour tenir les 2 qualités hebdomadaires sans s\'épuiser. Foulée souple, respiration naturelle, aucune pression.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Vendredi', type:'Tempo', titre:'2 × 8 minutes au seuil, introduction légère', duree:'45 min', pcts:[[65,70],[80,83]],
        echauff:'25 min progressif à {{P}}.',
        corps:'2 × 8 min à {{P}} avec 3 min de récupération au trot. Introduction légère au seuil — 16 min totales. Tu dois pouvoir prononcer quelques mots mais pas tenir une vraie conversation. Régulier sur les 2 blocs.',
        retour:'10 min footing très lent.',
        note:'RPE 6/10 · 2e qualité de la semaine, intentionnellement légère.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 70 minutes', duree:'70 min', pcts:[[65,65]],
        echauff:'', corps:'70 min à {{P}}. Rythme conversationnel tout au long. Première sortie longue du plan : pose les bases mentales de l\'endurance marathon. Hydrate-toi. Si tu dois ralentir pour parler, ralentis — la durée prime sur l\'allure.', retour:'',
        note:'RPE 4/10.' },
    ]},

  { num:2, phase:'Fondamentaux', charge:'Légère',
    objectif:'Côtes mercredi + seuil vendredi. La 2e qualité prend de l\'intensité progressivement.',
    conseil:'6 séances avec 2 qualités dans la même semaine dès S2. Les EF lundi, mardi et jeudi sont le carburant qui permet les deux qualités.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}. Deux qualités t\'attendent mercredi (côtes) et vendredi (seuil). Ce lundi EF ancre le rythme hebdomadaire et active la circulation. Vraiment léger, foulée économique, sans effort conscient.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mardi', type:'EF', titre:'Footing de récupération 35 minutes', duree:'35 min', pcts:[[60,62]],
        echauff:'', corps:'35 min à {{P}}, plus lentement que l\'EF standard. Les côtes mercredi demandent de l\'explosivité — arrive frais. Ce footing récupération du mardi est stratégique : léger sur les jambes, fluide, sans effort.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mercredi', type:'Côtes', titre:'8 côtes de 80 mètres', duree:'45 min', pcts:[[65,65],[100,105]],
        echauff:'25 min progressif à {{P}}, finir par 4 foulées bondissantes.',
        corps:'8 côtes de 80 mètres à effort maximal. Récupération : redescente en marchant (2 min). Appui avant-pied, genoux hauts, bras dynamiques. Les côtes recrutent les fibres rapides sans la fatigue de la piste — 8 sprints brefs et explosifs.',
        retour:'10 min footing très lent.',
        note:'RPE 8/10 sur chaque côte.' },
      { jour:'Jeudi', type:'EF', titre:'Footing fondamental 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}. Récupération active après les côtes. Les fibres musculaires recrutées hier ont besoin d\'afflux sanguin — ce footing lent favorise la régénération avant le seuil de vendredi. Pas d\'effort.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Vendredi', type:'Tempo', titre:'2 × 10 minutes au seuil', duree:'50 min', pcts:[[65,70],[80,84]],
        echauff:'25 min progressif à {{P}}.',
        corps:'2 × 10 min à {{P}} avec 3 min de récupération. 20 min au seuil au total. Maintiens une allure régulière sur les 2 blocs. Si tu accélères sur le 2e, tu es parti trop doucement sur le 1er — c\'est normal en début de plan.',
        retour:'10 min footing très lent.',
        note:'RPE 7/10 · 2e qualité. Montée en intensité progressive.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 80 minutes', duree:'80 min', pcts:[[65,65]],
        echauff:'', corps:'80 min à {{P}}. 10 min de plus que S1. Terrain varié si possible — les changements de surface renforcent les appuis. Hydrate-toi. Mécanise la foulée sur les parties plates. La progression est régulière et volontaire.', retour:'',
        note:'RPE 4/10.' },
    ]},

  { num:3, phase:'Fondamentaux', charge:'Modérée',
    objectif:'2 × 15 min seuil mercredi + 5 × 1000m vendredi. Deux qualités de bon niveau dès S3.',
    conseil:'La progression est délibérément plus rapide sur 6 séances. Les 3 EF permettent d\'encaisser des 2 qualités hebdomadaires.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}. Semaine avec 2 × 15 min seuil et 5 × 1000m — deux qualités exigeantes. Ce lundi léger pose les bases de l\'énergie de la semaine. Vraiment facile, foulée économique, sans montre si tu veux.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mardi', type:'EF', titre:'Footing de récupération 35 minutes', duree:'35 min', pcts:[[60,62]],
        echauff:'', corps:'35 min à {{P}}, allure très douce. Le 2 × 15 min seuil mercredi est une séance importante — 30 min totales au seuil. Arrive bien reposé. Ce footing lent est une récupération active, pas un entraînement.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mercredi', type:'Tempo', titre:'2 × 15 minutes au seuil aérobie', duree:'60 min', pcts:[[65,70],[82,87]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
        corps:'2 × 15 min à {{P}} avec 4 min de récupération au trot. 30 min totales au seuil dès S3 — la progression est rapide sur 6 séances. Régularité absolue : le 2e bloc doit être aussi soutenu que le 1er.',
        retour:'10 min footing très lent.',
        note:'RPE 7-8/10 · 30 min au seuil dès S3 sur le plan 6 séances.' },
      { jour:'Jeudi', type:'EF', titre:'Footing fondamental 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}. Récupération active entre les 2 qualités majeures de la semaine. Le 5 × 1000m vendredi nécessite des jambes fraîches — ce jeudi lent est la clé. Aucune ambition de performance, juste de la circulation.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Vendredi', type:'Fractionné', titre:'5 × 1000 mètres', duree:'60 min', pcts:[[65,65],[85,92]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
        corps:'5 × 1000 mètres à {{P}}. Récupération 2 min au trot entre chaque. Même allure du 1er au 5e. Après le seuil de mercredi, pars conservateur sur le 1er intervalle : mieux finir fort que partir trop vite.',
        retour:'10 min footing très lent.',
        note:'RPE 7-8/10 · 2e qualité de la semaine. Gère l\'énergie.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 85 minutes', duree:'85 min', pcts:[[65,65]],
        echauff:'', corps:'85 min à {{P}}. 5 min de plus que S2. La progression est régulière et volontaire — ne cherche pas à aller plus vite. Hydrate-toi toutes les 20-25 min. La sortie longue hebdomadaire construit la résistance à l\'effort long.', retour:'',
        note:'RPE 4/10.' },
    ]},

  { num:4, phase:'Fondamentaux', charge:'Modérée',
    objectif:'3 × 2000m mercredi + 3 × 15 min seuil vendredi. Montée en charge des 2 qualités. SL à 90 min.',
    conseil:'Semaine la plus chargée des fondamentaux. Les 2 EF (mardi/jeudi) sont vraiment faciles. Gère l\'énergie entre les 2 qualités.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}. Semaine la plus chargée des fondamentaux : 3 × 2000m + 3 × 15 min seuil + SL 90 min. Ce lundi EF est le fondement de ta gestion d\'énergie sur la semaine. Vraiment léger, sans effort.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mardi', type:'EF', titre:'Footing de récupération 35 minutes', duree:'35 min', pcts:[[60,62]],
        echauff:'', corps:'35 min à {{P}}, plus lentement que l\'allure EF. Les 3 × 2000m mercredi sont des fractionnés longs — arrive frais. Ce footing très doux prépare les jambes à l\'effort soutenu. Circulation sanguine, pas de fatigue.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mercredi', type:'Fractionné', titre:'3 × 2000 mètres, fractionnés longs', duree:'65 min', pcts:[[65,65],[80,85]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
        corps:'3 × 2000 mètres à {{P}}. Récupération 4 min au trot. Régulier sur les 3 blocs. Les 2000m sont plus longs que les 1000m — la gestion de l\'allure sur 2 km est un nouveau défi. Commence prudemment sur le 1er.',
        retour:'10 min footing très lent.',
        note:'RPE 8/10 · Fractionnés longs dès S4.' },
      { jour:'Jeudi', type:'EF', titre:'Footing fondamental 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}. Récupération active entre les 2 qualités majeures. Les 3 × 15 min seuil vendredi demandent de l\'énergie après les 2000m — ce jeudi léger est stratégique. Vraiment facile, sans ambition.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Vendredi', type:'Tempo', titre:'3 × 15 minutes au seuil', duree:'75 min', pcts:[[65,70],[82,87]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
        corps:'3 × 15 min à {{P}} avec 4 min de récupération. 45 min totales au seuil. Après les 2000m de mercredi, c\'est une semaine très exigeante. Pars à l\'allure basse de la zone, tiens la régularité sur les 3 blocs.',
        retour:'10 min footing très lent.',
        note:'RPE 7-8/10 · 45 min au seuil en fin de semaine chargée.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 90 minutes', duree:'90 min', pcts:[[65,65]],
        echauff:'', corps:'90 min à {{P}}. Premier cap symbolique : l\'heure et demie. Hydrate-toi toutes les 20 min. Gel recommandé à 1h pour habituer le corps à la nutrition en course. La phase de développement commence la semaine prochaine.', retour:'',
        note:'RPE 4-5/10.' },
    ]},

  { num:5, phase:'Développement', charge:'Moyenne',
    objectif:'Phase développement : 2 × 5000m OBJ mercredi + 3 × 15 min seuil vendredi. Séances spécifiques dès S5.',
    conseil:'Sur 6 séances, la progression est plus rapide. Les 2 × 5000m à allure marathon arrivent dès S5 pour ancrer l\'allure tôt dans le cycle.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 45 minutes', duree:'45 min', pcts:[[65,65]],
        echauff:'', corps:'45 min à {{P}}. Passage en phase développement. Les 2 × 5000m à allure marathon arrivent mercredi dès S5 — la progression est volontairement rapide. Ce lundi léger est le fondement de la semaine. Cadence régulière.', retour:'',
        note:'RPE 4/10.' },
      { jour:'Mardi', type:'EF', titre:'Footing de récupération 40 minutes', duree:'40 min', pcts:[[60,62]],
        echauff:'', corps:'40 min à {{P}}, plus lentement que l\'allure fondamentale. Les 2 × 5000m à allure marathon mercredi sont la première grande séance spécifique du plan — arrive frais. Ce footing très doux protège l\'énergie disponible.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mercredi', type:'Fractionné', titre:'2 × 5000 mètres à allure marathon', duree:'80 min', pcts:[[65,65],[78,82]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
        corps:'2 × 5000 mètres à {{P}}. Récupération 5 min au trot entre les 2 blocs. 10 km à allure marathon. Pars conservateur sur le 1er : les sensations doivent sembler faciles les 3 premières minutes. Le 2e bloc est le vrai test.',
        retour:'10 min footing très lent.',
        note:'RPE 7-8/10 · Séance spécifique marathon dès S5.' },
      { jour:'Jeudi', type:'EF', titre:'Footing fondamental 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}. Récupération active après les 2 × 5000m. Les 3 × 15 min seuil vendredi nécessitent des jambes récupérées — ce jeudi très léger est indispensable. Foulée souple, aucune pression de performance.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Vendredi', type:'Tempo', titre:'3 × 15 minutes au seuil', duree:'75 min', pcts:[[65,70],[82,87]],
        echauff:'25 min progressif à {{P}}.',
        corps:'3 × 15 min à {{P}} avec 4 min de récupération. 45 min au seuil en complément des 2 × 5000m de mercredi. Semaine dense. Pars à l\'allure basse de la zone — le corps est déjà sollicité. Régularité sur les 3 blocs.',
        retour:'10 min footing très lent.',
        note:'RPE 7-8/10 · Maintien du seuil en complément de la spécificité marathon.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 100 minutes', duree:'100 min', pcts:[[65,65]],
        echauff:'', corps:'100 min à {{P}}. Première sortie au-delà de 90 min. Gel recommandé à 1h pour habituer le corps à la nutrition en course. Hydratation toutes les 20 min. À partir de maintenant, la nutrition fait partie de l\'entraînement.', retour:'',
        note:'RPE 5/10.' },
    ]},

  { num:6, phase:'Développement', charge:'Moyenne',
    objectif:'Côtes mercredi + séance finisher vendredi. Variation des stimuli pour un développement physique complet.',
    conseil:'Les côtes travaillent la puissance, le finisher travaille la résistance à l\'allure marathon. Deux stimuli complémentaires dans une semaine.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 45 minutes', duree:'45 min', pcts:[[65,65]],
        echauff:'', corps:'45 min à {{P}}. Côtes mercredi + finisher vendredi cette semaine — deux stimuli puissants. Ce lundi EF maintient le volume sans entamer les réserves. Terrain plat, foulée économique, aucune intensité voulue.', retour:'',
        note:'RPE 4/10.' },
      { jour:'Mardi', type:'EF', titre:'Footing de récupération 40 minutes', duree:'40 min', pcts:[[60,62]],
        echauff:'', corps:'40 min à {{P}}, allure très douce. 12 côtes explosives t\'attendent mercredi — les jambes doivent être fraîches pour un effort maximal sur chaque montée. Ce footing lent est une préparation stratégique.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mercredi', type:'Côtes', titre:'12 côtes de 80 mètres', duree:'55 min', pcts:[[65,65],[100,105]],
        echauff:'25 min progressif à {{P}}, finir par 4 foulées bondissantes.',
        corps:'12 côtes de 80 mètres à effort maximal. Récupération : redescente en marchant (2 min). Appui avant-pied, genoux hauts, bras dynamiques. 12 côtes développent la puissance des extenseurs de hanche — muscles clés aux km 30-35 du marathon.',
        retour:'10 min footing très lent.',
        note:'RPE 8/10 · 12 côtes. Qualité sur toutes.' },
      { jour:'Jeudi', type:'EF', titre:'Footing fondamental 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}. Récupération active entre les côtes et le finisher de vendredi. Ce jeudi léger est le pont entre 2 séances très exigeantes. Aucune pression, juste de la circulation et de la récupération musculaire.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Vendredi', type:'Tempo', titre:'Séance finisher, 5 km seuil + 2 × 3 km allure marathon', duree:'75 min', pcts:[[65,65],[80,85],[78,82]],
        echauff:'25 min footing EF à {{P}}.',
        corps:'5 km à {{P}} (effort seuil, régulier) → 4 min récupération → 2 × 3 km à ton allure objectif marathon ({{OBJ}}), récup 3 min entre chaque. La transition seuil → allure marathon reproduit ce qui se passe dans un vrai marathon.',
        retour:'10 min footing léger.',
        note:'RPE 8/10 · Transition seuil vers allure marathon. Séance de qualité avancée.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 1h50', duree:'1h50', pcts:[[65,65]],
        echauff:'', corps:'1h50 à {{P}}. Gel à 1h. Hydratation toutes les 20 min. Après 2 qualités difficiles cette semaine, la SL doit rester à allure EF — ne cède pas à la tentation d\'accélérer. La régularité sur 1h50 est l\'objectif.', retour:'',
        note:'RPE 5/10.' },
    ]},

  { num:7, phase:'Développement', charge:'Élevée',
    objectif:'3 × 15 min seuil mercredi + 4 × 3 km OBJ vendredi. Double charge spécifique marathon.',
    conseil:'Les blocs OBJ en qualité pure (vendredi, sans la fatigue de la SL) permettent de graver l\'allure marathon avec précision.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 50 minutes', duree:'50 min', pcts:[[65,65]],
        echauff:'', corps:'50 min à {{P}}. Double charge cette semaine : 3 × 15 min seuil mercredi + 4 × 3 km OBJ vendredi. Ce lundi EF de 50 min maintient le volume sans entamer les réserves pour les deux qualités. Vraiment léger.', retour:'',
        note:'RPE 4/10.' },
      { jour:'Mardi', type:'EF', titre:'Footing de récupération 40 minutes', duree:'40 min', pcts:[[60,62]],
        echauff:'', corps:'40 min à {{P}}, plus lentement que l\'allure fondamentale. Le seuil mercredi est une séance importante — 45 min totales au seuil. Ce footing très doux du mardi préserve l\'énergie. Jambes légères, foulée économique.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mercredi', type:'Tempo', titre:'3 × 15 minutes au seuil', duree:'75 min', pcts:[[65,70],[82,87]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
        corps:'3 × 15 min à {{P}} avec 4 min de récupération. 45 min au seuil. Régularité sur les 3 blocs : le 3e doit être aussi fort que le 1er. Si tu craques sur le 3e, tu partais trop vite sur le 1er — le piège classique du seuil.',
        retour:'10 min footing très lent.',
        note:'RPE 8/10.' },
      { jour:'Jeudi', type:'EF', titre:'Footing fondamental 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}. Récupération active entre le seuil de mercredi et les 4 × 3 km OBJ de vendredi. Ce jeudi est le pivot de la semaine — léger, fluide, sans effort. Les blocs OBJ demandent des jambes fraîches.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Vendredi', type:'Fractionné', titre:'4 × 3 km à allure marathon', duree:'75 min', pcts:[[65,65],[78,82]],
        echauff:'25 min footing EF à {{P}}.',
        corps:'4 × 3 km exactement à ton allure objectif marathon ({{OBJ}}). Récupération 3 min au trot. 12 km à {{OBJ}} en blocs. Pars précisément à {{OBJ}} sur le 1er — ni plus rapide, ni plus lent. La précision de l\'allure est l\'objectif.',
        retour:'10 min footing léger.',
        note:'RPE 7-8/10 · Blocs OBJ purs. Régularité sur les 4.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 2 heures', duree:'2h', pcts:[[65,65]],
        echauff:'', corps:'2h à {{P}}. Premier cap psychologique majeur. Gel à 1h et 1h20. Hydratation systématique. À partir de 2h de course, la gestion mentale compte autant que la physique. Cours par segments de 20 min dans ta tête.', retour:'',
        note:'RPE 5/10.' },
    ]},

  { num:8, phase:'Développement', charge:'Élevée',
    objectif:'Séance finisher mercredi + 2 × 5000m OBJ vendredi + SL 2h10. Triple charge avant la phase spécifique.',
    conseil:'Semaine très chargée. Les 2 séances de qualité sont très exigeantes. Récupère bien jeudi entre les deux.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 50 minutes', duree:'50 min', pcts:[[65,65]],
        echauff:'', corps:'50 min à {{P}}. Semaine très exigeante : finisher mercredi + 2 × 5000m vendredi + SL 2h10. Ce lundi EF préserve chaque joule d\'énergie pour encaisser les 3 séances majeures. Reste vraiment conservateur.', retour:'',
        note:'RPE 4/10.' },
      { jour:'Mardi', type:'EF', titre:'Footing de récupération 40 minutes', duree:'40 min', pcts:[[60,62]],
        echauff:'', corps:'40 min à {{P}}, allure très douce. La séance finisher mercredi est la plus complexe du plan — 5 km seuil + 3 × 3 km OBJ. Arrive avec des jambes fraîches. Ce footing lent du mardi est une préparation stratégique.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mercredi', type:'Tempo', titre:'Séance finisher, 5 km seuil + 3 × 3 km allure marathon', duree:'90 min', pcts:[[65,65],[80,85],[78,82]],
        echauff:'25 min footing EF à {{P}}.',
        corps:'5 km à {{P}} (effort seuil, régulier) → 5 min récupération → 3 × 3 km à ton allure objectif marathon ({{OBJ}}), récup 3 min. La transition seuil → allure marathon est la clé de la réussite le jour J. Pars conservateur sur le 5 km.',
        retour:'10 min footing léger.',
        note:'RPE 8/10 · Séance de référence marathon.' },
      { jour:'Jeudi', type:'EF', titre:'Footing de récupération 35 minutes', duree:'35 min', pcts:[[60,62]],
        echauff:'', corps:'35 min à {{P}}, allure vraiment douce. Récupération cruciale entre le finisher de mercredi et les 2 × 5000m de vendredi. Les jambes ont été sollicitées hier — ce footing lent facilite la régénération musculaire.', retour:'',
        note:'RPE 3/10 · Très léger. Prépare les 5000m de vendredi.' },
      { jour:'Vendredi', type:'Fractionné', titre:'2 × 5000 mètres à allure marathon', duree:'80 min', pcts:[[65,65],[78,82]],
        echauff:'25 min progressif à {{P}}.',
        corps:'2 × 5000 mètres à {{P}}. Récupération 5 min au trot. Le lendemain d\'un finisher, les jambes sont encore sollicitées — pars 5 sec/km plus lentement que d\'habitude sur le 1er 5000m. Le corps s\'adapte à la répétition des efforts.',
        retour:'10 min footing très lent.',
        note:'RPE 7/10 · Intensité légèrement réduite pour tenir après mercredi.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 2h10', duree:'2h10', pcts:[[65,65]],
        echauff:'', corps:'2h10 à {{P}}. Gel à 1h et 1h25. Hydratation systématique. Fin de la phase développement : tu as accumulé suffisamment de base aérobie. La phase spécifique commence semaine prochaine. Cours régulier et conserve de l\'énergie.', retour:'',
        note:'RPE 5-6/10 · Fin de la phase développement.' },
    ]},

  { num:9, phase:'Spécificité marathon', charge:'Élevée',
    objectif:'Côtes mercredi + 4 × 3 km OBJ vendredi + SL 2h avec 20 min OBJ. Spécificité marathon totale.',
    conseil:'La phase spécifique est lancée. Toutes les séances de qualité travaillent maintenant autour de l\'allure marathon.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 50 minutes', duree:'50 min', pcts:[[65,65]],
        echauff:'', corps:'50 min à {{P}}. Début de phase spécifique. Côtes mercredi, 4 × 3 km OBJ vendredi et SL avec bloc OBJ dimanche — un triptyque exigeant. Ce lundi léger est le carburant silencieux de toute la semaine.', retour:'',
        note:'RPE 4/10.' },
      { jour:'Mardi', type:'EF', titre:'Footing de récupération 40 minutes', duree:'40 min', pcts:[[60,62]],
        echauff:'', corps:'40 min à {{P}}, allure très douce. 12 côtes explosives mercredi demandent des jambes fraîches et des fibres musculaires disponibles. Ce footing lent du mardi limite la fatigue résiduelle. Vraiment à l\'aise.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mercredi', type:'Côtes', titre:'12 côtes de 80 mètres, puissance marathon', duree:'55 min', pcts:[[65,65],[100,105]],
        echauff:'25 min progressif à {{P}}, finir par 4 foulées bondissantes.',
        corps:'12 côtes de 80 mètres à effort maximal. Récupération : redescente en marchant. Appui avant-pied, genoux hauts, bras actifs. Ces côtes renforcent les extenseurs de hanche et les mollets — musculature critique aux km 30-35 du marathon.',
        retour:'10 min footing très lent.',
        note:'RPE 8/10 · Puissance pour résister aux km 30-35.' },
      { jour:'Jeudi', type:'EF', titre:'Footing fondamental 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}. Récupération active entre les côtes de mercredi et les 4 × 3 km OBJ de vendredi. Ce jeudi léger est crucial pour tenir la qualité des blocs OBJ. Des jambes fraîches vendredi font toute la différence.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Vendredi', type:'Fractionné', titre:'4 × 3 km à allure marathon', duree:'75 min', pcts:[[65,65],[78,82]],
        echauff:'25 min footing EF à {{P}}.',
        corps:'4 × 3 km à ton allure objectif marathon ({{OBJ}}). Récupération 3 min au trot. 12 km à {{OBJ}} en blocs. Pars précisément à {{OBJ}} sur le 1er — ni plus rapide, ni plus lent. La précision de l\'allure est l\'objectif principal.',
        retour:'10 min footing léger.',
        note:'RPE 7-8/10 · Blocs OBJ spécifiques.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 2h avec 20 min allure marathon', duree:'2h', pcts:[[65,72],[75,80]],
        echauff:'', corps:'100 min à {{P}}, puis 20 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h. La phase spécifique est lancée : ces 20 min à {{OBJ}} après 100 min d\'EF simulent le dernier quart du marathon. Mémorise cette sensation.', retour:'',
        note:'RPE 6/10 en EF · 7/10 sur les 20 min.' },
    ]},

  { num:10, phase:'Spécificité marathon', charge:'Élevée',
    objectif:'3 × 15 min seuil mercredi + 2 × 5000m OBJ vendredi + SL 2h10 avec 25 min OBJ.',
    conseil:'Trois séances majeures dans la semaine. Les EF (lundi, mardi, jeudi) sont essentiels pour tenir le volume.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 50 minutes', duree:'50 min', pcts:[[65,65]],
        echauff:'', corps:'50 min à {{P}}. Trois séances majeures cette semaine : seuil mercredi, 2 × 5000m vendredi, SL avec 25 min OBJ dimanche. Ce lundi EF est le fondement de la semaine — vraiment léger, foulée économique.', retour:'',
        note:'RPE 4/10.' },
      { jour:'Mardi', type:'EF', titre:'Footing de récupération 40 minutes', duree:'40 min', pcts:[[60,62]],
        echauff:'', corps:'40 min à {{P}}, allure très douce. Le 3 × 15 min seuil mercredi est une séance de référence — 45 min au seuil total. Arrive frais. Ce footing très lent du mardi est une récupération active, pas un entraînement.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mercredi', type:'Tempo', titre:'3 × 15 minutes au seuil', duree:'75 min', pcts:[[65,70],[82,87]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
        corps:'3 × 15 min à {{P}} avec 4 min de récupération. 45 min au seuil. En phase spécifique, le seuil reste la base de la vitesse marathon. Régularité absolue sur les 3 blocs. Le 3e bloc révèle ta vraie forme du moment.',
        retour:'10 min footing très lent.',
        note:'RPE 8/10.' },
      { jour:'Jeudi', type:'EF', titre:'Footing fondamental 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}. Récupération active entre le seuil de mercredi et les 2 × 5000m de vendredi. Semaine très chargée. Ce jeudi lent est stratégique — des jambes fraîches vendredi font la différence sur les 5000m.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Vendredi', type:'Fractionné', titre:'2 × 5000 mètres à allure marathon', duree:'80 min', pcts:[[65,65],[78,82]],
        echauff:'25 min progressif à {{P}}.',
        corps:'2 × 5000 mètres à {{P}}. Récupération 5 min au trot. 10 km à allure marathon avec récupération. Après le seuil de mercredi, le 1er 5000m doit sembler presque trop lent les 2 premières minutes. Patiente et tiens l\'allure.',
        retour:'10 min footing très lent.',
        note:'RPE 7-8/10 · Séance spécifique marathon.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 2h10 avec 25 min allure marathon', duree:'2h10', pcts:[[65,72],[75,80]],
        echauff:'', corps:'105 min à {{P}}, puis 25 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h et 1h20. Hydratation systématique. 25 min à {{OBJ}} après 105 min d\'EF — tu approches la simulation du dernier tiers du marathon.', retour:'',
        note:'RPE 6/10 en EF · 7-8/10 sur les 25 min.' },
    ]},

  { num:11, phase:'Spécificité marathon', charge:'Maximale',
    objectif:'Séance finisher mercredi + 2 × 5000m OBJ vendredi + SL 2h20 avec 30 min OBJ. Pic de charge spécifique.',
    conseil:'Semaine de charge maximale. Les 3 EF (lundi, mardi, jeudi) sont la clé pour encaisser les 3 séances majeures.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 50 minutes', duree:'50 min', pcts:[[65,65]],
        echauff:'', corps:'50 min à {{P}}. Semaine de charge maximale : finisher mercredi, 2 × 5000m vendredi, SL 2h20 dimanche. Ce lundi EF maintient le volume de base sans entamer les réserves pour les 3 séances majeures. Vraiment conservateur.', retour:'',
        note:'RPE 4/10.' },
      { jour:'Mardi', type:'EF', titre:'Footing de récupération 35 minutes', duree:'35 min', pcts:[[60,62]],
        echauff:'', corps:'35 min à {{P}}, allure très douce. Le finisher mercredi est la séance la plus complexe du plan. Ces 35 min lentes du mardi préparent les jambes à encaisser l\'enchaînement 5 km seuil + 3 × 3 km OBJ. Reste vraiment à l\'aise.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mercredi', type:'Tempo', titre:'Séance finisher, 5 km seuil + 3 × 3 km allure marathon', duree:'90 min', pcts:[[65,65],[80,85],[78,82]],
        echauff:'25 min footing EF à {{P}}.',
        corps:'5 km à {{P}} (effort seuil, régulier) → 5 min récupération → 3 × 3 km à ton allure objectif marathon ({{OBJ}}), récup 3 min. Pars conservateur sur le 5 km. La transition seuil → allure marathon est la clé de la réussite le jour J.',
        retour:'10 min footing léger.',
        note:'RPE 8/10 · Séance de référence marathon.' },
      { jour:'Jeudi', type:'EF', titre:'Footing de récupération 35 minutes', duree:'35 min', pcts:[[60,62]],
        echauff:'', corps:'35 min à {{P}}, allure vraiment douce. Récupération active entre le finisher de mercredi et les 2 × 5000m de vendredi. Les jambes ont été très sollicitées hier — ce footing lent favorise la régénération musculaire.', retour:'',
        note:'RPE 3/10 · Crucial pour tenir les 5000m de vendredi.' },
      { jour:'Vendredi', type:'Fractionné', titre:'2 × 5000 mètres à allure marathon', duree:'80 min', pcts:[[65,65],[78,82]],
        echauff:'25 min progressif à {{P}}.',
        corps:'2 × 5000 mètres à {{P}}. Récupération 5 min au trot. Après le finisher de mercredi, pars conservateur sur le 1er 5000m. Cette séance développe la capacité à répéter l\'effort marathon — la qualité prime sur la vitesse.',
        retour:'10 min footing très lent.',
        note:'RPE 7/10 · Après le finisher de mercredi, pars conservateur.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 2h20 avec 30 min allure marathon', duree:'2h20', pcts:[[65,72],[75,80]],
        echauff:'', corps:'110 min à {{P}}, puis 30 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h, 1h20, 1h40. Hydratation systématique. Ces 30 min à {{OBJ}} après 1h50 de course simulent le dernier tiers du marathon en termes de fatigue musculaire.', retour:'',
        note:'RPE 6/10 en EF · 8/10 sur les 30 min.' },
    ]},

  { num:12, phase:'Spécificité marathon', charge:'Maximale',
    objectif:'LE pic de charge absolu. Grande SL 2h30 avec 30 min OBJ. La semaine la plus difficile du plan.',
    conseil:'Après cette semaine, tout est derrière toi. La SL 2h30 avec 30 min OBJ est la séance ultime de la préparation.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 50 minutes', duree:'50 min', pcts:[[65,65]],
        echauff:'', corps:'50 min à {{P}}. LE pic de charge cette semaine : 4 × 3 km OBJ + côtes mercredi, et grande SL 2h30 dimanche. Ce lundi EF préserve chaque joule d\'énergie pour les 2 séances majeures. Foulée légère, sans montre.', retour:'',
        note:'RPE 4/10.' },
      { jour:'Mardi', type:'EF', titre:'Footing de récupération 35 minutes', duree:'35 min', pcts:[[60,62]],
        echauff:'', corps:'35 min à {{P}}, allure vraiment douce. La grande SL 2h30 avec 30 min OBJ dimanche est la séance ultime du plan. Ces 35 min très lentes du mardi protègent les réserves musculaires. Aucune ambition de performance.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mercredi', type:'Fractionné', titre:'4 × 3 km à allure marathon + côtes finales', duree:'80 min', pcts:[[65,65],[78,82]],
        echauff:'25 min footing EF à {{P}}.',
        corps:'4 × 3 km à ton allure objectif marathon ({{OBJ}}), récup 3 min. Puis 4 côtes de 80m explosives pour finir. Les blocs OBJ gravent l\'allure marathon, les côtes finales réveillent les fibres rapides. Séance marathonienne complète.',
        retour:'10 min footing léger.',
        note:'RPE 7-8/10 · Séance de pic spécifique.' },
      { jour:'Jeudi', type:'EF', titre:'Footing de récupération 35 minutes', duree:'35 min', pcts:[[60,62]],
        echauff:'', corps:'35 min à {{P}}, allure très légère. Récupération active entre les 4 × 3 km OBJ de mercredi et la grande SL 2h30 de dimanche. Ce jeudi lent est crucial — ménage-toi absolument pour la séance ultime du plan.', retour:'',
        note:'RPE 3/10 · Ménage-toi pour la SL 2h30 de dimanche.' },
      { jour:'Vendredi', type:'EF', titre:'Footing léger 30 minutes', duree:'30 min', pcts:[[60,65]],
        echauff:'', corps:'30 min très légers à {{P}}. Juste garder les jambes en mouvement avant la grande SL dimanche. Aucun effort, aucune intensité. Préserve absolument toute ton énergie pour la sortie longue de demain.', retour:'',
        note:'RPE 3/10 · Préserve toute ton énergie pour dimanche.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Grande sortie longue 2h30 avec 30 min allure marathon', duree:'2h30', pcts:[[65,72],[75,80]],
        echauff:'', corps:'120 min à {{P}}, puis 30 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h, 1h20, 1h40, 2h. LA grande sortie du plan. Ces 30 min à {{OBJ}} après 2h de course sont l\'épreuve de vérité de ta préparation. Après dimanche, tout est derrière toi.', retour:'',
        note:'RPE 6/10 en EF · 8/10 sur les 30 min · Le pic de charge est atteint. Récupération maintenant.' },
    ]},

  { num:13, phase:'Pic de charge', charge:'Élevée (légère réduction)',
    objectif:'Volume réduit de -15%. Maintien de l\'intensité sur 2 qualités. Consolidation post-pic.',
    conseil:'Consolidation. L\'intensité reste mais le volume diminue. Le corps récupère tout en assimilant les adaptations de S12.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 45 minutes', duree:'45 min', pcts:[[65,65]],
        echauff:'', corps:'45 min à {{P}}. Consolidation post-pic de charge. Le volume baisse de 15% mais l\'intensité reste sur les 2 qualités. 5 min de moins qu\'en S11-S12 — le corps assimile les adaptations. Terrain souple de préférence.', retour:'',
        note:'RPE 4/10.' },
      { jour:'Mardi', type:'EF', titre:'Footing de récupération 35 minutes', duree:'35 min', pcts:[[60,62]],
        echauff:'', corps:'35 min à {{P}}, allure très douce. Le 3 × 15 min seuil mercredi maintient l\'intensité malgré la réduction de volume. Arrive frais. Ce footing lent du mardi est une récupération active post-pic S12.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mercredi', type:'Tempo', titre:'3 × 15 minutes au seuil', duree:'75 min', pcts:[[65,70],[82,87]],
        echauff:'25 min progressif à {{P}}.',
        corps:'3 × 15 min à {{P}} avec 4 min de récupération. Maintien de l\'intensité seuil malgré la réduction de volume. Les adaptations de S12 sont en cours d\'assimilation — la régularité sur les 3 blocs confirme ta progression.',
        retour:'10 min footing très lent.',
        note:'RPE 7-8/10.' },
      { jour:'Jeudi', type:'EF', titre:'Footing fondamental 35 minutes', duree:'35 min', pcts:[[65,65]],
        echauff:'', corps:'35 min à {{P}}. Plus court que les semaines précédentes — la réduction de volume s\'installe progressivement. Récupération active entre le seuil de mercredi et les 4 × 3 km OBJ de vendredi. Vraiment léger.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Vendredi', type:'Fractionné', titre:'4 × 3 km à allure marathon', duree:'75 min', pcts:[[65,65],[78,82]],
        echauff:'25 min footing EF à {{P}}.',
        corps:'4 × 3 km à ton allure objectif marathon ({{OBJ}}). Récupération 3 min au trot. 12 km à {{OBJ}} pour maintenir la mémoire musculaire de l\'allure cible. Dernière grande séance OBJ avant le début de l\'affûtage.',
        retour:'10 min footing léger.',
        note:'RPE 7-8/10.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 2h15 avec 30 min allure marathon', duree:'2h15', pcts:[[65,72],[75,80]],
        echauff:'', corps:'105 min à {{P}}, puis 30 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h, 1h20, 1h40. Légèrement plus court que S12 mais même intensité sur le bloc OBJ. Consolidation de la forme acquise en S12.', retour:'',
        note:'RPE 6/10 en EF · 8/10 sur les 30 min.' },
    ]},

  { num:14, phase:'Pic de charge', charge:'Réduite, pré-affûtage',
    objectif:'Volume réduit de -30%. 4 × 1500m mercredi + 2 × 15 min seuil vendredi. Début de super-compensation.',
    conseil:'Le corps entre en phase de recharge. Moins de volume, mêmes qualités. L\'affûtage commence doucement.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}. L\'affûtage commence. Les footings raccourcissent progressivement. Le corps entre en super-compensation — tu te recharges. Vraiment léger, aucune ambition de vitesse.', retour:'',
        note:'RPE 3-4/10.' },
      { jour:'Mardi', type:'EF', titre:'Footing de récupération 30 minutes', duree:'30 min', pcts:[[60,65]],
        echauff:'', corps:'30 min à {{P}}, allure vraiment légère. L\'affûtage commence — les footings de récupération raccourcissent et ralentissent. Le corps entre en super-compensation. Reste très léger, aucune envie de performance.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mercredi', type:'Fractionné', titre:'4 × 1500 mètres, maintien VMA pré-affûtage', duree:'60 min', pcts:[[65,65],[83,90]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
        corps:'4 × 1500 mètres à {{P}}. Récupération 3 min au trot. Intervalles plus courts que les semaines précédentes : maintien des sensations VMA sans générer de fatigue. Plus rapide que l\'allure marathon, moins long que les 2000m.',
        retour:'10 min footing très lent.',
        note:'RPE 7/10 · Moins de volume, mêmes sensations.' },
      { jour:'Jeudi', type:'EF', titre:'Footing de récupération 30 minutes', duree:'30 min', pcts:[[60,65]],
        echauff:'', corps:'30 min à {{P}}. Récupération légère entre les 4 × 1500m de mercredi et le 2 × 15 min seuil de vendredi. Affûtage en cours — chaque footing est court et lent volontairement. Le corps se recharge.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Vendredi', type:'Tempo', titre:'2 × 15 minutes au seuil, volume réduit', duree:'55 min', pcts:[[65,70],[82,87]],
        echauff:'25 min progressif à {{P}}.',
        corps:'2 × 15 min à {{P}} avec 4 min de récupération. Réduit de 33% par rapport aux 3 × 15 min habituels. Même intensité, moins de volume — le principe clé de l\'affûtage. Les sensations doivent être vives et légères.',
        retour:'10 min footing très lent.',
        note:'RPE 7/10 · Moins de blocs, même intensité. L\'affûtage commence.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 1h50 avec 15 min allure marathon', duree:'1h50', pcts:[[65,72],[75,80]],
        echauff:'', corps:'95 min à {{P}}, puis 15 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h. Sortie longue allégée — 40 min de moins que S13. Le bloc OBJ court maintient la sensation de l\'allure marathon. La SL principale est derrière toi.', retour:'',
        note:'RPE 5/10 en EF · 7/10 sur les 15 min · Allégée. Maintien des sensations.' },
    ]},

  { num:15, phase:'Consolidation', charge:'Réduite, affûtage',
    objectif:'4 séances légères pour laisser les adaptations s\'installer. Volume réduit de 50%.',
    conseil:'Dors 8h, mange bien. Ne rajoute pas de séances. Les jambes doivent fourmiller d\'impatience.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing léger 50 minutes', duree:'50 min', pcts:[[65,65]],
        echauff:'', corps:'50 min à {{P}}, allure vraiment légère. Le footing le plus long de la semaine de consolidation — maintien de l\'endurance de base sans fatiguer. Cours en nature, apprécie la légèreté des jambes. La semaine de course est imminente.', retour:'',
        note:'RPE 3/10 · Tu dois finir comme si tu venais de te promener.' },
      { jour:'Mercredi', type:'Tempo', titre:'2 × 15 minutes au seuil, volume réduit', duree:'55 min', pcts:[[65,72],[82,88]],
        echauff:'25 min progressif à {{P}}.', corps:'2 × 15 min à {{P}}. Volume réduit mais intensité maintenue. Récup 4 min. Termine par 1 km à {{OBJ}} pour réveiller les sensations de course. Les jambes doivent se sentir légères et vives.', retour:'10 min footing très lent.',
        note:'RPE 7/10 · Maintien des sensations sans fatigue.' },
      { jour:'Vendredi', type:'EF', titre:'Footing léger 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}, allure légère. Dans les 10 dernières minutes, place 4 à 6 accélérations de 60m à ton allure marathon pour garder les sensations neuromusculaires vives. Termine frais et dynamisé.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Dimanche', type:'EF', titre:'Footing léger 35 minutes', duree:'35 min', pcts:[[60,65]],
        echauff:'', corps:'35 min très légers à {{P}}. Dernier footing avant la semaine de course. Laisse les jambes rouler librement, le corps se recharge. Finis avec le sourire — le travail est fait.', retour:'',
        note:'RPE 3/10 · Tu dois finir frais et dynamisé.' },
    ]},

  { num:16, phase:'Semaine de course', charge:'Conserve, tu es prêt',
    objectif:'Arriver au départ reposé, confiant, les jambes fraîches. 15 semaines de travail ont été faites.',
    conseil:'Pars à {{OBJ}}/km dès le départ. L\'adrénaline va te pousser à aller plus vite, résiste.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing très léger 30 minutes', duree:'30 min', pcts:[[60,65]],
        echauff:'', corps:'30 min à {{P}}, vraiment lent. Maintenir la circulation sanguine en début de semaine de course. Pas d\'effort, pas de montre, juste des jambes qui bougent. Si tu te sens fatigué, réduis à 20 min — rester frais est la priorité.', retour:'',
        note:'RPE 3/10 · Aucun effort.' },
      { jour:'Mercredi', type:'Fractionné', titre:'8 × 1 min / 1 min à allure marathon', duree:'40 min',
        echauff:'15 min de footing très léger.',
        corps:'8 × 1 minute à ton allure objectif marathon ({{OBJ}}) / 1 minute au trot. Plus long que le 30/30 : ce stimulus réveille les fibres rapides et les jambes sans les épuiser. Le grand jour arrive dans 4 jours — reste frais.',
        retour:'10 min de jogging léger.',
        note:'RPE 6/10 · Maintien des sensations avant le marathon.' },
      { jour:'Samedi', type:'Activation', titre:'Activation J-1 + accélérations', duree:'30 min', pcts:[[60,65]],
        echauff:'', corps:'20 min de trot à {{P}}. Puis 6 à 8 accélérations progressives de 80m jusqu\'à ton allure objectif ({{OBJ}}) sur les 20 derniers mètres. Récupère 60 sec en marchant entre chaque.', retour:'',
        note:'Prépare tes affaires ce soir. Visualise les premiers kilomètres à {{OBJ}}/km.' },
      { jour:'Dimanche', type:'Course', titre:'MARATHON', duree:'Jour J',
        echauff:'10-15 min de jogging très léger avant le départ.',
        corps:'KM 1-8 : pars à {{OBJ}}/km exactement. KM 9-21 : régularité absolue, gel à chaque ravitaillement. KM 22-30 : maintiens {{OBJ}}, écoute ton corps. KM 31-35 : raccourcis la foulée, garde les bras actifs. KM 36-42 : donne absolument tout.',
        retour:'20-30 min de marche. Ravitaillement dans les 30 min.',
        note:'La douleur aux km 30-35 est normale. C\'est là que se gagne un marathon. Tiens bon.' },
    ]},
]
