// Marathon 16 semaines · 5 séances/semaine · Palier Intermédiaire (VMA 13.5 à 18.5)
// 5 séances : 2 qualités + EF récupération + EF long + SL
// {{P}} remplacé séquentiellement · {{OBJ}} = allure objectif marathon (80% VMA)
module.exports = [
  { num:1, phase:'Fondamentaux', charge:'Légère',
    objectif:'5 séances pour initier le rythme. Deux EF encadrent la qualité, la SL fonde l\'endurance de base.',
    conseil:'Ne cherche pas à te prouver quoi que ce soit. La première semaine d\'un plan à 5 séances peut sembler intense. Les deux EF doivent être vraiment faciles.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}. Corps en mouvement en début de semaine.', retour:'',
        note:'RPE 3/10 · Légèreté absolue.' },
      { jour:'Mardi', type:'EF', titre:'Footing de récupération 35 minutes', duree:'35 min', pcts:[[65,65]],
        echauff:'', corps:'35 min à {{P}}. Très léger. Récupération active avant la qualité.', retour:'',
        note:'RPE 3/10 · Préserve-toi pour le mercredi.' },
      { jour:'Mercredi', type:'Fractionné', titre:'6 × 400 mètres, réveil neuromusculaire', duree:'45 min', pcts:[[65,65],[90,95]],
        echauff:'20 min progressif à {{P}}, finir par 4 accélérations de 60m.',
        corps:'6 × 400 mètres à {{P}}. Récupération 90 sec au trot. Effort régulier sur les 6.',
        retour:'10 min footing très lent.',
        note:'RPE 6-7/10 · Découverte des allures.' },
      { jour:'Vendredi', type:'EF', titre:'Footing fondamental 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}. Récupération active avant la SL.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 70 minutes', duree:'70 min', pcts:[[65,65]],
        echauff:'', corps:'70 min à {{P}}. Rythme conversationnel. Hydrate-toi.', retour:'',
        note:'RPE 4/10 · La durée prime sur l\'allure.' },
    ]},

  { num:2, phase:'Fondamentaux', charge:'Légère',
    objectif:'Côtes + 2e qualité vendredi. Le plan à 5 séances introduit une 2e qualité dès S2.',
    conseil:'La 2e qualité vendredi est intentionnellement légère : accélérations et seuil court. Ne transforme pas ce vendredi en séance dure.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mardi', type:'EF', titre:'Footing de récupération 35 minutes', duree:'35 min', pcts:[[65,65]],
        echauff:'', corps:'35 min à {{P}}. Récupération avant les côtes.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mercredi', type:'Côtes', titre:'8 côtes de 80 mètres', duree:'45 min', pcts:[[65,65],[100,105]],
        echauff:'20 min progressif à {{P}}, finir par 4 foulées bondissantes.',
        corps:'8 côtes de 80 mètres à effort maximal. Récupération : redescente en marchant.',
        retour:'10 min footing très lent.',
        note:'RPE 8/10 sur chaque côte.' },
      { jour:'Vendredi', type:'Tempo', titre:'2 × 8 minutes au seuil, introduction légère', duree:'45 min', pcts:[[65,70],[80,83]],
        echauff:'20 min progressif à {{P}}.',
        corps:'2 × 8 min à {{P}} avec 3 min de récupération. Introduction progressive au seuil. Effort modéré.',
        retour:'10 min footing très lent.',
        note:'RPE 6-7/10 · Introduction légère au seuil. 2e qualité de la semaine.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 80 minutes', duree:'80 min', pcts:[[65,65]],
        echauff:'', corps:'80 min à {{P}}. Terrain varié si possible.', retour:'',
        note:'RPE 4/10.' },
    ]},

  { num:3, phase:'Fondamentaux', charge:'Modérée',
    objectif:'Séance seuil mercredi + 4 × 1000m vendredi. La 2e qualité gagne en intensité.',
    conseil:'Deux qualités dans la semaine exigent une gestion de l\'énergie rigoureuse. Les EF lundi et mardi sont vraiment légers.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mardi', type:'EF', titre:'Footing de récupération 35 minutes', duree:'35 min', pcts:[[65,65]],
        echauff:'', corps:'35 min à {{P}}. Très léger avant la séance seuil.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mercredi', type:'Tempo', titre:'2 × 10 minutes au seuil', duree:'50 min', pcts:[[65,70],[80,84]],
        echauff:'20 min progressif à {{P}}, finir par 4 accélérations de 60m.',
        corps:'2 × 10 min à {{P}} avec 3 min de récupération. Régularité sur les 2 blocs.',
        retour:'10 min footing très lent.',
        note:'RPE 7/10 · 20 min au seuil.' },
      { jour:'Vendredi', type:'Fractionné', titre:'4 × 1000 mètres', duree:'55 min', pcts:[[65,65],[85,92]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
        corps:'4 × 1000 mètres à {{P}}. Récupération 2 min au trot. Même allure du 1er au 4e.',
        retour:'10 min footing très lent.',
        note:'RPE 7-8/10 · 2e qualité de la semaine.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 85 minutes', duree:'85 min', pcts:[[65,65]],
        echauff:'', corps:'85 min à {{P}}. Régulier.', retour:'',
        note:'RPE 4/10.' },
    ]},

  { num:4, phase:'Fondamentaux', charge:'Modérée',
    objectif:'Montée en charge : 2 × 15 min seuil mercredi + 5 × 1000m vendredi. La SL à 90 min.',
    conseil:'Semaine la plus chargée des fondamentaux. Les deux qualités doivent être séparées de 2 jours (mercredi/vendredi) pour permettre une récupération suffisante.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}. Corps en mouvement.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mardi', type:'EF', titre:'Footing de récupération 35 minutes', duree:'35 min', pcts:[[65,65]],
        echauff:'', corps:'35 min à {{P}}. Récupération légère avant les 2 × 15 min.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mercredi', type:'Tempo', titre:'2 × 15 minutes au seuil aérobie', duree:'60 min', pcts:[[65,70],[82,87]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
        corps:'2 × 15 min à {{P}} avec 4 min de récupération. 30 min au seuil. Régularité absolue sur les 2 blocs.',
        retour:'10 min footing très lent.',
        note:'RPE 7-8/10 · 30 min au seuil. Pars conservateur.' },
      { jour:'Vendredi', type:'Fractionné', titre:'5 × 1000 mètres', duree:'60 min', pcts:[[65,65],[85,92]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
        corps:'5 × 1000 mètres à {{P}}. Récupération 2 min. Même allure du 1er au 5e.',
        retour:'10 min footing très lent.',
        note:'RPE 7-8/10 · Semaine à 2 qualités ambitieuses. Gère bien l\'énergie.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 90 minutes', duree:'90 min', pcts:[[65,65]],
        echauff:'', corps:'90 min à {{P}}. Gel recommandé à 1h. Premier cap symbolique.', retour:'',
        note:'RPE 4-5/10 · Cap des 90 min.' },
    ]},

  { num:5, phase:'Développement', charge:'Moyenne',
    objectif:'3 × 2000m mercredi + 2 × 15 min seuil vendredi. La 2e qualité renforce le seuil pendant que la 1re monte vers les longs intervalles.',
    conseil:'3 × 2000m est une étape clé. Les 2000m demandent plus de gestion d\'allure que les 1000m. Pars plus prudemment.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 45 minutes', duree:'45 min', pcts:[[65,65]],
        echauff:'', corps:'45 min à {{P}}.', retour:'',
        note:'RPE 4/10.' },
      { jour:'Mardi', type:'EF', titre:'Footing de récupération 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}. Récupération avant les 2000m.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mercredi', type:'Fractionné', titre:'3 × 2000 mètres, fractionnés longs', duree:'65 min', pcts:[[65,65],[80,85]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
        corps:'3 × 2000 mètres à {{P}}. Récupération 4 min. Régulier sur les 3 blocs.',
        retour:'10 min footing très lent.',
        note:'RPE 8/10 · Premier cap des 2000m.' },
      { jour:'Vendredi', type:'Tempo', titre:'2 × 15 minutes au seuil', duree:'60 min', pcts:[[65,70],[82,87]],
        echauff:'25 min progressif à {{P}}.',
        corps:'2 × 15 min à {{P}} avec 4 min de récupération. Maintien du travail seuil pendant la phase développement.',
        retour:'10 min footing très lent.',
        note:'RPE 7-8/10 · 2e qualité. La récupération entre mercredi et vendredi est critique.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 100 minutes', duree:'100 min', pcts:[[65,65]],
        echauff:'', corps:'100 min à {{P}}. Gel à 1h. Hydratation toutes les 20 min.', retour:'',
        note:'RPE 5/10 · Dès 90 min, tester la nutrition.' },
    ]},

  { num:6, phase:'Développement', charge:'Moyenne',
    objectif:'Côtes mercredi + 2 × 3000m vendredi. Variation des stimuli pour un développement complet.',
    conseil:'Les côtes et les 3000m sollicitent des systèmes différents. Cette complémentarité est intentionnelle.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 45 minutes', duree:'45 min', pcts:[[65,65]],
        echauff:'', corps:'45 min à {{P}}.', retour:'',
        note:'RPE 4/10.' },
      { jour:'Mardi', type:'EF', titre:'Footing de récupération 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}. Récupération avant les côtes.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mercredi', type:'Côtes', titre:'10 côtes de 80 mètres', duree:'50 min', pcts:[[65,65],[100,105]],
        echauff:'20 min progressif à {{P}}, finir par 4 foulées bondissantes.',
        corps:'10 côtes de 80 mètres à effort maximal. Récupération : redescente en marchant.',
        retour:'10 min footing très lent.',
        note:'RPE 8/10 · 10 côtes. Qualité d\'effort sur chacune.' },
      { jour:'Vendredi', type:'Fractionné', titre:'2 × 3000 mètres progressifs', duree:'65 min', pcts:[[65,65],[80,82],[82,85],[85,88]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
        corps:'2 × 3000 mètres à {{P}}. Récupération 5 min. Chaque 3000m en progression : 1er km à {{P}}, 2e à {{P}}, 3e à {{P}}.',
        retour:'10 min footing très lent.',
        note:'RPE 8/10 · La progression interne est la clé.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 1h50', duree:'1h50', pcts:[[65,65]],
        echauff:'', corps:'1h50 à {{P}}. Gel à 1h. La SL progresse régulièrement.', retour:'',
        note:'RPE 5/10.' },
    ]},

  { num:7, phase:'Développement', charge:'Élevée',
    objectif:'3 × 15 min seuil mercredi + 2 × 3000m progressifs vendredi. Double qualité intensive. Grosse semaine.',
    conseil:'Semaine la plus chargée de la phase développement. Les 2 EF (lundi/mardi) doivent être vraisemblablement faciles pour préserver l\'énergie.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 50 minutes', duree:'50 min', pcts:[[65,65]],
        echauff:'', corps:'50 min à {{P}}. Grosse semaine. Reste conservateur.', retour:'',
        note:'RPE 4/10.' },
      { jour:'Mardi', type:'EF', titre:'Footing de récupération 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}. Très léger avant le gros seuil.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mercredi', type:'Tempo', titre:'3 × 15 minutes au seuil', duree:'75 min', pcts:[[65,70],[82,87]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
        corps:'3 × 15 min à {{P}} avec 4 min de récupération. 45 min au seuil. Régularité sur les 3.',
        retour:'10 min footing très lent.',
        note:'RPE 8/10 · 45 min au seuil. Séance de référence.' },
      { jour:'Vendredi', type:'Fractionné', titre:'2 × 3000 mètres + 1 km allure marathon', duree:'70 min', pcts:[[65,65],[80,82],[82,85],[85,88],[78,82]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
        corps:'2 × 3000m à {{P}} (progressifs, récup 5 min), puis après 3 min de récup, 1 km à ton allure objectif marathon ({{OBJ}}). Introduction de l\'allure marathon après une séance de qualité.',
        retour:'10 min footing très lent.',
        note:'RPE 8/10 · Le km à {{OBJ}} en fin de séance te révèle la sensation de l\'allure cible fatigué.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 2 heures', duree:'2h', pcts:[[65,65]],
        echauff:'', corps:'2h à {{P}}. Gel à 1h et 1h20. Hydratation systématique.', retour:'',
        note:'RPE 5/10 · 2h de course, cap majeur.' },
    ]},

  { num:8, phase:'Développement', charge:'Élevée',
    objectif:'2 × 5000m à allure marathon mercredi + 3 × 15 min seuil vendredi. Double qualité marathon et seuil.',
    conseil:'2 × 5000m à allure marathon est une séance de référence du plan. Pars prudemment : tu dois tenir la même allure sur les 2 × 5000m.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 50 minutes', duree:'50 min', pcts:[[65,65]],
        echauff:'', corps:'50 min à {{P}}.', retour:'',
        note:'RPE 4/10.' },
      { jour:'Mardi', type:'EF', titre:'Footing de récupération 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}. Récupération légère.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mercredi', type:'Fractionné', titre:'2 × 5000 mètres à allure marathon', duree:'80 min', pcts:[[65,65],[78,82]],
        echauff:'20 min progressif à {{P}}, finir par 4 accélérations de 80m.',
        corps:'2 × 5000 mètres à {{P}}. Récupération 5 min. 10 km à allure marathon avec récupération. Pars conservateur.',
        retour:'10 min footing très lent.',
        note:'RPE 7-8/10 · La séance la plus spécifique jusqu\'ici.' },
      { jour:'Vendredi', type:'Tempo', titre:'3 × 15 minutes au seuil', duree:'75 min', pcts:[[65,70],[82,87]],
        echauff:'25 min progressif à {{P}}.',
        corps:'3 × 15 min à {{P}} avec 4 min de récupération. Maintien du volume seuil en parallèle des longs intervalles.',
        retour:'10 min footing très lent.',
        note:'RPE 7-8/10 · 2e qualité de la semaine. Gère l\'effort après les 5000m.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 2h10', duree:'2h10', pcts:[[65,65]],
        echauff:'', corps:'2h10 à {{P}}. Gel à 1h et 1h25. Fin de la phase développement.', retour:'',
        note:'RPE 5-6/10.' },
    ]},

  { num:9, phase:'Spécificité marathon', charge:'Élevée',
    objectif:'Côtes mercredi + SL 2h avec 20 min OBJ. Entrée en phase spécifique avec maintien de la puissance.',
    conseil:'La phase spécifique commence. Chaque SL intègre maintenant des blocs à allure marathon. Mémorise cette allure : c\'est celle du jour J.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 50 minutes', duree:'50 min', pcts:[[65,65]],
        echauff:'', corps:'50 min à {{P}}.', retour:'',
        note:'RPE 4/10.' },
      { jour:'Mardi', type:'EF', titre:'Footing de récupération 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mercredi', type:'Côtes', titre:'12 côtes de 80 mètres, puissance marathon', duree:'55 min', pcts:[[65,65],[100,105]],
        echauff:'20 min progressif à {{P}}, finir par 4 foulées bondissantes.',
        corps:'12 côtes de 80 mètres à effort maximal. Récupération : redescente en marchant. La puissance neuromusculaire construite ici résiste aux km 30-35 du marathon.',
        retour:'10 min footing très lent.',
        note:'RPE 8/10 · 12 côtes. Maintien de la qualité sur toutes.' },
      { jour:'Vendredi', type:'EF', titre:'Footing de récupération 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}. Récupération avant la grande SL.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 2h avec 20 min allure marathon', duree:'2h', pcts:[[65,72],[75,80]],
        echauff:'', corps:'100 min à {{P}}, puis 20 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h. Premier bloc OBJ en fin de SL.', retour:'',
        note:'RPE 6/10 en EF · 7/10 sur les 20 min · Mémorise la sensation de {{OBJ}}.' },
    ]},

  { num:10, phase:'Spécificité marathon', charge:'Élevée',
    objectif:'3 × 15 min seuil mercredi + 4 × 3 km OBJ vendredi + SL 2h10 avec 25 min OBJ. Semaine complète.',
    conseil:'Le vendredi introduit les blocs OBJ en séance de qualité pure. Différent des blocs en fin de SL : tu es frais, l\'allure doit être bien calée.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 50 minutes', duree:'50 min', pcts:[[65,65]],
        echauff:'', corps:'50 min à {{P}}.', retour:'',
        note:'RPE 4/10.' },
      { jour:'Mardi', type:'EF', titre:'Footing de récupération 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}. Récupération avant les séances clés.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mercredi', type:'Tempo', titre:'3 × 15 minutes au seuil', duree:'75 min', pcts:[[65,70],[82,87]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
        corps:'3 × 15 min à {{P}} avec 4 min de récupération. Maintien du volume seuil en phase spécifique.',
        retour:'10 min footing très lent.',
        note:'RPE 8/10 · 45 min au seuil pendant la phase spécifique.' },
      { jour:'Vendredi', type:'Fractionné', titre:'4 × 3 km à allure marathon', duree:'75 min', pcts:[[65,65],[78,82]],
        echauff:'20 min footing EF à {{P}}.',
        corps:'4 × 3 km exactement à ton allure objectif marathon ({{OBJ}}). Récupération 3 min au trot. 12 km à {{OBJ}} en blocs.',
        retour:'10 min footing léger.',
        note:'RPE 7-8/10 · Blocs OBJ purs. La régularité sur les 4 blocs est l\'objectif.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 2h10 avec 25 min allure marathon', duree:'2h10', pcts:[[65,72],[75,80]],
        echauff:'', corps:'105 min à {{P}}, puis 25 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h et 1h20.', retour:'',
        note:'RPE 6/10 en EF · 7-8/10 sur les 25 min.' },
    ]},

  { num:11, phase:'Spécificité marathon', charge:'Maximale',
    objectif:'Séance finisher mercredi + 2 × 5000m vendredi + SL 2h20 avec 30 min OBJ. Triple charge spécifique.',
    conseil:'Semaine de charge maximale. Les 3 séances de qualité sont à la limite du tolérable. Gère l\'énergie entre chaque.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 50 minutes', duree:'50 min', pcts:[[65,65]],
        echauff:'', corps:'50 min à {{P}}. Semaine de charge maximale. Conserve l\'énergie.', retour:'',
        note:'RPE 4/10.' },
      { jour:'Mardi', type:'EF', titre:'Footing de récupération 35 minutes', duree:'35 min', pcts:[[65,65]],
        echauff:'', corps:'35 min à {{P}}. Très léger. 3 séances majeures t\'attendent.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mercredi', type:'Tempo', titre:'Séance finisher, 5 km seuil + 3 × 3 km allure marathon', duree:'90 min', pcts:[[65,65],[80,85],[78,82]],
        echauff:'20 min footing EF à {{P}}.',
        corps:'5 km à {{P}} (effort seuil) → 5 min récupération → 3 × 3 km à ton allure objectif marathon ({{OBJ}}), récup 3 min entre chaque.',
        retour:'10 min footing léger.',
        note:'RPE 8/10 · Séance de référence marathon.' },
      { jour:'Vendredi', type:'Fractionné', titre:'2 × 5000 mètres à allure marathon', duree:'80 min', pcts:[[65,65],[78,82]],
        echauff:'20 min progressif à {{P}}.',
        corps:'2 × 5000 mètres à {{P}}. Récupération 5 min. Pars prudemment après la séance finisher de mercredi.',
        retour:'10 min footing très lent.',
        note:'RPE 7/10 · Volume maintenu, intensité légèrement réduite après mercredi.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 2h20 avec 30 min allure marathon', duree:'2h20', pcts:[[65,72],[75,80]],
        echauff:'', corps:'110 min à {{P}}, puis 30 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h, 1h20, 1h40.', retour:'',
        note:'RPE 6/10 en EF · 8/10 sur les 30 min · Gros bloc OBJ en fin de longue semaine.' },
    ]},

  { num:12, phase:'Spécificité marathon', charge:'Maximale',
    objectif:'LE pic de charge. Grande SL 2h30 avec 30 min OBJ. La semaine la plus difficile du plan.',
    conseil:'Cette semaine est intense. Après, le plus dur est derrière toi. Récupère bien entre chaque séance. La SL de dimanche est la reine.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 50 minutes', duree:'50 min', pcts:[[65,65]],
        echauff:'', corps:'50 min à {{P}}. Dernière grosse semaine. Reste léger lundi.', retour:'',
        note:'RPE 4/10.' },
      { jour:'Mardi', type:'EF', titre:'Footing de récupération 35 minutes', duree:'35 min', pcts:[[65,65]],
        echauff:'', corps:'35 min à {{P}}. Récupération légère.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mercredi', type:'Fractionné', titre:'4 × 3 km à allure marathon + côtes', duree:'80 min', pcts:[[65,65],[78,82]],
        echauff:'20 min footing EF à {{P}}.',
        corps:'4 × 3 km à ton allure objectif marathon ({{OBJ}}), récup 3 min. Puis 4 côtes de 80m explosives pour finir. Séance mixte OBJ et puissance.',
        retour:'10 min footing léger.',
        note:'RPE 7-8/10 · Séance marathonienne complète.' },
      { jour:'Vendredi', type:'EF', titre:'Footing de récupération 35 minutes', duree:'35 min', pcts:[[65,65]],
        echauff:'', corps:'35 min à {{P}}. Récupération légère avant la grande SL. Corps en mouvement, jambes préservées.', retour:'',
        note:'RPE 3/10 · Ménage-toi pour la SL 2h30 de dimanche.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Grande sortie longue 2h30 avec 30 min allure marathon', duree:'2h30', pcts:[[65,72],[75,80]],
        echauff:'', corps:'120 min à {{P}}, puis 30 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h, 1h20, 1h40, 2h. LA grande sortie du plan.', retour:'',
        note:'RPE 6/10 en EF · 8/10 sur les 30 min · Le pic de charge est atteint. Récupération dès maintenant.' },
    ]},

  { num:13, phase:'Pic de charge', charge:'Élevée (légère réduction)',
    objectif:'Volume légèrement réduit (-15%). Maintien de l\'intensité avec 2 qualités différenciées.',
    conseil:'Consolidation après S12. L\'intensité reste mais le volume allège légèrement. Ton corps récupère tout en assimilant les adaptations.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 45 minutes', duree:'45 min', pcts:[[65,65]],
        echauff:'', corps:'45 min à {{P}}.', retour:'',
        note:'RPE 4/10.' },
      { jour:'Mardi', type:'EF', titre:'Footing de récupération 35 minutes', duree:'35 min', pcts:[[65,65]],
        echauff:'', corps:'35 min à {{P}}. Récupération légère.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mercredi', type:'Tempo', titre:'3 × 15 minutes au seuil', duree:'75 min', pcts:[[65,70],[82,87]],
        echauff:'25 min progressif à {{P}}.',
        corps:'3 × 15 min à {{P}} avec 4 min de récupération. Maintien du travail seuil.',
        retour:'10 min footing très lent.',
        note:'RPE 7-8/10.' },
      { jour:'Vendredi', type:'Fractionné', titre:'4 × 3 km à allure marathon', duree:'75 min', pcts:[[65,65],[78,82]],
        echauff:'20 min footing EF à {{P}}.',
        corps:'4 × 3 km à ton allure objectif marathon ({{OBJ}}). Récupération 3 min. Maintien de la mémoire allure.',
        retour:'10 min footing léger.',
        note:'RPE 7-8/10.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 2h15 avec 30 min allure marathon', duree:'2h15', pcts:[[65,72],[75,80]],
        echauff:'', corps:'105 min à {{P}}, puis 30 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h, 1h20, 1h40.', retour:'',
        note:'RPE 6/10 en EF · 8/10 sur les 30 min.' },
    ]},

  { num:14, phase:'Pic de charge', charge:'Réduite, pré-affûtage',
    objectif:'Volume réduit (-30%). Maintien des sensations avec des séances plus légères. Début de la super-compensation.',
    conseil:'L\'affûtage commence. Moins de volume mais qualité maintenue. Les jambes commencent à se recharger.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}.', retour:'',
        note:'RPE 3-4/10.' },
      { jour:'Mardi', type:'EF', titre:'Footing de récupération 35 minutes', duree:'35 min', pcts:[[65,65]],
        echauff:'', corps:'35 min à {{P}}. Très léger.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mercredi', type:'Fractionné', titre:'4 × 1500 mètres, maintien VMA pré-affûtage', duree:'60 min', pcts:[[65,65],[83,90]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
        corps:'4 × 1500 mètres à {{P}}. Récupération 3 min. Plus court que les semaines précédentes. Maintien des qualités sans fatigue.',
        retour:'10 min footing très lent.',
        note:'RPE 7/10 · Moins de volume, mêmes sensations.' },
      { jour:'Vendredi', type:'Tempo', titre:'2 × 15 minutes au seuil, volume réduit', duree:'55 min', pcts:[[65,70],[82,87]],
        echauff:'25 min progressif à {{P}}.',
        corps:'2 × 15 min à {{P}} avec 4 min de récupération. Volume réduit vs les 3 × 15 min des semaines précédentes.',
        retour:'10 min footing très lent.',
        note:'RPE 7/10 · Moins de blocs, même intensité.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 1h50 avec 15 min allure marathon', duree:'1h50', pcts:[[65,72],[75,80]],
        echauff:'', corps:'95 min à {{P}}, puis 15 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h.', retour:'',
        note:'RPE 5/10 en EF · 7/10 sur les 15 min · Allégée. Maintien des sensations.' },
    ]},

  { num:15, phase:'Consolidation', charge:'Réduite, affûtage',
    objectif:'5 séances légères pour laisser les adaptations s\'installer. Volume réduit de 45%.',
    conseil:'Semaine d\'affûtage. Les jambes doivent commencer à fourmiller d\'impatience. Dors 8h. Ne rajoute rien.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing léger 35 minutes', duree:'35 min', pcts:[[65,65]],
        echauff:'', corps:'35 min très faciles à {{P}}.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mardi', type:'EF', titre:'Footing de récupération 30 minutes', duree:'30 min', pcts:[[60,65]],
        echauff:'', corps:'30 min à {{P}}. Très léger. Corps en mouvement.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mercredi', type:'Tempo', titre:'2 × 15 minutes au seuil, volume réduit', duree:'55 min', pcts:[[65,72],[82,88]],
        echauff:'25 min progressif à {{P}}.', corps:'2 × 15 min à {{P}}. Volume réduit mais intensité maintenue. Récup 4 min. Termine par 1 km à {{OBJ}}.', retour:'10 min footing très lent.',
        note:'RPE 7/10 · Maintien des sensations sans épuisement.' },
      { jour:'Vendredi', type:'EF', titre:'Footing léger 35 minutes', duree:'35 min', pcts:[[65,65]],
        echauff:'', corps:'35 min à {{P}}. Inclus 4 à 6 accélérations de 60m à allure marathon.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Dimanche', type:'EF', titre:'Footing léger 25 minutes', duree:'25 min', pcts:[[60,65]],
        echauff:'', corps:'25 min très légers à {{P}}. Dernier footing avant la semaine de course.', retour:'',
        note:'RPE 3/10 · Tu dois finir frais et dynamisé.' },
    ]},

  { num:16, phase:'Semaine de course', charge:'Conserve, tu es prêt',
    objectif:'Arriver au départ reposé, confiant, les jambes fraîches. 15 semaines de travail ont été faites.',
    conseil:'Pars à {{OBJ}}/km dès le départ. L\'adrénaline va te pousser à aller plus vite, résiste.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing très léger 30 minutes', duree:'30 min', pcts:[[60,65]],
        echauff:'', corps:'30 min à {{P}}. Maintenir la circulation. Vraiment facile.', retour:'',
        note:'RPE 3/10 · Aucun effort.' },
      { jour:'Mercredi', type:'Fractionné', titre:'8 × 1 min / 1 min à allure marathon', duree:'40 min',
        echauff:'15 min de footing très léger.',
        corps:'8 × 1 minute à ton allure objectif marathon ({{OBJ}}) / 1 minute au trot. Réveille les jambes sans les fatiguer.',
        retour:'10 min de jogging léger.',
        note:'RPE 6/10 · Maintien des sensations avant le marathon.' },
      { jour:'Samedi', type:'Activation', titre:'Activation J-1 + accélérations', duree:'30 min', pcts:[[60,65]],
        echauff:'', corps:'20 min de trot à {{P}}. Puis 6 à 8 accélérations progressives de 80m jusqu\'à ton allure objectif ({{OBJ}}). Récupère 60 sec en marchant.', retour:'',
        note:'Prépare tes affaires ce soir. Visualise les premiers kilomètres à {{OBJ}}/km.' },
      { jour:'Dimanche', type:'Course', titre:'MARATHON', duree:'Jour J',
        echauff:'10-15 min de jogging très léger avant le départ.',
        corps:'KM 1-8 : pars à {{OBJ}}/km exactement. KM 9-21 : régularité absolue, gel à chaque ravitaillement. KM 22-30 : maintiens {{OBJ}}, écoute ton corps. KM 31-35 : raccourcis la foulée, garde les bras actifs. KM 36-42 : donne absolument tout.',
        retour:'20-30 min de marche. Ravitaillement dans les 30 min.',
        note:'La douleur aux km 30-35 est normale. C\'est là que se gagne un marathon. Tiens bon.' },
    ]},
]
