// Marathon 16 semaines · 6 séances/semaine · Palier Intermédiaire (VMA 13.5 à 18.5)
// 6 séances : 2 qualités + 3 EF/RA + SL. Volume maximum.
// {{P}} remplacé séquentiellement · {{OBJ}} = allure objectif marathon (80% VMA)
module.exports = [
  { num:1, phase:'Fondamentaux', charge:'Légère',
    objectif:'6 séances pour lancer la préparation : 3 EF, 1 qualité légère, 1 EF jeudi, 1 SL. Volume de mise en route.',
    conseil:'Plan à 6 séances : les 3 EF encadrent la qualité et la SL. Garde les EF vraiment faciles. La charge de S1 est délibérément légère.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}. Corps en mouvement. Début de préparation.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mardi', type:'EF', titre:'Footing de récupération 35 minutes', duree:'35 min', pcts:[[60,62]],
        echauff:'', corps:'35 min à {{P}}. Très léger. Prépare la qualité du mercredi.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mercredi', type:'Fractionné', titre:'6 × 400 mètres, réveil neuromusculaire', duree:'45 min', pcts:[[65,65],[90,95]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 60m.',
        corps:'6 × 400 mètres à {{P}}. Récupération 90 sec au trot. Effort régulier sur les 6.',
        retour:'10 min footing très lent.',
        note:'RPE 6-7/10 · Première qualité. Découverte des allures.' },
      { jour:'Jeudi', type:'EF', titre:'Footing fondamental 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}. Récupération active entre qualité et vendredi.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Vendredi', type:'Tempo', titre:'2 × 8 minutes au seuil, introduction légère', duree:'45 min', pcts:[[65,70],[80,83]],
        echauff:'25 min progressif à {{P}}.',
        corps:'2 × 8 min à {{P}} avec 3 min de récupération. Introduction légère au seuil. Effort modéré.',
        retour:'10 min footing très lent.',
        note:'RPE 6/10 · 2e qualité de la semaine, intentionnellement légère.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 70 minutes', duree:'70 min', pcts:[[65,65]],
        echauff:'', corps:'70 min à {{P}}. Rythme conversationnel.', retour:'',
        note:'RPE 4/10.' },
    ]},

  { num:2, phase:'Fondamentaux', charge:'Légère',
    objectif:'Côtes mercredi + seuil vendredi. La 2e qualité prend de l\'intensité progressivement.',
    conseil:'6 séances avec 2 qualités dans la même semaine dès S2. Les EF lundi, mardi et jeudi sont le carburant qui permet les deux qualités.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mardi', type:'EF', titre:'Footing de récupération 35 minutes', duree:'35 min', pcts:[[60,62]],
        echauff:'', corps:'35 min à {{P}}. Léger avant les côtes.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mercredi', type:'Côtes', titre:'8 côtes de 80 mètres', duree:'45 min', pcts:[[65,65],[100,105]],
        echauff:'25 min progressif à {{P}}, finir par 4 foulées bondissantes.',
        corps:'8 côtes de 80 mètres à effort maximal. Récupération : redescente en marchant.',
        retour:'10 min footing très lent.',
        note:'RPE 8/10 sur chaque côte.' },
      { jour:'Jeudi', type:'EF', titre:'Footing fondamental 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}. Récupération après les côtes.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Vendredi', type:'Tempo', titre:'2 × 10 minutes au seuil', duree:'50 min', pcts:[[65,70],[80,84]],
        echauff:'25 min progressif à {{P}}.',
        corps:'2 × 10 min à {{P}} avec 3 min de récupération. 20 min au seuil.',
        retour:'10 min footing très lent.',
        note:'RPE 7/10 · 2e qualité. Montée en intensité progressive.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 80 minutes', duree:'80 min', pcts:[[65,65]],
        echauff:'', corps:'80 min à {{P}}. Terrain varié.', retour:'',
        note:'RPE 4/10.' },
    ]},

  { num:3, phase:'Fondamentaux', charge:'Modérée',
    objectif:'2 × 15 min seuil mercredi + 5 × 1000m vendredi. Deux qualités de bon niveau dès S3.',
    conseil:'La progression est délibérément plus rapide sur 6 séances. Les 3 EF permettent d\'encaisser des 2 qualités hebdomadaires.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mardi', type:'EF', titre:'Footing de récupération 35 minutes', duree:'35 min', pcts:[[60,62]],
        echauff:'', corps:'35 min à {{P}}. Léger avant le seuil.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mercredi', type:'Tempo', titre:'2 × 15 minutes au seuil aérobie', duree:'60 min', pcts:[[65,70],[82,87]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
        corps:'2 × 15 min à {{P}} avec 4 min de récupération. 30 min au seuil. Régularité sur les 2 blocs.',
        retour:'10 min footing très lent.',
        note:'RPE 7-8/10 · 30 min au seuil dès S3 sur le plan 6 séances.' },
      { jour:'Jeudi', type:'EF', titre:'Footing fondamental 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}. Récupération entre les 2 qualités.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Vendredi', type:'Fractionné', titre:'5 × 1000 mètres', duree:'60 min', pcts:[[65,65],[85,92]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
        corps:'5 × 1000 mètres à {{P}}. Récupération 2 min. Même allure du 1er au 5e.',
        retour:'10 min footing très lent.',
        note:'RPE 7-8/10 · 2e qualité de la semaine. Gère l\'énergie.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 85 minutes', duree:'85 min', pcts:[[65,65]],
        echauff:'', corps:'85 min à {{P}}. Régulier.', retour:'',
        note:'RPE 4/10.' },
    ]},

  { num:4, phase:'Fondamentaux', charge:'Modérée',
    objectif:'3 × 2000m mercredi + 3 × 15 min seuil vendredi. Montée en charge des 2 qualités. SL à 90 min.',
    conseil:'Semaine la plus chargée des fondamentaux. Les 2 EF (mardi/jeudi) sont vraiment faciles. Gère l\'énergie entre les 2 qualités.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mardi', type:'EF', titre:'Footing de récupération 35 minutes', duree:'35 min', pcts:[[60,62]],
        echauff:'', corps:'35 min à {{P}}. Léger avant les 2000m.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mercredi', type:'Fractionné', titre:'3 × 2000 mètres, fractionnés longs', duree:'65 min', pcts:[[65,65],[80,85]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
        corps:'3 × 2000 mètres à {{P}}. Récupération 4 min. Régulier sur les 3.',
        retour:'10 min footing très lent.',
        note:'RPE 8/10 · Fractionnés longs dès S4.' },
      { jour:'Jeudi', type:'EF', titre:'Footing fondamental 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}. Récupération entre les 2 qualités.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Vendredi', type:'Tempo', titre:'3 × 15 minutes au seuil', duree:'75 min', pcts:[[65,70],[82,87]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
        corps:'3 × 15 min à {{P}} avec 4 min de récupération. 45 min au seuil.',
        retour:'10 min footing très lent.',
        note:'RPE 7-8/10 · 45 min au seuil en fin de semaine chargée.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 90 minutes', duree:'90 min', pcts:[[65,65]],
        echauff:'', corps:'90 min à {{P}}. Gel à 1h. Cap des 90 min.', retour:'',
        note:'RPE 4-5/10.' },
    ]},

  { num:5, phase:'Développement', charge:'Moyenne',
    objectif:'Phase développement : 2 × 5000m OBJ mercredi + 3 × 15 min seuil vendredi. Séances spécifiques dès S5.',
    conseil:'Sur 6 séances, la progression est plus rapide. Les 2 × 5000m à allure marathon arrivent dès S5 pour ancrer l\'allure tôt dans le cycle.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 45 minutes', duree:'45 min', pcts:[[65,65]],
        echauff:'', corps:'45 min à {{P}}.', retour:'',
        note:'RPE 4/10.' },
      { jour:'Mardi', type:'EF', titre:'Footing de récupération 40 minutes', duree:'40 min', pcts:[[60,62]],
        echauff:'', corps:'40 min à {{P}}.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mercredi', type:'Fractionné', titre:'2 × 5000 mètres à allure marathon', duree:'80 min', pcts:[[65,65],[78,82]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
        corps:'2 × 5000 mètres à {{P}}. Récupération 5 min. 10 km à allure marathon. Pars conservateur.',
        retour:'10 min footing très lent.',
        note:'RPE 7-8/10 · Séance spécifique marathon dès S5.' },
      { jour:'Jeudi', type:'EF', titre:'Footing fondamental 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}. Récupération.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Vendredi', type:'Tempo', titre:'3 × 15 minutes au seuil', duree:'75 min', pcts:[[65,70],[82,87]],
        echauff:'25 min progressif à {{P}}.',
        corps:'3 × 15 min à {{P}} avec 4 min de récupération. 45 min au seuil.',
        retour:'10 min footing très lent.',
        note:'RPE 7-8/10 · Maintien du seuil en complément de la spécificité marathon.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 100 minutes', duree:'100 min', pcts:[[65,65]],
        echauff:'', corps:'100 min à {{P}}. Gel à 1h.', retour:'',
        note:'RPE 5/10.' },
    ]},

  { num:6, phase:'Développement', charge:'Moyenne',
    objectif:'Côtes mercredi + séance finisher vendredi. Variation des stimuli pour un développement physique complet.',
    conseil:'Les côtes travaillent la puissance, le finisher travaille la résistance à l\'allure marathon. Deux stimuli complémentaires dans une semaine.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 45 minutes', duree:'45 min', pcts:[[65,65]],
        echauff:'', corps:'45 min à {{P}}.', retour:'',
        note:'RPE 4/10.' },
      { jour:'Mardi', type:'EF', titre:'Footing de récupération 40 minutes', duree:'40 min', pcts:[[60,62]],
        echauff:'', corps:'40 min à {{P}}. Léger avant les côtes.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mercredi', type:'Côtes', titre:'12 côtes de 80 mètres', duree:'55 min', pcts:[[65,65],[100,105]],
        echauff:'25 min progressif à {{P}}, finir par 4 foulées bondissantes.',
        corps:'12 côtes de 80 mètres à effort maximal. Récupération : redescente en marchant.',
        retour:'10 min footing très lent.',
        note:'RPE 8/10 · 12 côtes. Qualité sur toutes.' },
      { jour:'Jeudi', type:'EF', titre:'Footing fondamental 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}. Récupération entre les 2 qualités.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Vendredi', type:'Tempo', titre:'Séance finisher, 5 km seuil + 2 × 3 km allure marathon', duree:'75 min', pcts:[[65,65],[80,85],[78,82]],
        echauff:'25 min footing EF à {{P}}.',
        corps:'5 km à {{P}} (effort seuil) → 4 min récupération → 2 × 3 km à ton allure objectif marathon ({{OBJ}}), récup 3 min entre chaque. Version réduite de la séance finisher.',
        retour:'10 min footing léger.',
        note:'RPE 8/10 · Transition seuil vers allure marathon. Séance de qualité avancée.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 1h50', duree:'1h50', pcts:[[65,65]],
        echauff:'', corps:'1h50 à {{P}}. Gel à 1h.', retour:'',
        note:'RPE 5/10.' },
    ]},

  { num:7, phase:'Développement', charge:'Élevée',
    objectif:'3 × 15 min seuil mercredi + 4 × 3 km OBJ vendredi. Double charge spécifique marathon.',
    conseil:'Les blocs OBJ en qualité pure (vendredi, sans la fatigue de la SL) permettent de graver l\'allure marathon avec précision.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 50 minutes', duree:'50 min', pcts:[[65,65]],
        echauff:'', corps:'50 min à {{P}}. Grosse semaine. Reste conservateur.', retour:'',
        note:'RPE 4/10.' },
      { jour:'Mardi', type:'EF', titre:'Footing de récupération 40 minutes', duree:'40 min', pcts:[[60,62]],
        echauff:'', corps:'40 min à {{P}}. Léger.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mercredi', type:'Tempo', titre:'3 × 15 minutes au seuil', duree:'75 min', pcts:[[65,70],[82,87]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
        corps:'3 × 15 min à {{P}} avec 4 min de récupération. 45 min au seuil.',
        retour:'10 min footing très lent.',
        note:'RPE 8/10.' },
      { jour:'Jeudi', type:'EF', titre:'Footing fondamental 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}. Récupération entre les 2 qualités.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Vendredi', type:'Fractionné', titre:'4 × 3 km à allure marathon', duree:'75 min', pcts:[[65,65],[78,82]],
        echauff:'25 min footing EF à {{P}}.',
        corps:'4 × 3 km exactement à ton allure objectif marathon ({{OBJ}}). Récupération 3 min au trot. 12 km à {{OBJ}} en blocs.',
        retour:'10 min footing léger.',
        note:'RPE 7-8/10 · Blocs OBJ purs. Régularité sur les 4.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 2 heures', duree:'2h', pcts:[[65,65]],
        echauff:'', corps:'2h à {{P}}. Gel à 1h et 1h20. Cap des 2h.', retour:'',
        note:'RPE 5/10.' },
    ]},

  { num:8, phase:'Développement', charge:'Élevée',
    objectif:'Séance finisher mercredi + 2 × 5000m OBJ vendredi + SL 2h10. Triple charge avant la phase spécifique.',
    conseil:'Semaine très chargée. Les 2 séances de qualité sont très exigeantes. Récupère bien jeudi entre les deux.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 50 minutes', duree:'50 min', pcts:[[65,65]],
        echauff:'', corps:'50 min à {{P}}. Semaine lourde. Préserve-toi lundi.', retour:'',
        note:'RPE 4/10.' },
      { jour:'Mardi', type:'EF', titre:'Footing de récupération 40 minutes', duree:'40 min', pcts:[[60,62]],
        echauff:'', corps:'40 min à {{P}}.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mercredi', type:'Tempo', titre:'Séance finisher, 5 km seuil + 3 × 3 km allure marathon', duree:'90 min', pcts:[[65,65],[80,85],[78,82]],
        echauff:'25 min footing EF à {{P}}.',
        corps:'5 km à {{P}} (effort seuil) → 5 min récupération → 3 × 3 km à ton allure objectif marathon ({{OBJ}}), récup 3 min.',
        retour:'10 min footing léger.',
        note:'RPE 8/10 · Séance de référence marathon.' },
      { jour:'Jeudi', type:'EF', titre:'Footing de récupération 35 minutes', duree:'35 min', pcts:[[60,62]],
        echauff:'', corps:'35 min à {{P}}. Récupération cruciale entre le finisher et les 5000m.', retour:'',
        note:'RPE 3/10 · Très léger. Prépare les 5000m de vendredi.' },
      { jour:'Vendredi', type:'Fractionné', titre:'2 × 5000 mètres à allure marathon', duree:'80 min', pcts:[[65,65],[78,82]],
        echauff:'25 min progressif à {{P}}.',
        corps:'2 × 5000 mètres à {{P}}. Récupération 5 min. Pars prudement après la séance finisher de mercredi.',
        retour:'10 min footing très lent.',
        note:'RPE 7/10 · Intensité légèrement réduite pour tenir après mercredi.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 2h10', duree:'2h10', pcts:[[65,65]],
        echauff:'', corps:'2h10 à {{P}}. Gel à 1h et 1h25.', retour:'',
        note:'RPE 5-6/10 · Fin de la phase développement.' },
    ]},

  { num:9, phase:'Spécificité marathon', charge:'Élevée',
    objectif:'Côtes mercredi + 4 × 3 km OBJ vendredi + SL 2h avec 20 min OBJ. Spécificité marathon totale.',
    conseil:'La phase spécifique est lancée. Toutes les séances de qualité travaillent maintenant autour de l\'allure marathon.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 50 minutes', duree:'50 min', pcts:[[65,65]],
        echauff:'', corps:'50 min à {{P}}.', retour:'',
        note:'RPE 4/10.' },
      { jour:'Mardi', type:'EF', titre:'Footing de récupération 40 minutes', duree:'40 min', pcts:[[60,62]],
        echauff:'', corps:'40 min à {{P}}.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mercredi', type:'Côtes', titre:'12 côtes de 80 mètres, puissance marathon', duree:'55 min', pcts:[[65,65],[100,105]],
        echauff:'25 min progressif à {{P}}, finir par 4 foulées bondissantes.',
        corps:'12 côtes de 80 mètres à effort maximal. Récupération : redescente en marchant. Renforcement neuromusculaire spécifique marathon.',
        retour:'10 min footing très lent.',
        note:'RPE 8/10 · Puissance pour résister aux km 30-35.' },
      { jour:'Jeudi', type:'EF', titre:'Footing fondamental 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}. Récupération entre côtes et OBJ.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Vendredi', type:'Fractionné', titre:'4 × 3 km à allure marathon', duree:'75 min', pcts:[[65,65],[78,82]],
        echauff:'25 min footing EF à {{P}}.',
        corps:'4 × 3 km à ton allure objectif marathon ({{OBJ}}). Récupération 3 min. 12 km à {{OBJ}} en blocs.',
        retour:'10 min footing léger.',
        note:'RPE 7-8/10 · Blocs OBJ spécifiques.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 2h avec 20 min allure marathon', duree:'2h', pcts:[[65,72],[75,80]],
        echauff:'', corps:'100 min à {{P}}, puis 20 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h. Mémorise {{OBJ}}.', retour:'',
        note:'RPE 6/10 en EF · 7/10 sur les 20 min.' },
    ]},

  { num:10, phase:'Spécificité marathon', charge:'Élevée',
    objectif:'3 × 15 min seuil mercredi + 2 × 5000m OBJ vendredi + SL 2h10 avec 25 min OBJ.',
    conseil:'Trois séances majeures dans la semaine. Les EF (lundi, mardi, jeudi) sont essentiels pour tenir le volume.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 50 minutes', duree:'50 min', pcts:[[65,65]],
        echauff:'', corps:'50 min à {{P}}.', retour:'',
        note:'RPE 4/10.' },
      { jour:'Mardi', type:'EF', titre:'Footing de récupération 40 minutes', duree:'40 min', pcts:[[60,62]],
        echauff:'', corps:'40 min à {{P}}.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mercredi', type:'Tempo', titre:'3 × 15 minutes au seuil', duree:'75 min', pcts:[[65,70],[82,87]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
        corps:'3 × 15 min à {{P}} avec 4 min de récupération. 45 min au seuil.',
        retour:'10 min footing très lent.',
        note:'RPE 8/10.' },
      { jour:'Jeudi', type:'EF', titre:'Footing fondamental 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}. Récupération entre seuil et 5000m.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Vendredi', type:'Fractionné', titre:'2 × 5000 mètres à allure marathon', duree:'80 min', pcts:[[65,65],[78,82]],
        echauff:'25 min progressif à {{P}}.',
        corps:'2 × 5000 mètres à {{P}}. Récupération 5 min. 10 km à allure marathon avec récupération.',
        retour:'10 min footing très lent.',
        note:'RPE 7-8/10 · Séance spécifique marathon.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 2h10 avec 25 min allure marathon', duree:'2h10', pcts:[[65,72],[75,80]],
        echauff:'', corps:'105 min à {{P}}, puis 25 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h et 1h20.', retour:'',
        note:'RPE 6/10 en EF · 7-8/10 sur les 25 min.' },
    ]},

  { num:11, phase:'Spécificité marathon', charge:'Maximale',
    objectif:'Séance finisher mercredi + 2 × 5000m OBJ vendredi + SL 2h20 avec 30 min OBJ. Pic de charge spécifique.',
    conseil:'Semaine de charge maximale. Les 3 EF (lundi, mardi, jeudi) sont la clé pour encaisser les 3 séances majeures.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 50 minutes', duree:'50 min', pcts:[[65,65]],
        echauff:'', corps:'50 min à {{P}}. Semaine de charge maximale. Reste conservateur.', retour:'',
        note:'RPE 4/10.' },
      { jour:'Mardi', type:'EF', titre:'Footing de récupération 35 minutes', duree:'35 min', pcts:[[60,62]],
        echauff:'', corps:'35 min à {{P}}. Très léger. 3 séances majeures cette semaine.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mercredi', type:'Tempo', titre:'Séance finisher, 5 km seuil + 3 × 3 km allure marathon', duree:'90 min', pcts:[[65,65],[80,85],[78,82]],
        echauff:'25 min footing EF à {{P}}.',
        corps:'5 km à {{P}} (effort seuil) → 5 min récupération → 3 × 3 km à ton allure objectif marathon ({{OBJ}}), récup 3 min.',
        retour:'10 min footing léger.',
        note:'RPE 8/10 · Séance de référence marathon.' },
      { jour:'Jeudi', type:'EF', titre:'Footing de récupération 35 minutes', duree:'35 min', pcts:[[60,62]],
        echauff:'', corps:'35 min à {{P}}. Récupération entre le finisher et les 5000m.', retour:'',
        note:'RPE 3/10 · Crucial pour tenir les 5000m de vendredi.' },
      { jour:'Vendredi', type:'Fractionné', titre:'2 × 5000 mètres à allure marathon', duree:'80 min', pcts:[[65,65],[78,82]],
        echauff:'25 min progressif à {{P}}.',
        corps:'2 × 5000 mètres à {{P}}. Récupération 5 min.',
        retour:'10 min footing très lent.',
        note:'RPE 7/10 · Après le finisher de mercredi, pars conservateur.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 2h20 avec 30 min allure marathon', duree:'2h20', pcts:[[65,72],[75,80]],
        echauff:'', corps:'110 min à {{P}}, puis 30 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h, 1h20, 1h40.', retour:'',
        note:'RPE 6/10 en EF · 8/10 sur les 30 min.' },
    ]},

  { num:12, phase:'Spécificité marathon', charge:'Maximale',
    objectif:'LE pic de charge absolu. Grande SL 2h30 avec 30 min OBJ. La semaine la plus difficile du plan.',
    conseil:'Après cette semaine, tout est derrière toi. La SL 2h30 avec 30 min OBJ est la séance ultime de la préparation.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 50 minutes', duree:'50 min', pcts:[[65,65]],
        echauff:'', corps:'50 min à {{P}}. Dernière grosse semaine. Préserve-toi lundi.', retour:'',
        note:'RPE 4/10.' },
      { jour:'Mardi', type:'EF', titre:'Footing de récupération 35 minutes', duree:'35 min', pcts:[[60,62]],
        echauff:'', corps:'35 min à {{P}}. Très léger.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mercredi', type:'Fractionné', titre:'4 × 3 km à allure marathon + côtes finales', duree:'80 min', pcts:[[65,65],[78,82]],
        echauff:'25 min footing EF à {{P}}.',
        corps:'4 × 3 km à ton allure objectif marathon ({{OBJ}}), récup 3 min. Puis 4 côtes de 80m explosives pour finir. Séance marathonienne complète.',
        retour:'10 min footing léger.',
        note:'RPE 7-8/10 · Séance de pic spécifique.' },
      { jour:'Jeudi', type:'EF', titre:'Footing de récupération 35 minutes', duree:'35 min', pcts:[[60,62]],
        echauff:'', corps:'35 min à {{P}}. Récupération légère avant la grande SL.', retour:'',
        note:'RPE 3/10 · Ménage-toi pour la SL 2h30 de dimanche.' },
      { jour:'Vendredi', type:'EF', titre:'Footing léger 30 minutes', duree:'30 min', pcts:[[60,65]],
        echauff:'', corps:'30 min très légers à {{P}}. Juste garder les jambes en mouvement avant la grande SL dimanche.', retour:'',
        note:'RPE 3/10 · Préserve toute ton énergie pour dimanche.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Grande sortie longue 2h30 avec 30 min allure marathon', duree:'2h30', pcts:[[65,72],[75,80]],
        echauff:'', corps:'120 min à {{P}}, puis 30 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h, 1h20, 1h40, 2h. LA grande sortie du plan.', retour:'',
        note:'RPE 6/10 en EF · 8/10 sur les 30 min · Le pic de charge est atteint. Récupération maintenant.' },
    ]},

  { num:13, phase:'Pic de charge', charge:'Élevée (légère réduction)',
    objectif:'Volume réduit de -15%. Maintien de l\'intensité sur 2 qualités. Consolidation post-pic.',
    conseil:'Consolidation. L\'intensité reste mais le volume diminue. Le corps récupère tout en assimilant les adaptations de S12.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 45 minutes', duree:'45 min', pcts:[[65,65]],
        echauff:'', corps:'45 min à {{P}}.', retour:'',
        note:'RPE 4/10.' },
      { jour:'Mardi', type:'EF', titre:'Footing de récupération 35 minutes', duree:'35 min', pcts:[[60,62]],
        echauff:'', corps:'35 min à {{P}}.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mercredi', type:'Tempo', titre:'3 × 15 minutes au seuil', duree:'75 min', pcts:[[65,70],[82,87]],
        echauff:'25 min progressif à {{P}}.',
        corps:'3 × 15 min à {{P}} avec 4 min de récupération.',
        retour:'10 min footing très lent.',
        note:'RPE 7-8/10.' },
      { jour:'Jeudi', type:'EF', titre:'Footing fondamental 35 minutes', duree:'35 min', pcts:[[65,65]],
        echauff:'', corps:'35 min à {{P}}.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Vendredi', type:'Fractionné', titre:'4 × 3 km à allure marathon', duree:'75 min', pcts:[[65,65],[78,82]],
        echauff:'25 min footing EF à {{P}}.',
        corps:'4 × 3 km à ton allure objectif marathon ({{OBJ}}). Récupération 3 min.',
        retour:'10 min footing léger.',
        note:'RPE 7-8/10.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 2h15 avec 30 min allure marathon', duree:'2h15', pcts:[[65,72],[75,80]],
        echauff:'', corps:'105 min à {{P}}, puis 30 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h, 1h20, 1h40.', retour:'',
        note:'RPE 6/10 en EF · 8/10 sur les 30 min.' },
    ]},

  { num:14, phase:'Pic de charge', charge:'Réduite, pré-affûtage',
    objectif:'Volume réduit de -30%. 4 × 1500m mercredi + 2 × 15 min seuil vendredi. Début de super-compensation.',
    conseil:'Le corps entre en phase de recharge. Moins de volume, mêmes qualités. L\'affûtage commence doucement.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing fondamental 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}. L\'affûtage commence. Les footings raccourcissent progressivement. Le corps entre en super-compensation — tu te recharges. Vraiment léger, aucune ambition de vitesse.', retour:'',
        note:'RPE 3-4/10.' },
      { jour:'Mardi', type:'EF', titre:'Footing de récupération 30 minutes', duree:'30 min', pcts:[[60,65]],
        echauff:'', corps:'30 min très légers à {{P}}.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Mercredi', type:'Fractionné', titre:'4 × 1500 mètres, maintien VMA pré-affûtage', duree:'60 min', pcts:[[65,65],[83,90]],
        echauff:'25 min progressif à {{P}}, finir par 4 accélérations de 80m.',
        corps:'4 × 1500 mètres à {{P}}. Récupération 3 min. Intervalles plus courts : maintien sans fatigue.',
        retour:'10 min footing très lent.',
        note:'RPE 7/10 · Moins de volume, mêmes sensations.' },
      { jour:'Jeudi', type:'EF', titre:'Footing de récupération 30 minutes', duree:'30 min', pcts:[[60,65]],
        echauff:'', corps:'30 min à {{P}}. Récupération légère.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Vendredi', type:'Tempo', titre:'2 × 15 minutes au seuil, volume réduit', duree:'55 min', pcts:[[65,70],[82,87]],
        echauff:'25 min progressif à {{P}}.',
        corps:'2 × 15 min à {{P}} avec 4 min de récupération. Réduit de 33% vs les 3 × 15 min habituels.',
        retour:'10 min footing très lent.',
        note:'RPE 7/10 · Moins de blocs, même intensité. L\'affûtage commence.' },
      { jour:'Dimanche', type:'Sortie longue', titre:'Sortie longue 1h50 avec 15 min allure marathon', duree:'1h50', pcts:[[65,72],[75,80]],
        echauff:'', corps:'95 min à {{P}}, puis 15 min à ton allure objectif marathon ({{OBJ}}). Gel à 1h.', retour:'',
        note:'RPE 5/10 en EF · 7/10 sur les 15 min · Allégée. Maintien des sensations.' },
    ]},

  { num:15, phase:'Consolidation', charge:'Réduite, affûtage',
    objectif:'4 séances légères pour laisser les adaptations s\'installer. Volume réduit de 50%.',
    conseil:'Dors 8h, mange bien. Ne rajoute pas de séances. Les jambes doivent fourmiller d\'impatience.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing léger 50 minutes', duree:'50 min', pcts:[[65,65]],
        echauff:'', corps:'50 min à {{P}}, allure vraiment légère. Le footing le plus long de la semaine de consolidation — maintien de l\'endurance de base sans fatiguer. Cours en nature, apprécie la légèreté des jambes. La semaine de course est imminente.', retour:'',
        note:'RPE 3/10 · Tu dois finir comme si tu venais de te promener.' },
      { jour:'Mercredi', type:'Tempo', titre:'2 × 15 minutes au seuil, volume réduit', duree:'55 min', pcts:[[65,72],[82,88]],
        echauff:'25 min progressif à {{P}}.', corps:'2 × 15 min à {{P}}. Volume réduit mais intensité maintenue. Récup 4 min. Termine par 1 km à {{OBJ}}.', retour:'10 min footing très lent.',
        note:'RPE 7/10 · Maintien des sensations.' },
      { jour:'Vendredi', type:'EF', titre:'Footing léger 40 minutes', duree:'40 min', pcts:[[65,65]],
        echauff:'', corps:'40 min à {{P}}, allure légère. Dans les 10 dernières minutes, place 4 à 6 accélérations de 60m à ton allure marathon pour garder les sensations neuromusculaires vives. Termine frais et dynamisé.', retour:'',
        note:'RPE 3/10.' },
      { jour:'Dimanche', type:'EF', titre:'Footing léger 35 minutes', duree:'35 min', pcts:[[60,65]],
        echauff:'', corps:'35 min très légers à {{P}}. Dernier footing avant la semaine de course. Laisse les jambes rouler librement, le corps se recharge. Finis avec le sourire.', retour:'',
        note:'RPE 3/10 · Tu dois finir frais et dynamisé.' },
    ]},

  { num:16, phase:'Semaine de course', charge:'Conserve, tu es prêt',
    objectif:'Arriver au départ reposé, confiant, les jambes fraîches. 15 semaines de travail ont été faites.',
    conseil:'Pars à {{OBJ}}/km dès le départ. L\'adrénaline va te pousser à aller plus vite, résiste.',
    seances:[
      { jour:'Lundi', type:'EF', titre:'Footing très léger 30 minutes', duree:'30 min', pcts:[[60,65]],
        echauff:'', corps:'30 min à {{P}}. Maintenir la circulation. Vraiment facile.', retour:'',
        note:'RPE 3/10 · Aucun effort.' },
      { jour:'Mercredi', type:'Fractionné', titre:'8 × 1 min / 1 min à allure marathon', duree:'40 min',
        echauff:'15 min de footing très léger.',
        corps:'8 × 1 minute à ton allure objectif marathon ({{OBJ}}) / 1 minute au trot. Réveille les jambes sans les fatiguer.',
        retour:'10 min de jogging léger.',
        note:'RPE 6/10 · Maintien des sensations avant le marathon.' },
      { jour:'Samedi', type:'Activation', titre:'Activation J-1 + accélérations', duree:'30 min', pcts:[[60,65]],
        echauff:'', corps:'20 min de trot à {{P}}. Puis 6 à 8 accélérations progressives de 80m jusqu\'à ton allure objectif ({{OBJ}}). Récupère 60 sec en marchant.', retour:'',
        note:'Prépare tes affaires ce soir. Visualise les premiers kilomètres à {{OBJ}}/km.' },
      { jour:'Dimanche', type:'Course', titre:'MARATHON', duree:'Jour J',
        echauff:'10-15 min de jogging très léger avant le départ.',
        corps:'KM 1-8 : pars à {{OBJ}}/km exactement. KM 9-21 : régularité absolue, gel à chaque ravitaillement. KM 22-30 : maintiens {{OBJ}}, écoute ton corps. KM 31-35 : raccourcis la foulée, garde les bras actifs. KM 36-42 : donne absolument tout.',
        retour:'20-30 min de marche. Ravitaillement dans les 30 min.',
        note:'La douleur aux km 30-35 est normale. C\'est là que se gagne un marathon. Tiens bon.' },
    ]},
]
